src/Kunstmaan/MediaBundle/Resources/views/Chooser/chooserShowFolder.html.twig
src/Kunstmaan/MediaBundle/Resources/views/Form/formWidgets.html.twig

Was previously loading full image

Added imagine_filter call in chooser widget thumbnails

---

src/Kunstmaan/UserManagementBundle/Controller/UsersController.php

This solution insert/update all the user data (also the password field) and flush the updated data once.

fix issue #91 and reduce flush

---

src/Kunstmaan/MediaBundle/Repository/FolderRepository.php

```
Error: Call to a member function getChildren() on a non-object in ........./vendor/kunstmaan/bundles-cms/src/Kunstmaan/MediaBundle/Repository/FolderRepository.php line 39 
```
https://github.com/Kunstmaan/KunstmaanBundlesCMS/blob/master/src/Kunstmaan/MediaBundle/Repository/FolderRepository.php#L39

Editing the top media folder results in an error

---

src/Kunstmaan/AdminBundle/Resources/translations/messages.it.yml
src/Kunstmaan/AdminBundle/Resources/translations/validators.it.yml
src/Kunstmaan/DashboardBundle/Resources/translations/messages.en.yml
src/Kunstmaan/DashboardBundle/Resources/translations/messages.it.yml
src/Kunstmaan/FormBundle/Resources/translations/messages.it.yml
src/Kunstmaan/MediaBundle/Resources/translations/messages.it.yml
src/Kunstmaan/MediaPagePartBundle/Resources/translations/messages.it.yml
src/Kunstmaan/NodeSearchBundle/Resources/translations/messages.it.yml
src/Kunstmaan/PagePartBundle/Resources/translations/messages.it.yml
src/Kunstmaan/PagePartBundle/Resources/translations/validators.it.yml
src/Kunstmaan/TranslatorBundle/Resources/translations/messages.it.yml
src/Kunstmaan/UserManagementBundle/Resources/translations/messages.it.yml
src/Kunstmaan/UserManagementBundle/Resources/translations/validators.it.yml

I've added italian translation where missing, and I've found a minor issue (a semicolon in the en translation).

added italian translation - fixed colon issue in en translation

---

docs/Installation.md

Just started experimenting with kunstmaan (on a Windows PC...). I couldn't resist to apply some fixes to the chapter I read. I just did a lot of things and if you don't agree with some of them, I just remove them from my PR.

Lots of fixes to the installation chapter

---

autoload.php.dist
src/Kunstmaan/NodeBundle/EventListener/NodeTranslationListener.php

Proposed solution for issue #174 
I am unsure if the fix for the `autoload.php.dist` is the way to go.
I copied it from [`app/autoload.php`](https://github.com/Kunstmaan/KunstmaanBundlesStandardEdition/blob/master/app/autoload.php).
I couldn't run the tests locally without it though.
I have PHP 5.5.9 installed.

Fix nodetranslation listener

---

src/Kunstmaan/AdminBundle/Entity/AclChangeset.php
src/Kunstmaan/MediaBundle/Entity/Folder.php
src/Kunstmaan/MediaBundle/Entity/Media.php
src/Kunstmaan/NodeBundle/Entity/Node.php
src/Kunstmaan/NodeBundle/Entity/NodeTranslation.php
src/Kunstmaan/NodeBundle/Entity/NodeVersion.php
src/Kunstmaan/PagePartBundle/Entity/PagePartRef.php
src/Kunstmaan/PagePartBundle/Entity/PageTemplateConfiguration.php
src/Kunstmaan/SeoBundle/Entity/Seo.php
src/Kunstmaan/TranslatorBundle/Entity/Translation.php

Made indices unique by prefixing entity name

---

src/Kunstmaan/AdminBundle/Helper/Security/Acl/AclHelper.php
src/Kunstmaan/AdminBundle/Helper/Security/Acl/AclNativeHelper.php

SQLite does not support database prefixes like this.
After this, I got a working demo site with SQLite :tada:

Do not prefix database when using SQLite

---

src/Kunstmaan/GeneratorBundle/Command/GenerateFormPageCommand.php
src/Kunstmaan/GeneratorBundle/Generator/FormPageGenerator.php
src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/formpage/Resources/config/pageparts/formpage.yml
src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/formpage/Resources/config/pagetemplates/formpage.yml
src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/formpage/Resources/views/Pages/FormPage/pagetemplate.html.twig
src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/formpage/Resources/views/Pages/FormPage/view.html.twig

Because creating a page that uses the form bundle is a bit complicated, I've added a very basic formpage generator to the generatorBundle.
I've based this generator mostly on the default PageGenerator, but did add some extra config files and removed some functions (for extra pageparts, etc).

New formPage generator

---

src/Kunstmaan/AdminBundle/Command/CreateUserCommand.php

fix invisible password #195

---

src/Kunstmaan/ArticleBundle/Resources/views/AbstractArticlePageAdminList/list.html.twig

This will make it possible to add a canAdd() check to the article bundle.
| Fixed tickets | #226

[Articlebundle] CanAdd check

---

.travis.yml
composer.json
src/Kunstmaan/FormBundle/Tests/Entity/FormSubmissionFieldTest.php

Fix "Cannot redeclare any()" in PHPUnit

---

CONTRIBUTING.md
docs/01-00-introduction.md
docs/02-00-getting-started.md
docs/03-00-installation.md
docs/03-01-system-requirements.md
docs/03-02-development-environment.md
docs/04-00-content-management.md
docs/04-01-creating-a-page-part.md
docs/04-02-creating-an-adminlist.md
docs/04-03-creating-a-pagetype.md
docs/04-04-adding-a-newssection-or-blog.md
docs/04-05-adding-a-search-engine.md
docs/05-00-cookbook.md
docs/05-01-going-single-language.md
docs/05-02-manage-translations.md
docs/05-03-google-analytics-dashboard.md
docs/07-01-reporting-issues.md
docs/07-02-pull-requests.md
docs/07-03-coding-standards.md

Change paths and links in the docs to work properly on bundles.kunstmaan.be

---

src/Kunstmaan/AdminBundle/Form/WysiwygType.php
src/Kunstmaan/AdminBundle/Resources/views/Form/fields.html.twig

Having a class on a wysiwyg field was overwriting the wysiwyg classes. Also clean up tabs.

Fix and cleanup wysiwyg formtype

---

docs/07-02-pull-requests.md

Add requirements for the pull request title to the documentation.

[Documentation] Added title requirements for pull requests

---

docs/03-00-installation.md

[Documentation] removed the acme bundle question and added the doctrine:database:create command

---

src/Kunstmaan/AdminBundle/Resources/ui/scss/default-theme/general/_app__content.scss
src/Kunstmaan/AdminBundle/Resources/ui/scss/default-theme/general/_app__sidebar.scss

[AdminBundle] Fix height calculation of the sidebar so that it follows the height of the page when possible

---

src/Kunstmaan/AdminBundle/Resources/ui/js/_app-sidebar-tree.js
src/Kunstmaan/AdminBundle/Resources/ui/js/_page-editor.js

[AdminBundle] Make it possible to open a link in new tab in the sidebar

---

src/Kunstmaan/AdminBundle/Resources/views/Form/fields.html.twig

[AdminBundle] Fix classmerge for select-boxes

---

src/Kunstmaan/AdminBundle/Tests/Helper/Security/Acl/AclHelperTest.php
src/Kunstmaan/FormBundle/Entity/FormSubmissionField.php

[FormBundle] Fix Doctrine 2.5 BC break for the 3.0 branch

---

composer.json
src/Kunstmaan/AdminBundle/composer.json
src/Kunstmaan/AdminListBundle/composer.json
src/Kunstmaan/ArticleBundle/composer.json
src/Kunstmaan/BehatBundle/composer.json
src/Kunstmaan/DashboardBundle/composer.json
src/Kunstmaan/FormBundle/composer.json
src/Kunstmaan/GeneratorBundle/composer.json
src/Kunstmaan/LanguageChooserBundle/composer.json
src/Kunstmaan/LiveReloadBundle/composer.json
src/Kunstmaan/MediaBundle/composer.json
src/Kunstmaan/MediaPagePartBundle/composer.json
src/Kunstmaan/NodeBundle/composer.json
src/Kunstmaan/NodeSearchBundle/composer.json
src/Kunstmaan/PagePartBundle/composer.json
src/Kunstmaan/RedirectBundle/composer.json
src/Kunstmaan/SearchBundle/composer.json
src/Kunstmaan/SeoBundle/composer.json
src/Kunstmaan/SitemapBundle/composer.json
src/Kunstmaan/TaggingBundle/composer.json
src/Kunstmaan/TranslatorBundle/composer.json
src/Kunstmaan/UserManagementBundle/composer.json
src/Kunstmaan/UtilitiesBundle/composer.json
src/Kunstmaan/VotingBundle/composer.json

Upgrade dev-master branch alias to 3.2-dev

---

src/Kunstmaan/MediaBundle/Resources/translations/messages.en.yml
src/Kunstmaan/MediaBundle/Resources/ui/js/_dnd-upload.js

[MediaBundle] Fix translations and behaviour for Drag and Drop media

---

src/Kunstmaan/GeneratorBundle/Generator/PagePartGenerator.php

| Fixed tickets | #21
Removed glob calls in favor of symfony finder.

[GeneratorBundle] Removed glob calls in favor of symfony finder

---

src/Kunstmaan/MediaBundle/Controller/FolderController.php
src/Kunstmaan/MediaBundle/Resources/views/Folder/addsub-modal.html.twig
src/Kunstmaan/MediaBundle/Resources/views/Folder/delete-modal.html.twig

[MediaBundle] Passed the type parameter on creation/deletion subfolder in media-chooser

---

src/Kunstmaan/FormBundle/Event/FormEvents.php
src/Kunstmaan/FormBundle/Event/SubmissionEvent.php
src/Kunstmaan/FormBundle/Helper/FormHandler.php

Can come in handy when you want to do additional things when a new submission gets saved.

[FormBundle] Dispatch an event when a new formpage submission gets saved

---

src/Kunstmaan/ArticleBundle/AdminList/AbstractArticlePageAdminListConfigurator.php

[ArticleBundle] Fix default sorting of article pages in adminlist, issue due to doctrine 2.5 adding validation checks

---

src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/admintests/Features/AdminPage.feature
src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/admintests/Features/AdminSettingsUser.feature
src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/admintests/Features/Context/FeatureContext.php
src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/admintests/Features/Context/GroupContext.php
src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/admintests/Features/Context/MediaContext.php
src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/admintests/Features/Context/PageContext.php
src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/admintests/Features/Context/RoleContext.php
src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/admintests/Features/Context/UserContext.php

Behat tests are now up to date.

[GeneratorBundle] Updated behat tests for the new backend and demosite

---

src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/pagepart/Resources/views/PageParts/view.html.twig

| Fixed tickets | #346
Fix in the generator bundle to make wysiwyg template visible in frontend.

[GeneratorBundle] Fix wysiwyg template to make it visible in frontend

---

src/Kunstmaan/AdminBundle/EventListener/SessionSecurityListener.php

[AdminBundle] Prevent session hijacking checks from starting a session and preventing pages to be cached in Varnish

---

src/Kunstmaan/AdminBundle/Resources/ui/js/_colorpicker.js
src/Kunstmaan/AdminBundle/Resources/ui/js/_nested-form.js
src/Kunstmaan/AdminBundle/Resources/ui/js/_pagepart-editor.js
src/Kunstmaan/AdminBundle/Resources/ui/js/_tooltip.js
src/Kunstmaan/AdminBundle/Resources/ui/js/app.js
src/Kunstmaan/AdminBundle/Resources/views/Default/_js_footer.html.twig

[AdminBundle] Fix tooltip and colorpicker implementations

---

src/Kunstmaan/AdminBundle/Resources/ui/js/_rich-editor.js
src/Kunstmaan/AdminBundle/Resources/views/Default/_ckeditor_configs.html.twig
src/Kunstmaan/AdminBundle/Resources/views/Default/_js_footer.html.twig
src/Kunstmaan/AdminBundle/Resources/views/Form/fields.html.twig

Fix issue322: Allow custom configuration for the ckEditors

---

src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/defaultsite/DataFixtures/ORM/DefaultSiteGenerator/DefaultSiteFixtures.php

[GeneratorBundle] Fix typo generator bundle

---

src/Kunstmaan/NodeBundle/EventListener/SlugListener.php

[NodeBundle] Removed redundant code in SlugListener

---

src/Kunstmaan/FormBundle/Resources/views/FormSubmissions/list.html.twig

[FormBundle] Layout export button form-bundle

---

src/Kunstmaan/MediaBundle/Resources/config/pdf_preview.yml

[MediaBundle] Fix error on pdf preview

---

src/Kunstmaan/NodeBundle/Helper/Menu/ActionsMenuBuilder.php

[NodeBundle] Fix for publishing a draft version of page

---

src/Kunstmaan/GeneratorBundle/Generator/FormPageGenerator.php
src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/formpage/Resources/views/Pages/FormPage/pagetemplate.html.twig

[GeneratorBundle] corrected Wrong bundlename in pagetemplate

---

src/Kunstmaan/TranslatorBundle/Resources/views/Modals/_modals.html.twig
src/Kunstmaan/TranslatorBundle/Resources/views/Translator/list.html.twig

[TranslatorBundle] add confirmation box to force import

---

src/Kunstmaan/DashboardBundle/Controller/GoogleAnalyticsController.php

[DashboardBundle] Fixes: the code from google is not decoded

---

src/Kunstmaan/FormBundle/AdminList/FormSubmissionExportListConfigurator.php

[FormBundle] added buildFilters method as required by interface

---

src/Kunstmaan/AdminBundle/Resources/ui/vendor_bower/bootstrap-sass-official/assets/stylesheets/bootstrap/_alerts.scss
src/Kunstmaan/AdminListBundle/Resources/views/Default/add_or_edit.html.twig

[AdminListBundle] The form tag should be opened on a higher level, otherwise nested entities in adminlists will not work

---

src/Kunstmaan/NodeBundle/Controller/WidgetsController.php

[NodeBundle] Show published subpages of structured nodes as online in the link chooser popup

---

src/Kunstmaan/AdminBundle/Resources/ui/js/_datepicker.js
src/Kunstmaan/AdminBundle/Resources/ui/scss/default-theme/components/_components.scss
src/Kunstmaan/AdminBundle/Resources/ui/scss/default-theme/components/forms/_date-time-group.scss
src/Kunstmaan/AdminBundle/Resources/ui/scss/default-theme/components/vendors/eonasdan-bootstrap-datetimepicker/_bootstrap-datetimepicker.scss
src/Kunstmaan/AdminBundle/Resources/ui/scss/default-theme/helpers/_helper-classes.scss
src/Kunstmaan/AdminBundle/Resources/views/Form/fields.html.twig

[AdminBundle] fix date time picker widget when there's only a date input field

---

src/Kunstmaan/NodeBundle/Repository/NodeTranslationRepository.php

[NodeBundle] Don't add slug for structure node

---

src/Kunstmaan/AdminBundle/Resources/views/Default/index.html.twig

[AdminBundle] Fix title and edit button styling of old dashboard

---

src/Kunstmaan/AdminListBundle/Resources/views/AdminListTwigExtension/filters.html.twig

[AdminListBundle] Fixes adminlist filters

---

src/Kunstmaan/AdminBundle/Resources/ui/js/_page-editor.js

[AdminBundle] Fix drag and drop sub entities

---

src/Kunstmaan/AdminBundle/Resources/ui/js/_rich-editor.js

[AdminBundle] syntax error in rich editor js

---

src/Kunstmaan/GeneratorBundle/Generator/DefaultSiteGenerator.php

[GeneratorBundle] Re-add services.yml configuration for the twig extension

---

src/Kunstmaan/NodeBundle/Twig/NodeTwigExtension.php

Added a twig function to get page information based on a node translation.

[NodeBundle] Add twig function get page by nodeTranslation

---

src/Kunstmaan/AdminBundle/Resources/ui/scss/default-theme/components/structures/_page-actions.scss

[AdminBundle] Update layout to fix with or without sub-actions

---

src/Kunstmaan/AdminBundle/Resources/ui/scss/default-theme/components/forms/_form-group.scss

[AdminBundle] Fix Select 2 in form-controls

---

src/Kunstmaan/MediaBundle/Resources/views/Form/formWidgets.html.twig

[MediaBundle] Fix Media previews

---

UPGRADE-3.2.md
src/Kunstmaan/NodeBundle/Controller/SlugController.php
src/Kunstmaan/NodeBundle/Helper/NodeMenu.php
src/Kunstmaan/NodeBundle/Repository/NodeTranslationRepository.php
src/Kunstmaan/NodeBundle/Resources/config/services.yml
src/Kunstmaan/NodeBundle/Twig/NodeTwigExtension.php

[NodeBundle] change nodeMenu in renderContext to twig function

---

docs/05-00-cookbook.md
docs/05-05-building-custom-filter-on-multiple-columns.md

[Documentation] Add custom filter documentation to cookbook

---

src/Kunstmaan/GeneratorBundle/Generator/DoctrineEntityGenerator.php

[GeneratorBundle] Prevent class not found bug when creating an entity and admin list

---

src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/Resources/views/Layout/layout.html.twig

[GeneratorBundle] Fix for nodemenu in generated twig template

---

.travis.yml
composer.json

Since PR #304 we cannot support Symfony 2.3 anymore

[Dependencies] Remove support for symfony 2.3

---

src/Kunstmaan/LeadGenerationBundle/Form/Rule/AfterXScrollPercentRuleAdminType.php

[LeadGenerationBundle] remove commented code

---

docs/03-00-installation.md

[Documentation] Use stable version instead of master (as the latter can be unstable)

---

docs/05-07-using-the-menubundle.md
src/Kunstmaan/MenuBundle/.gitignore
src/Kunstmaan/MenuBundle/AdminList/MenuAdminListConfigurator.php
src/Kunstmaan/MenuBundle/AdminList/MenuItemAdminListConfigurator.php
src/Kunstmaan/MenuBundle/Controller/MenuAdminListController.php
src/Kunstmaan/MenuBundle/Controller/MenuItemAdminListController.php
src/Kunstmaan/MenuBundle/DependencyInjection/Configuration.php
src/Kunstmaan/MenuBundle/DependencyInjection/KunstmaanMenuExtension.php
src/Kunstmaan/MenuBundle/Entity/Menu.php
src/Kunstmaan/MenuBundle/Entity/MenuItem.php
src/Kunstmaan/MenuBundle/Form/MenuItemAdminType.php
src/Kunstmaan/MenuBundle/KunstmaanMenuBundle.php
src/Kunstmaan/MenuBundle/LICENSE
src/Kunstmaan/MenuBundle/Repository/MenuItemRepository.php
src/Kunstmaan/MenuBundle/Resources/config/routing.yml
src/Kunstmaan/MenuBundle/Resources/config/services.yml
src/Kunstmaan/MenuBundle/Resources/views/AdminList/edit-menu-item.html.twig
src/Kunstmaan/MenuBundle/Resources/views/AdminList/list-menu-item.html.twig
src/Kunstmaan/MenuBundle/Resources/views/AdminList/menu-item-online.html.twig
src/Kunstmaan/MenuBundle/Resources/views/AdminList/menu-item-title.html.twig
src/Kunstmaan/MenuBundle/Resources/views/AdminList/menu-item-url.html.twig
src/Kunstmaan/MenuBundle/Service/MenuAdaptor.php
src/Kunstmaan/MenuBundle/Twig/MenuTwigExtension.php
src/Kunstmaan/MenuBundle/composer.json

[MenuBundle] Added the KunstmaanMenuBundle

---

src/Kunstmaan/SitemapBundle/Entity/SitemapPage.php

[SitemapBundle] Add required interface to the SitemapPage

---

LICENSE

[Documentation] Updated copyright to 2015

---

docs/04-07 Working-with-adminlists.md

Adding documentation about working with adminlists.

[Documentation] Working with adminlists

---

src/Kunstmaan/NodeBundle/Resources/views/NodeAdmin/_modals.html.twig

fix datepicker issue: couldn't go lower in time then the current time, even when the specified date is in the future

[AdminBundle] fix date time picker widget, time issue

---

src/Kunstmaan/AdminBundle/Helper/FormWidgets/FormWidget.php
src/Kunstmaan/AdminBundle/Helper/FormWidgets/Tabs/Tab.php

[AdminBundle] Make it possible to use a custom form template without overriding the default Tab/FormWidget

---

src/Kunstmaan/SitemapBundle/Entity/SitemapPage.php

[SitemapBundle] Fix HiddenFromSitemap interface name

---

src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/gulp/package.json

[GeneratorBundle] Increase the version of Gulp

---

src/Kunstmaan/NodeBundle/EventListener/SlugListener.php

It was not possible to define a custom RouteLoader for a page that was using the SlugActionInterface.

[NodeBundle] Allow custom route loaders in combination with SlugActionInterface

---

src/Kunstmaan/AdminBundle/Resources/ui/scss/default-theme/components/forms/_date-time-group.scss
src/Kunstmaan/AdminBundle/Resources/views/Form/fields.html.twig

[AdminBundle] Clear floats datetime group | html structure bootstrap radio buttons

---

src/Kunstmaan/NodeBundle/Resources/views/NodeAdmin/_modals.html.twig

[NodeBundle] Fix the possibility to publish and unpublish today

---

src/Kunstmaan/AdminBundle/Resources/ui/scss/default-theme/components/forms/_date-time-group.scss
src/Kunstmaan/AdminBundle/Resources/ui/scss/default-theme/components/structures/_pp.scss

[AdminBundle] Fix the datepickers not overflowing their containers

---

src/Kunstmaan/NodeBundle/EventListener/NodeTranslationListener.php

[NodeBundle] Slugify the slug when saving the page

---

.gitignore
src/Kunstmaan/AdminBundle/.travis.yml
src/Kunstmaan/AdminListBundle/.travis.yml
src/Kunstmaan/ArticleBundle/.travis.yml
src/Kunstmaan/BehatBundle/.travis.yml
src/Kunstmaan/DashboardBundle/.travis.yml
src/Kunstmaan/FormBundle/.travis.yml
src/Kunstmaan/GeneratorBundle/.travis.yml
src/Kunstmaan/LanguageChooserBundle/.travis.yml
src/Kunstmaan/LiveReloadBundle/.travis.yml
src/Kunstmaan/MediaBundle/.travis.yml
src/Kunstmaan/MediaPagePartBundle/.travis.yml
src/Kunstmaan/NodeBundle/.travis.yml
src/Kunstmaan/NodeSearchBundle/.travis.yml
src/Kunstmaan/PagePartBundle/.travis.yml
src/Kunstmaan/RedirectBundle/.travis.yml
src/Kunstmaan/SearchBundle/.travis.yml
src/Kunstmaan/SeoBundle/.travis.yml
src/Kunstmaan/SitemapBundle/.travis.yml
src/Kunstmaan/TaggingBundle/.travis.yml
src/Kunstmaan/TranslatorBundle/.travis.yml
src/Kunstmaan/UserManagementBundle/.travis.yml
src/Kunstmaan/UtilitiesBundle/.travis.yml
src/Kunstmaan/VotingBundle/.travis.yml

For more info see:
http://docs.travis-ci.com/user/migrating-from-legacy/?utm_source=legacy-notice&utm_medium=banner&utm_campaign=legacy-upgrade

[Tests] Use new travis config for submodules and bring them in line with eachother

---

docs/04-05-adding-a-search-engine.md

So I'm suggesting an update. AFAIK this should put the docs in line with the implementation.

[Documentation] Update the search docs

---

src/Kunstmaan/NodeBundle/EventListener/NodeTranslationListener.php

Pull request #558 is breaking the slug for root nodes.

Don't ensure slug for root nodes (broken after #558)

---

src/Kunstmaan/AdminBundle/Resources/views/Default/_js_footer.html.twig

Added missing assetic dependency for icon-chooser.js

---

src/Kunstmaan/TaggingBundle/Entity/TagManager.php

[TaggingBundle] Change parameter type to BaseTaggable

---

docs/05-01-going-single-language.md

change parameters.yml.dist so these changes are part of the repo. parameters so they work locally

[Documentation] Update the single language documentation

---

src/Kunstmaan/AdminBundle/Resources/ui/js/_datepicker.js
src/Kunstmaan/AdminBundle/Resources/ui/js/_pagepart-editor.js

[AdminBundle] Fix the datepicker with new added fields

---

src/Kunstmaan/PagePartBundle/Resources/views/PagePartAdminTwigExtension/pagepart.html.twig

This PR fixes the back-end rendering of pageparts that contain bootstrap3 columns.

[PagePartBundle] fix for pageparts containing bootstrap3 columns

---

src/Kunstmaan/MenuBundle/Entity/MenuItem.php
src/Kunstmaan/MenuBundle/Twig/MenuTwigExtension.php

[MenuBundle] Make it possible to show hidden from nav menu nodes via the menu bundle twig extension

---

src/Kunstmaan/GeneratorBundle/Command/GenerateEntityCommand.php

This isn't the pagepart generator context.

[GeneratorBundle] Fix minor typo

---

src/Kunstmaan/MediaBundle/Helper/RemoteSlide/RemoteSlideHandler.php
src/Kunstmaan/MediaBundle/Resources/views/Media/RemoteSlide/preview.html.twig

[MediaBundle] Fixed 404 slideshare embed code

---

src/Kunstmaan/AdminBundle/Helper/Security/Acl/AclHelper.php

[AdminBundle] Fixed warning in acl helper on exception handling

---

src/Kunstmaan/AdminBundle/Resources/ui/js/_pagepart-editor.js

[NodeBundle] Prevent add pagepart from blocking page

---

src/Kunstmaan/AdminListBundle/Controller/AdminListController.php

This event is being fired only from the edit action right now, so it's impossible to add tabs via event listener for a new entity. #349

[AdminListBundle] Dispatch ADAPT_SIMPLE_FORM event in the AdminListController add action

---

src/Kunstmaan/AdminBundle/Resources/ui/js/_rich-editor.js

[AdminBundle] Allow custom ckeditor height

---

src/Kunstmaan/AdminBundle/Resources/ui/js/_auto-collapse-tabs.js

[AdminBundle] Fix js error in media chooser

---

src/Kunstmaan/AdminBundle/Resources/ui/js/_pagepart-editor.js
src/Kunstmaan/AdminBundle/Resources/ui/scss/default-theme/components/structures/_pp.scss
src/Kunstmaan/PagePartBundle/Resources/translations/messages.en.yml
src/Kunstmaan/PagePartBundle/Resources/views/PagePartAdminTwigExtension/pagepart.html.twig

[PagePartBundle] Added move up/down buttons for re-ordering pageparts

---

src/Kunstmaan/NodeBundle/Controller/NodeAdminController.php
src/Kunstmaan/NodeBundle/EventListener/NodeListener.php
src/Kunstmaan/NodeBundle/Form/NodeMenuTabAdminType.php
src/Kunstmaan/NodeBundle/Form/NodeMenuTabTranslationAdminType.php
src/Kunstmaan/SeoBundle/EventListener/NodeListener.php

[NodeBundle] Make it possible to configure internalName and weight for structure nodes

---

src/Kunstmaan/AdminBundle/Command/CreateUserCommand.php

| Fixed tickets | Fixes PR #614
You can now either pass a groupname or a group number (interactive suggestion).

[AdminBundle] Fix CreateUserCommand with --group option

---

src/Kunstmaan/FixturesBundle/Builder/PagePartBuilder.php

[FixturesBundle] Make sure pagepart translations are saved in fixtures

---

src/Kunstmaan/PagePartBundle/Resources/views/FormWidgets/PageTemplateWidget/widget.html.twig

Translate the names of contexts.

[PagePartBundle] Translate context names

---

src/Kunstmaan/MenuBundle/Twig/MenuTwigExtension.php

Adds an option to set a class on the currently active link in  a menu.

[MenuBundle] Add option for activeClass on links for MenuBundle

---

src/Kunstmaan/FixturesBundle/Builder/PageBuilder.php

[FixturesBundle] Add option to set pagetemplate in fixtures

---

src/Kunstmaan/SeoBundle/Resources/views/Admin/Settings/robotsSettings.html.twig

This way it can be easily customised when using the boekkooi/twig-jack-bundle.

[SEOBundle] Wrap cookbook information in block tag

---

src/Kunstmaan/AdminBundle/Resources/views/layout.html.twig

This way it can be easily customised when using the `boekkooi/twig-jack-bundle`.

[AdminBundle] Wrap the login logo in a block tag

---

src/Kunstmaan/FixturesBundle/Builder/PagePartBuilder.php

[FixturesBundle] Insights fix for fixtures

---

src/Kunstmaan/AdminBundle/Resources/ui/js/_url-chooser.js

Trigger javascript change events when an url or media is selected

[AdminBundle] Trigger change event for urlChooser and mediaChooser

---

src/Kunstmaan/MultiDomainBundle/Helper/DomainConfiguration.php
src/Kunstmaan/NodeBundle/Helper/DomainConfiguration.php

[MultiDomainBundle] Cache root node

---

src/Kunstmaan/RedirectBundle/Form/RedirectAdminType.php

[RedirectBundle] remove double input info

---

src/Kunstmaan/NodeBundle/Event/Events.php

[NodeBundle] Documentation fix

---

src/Kunstmaan/MenuBundle/Controller/MenuItemAdminListController.php

[MenuBundle] Make it possible to move menu items up/down

---

UPGRADE-3.3.md

[Documentation] Fix upgrade to 3.3 command

---

src/Kunstmaan/NodeBundle/EventListener/NodeTranslationListener.php
src/Kunstmaan/NodeBundle/Resources/config/services.yml

| Fixed tickets | #594
Following the request from @krispypen. I haven’t ran the code yet.

[NodeBundle] don’t use session if not in request scope

---

src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/searchpage/Resources/views/Pages/SearchPage/view.html.twig

| Fixed tickets | #709 
Fixed exception for top level search results

[GeneratorBundle] fixed exception for top level search results

---

src/Kunstmaan/NodeBundle/Controller/NodeAdminController.php
src/Kunstmaan/NodeBundle/Repository/NodeTranslationRepository.php

Set logical default weight for subpages.

[NodeBundle] Set default weight for new subpage

---

src/Kunstmaan/AdminBundle/autoload.php.dist
src/Kunstmaan/AdminBundle/phpunit.xml.dist

[AdminBundle] fix annotation autoloading for tests

---

src/Kunstmaan/FormBundle/AdminList/FormPageAdminListConfigurator.php
src/Kunstmaan/FormBundle/AdminList/FormSubmissionAdminListConfigurator.php

[FormBundle] fix view icon

---

src/Kunstmaan/MediaBundle/Controller/FolderController.php
src/Kunstmaan/MediaBundle/Resources/views/Folder/foldertreeview.html.twig
src/Kunstmaan/MediaBundle/Resources/views/Folder/show.html.twig
src/Kunstmaan/MediaBundle/Resources/views/Media/show.html.twig

[MediaBundle] fix folder position saving via drag and drop

---

src/Kunstmaan/MediaBundle/Controller/FolderController.php

[FolderBundle] refactor reorderAction

---

src/Kunstmaan/MediaBundle/Helper/RemoteVideo/RemoteVideoHandler.php
src/Kunstmaan/MediaBundle/Tests/Helper/RemoteVideo/RemoteVideoHandlerTest.php

[MediaBundle] add parsing youtu.be urls

---

src/Kunstmaan/AdminBundle/Resources/ui/js/_rich-editor.js

As requested by @kimausloos & @indrikenens

[AdminBundle] add div wrapper to tables

---

src/Kunstmaan/LeadGenerationBundle/Resources/views/AdminList/popup-edit.html.twig
src/Kunstmaan/LeadGenerationBundle/Resources/views/AdminList/rules-edit.html.twig

In some cases edit is used for add, then the fallback is required.

[LeadGenerationBundle] Handle type via request url as fallback

---

src/Kunstmaan/MediaBundle/Helper/File/FileHandler.php

[MediaBundle] Fixed image file extension

---

src/Kunstmaan/TranslatorBundle/Form/TranslationAdminType.php

[TranslatorBundle] add missing use statement

---

src/Kunstmaan/AdminBundle/Resources/views/Default/sidebar.html.twig

[AdminBundle] Fix admin sidebar when NodeBundle is not used

---

src/Kunstmaan/AdminBundle/Resources/ui/js/_pagepart-editor.js

This can be used if you need advanced JS functionality for custom
pageparts.
Fixes #695
| Fixed tickets | #695

[AdminBundle] Make PagePartEditor emit events on add, edit and delete

---

UPGRADE-3.4.md

upgrade doc v3.3 -> v3.4

---

phpunit.xml.dist
src/Kunstmaan/AdminBundle/Tests/Helper/DomainConfigurationTest.php
src/Kunstmaan/MultiDomainBundle/Helper/DomainConfiguration.php
src/Kunstmaan/MultiDomainBundle/Tests/EventListener/HostOverrideListenerTest.php
src/Kunstmaan/MultiDomainBundle/Tests/Helper/AdminPanel/SitesAdminPanelAdaptorTest.php
src/Kunstmaan/MultiDomainBundle/Tests/Helper/DomainConfigurationTest.php
src/Kunstmaan/MultiDomainBundle/Tests/Helper/HostOverrideCleanupHandlerTest.php
src/Kunstmaan/MultiDomainBundle/Tests/Router/DomainBasedLocaleRouterTest.php
src/Kunstmaan/NodeBundle/Router/SlugRouter.php
src/Kunstmaan/NodeBundle/Tests/Router/SlugRouterTest.php

[Tests] unit tests + small fixes

---

src/Kunstmaan/MediaBundle/Form/AbstractRemoteType.php
src/Kunstmaan/MediaBundle/Form/RemoteAudio/RemoteAudioType.php
src/Kunstmaan/MediaBundle/Form/RemoteSlide/RemoteSlideType.php
src/Kunstmaan/MediaBundle/Form/RemoteVideo/RemoteVideoType.php

[MediaBundle] Refactor remote media types

---

src/Kunstmaan/AdminBundle/EventListener/PasswordCheckListener.php

[AdminBundle] fix admin 404 (#169)

---

src/Kunstmaan/AdminBundle/Resources/ui/js/_auto-collapse-buttons.js
src/Kunstmaan/NodeBundle/Helper/Menu/ActionsMenuBuilder.php

[NodeBundle] Show publish button when editing a page

---

src/Kunstmaan/SeoBundle/Resources/views/SeoTwigExtension/metadata.html.twig

[SeoBundle] Add extra tags OG tags

---

src/Kunstmaan/MenuBundle/Twig/MenuTwigExtension.php

[MenuBundle] Let define extra link classes to decorator

---

src/Kunstmaan/NodeBundle/Form/Type/SlugType.php
src/Kunstmaan/NodeBundle/Resources/config/services.yml

| Q               | A
| Fixed tickets | #753

[NodeBundle] fix slug refresh button behaviour

---

src/Kunstmaan/MenuBundle/Twig/MenuTwigExtension.php

It is called with swapped attributes on line 68

[MenuBundle] Swap default options paramers

---

UPGRADE-3.4.md

| Fixed tickets | Added documentation

[Documentation] Added documentation for Social and Seo update

---

src/Kunstmaan/MediaBundle/Helper/File/FileHandler.php

[MediaBundle] fix remove percent sign from filename when uploading

---

src/Kunstmaan/SeoBundle/Resources/views/SeoTwigExtension/metadata.html.twig

Older versions of the bundles have an issue. They didn't have original_height/width in there metadata.
This pull request will check if it exists.

[SeoBundle] Check for older bundles version

---

docs/05-06-using-the-leadgenerationbundle.md
src/Kunstmaan/LeadGenerationBundle/DependencyInjection/Configuration.php
src/Kunstmaan/LeadGenerationBundle/DependencyInjection/KunstmaanLeadGenerationExtension.php
src/Kunstmaan/LeadGenerationBundle/Resources/config/services.yml
src/Kunstmaan/LeadGenerationBundle/Resources/views/Newsletter/index.html.twig
src/Kunstmaan/LeadGenerationBundle/Resources/views/initialize-js.html.twig
src/Kunstmaan/LeadGenerationBundle/Twig/PopupTwigExtension.php

[LeadGenerationBundle] Improved in the documentation and twig demo templates + added debug configuration parameter

---

src/Kunstmaan/AdminBundle/Command/CreateUserCommand.php

[AdminBundle] Fix assigning groups to user in kuma:user:create command

---

src/Kunstmaan/LeadGenerationBundle/Entity/Rule/OnExitIntentRule.php
src/Kunstmaan/LeadGenerationBundle/Form/Rule/OnExitIntentAdminType.php
src/Kunstmaan/LeadGenerationBundle/Resources/public/js/rule/OnExitIntentRule.js
src/Kunstmaan/LeadGenerationBundle/Resources/translations/messages.en.yml
src/Kunstmaan/LeadGenerationBundle/Service/PopupManager.php

[LeadGenerationBundle] Added extra lead generation rule: on exit intent

---

src/Kunstmaan/SeoBundle/Resources/views/SeoTwigExtension/metadata.html.twig

Q             | A
We should also consider moving to xx_XX locales in the default settings.

[SeoBundle] Facebook only accepts locales in format xx_XX

---

src/Kunstmaan/MediaBundle/Helper/File/FileHandler.php

Backporting #780 into the 3.2 branch

[MediaBundle] Proposed fix/feature for web safe filenames

---

src/Kunstmaan/AdminListBundle/AdminList/Configurator/AbstractDoctrineORMAdminListConfigurator.php

[AdminListBundle] Fix for ORM adminlist to allow setting a custom number of items per page

---

src/Kunstmaan/MenuBundle/Twig/MenuTwigExtension.php

Add separate function to get menu items

---

src/Kunstmaan/SeoBundle/Twig/SeoTwigExtension.php

Backport of #788 to the 3.1 branch

[SeoBundle] Add cache to SeoTwigExtension

---

src/Kunstmaan/DashboardBundle/Resources/translations/messages.de.yml

German translation for the dashboard widget.

added german dashboard translation

---

src/Kunstmaan/SeoBundle/Resources/views/SeoTwigExtension/metadata.html.twig

A typo was discovered in the article meta tags.

[SeoBundle] Closed article meta tags

---

src/Kunstmaan/MediaBundle/Resources/translations/messages.en.yml
src/Kunstmaan/MediaBundle/Resources/views/Chooser/chooserShowFolder.html.twig

[MediaBundle] Add 'Add media' button translation

---

src/Kunstmaan/LeadGenerationBundle/Controller/PopupsAdminListController.php
src/Kunstmaan/MenuBundle/Controller/MenuAdminListController.php
src/Kunstmaan/MenuBundle/Controller/MenuItemAdminListController.php

| Fixed tickets | insights fixes

[MenuBundle, LeadgenerationBundle] Removed unused use statements and add typehints

---

src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/Resources/views/Layout/layout.html.twig

[GeneratorBundle] Spaceless in layout twig

---

src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/Resources/views/Layout/_favicons.html.twig

[GeneratorBundle] Favicons

---

src/Kunstmaan/MenuBundle/Controller/MenuItemAdminListController.php
src/Kunstmaan/MenuBundle/Entity/BaseMenuItem.php
src/Kunstmaan/MenuBundle/Entity/MenuItem.php
src/Kunstmaan/MenuBundle/Form/MenuItemAdminType.php

This should fix the problem of not being able to choose a parent when extending a menu entity.

[MenuBundle] Fix parent menu item in menu edit form

---

src/Kunstmaan/NodeBundle/Repository/NodeRepository.php

[NodeBundle] Also expose the NodeTranslation id in link chooser template

---

src/Kunstmaan/SeoBundle/Form/SeoType.php

Fix bad SeoType::NOFOLLOW value

[SeoBundle] Fix bad NOFOLLOW value in SeoType

---

src/Kunstmaan/AdminBundle/Resources/ui/scss/default-theme/general/_app__content.scss
src/Kunstmaan/NodeBundle/Resources/views/NodeAdmin/edit.html.twig

[AdminBundle] Add indication that page is online/offline

---

src/Kunstmaan/AdminBundle/Resources/ui/js/_auto-collapse-tabs.js

[AdminBundle] Fix -is not a function- bug

---

src/Kunstmaan/NodeBundle/Form/Type/SlugType.php

SlugType should accept any implementation of SlugifierInterface.

[NodeBundle] Make SlugType accept SlugifierInterface

---

src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/pagepart/Resources/views/PageParts/ImagePagePart/view.html.twig

Add a check for GIF images (do not apply an imagine filter)

[GeneratorBundle] Add check for GIF's in image-pp

---

src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/gulp/.groundcontrolrc

Add woff2 to default .groundcontrolrc

[GeneratorBundle] Add woff2 to Ground Control

---

docs/05-09-defining-custom-ckeditor-configuration.md
docs/05-10-structure-pages
docs/05-11-adding-a-custom-controller.md

A few bits of documentation:
- how to make custom configurations for the wysiwyg form type.
- how to create structure pages

[Documentation] Cookbook items containing some documentation

---

src/Kunstmaan/AdminBundle/Resources/ui/scss/default-theme/general/_login.scss
src/Kunstmaan/AdminBundle/Resources/views/ChangePassword/changePassword.html.twig
src/Kunstmaan/AdminBundle/Resources/views/ChangePassword/changePassword_content.html.twig

[AdminBundle] Correct styling for Change password form errors

---

src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/pagepart/Resources/views/PageParts/VideoPagePart/view.html.twig

[GeneratorBundle] Videopp adding compatibility for Vimeo and Dailymotion

---

docs/01-00-introduction.md
docs/03-02-development-environment.md

[Documentation] Fixed typo + puphpet image in docs

---

UPGRADE-3.4.md

[SeoBundle, Documentation] Added removal of SEOtags to release notes

---

src/Kunstmaan/MenuBundle/Service/MenuService.php

[MenuBundle] Make sure there are no duplicate locales in the list

---

src/Kunstmaan/AdminListBundle/Controller/AdminListController.php
src/Kunstmaan/LeadGenerationBundle/Entity/Rule/LocaleBlacklistRule.php
src/Kunstmaan/LeadGenerationBundle/Entity/Rule/LocaleWhitelistRule.php
src/Kunstmaan/LeadGenerationBundle/Form/Rule/LocaleBlackListAdminType.php
src/Kunstmaan/LeadGenerationBundle/Form/Rule/LocaleWhiteListAdminType.php
src/Kunstmaan/LeadGenerationBundle/Resources/config/services.yml
src/Kunstmaan/LeadGenerationBundle/Resources/public/js/rule/LocaleBlacklistRule.js
src/Kunstmaan/LeadGenerationBundle/Resources/public/js/rule/LocaleWhitelistRule.js
src/Kunstmaan/LeadGenerationBundle/Service/Rule/LocaleRuleService.php

Add 2 new rules to the LeadGenerationBundle.

[LeadGenerationBundle] Add LocaleBlacklistRule and LocaleWhitelistRule

---

src/Kunstmaan/AdminListBundle/Resources/config/services.yml
src/Kunstmaan/AdminListBundle/Resources/views/AdminListTwigExtension/widget.html.twig
src/Kunstmaan/AdminListBundle/Service/Pager/TwitterBootstrapAdminListTemplate.php
src/Kunstmaan/AdminListBundle/Service/Pager/TwitterBootstrapAdminListView.php

| Fixed tickets | 867
https://github.com/Kunstmaan/KunstmaanBundlesCMS/issues/867

[AdminListBundle] Fixed display page 1

---

src/Kunstmaan/MediaBundle/Helper/RemoteVideo/RemoteVideoHandler.php

| Fixed tickets | https://github.com/Kunstmaan/KunstmaanBundlesCMS/issues/858

[MediaBundle] better thumb for youtube media

---

src/Kunstmaan/MediaBundle/Resources/views/Chooser/chooserShowFolder.html.twig

| Fixed tickets | https://github.com/Kunstmaan/KunstmaanBundlesCMS/issues/623

[MediaBundle] fix media handler issue

---

src/Kunstmaan/AdminBundle/Resources/ui/scss/default-theme/general/_app__header.scss
src/Kunstmaan/AdminBundle/Resources/views/layout.html.twig

added brand logo on login page [AdminBundle]

---

src/Kunstmaan/AdminBundle/Command/CreateUserCommand.php

| Fixed tickets | https://github.com/Kunstmaan/KunstmaanBundlesStandardEdition/issues/178

[AdminBundle] refactor create user command

---

src/Kunstmaan/GeneratorBundle/Generator/KunstmaanGenerator.php
src/Kunstmaan/GeneratorBundle/Generator/LayoutGenerator.php
src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/Resources/views/Default/index.html.twig
src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/Resources/views/Layout/_header.html.twig
src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/Resources/views/Layout/layout.html.twig
src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/Resources/views/Page/layout.html.twig

| Fixed tickets | https://github.com/Kunstmaan/KunstmaanBundlesCMS/issues/864

[GeneratorBundle] Change default twig includes

---

src/Kunstmaan/TaggingBundle/AdminList/TagAdminListConfigurator.php

| Fixed tickets | https://github.com/Kunstmaan/KunstmaanBundlesStandardEdition/issues/176

[TaggingBundle] Fix created/updated fieldnames

---

src/Kunstmaan/AdminBundle/Resources/ui/scss/default-theme/components/blocks/_buttons.scss
src/Kunstmaan/AdminBundle/Resources/ui/scss/default-theme/helpers/_helper-classes.scss
src/Kunstmaan/MediaBundle/Resources/translations/messages.de.yml
src/Kunstmaan/MediaBundle/Resources/translations/messages.en.yml
src/Kunstmaan/MediaBundle/Resources/translations/messages.fr.yml
src/Kunstmaan/MediaBundle/Resources/translations/messages.it.yml
src/Kunstmaan/MediaBundle/Resources/views/Chooser/chooserShowFolder.html.twig
src/Kunstmaan/MediaBundle/Resources/views/Folder/show.html.twig

with icon and actio_short translation in four languages.

[MediaBundle] added short version of delete and add folder btns 

---

src/Kunstmaan/GeneratorBundle/Command/GenerateAdminTestsCommand.php
src/Kunstmaan/GeneratorBundle/Command/GenerateBundleCommand.php
src/Kunstmaan/GeneratorBundle/Helper/InputAssistant.php

| Fixed tickets | https://github.com/Kunstmaan/KunstmaanBundlesCMS/issues/811

[GeneratorBundle] Namespace bug in generator

---

src/Kunstmaan/AdminBundle/Resources/ui/scss/default-theme/general/_app__header.scss

[MainBundle] fixed responsiveness main nav

---

docs/07-05-Roadmap.md

Created a roadmap.md file based on @jockri 's post.
| Fixed tickets | #828

[Documentation] Create roadmap.md

---

docs/07-05-roadmap.md

[Documentations] Updated roadmap

---

src/Kunstmaan/AdminBundle/Resources/ui/js/_pagepart-editor.js
src/Kunstmaan/AdminBundle/Resources/ui/scss/default-theme/components/structures/_page-template.scss
src/Kunstmaan/AdminBundle/Resources/ui/scss/default-theme/components/structures/_pp.scss
src/Kunstmaan/AdminBundle/Resources/ui/scss/default-theme/config/general/_colors.scss
src/Kunstmaan/PagePartBundle/Resources/translations/messages.en.yml
src/Kunstmaan/PagePartBundle/Resources/views/FormWidgets/PageTemplateWidget/widget.html.twig
src/Kunstmaan/PagePartBundle/Resources/views/PagePartAdminTwigExtension/pagepart.html.twig

Minimize-maximize each pp, min-max pp per region, view scroll when moving pp.
| Fixed tickets | #216

[PagePartBundle, AdminBundle] resizing pp + scroll when pp moves

---

src/Kunstmaan/MediaBundle/Resources/views/Folder/show.html.twig

[MediaBundle] sorting of media in thumb-view

---

src/Kunstmaan/MediaBundle/Resources/translations/messages.en.yml
src/Kunstmaan/MediaBundle/Resources/views/Folder/show.html.twig

[MediaBundle] theme sorting of media in thumb-view correctly

---

src/Kunstmaan/MediaBundle/Resources/views/Chooser/chooserShowFolder.html.twig
src/Kunstmaan/MediaBundle/Resources/views/Folder/show.html.twig
src/Kunstmaan/MediaBundle/Resources/views/Form/formWidgets.html.twig

[MediaBundle] fix retina filter for mediabundle

---

src/Kunstmaan/AdminBundle/Helper/FormWidgets/Tabs/TabPane.php
src/Kunstmaan/AdminBundle/Twig/AdminPermissionsTwigExtension.php
src/Kunstmaan/AdminBundle/Twig/LocaleSwitcherTwigExtension.php
src/Kunstmaan/AdminBundle/Twig/TabsTwigExtension.php
src/Kunstmaan/AdminListBundle/Twig/AdminListTwigExtension.php
src/Kunstmaan/DashboardBundle/Controller/GoogleAnalyticsController.php
src/Kunstmaan/DashboardBundle/Helper/Google/ClientHelper.php
src/Kunstmaan/NodeBundle/Entity/Node.php
src/Kunstmaan/NodeBundle/Entity/NodeTranslation.php
src/Kunstmaan/NodeSearchBundle/Twig/KunstmaanNodeSearchTwigExtension.php
src/Kunstmaan/PagePartBundle/Helper/PagePartConfigurationReader.php
src/Kunstmaan/PagePartBundle/Helper/PageTemplateConfigurationReader.php
src/Kunstmaan/PagePartBundle/Twig/Extension/PagePartAdminTwigExtension.php
src/Kunstmaan/PagePartBundle/Twig/Extension/PagePartTwigExtension.php
src/Kunstmaan/PagePartBundle/Twig/Extension/PageTemplateTwigExtension.php
src/Kunstmaan/TranslatorBundle/Service/Translator/Translator.php

Removing and changing deprecated functions:
- Changing all twig extensions with the environment
- Remove cascade validation and change to Asset/Valid on Entity
- Remove deprecated isScopeActive call on container

Fix#deprecations 2.8

---

src/Kunstmaan/AdminBundle/Resources/ui/js/_characters-left.js
src/Kunstmaan/AdminBundle/Resources/ui/js/app.js
src/Kunstmaan/AdminBundle/Resources/ui/scss/default-theme/components/forms/_form-control.scss
src/Kunstmaan/AdminBundle/Resources/ui/scss/default-theme/components/forms/_form-group.scss
src/Kunstmaan/AdminBundle/Resources/ui/scss/default-theme/config/general/_colors.scss
src/Kunstmaan/AdminBundle/Resources/views/Form/fields.html.twig

[AdminBundle] character counter for input fields with a limited character count

---

src/Kunstmaan/AdminBundle/Resources/views/ChangePassword/changePassword_content.html.twig
src/Kunstmaan/AdminBundle/Resources/views/Default/editIndex.html.twig
src/Kunstmaan/AdminBundle/Resources/views/Resetting/reset_content.html.twig
src/Kunstmaan/AdminListBundle/Resources/views/Default/add_or_edit.html.twig
src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/defaultsite/Resources/views/Pages/FormPage/pagetemplate.html.twig
src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/formpage/Resources/views/Pages/FormPage/pagetemplate.html.twig
src/Kunstmaan/MediaBundle/Resources/views/Folder/addsub-modal.html.twig
src/Kunstmaan/MediaBundle/Resources/views/Folder/show.html.twig
src/Kunstmaan/MediaBundle/Resources/views/Media/addType-modal.html.twig
src/Kunstmaan/MediaBundle/Resources/views/Media/create.html.twig
src/Kunstmaan/MediaBundle/Resources/views/Media/show.html.twig
src/Kunstmaan/NodeBundle/Resources/views/NodeAdmin/edit.html.twig
src/Kunstmaan/TranslatorBundle/Resources/views/Translator/addTranslation.html.twig
src/Kunstmaan/TranslatorBundle/Resources/views/Translator/editTranslation.html.twig
src/Kunstmaan/UserManagementBundle/Resources/views/Groups/add.html.twig
src/Kunstmaan/UserManagementBundle/Resources/views/Groups/edit.html.twig
src/Kunstmaan/UserManagementBundle/Resources/views/Roles/add.html.twig
src/Kunstmaan/UserManagementBundle/Resources/views/Roles/edit.html.twig
src/Kunstmaan/UserManagementBundle/Resources/views/Users/add.html.twig
src/Kunstmaan/UserManagementBundle/Resources/views/Users/edit.html.twig

[AllBundles] Deprecated form_enctype, replace it with correct form_start

---

src/Kunstmaan/AdminBundle/Entity/Group.php
src/Kunstmaan/MenuBundle/Entity/BaseMenuItem.php
src/Kunstmaan/MenuBundle/Entity/MenuItem.php

[AdminBundle, MenuBundle] deprecated Assert\Callback on entity, put it above function instead

---

src/Kunstmaan/NodeBundle/Entity/HasNodeInterface.php
src/Kunstmaan/NodeBundle/Entity/HideFromNodeTreeInterface.php
src/Kunstmaan/NodeSearchBundle/Helper/SearchTypeInterface.php

[NodeBundle, NodeSearchBundle] Remove some deprecations

---

src/Kunstmaan/AdminBundle/Resources/views/Default/_js_footer.html.twig

[AdminBundle] Characters-left javascript needs to be added to the js_footer for assetic dumping

---

src/Kunstmaan/TaggingBundle/Entity/TagManager.php

The Tags collection need to be cloned before saveTagging

[TaggingBundle] Lost old tags after adding new one to an entity

---

src/Kunstmaan/AdminListBundle/Resources/views/Default/export.csv.twig

Took over this pull request bc the original poster did not respond for some time.
CSV export: Fix issue where only first row below the header has content.
| New feature?  | |no
| BC breaks?    | |no
| Fixed tickets | #822

[AdminlistBundle] Update issue 822 export.csv.twig

---

composer.json

[Composer] Fix imagine version in bundles

---

composer.json
src/Kunstmaan/MediaBundle/composer.json

[Composer ]Use imagine v5.0 to fix background filter

---

src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/defaultsite/Form/PageParts/UspPagePartAdminType.php
src/Kunstmaan/TranslatorBundle/Form/TranslationAdminType.php

[GeneratorBundle, TranslatorBundle] The option "type" of the CollectionType has been renamed to "entry_type"

---

src/Kunstmaan/AdminBundle/Form/UserType.php
src/Kunstmaan/UserManagementBundle/Controller/UsersController.php

[AdminBundle, UserManagementBundle]: Change argument passing to form type

---

src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/Resources/views/Layout/_css.html.twig
src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/Resources/views/Layout/_js_header.html.twig

[GenerarorBundle] Fix assets_version deprecated messages

---

src/Kunstmaan/AdminBundle/Helper/FormWidgets/FormWidget.php
src/Kunstmaan/AdminBundle/Helper/FormWidgets/Tabs/TabPane.php
src/Kunstmaan/AdminBundle/Resources/doc/FormCollectionAdditions.md
src/Kunstmaan/AdminListBundle/Controller/AdminListController.php
src/Kunstmaan/AdminListBundle/Resources/doc/AdminListBundle.md
src/Kunstmaan/FormBundle/Entity/PageParts/CheckboxPagePart.php
src/Kunstmaan/FormBundle/Entity/PageParts/ChoicePagePart.php
src/Kunstmaan/FormBundle/Entity/PageParts/EmailPagePart.php
src/Kunstmaan/FormBundle/Entity/PageParts/FileUploadPagePart.php
src/Kunstmaan/FormBundle/Entity/PageParts/MultiLineTextPagePart.php
src/Kunstmaan/FormBundle/Entity/PageParts/SingleLineTextPagePart.php
src/Kunstmaan/FormBundle/Helper/FormHandler.php
src/Kunstmaan/PagePartBundle/Controller/PagePartAdminController.php
src/Kunstmaan/PagePartBundle/PagePartAdmin/PagePartAdmin.php
src/Kunstmaan/PagePartBundle/Resources/doc/PagePartBundle.md
src/Kunstmaan/UserManagementBundle/Controller/UsersController.php

[AllBundles]: use fully qualified class names for forms

---

UPGRADE-3.5.md
src/Kunstmaan/AdminListBundle/Controller/AdminListController.php
src/Kunstmaan/ArticleBundle/Controller/AbstractArticleAuthorAdminListController.php
src/Kunstmaan/ArticleBundle/Controller/AbstractArticlePageAdminListController.php
src/Kunstmaan/NodeSearchBundle/Configuration/NodePagesConfiguration.php

[AdminBundle, ArticleBundle] remove dep getRequest()

---

src/Kunstmaan/AdminBundle/Helper/FormWidgets/Tabs/TabPane.php

[AdminBundle]: Add use statement for form type

---

src/Kunstmaan/GeneratorBundle/Command/KunstmaanGenerateCommand.php

[GeneratorBundle]: getEntityManager deprecated

---

.travis.yml
src/Kunstmaan/MediaBundle/Helper/Transformer/PdfTransformer.php
src/Kunstmaan/MediaBundle/Resources/config/services.yml
src/Kunstmaan/MenuBundle/Resources/config/services.yml
src/Kunstmaan/NodeBundle/Resources/config/services.yml
src/Kunstmaan/RedirectBundle/Resources/config/services.yml
src/Kunstmaan/TranslatorBundle/Resources/config/repositories.yml

[AllBundles]: remove deprecation notices

---

src/Kunstmaan/LeadGenerationBundle/Controller/AbstractNewsletterController.php

[LeadGenerationbundle] deprecation fix

---

composer.json

[Composer] Update sensio distribution bundle for symfony 2.8

---

src/Kunstmaan/AdminBundle/Resources/ui/js/_pagepart-editor.js

[AdminBundle]: targetId needs dollar sine

---

composer.json

[Composer]: update assetic bundle

---

src/Kunstmaan/FormBundle/Form/ChoiceFormSubmissionType.php
src/Kunstmaan/FormBundle/Form/ChoicePagePartAdminType.php
src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/defaultsite/Resources/views/PageParts/PageBannerPagePart/view.html.twig
src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/defaultsite/Resources/views/PageParts/ServicePagePart/view.html.twig
src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/pagepart/Resources/views/PageParts/ImagePagePart/view.html.twig
src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/pagepart/Resources/views/PageParts/VideoPagePart/view.html.twig
src/Kunstmaan/MediaBundle/Helper/RemoteVideo/RemoteVideoHandler.php
src/Kunstmaan/MediaBundle/Resources/views/Chooser/chooserShowFolder.html.twig
src/Kunstmaan/MediaBundle/Resources/views/Folder/show.html.twig
src/Kunstmaan/MediaBundle/Resources/views/Form/formWidgets.html.twig
src/Kunstmaan/MediaBundle/Resources/views/Media/Image/show.html.twig

[AllBundles]: fixes for symfony 2.8 compability

---

src/Kunstmaan/AdminListBundle/AdminList/FilterType/DBAL/DateFilterType.php
src/Kunstmaan/AdminListBundle/AdminList/FilterType/DBAL/DateTimeFilterType.php
src/Kunstmaan/AdminListBundle/AdminList/FilterType/ORM/DateTimeFilterType.php

[AdminListBundle]: add validation for datetime #807

---

src/Kunstmaan/NodeBundle/Entity/NodeTranslation.php

[MediaBundle] validate slug input

---

src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/Controller/AuthorAdminListController.php
src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/Controller/PageAdminListController.php

[GeneratorBundle]: request needs to be passed in generatorbundle

---

src/Kunstmaan/MediaBundle/Resources/ui/js/_bulk-upload.js

[MediaBundle] fix bulk upload errors display

---

src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/Resources/views/Layout/_css.html.twig
src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/Resources/views/Layout/_js_header.html.twig
src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/Resources/views/Layout/layout.html.twig

[GeneratorBundle] Remove style-ie9.min.css & _js_header.html.twig

---

src/Kunstmaan/SeoBundle/DependencyInjection/KunstmaanSeoExtension.php
src/Kunstmaan/SeoBundle/Resources/config/imagine_filters.yml
src/Kunstmaan/SeoBundle/Resources/views/SeoTwigExtension/metadata.html.twig
src/Kunstmaan/SeoBundle/Twig/SeoTwigExtension.php

[SeoBundle]: add imagine filter for seo images, refs #765

---

src/Kunstmaan/MediaBundle/Resources/views/Folder/show.html.twig

[MediaBundle]: check if imageurlretina is defined, refs #978

---

src/Kunstmaan/NodeBundle/Controller/NodeAdminController.php
src/Kunstmaan/NodeBundle/Event/Events.php
src/Kunstmaan/NodeBundle/Event/RecopyPageTranslationNodeEvent.php
src/Kunstmaan/NodeBundle/EventListener/LogPageEventsSubscriber.php
src/Kunstmaan/NodeBundle/Helper/Menu/ActionsMenuBuilder.php
src/Kunstmaan/NodeBundle/Repository/NodeTranslationRepository.php
src/Kunstmaan/NodeBundle/Resources/translations/messages.de.yml
src/Kunstmaan/NodeBundle/Resources/translations/messages.en.yml
src/Kunstmaan/NodeBundle/Resources/translations/messages.es.yml
src/Kunstmaan/NodeBundle/Resources/translations/messages.fr.yml
src/Kunstmaan/NodeBundle/Resources/translations/messages.it.yml
src/Kunstmaan/NodeBundle/Resources/views/NodeAdmin/_modals.html.twig
src/Kunstmaan/NodeBundle/Tests/Helper/Menu/ActionsMenuBuilderTest.php

[NodeBundle]: add ability to recopy content from other language

---

src/Kunstmaan/AdminListBundle/AdminList/Configurator/AbstractAdminListConfigurator.php
src/Kunstmaan/AdminListBundle/AdminList/SortableInterface.php
src/Kunstmaan/AdminListBundle/Controller/AdminListController.php
src/Kunstmaan/AdminListBundle/Resources/doc/AdminListBundle.md
src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/adminlist/AdminList/AdminListConfigurator.php
src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/defaultsite/AdminList/BikeAdminListConfigurator.php

[AdminListBundle, GeneratorBundle]: add sortable interface

---

src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/admintests/Features/Context/PageContext.php

[GeneratorBundle]: use namespace paths for admin tests generator

---

src/Kunstmaan/NodeBundle/Repository/NodeTranslationRepository.php

[NodeBundle]: remove getChildren on NodeTranslationRepository -> never used

---

.travis.yml
src/Kunstmaan/AdminBundle/.travis.yml
src/Kunstmaan/AdminListBundle/.travis.yml
src/Kunstmaan/ArticleBundle/.travis.yml
src/Kunstmaan/BehatBundle/.travis.yml
src/Kunstmaan/DashboardBundle/.travis.yml
src/Kunstmaan/FixturesBundle/.travis.yml
src/Kunstmaan/FormBundle/.travis.yml
src/Kunstmaan/GeneratorBundle/.travis.yml
src/Kunstmaan/LanguageChooserBundle/.travis.yml
src/Kunstmaan/LeadGenerationBundle/.travis.yml
src/Kunstmaan/LiveReloadBundle/.travis.yml
src/Kunstmaan/MediaBundle/.travis.yml
src/Kunstmaan/MediaPagePartBundle/.travis.yml
src/Kunstmaan/MenuBundle/.travis.yml
src/Kunstmaan/NodeBundle/.travis.yml
src/Kunstmaan/NodeSearchBundle/.travis.yml
src/Kunstmaan/PagePartBundle/.travis.yml
src/Kunstmaan/RedirectBundle/.travis.yml
src/Kunstmaan/SearchBundle/.travis.yml
src/Kunstmaan/SeoBundle/.travis.yml
src/Kunstmaan/SitemapBundle/.travis.yml
src/Kunstmaan/TaggingBundle/.travis.yml
src/Kunstmaan/TranslatorBundle/.travis.yml
src/Kunstmaan/UserManagementBundle/.travis.yml
src/Kunstmaan/UtilitiesBundle/.travis.yml
src/Kunstmaan/VotingBundle/.travis.yml

[Travis]: remove php 7 from allowed failures

---

src/Kunstmaan/MediaBundle/Helper/File/FileHandler.php

Use an interface instead of a concrete implementation

[MediaBundle] use `SlugifierInterface`

---

docs/04-03-creating-a-pagetype.md

[docs] Fixes typo

---

src/Kunstmaan/AdminBundle/Resources/ui/scss/default-theme/components/vendors/bootstrap-components/_input-group-addon.scss

[AdminBundle] Fix info_text at select2 field

---

src/Kunstmaan/AdminBundle/Helper/Menu/MenuBuilder.php
src/Kunstmaan/AdminBundle/Helper/VersionCheck/VersionChecker.php
src/Kunstmaan/AdminListBundle/Twig/AdminListTwigExtension.php
src/Kunstmaan/FormBundle/Helper/FormMailer.php
src/Kunstmaan/LanguageChooserBundle/Router/LanguageChooserRouter.php
src/Kunstmaan/MediaBundle/Controller/FolderController.php
src/Kunstmaan/NodeBundle/Controller/NodeAdminController.php
src/Kunstmaan/NodeBundle/Resources/config/services.yml
src/Kunstmaan/NodeSearchBundle/Configuration/NodePagesConfiguration.php
src/Kunstmaan/NodeSearchBundle/Services/SearchService.php
src/Kunstmaan/TranslatorBundle/Service/Translator/Translator.php

remove all usages of deprecated `request` service

use `request_stack` instead of `request`

---

src/Kunstmaan/AdminBundle/Resources/ui/scss/default-theme/components/structures/_page-actions.scss
src/Kunstmaan/AdminBundle/Resources/ui/scss/default-theme/general/_app__content.scss
src/Kunstmaan/AdminBundle/Resources/ui/scss/default-theme/general/_login.scss
src/Kunstmaan/AdminBundle/Resources/ui/scss/default-theme/helpers/_helpers.scss
src/Kunstmaan/AdminBundle/Resources/ui/scss/default-theme/helpers/mixins/_viewport-unit.scss

[AdminBundle] update backend responsive

---

src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/bower/bower.json
src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/gulp/.groundcontrolrc
src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/pagepart/Resources/views/PageParts/ImagePagePart/view.html.twig

update image pp

---

src/Kunstmaan/AdminBundle/Resources/ui/scss/default-theme/general/_app__content.scss

[AdminBundle] add margin to responsive table inside app__content

---

src/Kunstmaan/AdminListBundle/AdminList/Configurator/AbstractDoctrineDBALAdminListConfigurator.php
src/Kunstmaan/AdminListBundle/AdminList/Configurator/AbstractDoctrineORMAdminListConfigurator.php
src/Kunstmaan/AdminListBundle/Controller/AdminListController.php
src/Kunstmaan/AdminListBundle/Resources/views/AdminListTwigExtension/widget.html.twig

[AdminListBundle] Some missing stuff for the new canView

---

src/Kunstmaan/MediaBundle/Resources/config/handlers.yml
src/Kunstmaan/NodeSearchBundle/Resources/config/services.yml
src/Kunstmaan/SeoBundle/Resources/config/parameters.yml

[AllBundles] Deprecation fixes

---

src/Kunstmaan/PagePartBundle/PagePartAdmin/PagePartAdmin.php

[PagePartBundle]: transform service to fqn for forms

---

src/Kunstmaan/RedirectBundle/AdminList/RedirectAdminListConfigurator.php
src/Kunstmaan/RedirectBundle/Form/RedirectAdminType.php
src/Kunstmaan/RedirectBundle/Tests/Form/RedirectAdminTypeTest.php

[RedirectBundle]: Add admin type options for form

---

UPGRADE-3.5.md
src/Kunstmaan/FormBundle/Entity/FormSubmissionFieldTypes/FileFormSubmissionField.php
src/Kunstmaan/FormBundle/Resources/views/FileUploadPagePart/submission.html.twig
src/Kunstmaan/FormBundle/UPGRADE-3.5.1.md

[FormBundle] FileUploadPagePart overwrites media with the same name

---

src/Kunstmaan/AdminBundle/Helper/VersionCheck/VersionChecker.php

[AdminBundle] change console path in version check

---

src/Kunstmaan/GeneratorBundle/Command/GenerateDefaultSiteCommand.php
src/Kunstmaan/GeneratorBundle/Command/KunstmaanGenerateCommand.php
src/Kunstmaan/GeneratorBundle/Generator/DefaultPagePartGenerator.php
src/Kunstmaan/GeneratorBundle/Generator/DefaultSiteGenerator.php
src/Kunstmaan/GeneratorBundle/Generator/PagePartGenerator.php

[GeneratorBundle]: add file_get_contents to Yaml::parse function

---

src/Kunstmaan/AdminBundle/Resources/views/ChangePassword/changePassword.html.twig
src/Kunstmaan/AdminBundle/Resources/views/Resetting/checkEmail.html.twig
src/Kunstmaan/AdminBundle/Resources/views/Resetting/passwordAlreadyRequested.html.twig
src/Kunstmaan/AdminBundle/Resources/views/Security/login.html.twig

[AdminBundle]: Change fosuser extends to syntax without namespaces

---

TestListener.php
src/Kunstmaan/TranslatorBundle/Tests/TestListener.php

[TestListener]: change nelmio doctrine to new class

---

src/Kunstmaan/AdminBundle/Form/UserType.php
src/Kunstmaan/FormBundle/Form/ChoiceFormSubmissionType.php
src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/defaultsite/Form/BikeAdminType.php
src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/defaultsite/Form/PageParts/ServicePagePartAdminType.php
src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/pagepart/Form/PageParts/ButtonPagePart/ButtonPagePartAdminType.php
src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/pagepart/Form/PageParts/HeaderPagePart/HeaderPagePartAdminType.php
src/Kunstmaan/LeadGenerationBundle/Form/Rule/LocaleBlackListAdminType.php
src/Kunstmaan/LeadGenerationBundle/Form/Rule/LocaleWhiteListAdminType.php
src/Kunstmaan/MediaBundle/Form/AbstractRemoteType.php
src/Kunstmaan/MediaBundle/Form/FolderType.php
src/Kunstmaan/MediaBundle/Form/RemoteAudio/RemoteAudioType.php
src/Kunstmaan/MediaBundle/Form/RemoteSlide/RemoteSlideType.php
src/Kunstmaan/MediaBundle/Form/RemoteVideo/RemoteVideoType.php
src/Kunstmaan/MenuBundle/Form/MenuItemAdminType.php
src/Kunstmaan/NodeBundle/Form/NodeMenuTabTranslationAdminType.php
src/Kunstmaan/PagePartBundle/Form/HeaderPagePartAdminType.php
src/Kunstmaan/RedirectBundle/Form/RedirectAdminType.php
src/Kunstmaan/SeoBundle/Form/SeoType.php
src/Kunstmaan/SeoBundle/Form/SocialType.php
src/Kunstmaan/TaggingBundle/Form/TagsAdminType.php

[AllBundles]: remove choices_as_values

---

src/Kunstmaan/AdminBundle/DependencyInjection/KunstmaanAdminExtension.php
src/Kunstmaan/AdminBundle/Resources/config/services.yml

[AdminBundle] Fix security acl permission map

---

src/Kunstmaan/NodeBundle/Resources/config/services.yml

[NodeBundle] fix acl permissionmap service definition

---

src/Kunstmaan/AdminBundle/Resources/views/Form/fields.html.twig
src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/common/Form/EntityAdminType.php
src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/defaultsite/Form/PageParts/PageBannerPagePartAdminType.php
src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/defaultsite/Form/PageParts/ServicePagePartAdminType.php
src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/defaultsite/Form/Pages/ContentPageAdminType.php
src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/defaultsite/Form/UspItemAdminType.php
src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/pagepart/Form/PageParts/AudioPagePart/AudioPagePartAdminType.php
src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/pagepart/Form/PageParts/DownloadPagePart/DownloadPagePartAdminType.php
src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/pagepart/Form/PageParts/ImagePagePart/ImagePagePartAdminType.php
src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/pagepart/Form/PageParts/VideoPagePart/VideoPagePartAdminType.php
src/Kunstmaan/MediaBundle/Controller/ChooserController.php
src/Kunstmaan/MediaBundle/Controller/MediaController.php
src/Kunstmaan/MediaBundle/Form/RemoteVideo/RemoteVideoType.php
src/Kunstmaan/MediaBundle/Helper/File/FileHandler.php
src/Kunstmaan/MediaBundle/Helper/Media/AbstractMediaHandler.php
src/Kunstmaan/MediaBundle/Helper/RemoteAudio/RemoteAudioHandler.php
src/Kunstmaan/MediaBundle/Helper/RemoteSlide/RemoteSlideHandler.php
src/Kunstmaan/MediaBundle/Helper/RemoteVideo/RemoteVideoHandler.php
src/Kunstmaan/MediaPagePartBundle/Form/AudioPagePartAdminType.php
src/Kunstmaan/MediaPagePartBundle/Form/DownloadPagePartAdminType.php
src/Kunstmaan/MediaPagePartBundle/Form/ImagePagePartAdminType.php
src/Kunstmaan/MediaPagePartBundle/Form/SlidePagePartAdminType.php
src/Kunstmaan/MediaPagePartBundle/Form/VideoPagePartAdminType.php
src/Kunstmaan/PagePartBundle/Resources/doc/PagePartBundle.md
src/Kunstmaan/SeoBundle/Form/SeoType.php

[AllBundles] Fix media chooser form type + media handlers

---

src/Kunstmaan/AdminBundle/Resources/ui/js/_pagepart-editor.js

[AdminBundle]: add correct syntax for variables in pagepart editor

---

src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/adminlist/AdminList/AdminListConfigurator.php

[GeneratorBundle]: Check if sortfield requested

---

src/Kunstmaan/GeneratorBundle/Command/GenerateAdminListCommand.php

[GeneratorBundle]: add quotes for routing generation

---

src/Kunstmaan/AdminBundle/Resources/ui/js/_pagepart-editor.js

[AdminBundle]: check correct parent when moving page parts

---

src/Kunstmaan/GeneratorBundle/Generator/PagePartGenerator.php

[GeneratorBundle]: Use fqn for class when generating admin tests

---

src/Kunstmaan/AdminBundle/Resources/ui/js/_media-chooser.js
src/Kunstmaan/AdminBundle/Resources/ui/js/_url-chooser.js

| Fixed tickets | [MediaBundle] Media chooser preview not shown #464

[MediaBundle] add preview icon for pdf upload

---

src/Kunstmaan/GeneratorBundle/Command/KunstmaanGenerateCommand.php

[GeneratorBundle] Fix slash character in the Entity alias name

---

src/Kunstmaan/PagePartBundle/Resources/views/PagePartAdminTwigExtension/pagepart.html.twig

Fix untranslated text

---

src/Kunstmaan/MediaBundle/Resources/views/Folder/show.html.twig

Translate media sort fields

---

src/Kunstmaan/AdminBundle/DependencyInjection/KunstmaanAdminExtension.php

[AdminBundle]: change fos_user_resetting to FQN name

---

src/Kunstmaan/PagePartBundle/Controller/PagePartAdminController.php

[PagePartBundle]: check if pagepart admintype is a service

---

src/Kunstmaan/AdminBundle/Resources/ui/js/_pagepart-editor.js

[AdminBundle] Prevent duplicate reInits in the same pagepart

---

src/Kunstmaan/AdminBundle/Resources/ui/js/_rich-editor.js

[AdminBundle] Save the content of the ckeditor before destroying it

---

src/Kunstmaan/AdminListBundle/AdminList/Configurator/AbstractDoctrineORMAdminListConfigurator.php
src/Kunstmaan/AdminListBundle/Controller/AdminListController.php

[AdminListBundle] Fix admin list sorting

---

UPGRADE-X.X.md
docs/05-12-using-a-custom-filesystem-for-the-media-bundle.md
src/Kunstmaan/MediaBundle/Helper/File/FileHandler.php
src/Kunstmaan/MediaBundle/Resources/config/handlers.yml
src/Kunstmaan/MediaBundle/Resources/config/services.yml

[MediaBundle] Pluggable filesystem

---

src/Kunstmaan/AdminListBundle/AdminList/Configurator/AbstractDoctrineORMAdminListConfigurator.php

Sorry, I missed the alias. Linked PR: https://github.com/Kunstmaan/KunstmaanBundlesCMS/pull/1071

[AdminListBundle] Bugfix: Default add order by fix

---

src/Kunstmaan/NodeBundle/Repository/NodeRepository.php

The select query takes a long time if you have many pages and is unnecessary.

[NodeBundle] remove subquery in tree query

---

docs/04-02-creating-an-adminlist.md

[Docs] Fixed a spelling mistake (creating-an-adminlist)

---

src/Kunstmaan/AdminBundle/Resources/translations/messages.nl.yml
src/Kunstmaan/AdminBundle/Resources/translations/validators.nl.yml
src/Kunstmaan/FormBundle/Resources/translations/messages.nl.yml
src/Kunstmaan/MediaBundle/Resources/translations/messages.nl.yml
src/Kunstmaan/MediaBundle/Resources/views/Folder/show.html.twig
src/Kunstmaan/MediaPagePartBundle/Resources/translations/messages.nl.yml
src/Kunstmaan/NodeBundle/Resources/translations/messages.nl.yml
src/Kunstmaan/PagePartBundle/Resources/translations/messages.nl.yml
src/Kunstmaan/PagePartBundle/Resources/translations/validators.nl.yml
src/Kunstmaan/RedirectBundle/Resources/translations/messages.nl.yml
src/Kunstmaan/SeoBundle/Resources/translations/messages.nl.yml
src/Kunstmaan/TranslatorBundle/Resources/translations/messages.nl.yml
src/Kunstmaan/UserManagementBundle/Resources/translations/messages.nl.yml
src/Kunstmaan/UserManagementBundle/Resources/translations/validators.nl.yml

Adding Dutch translation files for Kunstmaan Bundles
| Fixed tickets | #1065

Dutch translations

---

src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/pagepart/Resources/views/PageParts/ImagePagePart/view.html.twig

[GeneratorBundle]: change imagepagepart, url's are already absolute

---

src/Kunstmaan/MediaBundle/Resources/views/Media/Image/aviary.html.twig
src/Kunstmaan/MediaBundle/Resources/views/Media/Image/show.html.twig

Make it easier to override aviary js

[MediaBundle] Move aviary js to own file

---

src/Kunstmaan/NodeSearchBundle/Configuration/NodePagesConfiguration.php

Added execution of `PageInterface::service()` method in `NodePagesConfiguration::renderCustomSearchView()`.
Also removed unused `use` statement.

[NodeSearchBundle] fire service() method on Page in renderCustomSearchView()

---

src/Kunstmaan/MediaBundle/Helper/RemoteVideo/RemoteVideoHandler.php

Make remote thumbnails loading with relative protocol

---

docs/03-00-installation.md
docs/04-02-creating-an-adminlist.md
docs/04-03-creating-a-pagetype.md

[Documentation]
Remove git prompt message because it is never triggered
Fix errors in example source
Clarify some sections

[Documentation] Fix errors and improve documentation

---

src/Kunstmaan/FormBundle/Entity/FormSubmissionField.php

| Fixed tickets | #1120 
[FormBundle] remove reference to non-existing repository

[FormBundle] Fix #1120 bad reference to repository

---

src/Kunstmaan/AdminListBundle/AdminList/Configurator/AbstractAdminListConfigurator.php

| Fixed tickets | #1087 
[AdminListBundle] Implement missing function

[AdminListBundle] Implement missing function fixes #1087

---

src/Kunstmaan/MediaBundle/Command/CleanDeletedMediaCommand.php
src/Kunstmaan/MediaBundle/EventListener/DoctrineMediaListener.php
src/Kunstmaan/MediaBundle/Helper/File/FileHandler.php
src/Kunstmaan/MediaBundle/Repository/MediaRepository.php
src/Kunstmaan/MediaBundle/Resources/config/services.yml
src/Kunstmaan/MediaBundle/Resources/doc/MediaBundle.md

[MediaBundle] Implement command, adapt file handler to know how to remove files and it's directories

[MediaBundle] Implement clean deleted media command

---

src/Kunstmaan/NodeBundle/Repository/NodeRepository.php

See https://github.com/Kunstmaan/KunstmaanBundlesCMS/pull/1133

[NodeBundle]: add group by clause for mysql 5.7 for symfony 2

---

src/Kunstmaan/NodeBundle/Repository/NodeRepository.php

[NodeBundle] Fix admin tree

---

src/Kunstmaan/AdminBundle/DependencyInjection/Configuration.php

| Fixed tickets | #1124 
Parameters remain defined even in disabled status, because a service requires them...

[AdminBundle] fixed undefined index client_id

---

src/Kunstmaan/AdminBundle/Resources/translations/messages.nl.yml

[AdminBundle]: add missing dutch translations

---

src/Kunstmaan/AdminBundle/Security/OAuthAuthenticator.php

[AdminBundle] fix oAuth authenticator typehint

---

src/Kunstmaan/DashboardBundle/Resources/translations/messages.nl.yml

Add messages.nl.yml for google analytics dashboard

---

src/Kunstmaan/NodeBundle/Resources/translations/messages.en.yml

Translation of publish button is wrong.

[NodeBundle] unpublish needs to be publish

---

src/Kunstmaan/AdminBundle/Resources/translations/messages.hu.yml
src/Kunstmaan/AdminListBundle/Resources/translations/messages.hu.yml
src/Kunstmaan/ArticleBundle/Resources/translations/messages.hu.yml
src/Kunstmaan/DashboardBundle/Resources/translations/messages.hu.yml
src/Kunstmaan/FormBundle/Resources/translations/messages.hu.yml
src/Kunstmaan/LeadGenerationBundle/Resources/translations/messages.hu.yml
src/Kunstmaan/MediaBundle/Resources/translations/messages.hu.yml
src/Kunstmaan/MediaPagePartBundle/Resources/translations/messages.hu.yml
src/Kunstmaan/MultiDomainBundle/Resources/translations/messages.hu.yml
src/Kunstmaan/NodeBundle/Resources/translations/messages.hu.yml
src/Kunstmaan/NodeSearchBundle/Resources/translations/messages.hu.yml
src/Kunstmaan/PagePartBundle/Resources/translations/messages.hu.yml
src/Kunstmaan/RedirectBundle/Resources/translations/messages.hu.yml
src/Kunstmaan/SeoBundle/Resources/translations/messages.hu.yml
src/Kunstmaan/TaggingBundle/Resources/translations/messages.hu.yml
src/Kunstmaan/TranslatorBundle/Resources/translations/messages.hu.yml
src/Kunstmaan/UserManagementBundle/Resources/translations/messages.hu.yml

Add hungarian translations

---

src/Kunstmaan/AdminListBundle/Resources/config/services.yml
src/Kunstmaan/AdminListBundle/Service/ExportService.php

Translate adminlist Excel export headers

[AdminListBundle] Translate adminlist excel export headers

---

src/Kunstmaan/AdminBundle/EventListener/AdminLocaleListener.php

Fixes issue #1164

---

src/Kunstmaan/AdminListBundle/Resources/views/Default/list.html.twig
src/Kunstmaan/DashboardBundle/Resources/translations/messages.hu.yml
src/Kunstmaan/FormBundle/Resources/translations/messages.hu.yml
src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/defaultsite/DataFixtures/ORM/DefaultSiteGenerator/DefaultSiteFixtures.php
src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/searchpage/Resources/views/Pages/SearchPage/view.html.twig
src/Kunstmaan/GeneratorBundle/Resources/translations/messages.en.yml
src/Kunstmaan/GeneratorBundle/Resources/translations/messages.hu.yml
src/Kunstmaan/LeadGenerationBundle/Resources/translations/messages.en.yml
src/Kunstmaan/LeadGenerationBundle/Resources/translations/messages.hu.yml
src/Kunstmaan/LeadGenerationBundle/Resources/views/AdminList/popup-list.html.twig
src/Kunstmaan/LeadGenerationBundle/Resources/views/AdminList/rules-list.html.twig
src/Kunstmaan/MediaBundle/Resources/translations/messages.hu.yml
src/Kunstmaan/NodeBundle/Resources/translations/messages.hu.yml
src/Kunstmaan/NodeSearchBundle/Resources/translations/messages.hu.yml
src/Kunstmaan/PagePartBundle/Resources/translations/messages.en.yml
src/Kunstmaan/PagePartBundle/Resources/translations/messages.hu.yml
src/Kunstmaan/PagePartBundle/Resources/views/FormWidgets/PageTemplateWidget/widget.html.twig
src/Kunstmaan/PagePartBundle/Resources/views/PagePartAdminTwigExtension/pagepart.html.twig
src/Kunstmaan/RedirectBundle/Resources/translations/messages.hu.yml
src/Kunstmaan/SeoBundle/Resources/translations/messages.hu.yml
src/Kunstmaan/UserManagementBundle/Resources/translations/messages.hu.yml

[All bundle] Translation fixes

---

src/Kunstmaan/AdminBundle/Resources/translations/messages.de.yml
src/Kunstmaan/AdminBundle/Resources/translations/messages.en.yml
src/Kunstmaan/AdminBundle/Resources/translations/messages.es.yml
src/Kunstmaan/AdminBundle/Resources/translations/messages.fr.yml
src/Kunstmaan/AdminBundle/Resources/translations/messages.hu.yml
src/Kunstmaan/AdminBundle/Resources/translations/messages.it.yml
src/Kunstmaan/AdminBundle/Resources/translations/messages.nl.yml
src/Kunstmaan/AdminListBundle/Resources/views/Default/list.html.twig
src/Kunstmaan/NodeBundle/Resources/translations/messages.hu.yml

Fix translation

---

src/Kunstmaan/AdminListBundle/Resources/views/AdminListTwigExtension/widget.html.twig

[AdminListBundle] Updated list template to use an icon for the View link

---

src/Kunstmaan/AdminListBundle/Resources/views/Default/add_or_edit.html.twig

[AdminListBundle] Fix adminlist SimpleItemAction template

---

src/Kunstmaan/MediaBundle/Helper/RemoteVideo/RemoteVideoHandler.php

Video thumbnail fix

---

src/Kunstmaan/SeoBundle/Resources/views/SeoTwigExtension/metadata.html.twig

Added a check on the twitterImage

[SeoBundle] check on twitterImage

---

src/Kunstmaan/AdminBundle/Resources/ui/js/_datepicker.js
src/Kunstmaan/NodeBundle/DependencyInjection/Configuration.php
src/Kunstmaan/NodeBundle/DependencyInjection/KunstmaanNodeExtension.php
src/Kunstmaan/NodeBundle/Resources/views/NodeAdmin/_modals.html.twig

[NodeBundle] Make node publish date stepping configurable

---

docs/05-09-defining-custom-ckeditor-configuration.md

[AdminBundle] Upgrade CKEditor configuration doc

---

src/Kunstmaan/MediaBundle/Controller/MediaController.php

| Fixed tickets | #1198 
When the FileUploadForm was invalid inside a modal, the controller action still tried to handle this invalid form as it would a form on a normal page. This approach does not work inside the modal and caused a crash.

[MediaBundle] Workaround crash when invalid FileUploadForm inside modal

---

src/Kunstmaan/AdminListBundle/Resources/views/Default/list.html.twig

Fixed wrong translations amdin -> admin

---

docs/07-05-roadmap.md

Minor typo

---

.travis.yml

[Travis] Better travic config

---

src/Kunstmaan/UserManagementBundle/Resources/translations/messages.hu.yml

Hungarian translation fix

---

src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/admintests/Features/Context/FeatureContext.php
src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/admintests/Features/Context/MediaContext.php
src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/admintests/Features/Context/PageContext.php
src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/admintests/Features/Context/PagePartContext.php
src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/defaultsite/Entity/Pages/BehatTestPage.php
src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/defaultsite/Entity/Pages/ContentPage.php
src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/pagepart/Form/PageParts/AudioPagePart/AudioPagePartAdminType.php
src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/pagepart/Form/PageParts/ButtonPagePart/ButtonPagePartAdminType.php
src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/pagepart/Form/PageParts/DownloadPagePart/DownloadPagePartAdminType.php
src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/pagepart/Form/PageParts/HeaderPagePart/HeaderPagePartAdminType.php
src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/pagepart/Form/PageParts/ImagePagePart/ImagePagePartAdminType.php
src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/pagepart/Form/PageParts/IntroTextPagePart/IntroTextPagePartAdminType.php
src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/pagepart/Form/PageParts/LinePagePart/LinePagePartAdminType.php
src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/pagepart/Form/PageParts/LinkPagePart/LinkPagePartAdminType.php
src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/pagepart/Form/PageParts/RawHtmlPagePart/RawHtmlPagePartAdminType.php
src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/pagepart/Form/PageParts/TextPagePart/TextPagePartAdminType.php
src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/pagepart/Form/PageParts/ToTopPagePart/ToTopPagePartAdminType.php
src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/pagepart/Form/PageParts/TocPagePart/TocPagePartAdminType.php
src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/pagepart/Form/PageParts/VideoPagePart/VideoPagePartAdminType.php

We are using Jenkins with PMD and Checkstyle. Some files cause warnings.

[GeneratorBundle] formatting fix

---

src/Kunstmaan/PagePartBundle/PagePartConfigurationReader/PagePartConfigurationReader.php
src/Kunstmaan/PagePartBundle/PageTemplate/PageTemplateConfigurationReader.php

[PagePartBundle] Make ConfigurationReader properties protected

---

src/Kunstmaan/NodeBundle/Controller/NodeAdminController.php
src/Kunstmaan/NodeBundle/Helper/Menu/ActionsMenuBuilder.php
src/Kunstmaan/NodeBundle/Tests/Helper/Menu/ActionsMenuBuilderTest.php

[NodeBundle] allow deleting homepage when no children attached

---

src/Kunstmaan/MediaBundle/Resources/views/Media/Image/aviary.html.twig

https://developers.aviary.com/docs/web/setup-guide

[MediaBundle] Updated aviary url to https

---

src/Kunstmaan/AdminBundle/Resources/views/Form/fields.html.twig

[AdminBundle] remove up/down buttons when sortable is false

---

src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/defaultsite/DataFixtures/ORM/DefaultSiteGenerator/DefaultSiteFixtures.php
src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/defaultsite/Resources/translations/fixture.de.yml
src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/defaultsite/Resources/translations/fixture.en.yml
src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/defaultsite/Resources/translations/fixture.fr.yml
src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/defaultsite/Resources/translations/fixture.hu.yml
src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/defaultsite/Resources/translations/fixture.nl.yml

Move fixture translations to yml files.

Upgrade fixtures translation

---

docs/05-06-using-the-leadgenerationbundle.md
src/Kunstmaan/LeadGenerationBundle/Entity/Popup/AbstractPopup.php
src/Kunstmaan/LeadGenerationBundle/Form/Popup/AbstractPopupAdminType.php
src/Kunstmaan/LeadGenerationBundle/Form/Rule/AbstractRuleAdminType.php
src/Kunstmaan/LeadGenerationBundle/Resources/public/js/popup/Popup.js

[LeadGenerationBundle] Fix some syntax errors

---

docs/03-00-installation.md

[DOCS] Added gem install bundler to installation docs

---

src/Kunstmaan/RedirectBundle/Entity/Redirect.php
src/Kunstmaan/RedirectBundle/Resources/translations/validators.en.yml

If origin and target are the same you get a redirect loop

[RedirectBundle] Added violation if origin and target are the same

---

src/Kunstmaan/AdminBundle/Resources/ui/js/_app-check-if-edited.js
src/Kunstmaan/AdminBundle/Resources/ui/js/_auto-collapse-buttons.js
src/Kunstmaan/NodeBundle/Helper/NodeAdmin/NodeAdminPublisher.php

[AdminBundle, NodeBundle], fix #491

---

src/Kunstmaan/MediaBundle/Command/MigrateSoftDeletedCommand.php
src/Kunstmaan/MediaBundle/Command/RenameSoftDeletedCommand.php
src/Kunstmaan/MediaBundle/EventListener/DoctrineMediaListener.php

| BC breaks?    | yes?
Reopen pull-request https://github.com/Kunstmaan/KunstmaanBundlesCMS/pull/1215

[MediaBundle] Rename soft deleted media

---

src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/admintests/Features/AdminSettingsUser.feature

[GeneratorBundle]: fix last test

---

src/Kunstmaan/GeneratorBundle/DataFixtures/ORM/GroupFixtures.php

[GeneratorBundle]: add superadmin instead of guests

---

src/Kunstmaan/NodeBundle/Resources/translations/messages.en.yml

[NodeBundle] Clarify that page will be deleted in all languages

---

src/Kunstmaan/NodeBundle/Entity/NodeVersionLock.php

[NodeBundle] Typo

---

src/Kunstmaan/FormBundle/AdminList/FormPageAdminListConfigurator.php

[FormBundle] Remove reference to removed sequence_number column

---

src/Kunstmaan/NodeBundle/Resources/views/NodeAdmin/pagenottranslated.html.twig

Remove whitespace

---

src/Kunstmaan/AdminBundle/Resources/translations/messages.nl.yml
src/Kunstmaan/AdminListBundle/Resources/translations/messages.nl.yml
src/Kunstmaan/ArticleBundle/Resources/translations/messages.nl.yml
src/Kunstmaan/FormBundle/Resources/translations/messages.nl.yml
src/Kunstmaan/GeneratorBundle/Resources/translations/messages.nl.yml
src/Kunstmaan/LeadGenerationBundle/Resources/translations/messages.nl.yml
src/Kunstmaan/MediaBundle/Resources/translations/messages.nl.yml
src/Kunstmaan/MenuBundle/Resources/translations/messages.nl.yml
src/Kunstmaan/NodeBundle/Resources/translations/messages.nl.yml
src/Kunstmaan/NodeSearchBundle/Resources/translations/messages.nl.yml
src/Kunstmaan/PagePartBundle/Resources/translations/messages.nl.yml
src/Kunstmaan/RedirectBundle/Resources/translations/messages.nl.yml
src/Kunstmaan/SeoBundle/Resources/translations/messages.nl.yml
src/Kunstmaan/TaggingBundle/Resources/translations/messages.nl.yml
src/Kunstmaan/TranslatorBundle/Resources/translations/messages.nl.yml
src/Kunstmaan/UserManagementBundle/Resources/translations/messages.nl.yml

Missing NL translations

---

src/Kunstmaan/NodeBundle/Form/NodeMenuTabTranslationAdminType.php

Prevent to translate integer values

---

src/Kunstmaan/AdminBundle/Helper/DomainConfiguration.php
src/Kunstmaan/AdminBundle/Helper/DomainConfigurationInterface.php
src/Kunstmaan/AdminBundle/Resources/views/MultiDomainAdminTwigExtension/widget.html.twig
src/Kunstmaan/AdminBundle/Twig/MultiDomainAdminTwigExtension.php
src/Kunstmaan/MultiDomainBundle/Controller/SiteSwitchController.php
src/Kunstmaan/MultiDomainBundle/Helper/DomainConfiguration.php
src/Kunstmaan/NodeBundle/Resources/views/Widgets/selectLink.html.twig

[AllBundles] Fixed switching domain

---

src/Kunstmaan/MediaBundle/Resources/views/Folder/show.html.twig

[MediaBundle] Added pagination for thumbnail view

---

UPGRADE-3.0.md
src/Kunstmaan/NodeBundle/Resources/config/services.yml

[NodeBundle] Cleanup old command

---

src/Kunstmaan/MenuBundle/Form/MenuItemAdminType.php
src/Kunstmaan/MenuBundle/Resources/translations/messages.en.yml
src/Kunstmaan/MenuBundle/Resources/views/AdminList/edit-menu-item.html.twig
src/Kunstmaan/MenuBundle/Resources/views/AdminList/list-menu-item.html.twig
src/Kunstmaan/MenuBundle/Resources/views/AdminList/menu-item-online.html.twig

[MenuBundle] Added translations

---

src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/pagepart/Form/PageParts/ButtonPagePart/ButtonPagePartAdminType.php
src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/pagepart/Form/PageParts/HeaderPagePart/HeaderPagePartAdminType.php
src/Kunstmaan/LeadGenerationBundle/Form/Rule/LocaleBlackListAdminType.php
src/Kunstmaan/LeadGenerationBundle/Form/Rule/LocaleWhiteListAdminType.php
src/Kunstmaan/MediaBundle/Form/AbstractRemoteType.php
src/Kunstmaan/MediaBundle/Form/FolderType.php
src/Kunstmaan/NodeBundle/Form/NodeMenuTabTranslationAdminType.php

[AllBundles] Remove choices_as_values

---

src/Kunstmaan/SearchBundle/Search/LanguageAnalysisFactory.php
src/Kunstmaan/SearchBundle/Search/NGramAnalysisFactory.php

[SearchBundle] swap the filter order index/suggestion analyzer

---

src/Kunstmaan/PagePartBundle/Helper/FormWidgets/PageTemplateWidget.php

[PagePartBundle] fix typo

---

src/Kunstmaan/ArticleBundle/Controller/AbstractArticleOverviewPageController.php
src/Kunstmaan/SeoBundle/Controller/RobotsController.php

[ArticleBundle][SeoBundle] Use built-in getDoctrine

---

src/Kunstmaan/AdminBundle/Controller/BaseSettingsController.php
src/Kunstmaan/AdminBundle/Controller/SettingsController.php
src/Kunstmaan/DashboardBundle/Controller/GoogleAnalyticsController.php
src/Kunstmaan/NodeBundle/Controller/NodeAdminController.php
src/Kunstmaan/SeoBundle/Controller/Admin/SettingsController.php
src/Kunstmaan/UserManagementBundle/Controller/GroupsController.php
src/Kunstmaan/UserManagementBundle/Controller/RolesController.php
src/Kunstmaan/UserManagementBundle/Controller/UsersController.php

[AllBundles] Use built-in authorization check

---

src/Kunstmaan/PagePartBundle/Twig/Extension/PagePartTwigExtension.php

[PagePartBundle] Remove duplicate code in PagePartTwigExtension

---

src/Kunstmaan/DashboardBundle/Helper/Google/ClientHelper.php

[DashboardBundle] Fix custom router incompatibility, code style

---

src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/Resources/ui/js/app.js
src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/Resources/ui/js/cookieConsent.js
src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/Resources/ui/scss/components/_components.scss
src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/Resources/ui/scss/components/structures/_cookie-consent.scss
src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/Resources/ui/scss/config/vendors/_cargobay-vars.scss

| Fixed tickets | cookie consent in generator bundle

[GeneratorBundle] Add cookie consent to generatorBundle

---

src/Kunstmaan/NodeSearchBundle/Entity/AbstractSearchPage.php

[NodeSearchBundle]: php doc not correct

---

src/Kunstmaan/AdminListBundle/Controller/AdminListController.php

[AdminListBundle] Update PhpDoc

---

src/Kunstmaan/AdminBundle/Twig/AdminPermissionsTwigExtension.php
src/Kunstmaan/AdminBundle/Twig/DateByLocaleExtension.php
src/Kunstmaan/AdminBundle/Twig/FormToolsExtension.php
src/Kunstmaan/AdminBundle/Twig/GoogleSignInTwigExtension.php
src/Kunstmaan/AdminBundle/Twig/LocaleSwitcherTwigExtension.php
src/Kunstmaan/AdminBundle/Twig/MenuTwigExtension.php
src/Kunstmaan/AdminBundle/Twig/MultiDomainAdminTwigExtension.php
src/Kunstmaan/AdminBundle/Twig/TabsTwigExtension.php
src/Kunstmaan/AdminListBundle/Twig/AdminListTwigExtension.php
src/Kunstmaan/ConfigBundle/Twig/ConfigTwigExtension.php
src/Kunstmaan/LeadGenerationBundle/Twig/PopupTwigExtension.php
src/Kunstmaan/MenuBundle/Twig/MenuTwigExtension.php
src/Kunstmaan/MultiDomainBundle/Twig/MultiDomainTwigExtension.php
src/Kunstmaan/NodeBundle/Twig/NodeTwigExtension.php
src/Kunstmaan/NodeBundle/Twig/PagesConfigurationTwigExtension.php
src/Kunstmaan/NodeBundle/Twig/UrlReplaceTwigExtension.php
src/Kunstmaan/NodeSearchBundle/Twig/KunstmaanNodeSearchTwigExtension.php
src/Kunstmaan/PagePartBundle/Twig/Extension/PagePartAdminTwigExtension.php
src/Kunstmaan/PagePartBundle/Twig/Extension/PagePartTwigExtension.php
src/Kunstmaan/PagePartBundle/Twig/Extension/PageTemplateTwigExtension.php
src/Kunstmaan/SeoBundle/Twig/GoogleAnalyticsTwigExtension.php
src/Kunstmaan/SeoBundle/Twig/SeoTwigExtension.php
src/Kunstmaan/SitemapBundle/Twig/SitemapTwigExtension.php
src/Kunstmaan/UtilitiesBundle/Twig/UtilitiesTwigExtension.php

Reverts Kunstmaan/KunstmaanBundlesCMS#1336

Revert "[AllBundle]: removed getName from twig extensions"

---

src/Kunstmaan/AdminBundle/Helper/DomainConfiguration.php
src/Kunstmaan/AdminBundle/Helper/DomainConfigurationInterface.php
src/Kunstmaan/AdminBundle/Resources/views/MultiDomainAdminTwigExtension/widget.html.twig
src/Kunstmaan/AdminBundle/Twig/MultiDomainAdminTwigExtension.php
src/Kunstmaan/MultiDomainBundle/Controller/SiteSwitchController.php
src/Kunstmaan/MultiDomainBundle/Helper/DomainConfiguration.php
src/Kunstmaan/NodeBundle/Resources/views/Widgets/selectLink.html.twig

Reverts Kunstmaan/KunstmaanBundlesCMS#1302

Revert "[AllBundles] Fixed switching domain"

---

src/Kunstmaan/AdminBundle/Helper/DomainConfiguration.php
src/Kunstmaan/AdminBundle/Helper/DomainConfigurationInterface.php
src/Kunstmaan/MultiDomainBundle/Helper/DomainConfiguration.php

| Fixed tickets | #1302 
@jockri @sandergo90 New PR after revert, see #1302

[AdminBundle][MultiDomainBundle] Fixed missing getFullHostConfig

---

src/Kunstmaan/MediaBundle/Resources/config/services.yml

[MediaBundle] Cleanup service old media migrate command

---

composer.json

[Composer] Update fzaninotto/faker to 1.6

---

composer.json

[Composer] Update fzaninotto/faker in sf3

---

src/Kunstmaan/RedirectBundle/Entity/Redirect.php

| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | yes |
| Fixed tickets | #1309 |

[RedirectBundle] Added unique entity constraint for redirect entity

---

src/Kunstmaan/GeneratorBundle/Generator/PagePartGenerator.php

[GeneratorBundle] better papgepart code generation

---

src/Kunstmaan/ConfigBundle/Controller/ConfigController.php

[ConfigBundle] Fixed: non-abstract classes in constructor, code style

---

src/Kunstmaan/UserManagementBundle/Controller/UsersController.php

[UserManagementBundle] Use built-in authorization check

---

src/Kunstmaan/AdminBundle/Controller/DefaultController.php
src/Kunstmaan/DashboardBundle/Controller/GoogleAnalyticsAJAXController.php
src/Kunstmaan/MediaBundle/Controller/FolderController.php
src/Kunstmaan/MediaBundle/Controller/MediaController.php
src/Kunstmaan/MediaBundle/Resources/translations/messages.en.yml
src/Kunstmaan/NodeBundle/Controller/NodeAdminController.php
src/Kunstmaan/SeoBundle/Controller/Admin/SettingsController.php
src/Kunstmaan/TranslatorBundle/Controller/TranslatorCommandController.php
src/Kunstmaan/TranslatorBundle/Controller/TranslatorController.php
src/Kunstmaan/UserManagementBundle/Controller/GroupsController.php
src/Kunstmaan/UserManagementBundle/Controller/RolesController.php
src/Kunstmaan/UserManagementBundle/Controller/UsersController.php
src/Kunstmaan/UserManagementBundle/Resources/translations/messages.en.yml

| Q | A |
| --- | --- |
Use built-in flash bag and added some translations

[AllBundles] Use built-in flash

---

src/Kunstmaan/PagePartBundle/Resources/translations/messages.nl.yml

Url chooser dutch

---

src/Kunstmaan/AdminListBundle/Service/ExportService.php

Allow custom xlsx template on string values, check on template existence not on being an object.

[AdminList] Allow custom xlsx template on string values

---

src/Kunstmaan/NodeBundle/Form/NodeChoiceType.php

[NodeBundle]: check if we have a request

---

src/Kunstmaan/AdminBundle/Helper/VersionCheck/VersionChecker.php

Update Guzzle version

---

src/Kunstmaan/AdminListBundle/AdminList/Configurator/AbstractAdminListConfigurator.php
src/Kunstmaan/AdminListBundle/AdminList/Field.php
src/Kunstmaan/AdminListBundle/AdminList/FieldAlias.php
src/Kunstmaan/AdminListBundle/Resources/views/AdminListTwigExtension/widget.html.twig
src/Kunstmaan/AdminListBundle/Service/ExportService.php

Add column sort and export possibility for a field that is filled by a one to many relation. 
Pull request on master instead of sf3: https://github.com/Kunstmaan/KunstmaanBundlesCMS/pull/1374

[AdminListBundle] Add column sort and export for one to many field

---

src/Kunstmaan/AdminBundle/Helper/Security/OAuth/OAuthUserCreator.php

See https://github.com/FriendsOfSymfony/FOSUserBundle/blob/28151dcb25de663c05ce26917fd6a0b5cb2787cf/Upgrade.md

[AdminBundle]: remove locked setter

---

phpunit.xml.dist
src/Kunstmaan/AdminBundle/Resources/views/Resetting/request_content.html.twig
src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/admintests/Features/AdminForgotPassword.feature

See https://github.com/FriendsOfSymfony/FOSUserBundle/pull/2250
Changing symfony deprecation helper, see http://symfony.com/blog/new-in-symfony-2-7-phpunit-bridge. Our test do not have to fail when a deprecation is noticed.

[AdminBundle]: Change admin tests for new fos user flow see #2250 on fos user

---

src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/admintests/Features/Context/MediaContext.php

[GeneratorBundle]: fix media admin test

---

src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/admintests/Features/AdminSettingsUser.feature

[GeneratorBundle]: fix user admin tes

---

src/Kunstmaan/MediaBundle/Controller/IconFontController.php
src/Kunstmaan/MediaBundle/Form/Type/IconFontType.php
src/Kunstmaan/MediaBundle/Helper/IconFont/DefaultIconFontLoader.php

[MediaBundle]: check if the extension for iconfontloader is css

---

src/Kunstmaan/GeneratorBundle/Command/GeneratePageCommand.php
src/Kunstmaan/GeneratorBundle/Generator/PageGenerator.php
src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/common/Form/EntityAdminType.php
src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/page/Entity/Pages/ExtraFunctions.php

[GeneratorBundle] better code generation and some fixes

---

composer.json

[Composer]: lock fos-user version

---

src/Kunstmaan/GeneratorBundle/Command/GeneratePageCommand.php

Fix typo made in pull request https://github.com/Kunstmaan/KunstmaanBundlesCMS/pull/1359

[GeneratorBundle]: fix typo made

---

src/Kunstmaan/MediaBundle/Resources/translations/messages.en.yml
src/Kunstmaan/MediaBundle/Resources/translations/messages.hu.yml

Duplicate mappings in YAML has been deprecated

[MediaBundle] Remove duplicate translation

---

src/Kunstmaan/AdminBundle/Command/UpdateAclCommand.php

[AdminBundle] Typo

---

src/Kunstmaan/MediaBundle/Helper/RemoteSlide/RemoteSlideHandler.php
src/Kunstmaan/MediaBundle/Resources/views/Media/RemoteSlide/preview.html.twig

[MediaBundle] Use https link for slideshare embed

---

src/Kunstmaan/NodeBundle/Form/NodeMenuTabTranslationAdminType.php

[NodeBundle]: remove choices_as_values

---

README.md
composer.json
docs/01-00-introduction.md
docs/02-00-getting-started.md
docs/05-02-manage-translations.md
docs/07-02-pull-requests.md
docs/07-03-coding-standards.md
src/Kunstmaan/AdminBundle/README.md
src/Kunstmaan/AdminListBundle/README.md
src/Kunstmaan/ArticleBundle/README.md
src/Kunstmaan/FormBundle/README.md
src/Kunstmaan/GeneratorBundle/README.md
src/Kunstmaan/MediaBundle/README.md
src/Kunstmaan/MediaPagePartBundle/README.md
src/Kunstmaan/NodeBundle/README.md
src/Kunstmaan/NodeBundle/Resources/doc/ChainRouter.md
src/Kunstmaan/PagePartBundle/README.md
src/Kunstmaan/SeoBundle/README.md
src/Kunstmaan/TaggingBundle/README.md
src/Kunstmaan/TranslatorBundle/README.md
src/Kunstmaan/UserManagementBundle/README.md
src/Kunstmaan/VotingBundle/README.md

[AllBundles]: change symfony 2 to symfony 3

---

src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/defaultsite/app/KunstmaanSitemapBundle/views/SitemapPage/view.html.twig

[GeneratorBundle] Site map view fix

---

README.md
docs/07-00-contributing.md
docs/07-02-pull-requests.md
docs/07-07-release-process.md

[Docs] update docs

---

README.md
docs/07-02-pull-requests.md
docs/07-07-release-process.md

[Docs] Change release process documentation

---

composer.json

[All] Allow symfony/monolog-bundle v3

---

src/Kunstmaan/GeneratorBundle/Command/KunstmaanGenerateCommand.php

When generating a new page, an error will popup that 'minHeight' does not exists. This is related to #1273 where the generator was adapted. MinHeight etc. is not set when the type of field is different from image of media.

[GeneratorBundle]: set default values

---

src/Kunstmaan/TaggingBundle/Entity/Tag.php

[TaggingBundle]: make tag names translatable

---

src/Kunstmaan/AdminBundle/Resources/views/Default/_ckeditor_configs.html.twig
src/Kunstmaan/AdminBundle/Resources/views/Default/_css.html.twig
src/Kunstmaan/AdminBundle/Resources/views/Default/_js_footer.html.twig
src/Kunstmaan/AdminBundle/Resources/views/Default/_js_header.html.twig
src/Kunstmaan/MediaBundle/Resources/views/Media/Image/show.html.twig
src/Kunstmaan/PagePartBundle/Resources/views/PagePartAdminTwigExtension/widget.html.twig

[ALL] updated twig includes to correct convention

---

src/Kunstmaan/GeneratorBundle/Resources/translations/messages.nl.yml

[GeneratorBundle]: incorrect translation for search page

---

src/Kunstmaan/AdminListBundle/Resources/views/Default/export.csv.twig

if you export to csv all will be on one line.

[AdminListBundle] export csv bug

---

src/Kunstmaan/GeneratorBundle/Generator/PagePartGenerator.php

[GeneratorBundle] Fix when using traits inside pages folder

---

src/Kunstmaan/NodeBundle/EventListener/NodeTranslationListener.php
src/Kunstmaan/NodeBundle/Repository/NodeTranslationRepository.php
src/Kunstmaan/NodeBundle/Resources/config/services.yml

[NodeBundle] ignore slug of structurenode when changing slug of page

---

src/Kunstmaan/AdminListBundle/Controller/AdminListController.php

| Fixed tickets | #1066 
This change makes it easier to use other sorting strategies besides the default one. For example, if you want to use the Gedmo Sortable behavior the sort weight is set automatically, meaning that the code that sets the sort weight in the AdminListController can be skipped.

[AdminListBundle] Moved setting of sort weight on new items to a protected method (revised)

---

src/Kunstmaan/TranslatorBundle/Controller/TranslatorCommandController.php
src/Kunstmaan/TranslatorBundle/Resources/config/services.yml
src/Kunstmaan/TranslatorBundle/Resources/translations/messages.de.yml
src/Kunstmaan/TranslatorBundle/Resources/translations/messages.en.yml
src/Kunstmaan/TranslatorBundle/Resources/translations/messages.fr.yml
src/Kunstmaan/TranslatorBundle/Resources/translations/messages.nl.yml
src/Kunstmaan/TranslatorBundle/Resources/views/Translator/list.html.twig
src/Kunstmaan/TranslatorBundle/Service/Command/Exporter/CSVFileExporter.php
src/Kunstmaan/TranslatorBundle/Service/Command/Exporter/ExportCommandHandler.php

Add the possibility to export the translations to a CSV file.

[TranslatorBundle]: add csv export for translations

---

src/Kunstmaan/NodeSearchBundle/Search/NodeSearcher.php

Make the properties of NodeSearcher protected so it's easier/cleaner to extend it.

[NodeSearchBundle] Make NodeSearcher properties protected for extending

---

.travis.yml
composer.json

[All] move from php 5.5 to php 5.6

---

docs/04-05-adding-a-search-engine.md
src/Kunstmaan/NodeSearchBundle/DependencyInjection/Configuration.php
src/Kunstmaan/NodeSearchBundle/DependencyInjection/KunstmaanNodeSearchExtension.php
src/Kunstmaan/NodeSearchBundle/Helper/IndexablePagePartsService.php
src/Kunstmaan/NodeSearchBundle/Resources/config/services.yml

In standard use cases, indexing the page parts from the main region will be enough. If you want index multiple regions this PR request is just for you!

[NodeSearchBundle]: add possibility to index multiple regions

---

src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/adminlist/Controller/EntityAdminListController.php

[GeneratorBundle] fixed bug in adminlist view route

---

docs/04-02-creating-an-adminlist.md

[Documentation] Update adminlist documentation

---

src/Kunstmaan/AdminListBundle/AdminList/Configurator/AbstractAdminListConfigurator.php

[AdminListBundle] fixed type from string to array

---

src/Kunstmaan/ArticleBundle/Form/AbstractArticlePageAdminType.php
src/Kunstmaan/ArticleBundle/Resources/translations/messages.en.yml
src/Kunstmaan/ArticleBundle/Resources/translations/messages.hu.yml
src/Kunstmaan/ArticleBundle/Resources/translations/messages.nl.yml

| Fixed tickets | Fixed a typo in the translations

[ArticleBundle] Fix typo in translations

---

UPGRADE-4.1.md
src/Kunstmaan/RedirectBundle/AdminList/RedirectAdminListConfigurator.php
src/Kunstmaan/RedirectBundle/Entity/Redirect.php
src/Kunstmaan/RedirectBundle/Form/RedirectAdminType.php
src/Kunstmaan/RedirectBundle/Resources/translations/messages.en.yml
src/Kunstmaan/RedirectBundle/Resources/translations/messages.hu.yml
src/Kunstmaan/RedirectBundle/Resources/translations/messages.nl.yml

[RedirectBundle]: add note to redirect

---

src/Kunstmaan/AdminBundle/Resources/translations/messages.en.yml
src/Kunstmaan/AdminBundle/Resources/translations/messages.nl.yml
src/Kunstmaan/AdminBundle/Resources/views/Security/login.html.twig
src/Kunstmaan/AdminBundle/Resources/views/layout.html.twig

[AdminBundle] Add missing translations for admin login

---

src/Kunstmaan/AdminBundle/Resources/translations/messages.en.yml
src/Kunstmaan/AdminBundle/Resources/translations/messages.nl.yml
src/Kunstmaan/AdminBundle/Resources/views/Default/sidebar.html.twig
src/Kunstmaan/AdminListBundle/Controller/AdminListController.php
src/Kunstmaan/AdminListBundle/Resources/translations/messages.en.yml
src/Kunstmaan/AdminListBundle/Resources/translations/messages.nl.yml
src/Kunstmaan/AdminListBundle/Resources/views/AdminListTwigExtension/widget.html.twig
src/Kunstmaan/FormBundle/AdminList/FormPageAdminListConfigurator.php
src/Kunstmaan/FormBundle/Resources/translations/messages.en.yml
src/Kunstmaan/FormBundle/Resources/translations/messages.nl.yml
src/Kunstmaan/MenuBundle/Controller/MenuAdminListController.php
src/Kunstmaan/MenuBundle/Controller/MenuItemAdminListController.php
src/Kunstmaan/MenuBundle/Resources/translations/messages.en.yml
src/Kunstmaan/MenuBundle/Resources/translations/messages.nl.yml
src/Kunstmaan/MenuBundle/Service/MenuAdaptor.php
src/Kunstmaan/NodeBundle/AdminList/NodeAdminListConfigurator.php
src/Kunstmaan/NodeBundle/Controller/NodeAdminController.php
src/Kunstmaan/NodeBundle/Resources/translations/messages.en.yml
src/Kunstmaan/NodeBundle/Resources/translations/messages.nl.yml
src/Kunstmaan/NodeBundle/Resources/views/Admin/list.html.twig
src/Kunstmaan/NodeBundle/Resources/views/Admin/online.html.twig
src/Kunstmaan/SeoBundle/Helper/Menu/SeoManagementMenuAdaptor.php
src/Kunstmaan/SeoBundle/Resources/translations/messages.en.yml
src/Kunstmaan/SeoBundle/Resources/translations/messages.nl.yml

[AllBundles] Add missing translations

---

src/Kunstmaan/RedirectBundle/Tests/AdminList/RedirectAdminListConfiguratorTest.php

[KunstmaanRedirectBundle]: fix admin tests

---

src/Kunstmaan/AdminListBundle/Entity/EntityVersionLock.php

| Fixed tickets | #1498 
Fix for feature #1496

[AdminListBundle] Renamed index nt_owner_public_idx in EntityVersionLock

---

src/Kunstmaan/AdminBundle/Form/MediaTokenTransformer.php

[AdminBundle]: fix #1514

---

src/Kunstmaan/AdminListBundle/Resources/translations/messages.en.yml
src/Kunstmaan/AdminListBundle/Resources/translations/messages.hu.yml
src/Kunstmaan/AdminListBundle/Resources/translations/messages.nl.yml
src/Kunstmaan/AdminListBundle/Resources/views/FilterType/booleanFilter.html.twig
src/Kunstmaan/AdminListBundle/Resources/views/FilterType/dateFilter.html.twig
src/Kunstmaan/AdminListBundle/Resources/views/FilterType/dateTimeFilter.html.twig
src/Kunstmaan/AdminListBundle/Resources/views/FilterType/enumerationFilter.html.twig
src/Kunstmaan/AdminListBundle/Resources/views/FilterType/numberFilter.html.twig
src/Kunstmaan/AdminListBundle/Resources/views/FilterType/stringFilter.html.twig

This PR adds translation for filter types on admin lists.

[AdminListBundle] add translation for filter types

---

docs/02-00-getting-started.md

[Docs]: fix getting started links

---

docs/03-01-intro.md
src/Kunstmaan/GeneratorBundle/Generator/KunstmaanGenerator.php
src/Kunstmaan/GeneratorBundle/Generator/LayoutGenerator.php

[GeneratorBundle] Make buildUI.sh executable

---

src/Kunstmaan/SeoBundle/Entity/Seo.php
src/Kunstmaan/SeoBundle/Form/SeoType.php
src/Kunstmaan/SeoBundle/Resources/translations/messages.en.yml
src/Kunstmaan/SeoBundle/Resources/translations/messages.hu.yml
src/Kunstmaan/SeoBundle/Resources/translations/messages.nl.yml

Same as https://github.com/Kunstmaan/KunstmaanBundlesCMS/pull/1519 but for symfony 2 versions

[SeoBundle]: change meta length

---

README.md
docs/02-00-getting-started.md
docs/03-01-intro.md
docs/04-01-intro.md
docs/05-01-intro.md
docs/99-00-contributing.md
docs/99-02-pull-requests.md

With the change of the documentation, some paths are not correct.

[Docs]: change documentation paths

---

src/Kunstmaan/PagePartBundle/Resources/views/PagePartAdminTwigExtension/add_pagepart.html.twig
src/Kunstmaan/PagePartBundle/Resources/views/PagePartAdminTwigExtension/widget.html.twig

[PagePartBundle] Fix new pagepart chooser

---

composer.json

[Composer] update fos userbundle dependency

---

src/Kunstmaan/AdminListBundle/AdminList/Configurator/AbstractPageAdminListConfigurator.php
src/Kunstmaan/NodeBundle/Entity/HideSidebarInNodeEditInterface.php
src/Kunstmaan/NodeBundle/Resources/views/NodeAdmin/edit.html.twig

[NodeBundle, AdminListBundle]: fix new introduced abstractPageAdminList

---

src/Kunstmaan/MultiDomainBundle/Twig/MultiDomainTwigExtension.php

[MultiDomainBundle] Removed unused and invalid interface from TwigExtension

---

docs/06-04-config-bundle.md
src/Kunstmaan/ConfigBundle/Resources/doc/ConfigBundle.md

[KunstmaanConfigBundle]: change typo

---

src/Kunstmaan/AdminBundle/Resources/translations/messages.pl.yml
src/Kunstmaan/AdminListBundle/Resources/translations/messages.pl.yml
src/Kunstmaan/ArticleBundle/Resources/translations/messages.pl.yml
src/Kunstmaan/CacheBundle/Resources/translations/messages.pl.yml
src/Kunstmaan/DashboardBundle/Resources/translations/messages.pl.yml
src/Kunstmaan/FormBundle/Resources/translations/messages.pl.yml
src/Kunstmaan/GeneratorBundle/Resources/translations/messages.pl.yml
src/Kunstmaan/LeadGenerationBundle/Resources/translations/messages.pl.yml
src/Kunstmaan/MediaBundle/Resources/translations/messages.pl.yml
src/Kunstmaan/MediaPagePartBundle/Resources/translations/messages.pl.yml
src/Kunstmaan/MenuBundle/Resources/translations/messages.pl.yml
src/Kunstmaan/MultiDomainBundle/Resources/translations/messages.pl.yml
src/Kunstmaan/NodeBundle/Resources/translations/messages.pl.yml
src/Kunstmaan/NodeSearchBundle/Resources/translations/messages.pl.yml
src/Kunstmaan/PagePartBundle/Resources/translations/messages.pl.yml
src/Kunstmaan/RedirectBundle/Resources/translations/messages.pl.yml
src/Kunstmaan/SeoBundle/Resources/translations/messages.pl.yml
src/Kunstmaan/TaggingBundle/Resources/translations/messages.pl.yml
src/Kunstmaan/TranslatorBundle/Resources/translations/messages.pl.yml
src/Kunstmaan/UserManagementBundle/Resources/translations/messages.pl.yml

[All] Add polish translations

---

src/Kunstmaan/AdminBundle/Resources/views/Default/_js_footer.html.twig
src/Kunstmaan/GeneratorBundle/Generator/LayoutGenerator.php
src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/Resources/admin/js/admin-bundle-extra.js
src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/groundcontrol/bin/configured-tasks.js
src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/groundcontrol/gulpfile.babel.js

On request of @sandergo90: possibility to add extra javascript in the backend (if necessary).

[AdminBundle] [GeneratorBundle]: Add possibility to add extra js for the backend

---

groundcontrol/admin-bundle.tasks.js
groundcontrol/dashboard-bundle.tasks.js
groundcontrol/translator-bundle.tasks.js
gulpfile.babel.js

[UI] Added server & watch tasks for development

---

docs/03-01-intro.md

[DOCS]: add gulp-cli dependency

---

docs/06-03-article-bundle.md

This list wasn't up to date with what classes are generated, and where they're generated. This PR fixes that.
PS: This may concern more versions than just 4.0 (which this PR is for), so `master` might be a better fit.

[Docs] Update list of generated classes

---

src/Kunstmaan/SeoBundle/EventListener/NodeListener.php

This is a fix for PR #1348. No more new objects but FQCN as form types.

[SeoBundle] Fix Seo tab nodelistener

---

src/Kunstmaan/MediaBundle/Resources/views/Media/RemoteAudio/preview.html.twig

[MediaBundle] Fix audio display if media type isn't soundcloud

---

src/Kunstmaan/NodeBundle/Helper/Menu/ActionsMenuBuilder.php
src/Kunstmaan/NodeBundle/Resources/views/NodeAdmin/_modals.html.twig

Fix this error (When manual created page entity doesn't implement HasPageTemplateInterface)

[NodeBundle] Fix export pagetemplate

---

.travis.yml

[Travis] Add php 7.1 to travis

---

src/Kunstmaan/AdminBundle/Controller/DefaultController.php
src/Kunstmaan/AdminListBundle/Controller/AdminListController.php
src/Kunstmaan/ConfigBundle/Controller/ConfigController.php
src/Kunstmaan/FormBundle/Helper/FormHandler.php
src/Kunstmaan/LeadGenerationBundle/Controller/AbstractNewsletterController.php
src/Kunstmaan/MediaBundle/Controller/FolderController.php
src/Kunstmaan/MediaBundle/Controller/MediaController.php
src/Kunstmaan/SeoBundle/Controller/Admin/SettingsController.php
src/Kunstmaan/TranslatorBundle/Controller/TranslatorController.php
src/Kunstmaan/UserManagementBundle/Controller/GroupsController.php
src/Kunstmaan/UserManagementBundle/Controller/RolesController.php
src/Kunstmaan/UserManagementBundle/Controller/UsersController.php

Missing upgrade step https://github.com/symfony/symfony/blob/master/UPGRADE-3.2.md#form

[AllBundles] Add form isSubmitted before isValid

---

src/Kunstmaan/AdminListBundle/Resources/views/Page/list.html.twig

[AdminListBundle] Fix check canAdd on pages adminlist
