Kunstmaan/KunstmaanBundlesCMS

- src/Kunstmaan/GeneratorBundle/Command/GeneratePageCommand.php
- src/Kunstmaan/GeneratorBundle/Generator/PageGenerator.php
- src/Kunstmaan/GeneratorBundle/Generator/PagePartGenerator.php
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/adminlist/AdminList/AdminListConfigurator.php
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/page/Entity/Pages/ExtraFunctions.php
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/pagepart/Entity/PageParts/ExtraFunctions.php
> [GeneratorBundle] fix/refactor forms fqcn

- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/Entity/Category.php
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/Entity/Pages/Category.php
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/Entity/Pages/OverviewPage.php
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/Entity/Pages/Page.php
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/Entity/Tag.php
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/defaultsite/Entity/PageParts/BikesListPagePart.php
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/defaultsite/Entity/PageParts/PageBannerPagePart.php
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/defaultsite/Entity/PageParts/ServicePagePart.php
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/defaultsite/Entity/PageParts/UspPagePart.php
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/defaultsite/Entity/Pages/ContentPage.php
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/pagepart/Entity/PageParts/AudioPagePart/AudioPagePart.php
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/pagepart/Entity/PageParts/ButtonPagePart/ButtonPagePart.php
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/pagepart/Entity/PageParts/DownloadPagePart/DownloadPagePart.php
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/pagepart/Entity/PageParts/HeaderPagePart/HeaderPagePart.php
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/pagepart/Entity/PageParts/ImagePagePart/ImagePagePart.php
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/pagepart/Entity/PageParts/IntroTextPagePart/IntroTextPagePart.php
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/pagepart/Entity/PageParts/LinePagePart/LinePagePart.php
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/pagepart/Entity/PageParts/LinkPagePart/LinkPagePart.php
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/pagepart/Entity/PageParts/RawHtmlPagePart/RawHtmlPagePart.php
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/pagepart/Entity/PageParts/TextPagePart/TextPagePart.php
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/pagepart/Entity/PageParts/ToTopPagePart/ToTopPagePart.php
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/pagepart/Entity/PageParts/TocPagePart/TocPagePart.php
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/pagepart/Entity/PageParts/VideoPagePart/VideoPagePart.php
| Fixed tickets |  #1590
-Not all classes were updated.
-Also replaces some tabs with spaces
more info: #1590
> [GeneratorBundle] refactor to new SF3 forms with FQCN

- src/Kunstmaan/PagePartBundle/Controller/PagePartAdminController.php
> [PagePartBundle] fix pp chooser button after add

- src/Kunstmaan/AdminBundle/DependencyInjection/Compiler/DataCollectorPass.php
> [AdminBundle]: check if profiler is enabled

- src/Kunstmaan/AdminBundle/Resources/config/console_listener.yml
- src/Kunstmaan/NodeBundle/Helper/NodeAdmin/NodeAdminPublisher.php
- src/Kunstmaan/NodeSearchBundle/Configuration/NodePagesConfiguration.php
- src/Kunstmaan/NodeSearchBundle/EventListener/NodeIndexUpdateEventListener.php
- src/Kunstmaan/NodeSearchBundle/Resources/config/update_listener.yml
| Fixed tickets | #1509, #1547, #1606
> [NodeSearchBundle] Bugfix for indexing StructuredNodes and children

- docs/05-03-manage-translations.md
- docs/05-12-adding-a-custom-controller.md
> [DOCS] Fix typos in documentation

- .github/CONTRIBUTING.md
> [Docs] Fix the links in the contributing.md file

- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/Repository/PageRepository.php
> [SensioGeneratorBundle] set limit in PageRepository stub

- UPGRADE-4.0.md
> [Docs] fix markdown in upgrade guide

- src/Kunstmaan/MediaBundle/Entity/Media.php
> [MediaBundle] Don't show filesize if null

- src/Kunstmaan/AdminBundle/Form/MediaTokenTransformer.php
| Fixed tickets | https://github.com/Kunstmaan/KunstmaanBundlesCMS/issues/1592
> [KunstmaanAdminBundle] Fix adding image in WYSIWYG editor

- src/Kunstmaan/AdminListBundle/Controller/AdminListController.php
> [AdminListBundle] Incorrect logic checking if version lock is active

- src/Kunstmaan/NodeSearchBundle/Configuration/NodePagesConfiguration.php
| New feature?  | yes -> improvement
| Related tickets | #1417
> [NodeSearchBundle] Indexing styles and scripts fix

- docs/06-04-config-bundle.md
| New feature?  | o
| BC breaks?    | o
| Deprecations? | o
| Fixed tickets | #1573
> [Docs] Update 06-04-config-bundle.md

- docs/99-00-contributing.md
- docs/99-08-groundcontrol.md
> [UI] Added some documentation on how to contribute to the Ground Control skeleton

- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/defaultsite/Controller/DefaultController.php
| New feature?  | improvment
| Fixed tickets | #1316
> [GeneratorBundle] Preffered locale

- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/Resources/ui/scss/admin-style.scss
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/Resources/ui/scss/components/_components.scss
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/Resources/ui/scss/config/_config.scss
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/Resources/ui/scss/config/vendors/_cargobay-imports.scss
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/Resources/ui/scss/general/_general.scss
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/Resources/ui/scss/helpers/_helpers.scss
| Fixed tickets | [1638](https://github.com/Kunstmaan/KunstmaanBundlesCMS/issues/1638)
> [GeneratorBundle] Separate import rules for scss imports

- README.md
> Update badges in README.txt

- src/Kunstmaan/AdminBundle/Resources/ui/scss/default-theme/components/forms/_form-control.scss
> [AdminBundle] Align counter in input-group

- src/Kunstmaan/NodeSearchBundle/Configuration/NodePagesConfiguration.php
- src/Kunstmaan/NodeSearchBundle/Resources/config/services.yml
> [NodeSearchBundle] shards and replicas configurable

- groundcontrol/tasks/build-gc-skeleton.js
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/groundcontrol/bin/config/webpack.config.admin-extra.js
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/groundcontrol/bin/config/webpack.config.app.js
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/groundcontrol/bin/config/webpack.config.default.js
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/groundcontrol/bin/config/webpack.config.styleguide.js
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/groundcontrol/bin/configured-tasks.js
In the future we'll need to extend our webpack configuration. To avoid duplication of code between bundles it makes more sense to consolidate all common configuration (eg babel) into a single webpack configuration file.
> [UI] Extracted webpack configuration into separate files

- src/Kunstmaan/AdminBundle/EventListener/PasswordResettingListener.php
- src/Kunstmaan/ArticleBundle/Form/AbstractAuthorAdminType.php
- src/Kunstmaan/DashboardBundle/Widget/DashboardWidget.php
- src/Kunstmaan/MediaBundle/Helper/Media/AbstractMediaHandler.php
- src/Kunstmaan/NodeBundle/Event/SlugEvent.php
- src/Kunstmaan/NodeBundle/Form/NodeChoiceType.php
- src/Kunstmaan/UtilitiesBundle/Twig/UtilitiesTwigExtension.php
| Fixed tickets | https://github.com/Kunstmaan/KunstmaanBundlesCMS/issues/1677
> [AllBundles] - Method visibility public

- src/Kunstmaan/PagePartBundle/Resources/views/PagePartAdminTwigExtension/modal.html.twig
> [PagePartBundle]: pp preview needs to be not empty and defined

- .sensiolabs.yml
| Fixed tickets | https://github.com/Kunstmaan/KunstmaanBundlesCMS/issues/1696
> [AllBundles] .sensiolabs.yml to ignore .xml.dist files

- .sensiolabs.yml
| Fixed tickets | should fix sensio labs analysis
> [AllBundles] repair sensio analysis

- src/Kunstmaan/AdminListBundle/Service/EntityVersionLockService.php
| Fixed tickets | https://github.com/Kunstmaan/KunstmaanBundlesCMS/issues/1688
> [AdminListBundle] strict comparison with ===

- src/Kunstmaan/NodeBundle/Helper/URLHelper.php
| Fixed tickets | https://github.com/Kunstmaan/KunstmaanBundlesCMS/issues/1683
> [NodeBundle] unused class property

- .gitignore
Should be in global gitignore. Create and use it like so:
```
touch ~/.gitignore_global
git config --global core.excludesfile ~/.gitignore_global .
```
Then add .idea to the file
| Fixed tickets | https://github.com/Kunstmaan/KunstmaanBundlesCMS/issues/1685
> [SensiolabsInsight] - remove user .gitignore files

- src/Kunstmaan/SearchBundle/Command/PopulateIndexCommand.php
> [SearchBundle][FIX] Populate command failing 

- UPGRADE-5.0.md
- src/Kunstmaan/NodeSearchBundle/Configuration/NodePagesConfiguration.php
- src/Kunstmaan/SearchBundle/Command/SetupIndexCommand.php
- src/Kunstmaan/SearchBundle/Configuration/SearchConfigurationInterface.php
- src/Kunstmaan/SearchBundle/Resources/config/services.yml
> [SearchBundle][FIX] SetupIndex command failing

- src/Kunstmaan/AdminBundle/DependencyInjection/KunstmaanAdminExtension.php
- src/Kunstmaan/AdminBundle/EventListener/MappingListener.php
- src/Kunstmaan/AdminBundle/Helper/FormWidgets/Tabs/TabPane.php
- src/Kunstmaan/DashboardBundle/Command/GoogleAnalyticsDataCollectCommand.php
- src/Kunstmaan/DashboardBundle/Command/Helper/Analytics/ChartDataCommandHelper.php
- src/Kunstmaan/DashboardBundle/Command/Helper/Analytics/GoalCommandHelper.php
- src/Kunstmaan/DashboardBundle/Helper/Google/Analytics/ConfigHelper.php
- src/Kunstmaan/FixturesBundle/Builder/PageBuilder.php
- src/Kunstmaan/FormBundle/Entity/FormSubmissionFieldTypes/ChoiceFormSubmissionField.php
- src/Kunstmaan/FormBundle/Tests/Entity/PageParts/ChoicePagePartTest.php
- src/Kunstmaan/FormBundle/Tests/Entity/PageParts/EmailPagePartTest.php
- src/Kunstmaan/FormBundle/Tests/Entity/PageParts/FileUploadPagePartTest.php
- src/Kunstmaan/FormBundle/Tests/Entity/PageParts/MultiLineTextPagePartTest.php
- src/Kunstmaan/FormBundle/Tests/Entity/PageParts/SingleLineTextPagePartTest.php
- src/Kunstmaan/MediaBundle/Helper/File/FileHandler.php
- src/Kunstmaan/NodeBundle/EventListener/MappingListener.php
- src/Kunstmaan/NodeBundle/EventListener/NodeTranslationListener.php
- src/Kunstmaan/NodeBundle/Router/SlugRouter.php
- src/Kunstmaan/NodeBundle/Tests/Helper/Menu/ActionsMenuBuilderTest.php
- src/Kunstmaan/NodeBundle/Validation/URLValidator.php
- src/Kunstmaan/PagePartBundle/EventListener/NodeListener.php
- src/Kunstmaan/PagePartBundle/PagePartConfigurationReader/PagePartConfigurationParser.php
- src/Kunstmaan/TaggingBundle/Entity/TagManager.php
- src/Kunstmaan/TranslatorBundle/Command/ExportTranslationsCommand.php
Some general code style fixes as detected by phpstorm. Each commit is a specific code inspection fixed
> [AllBundles] Code style fixes

- src/Kunstmaan/TranslatorBundle/Controller/TranslatorController.php
> [TranslatorBundle] Use correct parameter to define locale columns

- src/Kunstmaan/AdminBundle/Resources/views/Toolbar/bundles_version.html.twig
> [AdminBundle] Fix toolbar version checker

- src/Kunstmaan/AdminBundle/Resources/views/Form/fields.html.twig
> [AdminBundle] remove hard coded 'validators' from twig view

- src/Kunstmaan/MediaBundle/Resources/views/Folder/show.html.twig
> [MediaBundle] Include filters even if no results found

- src/Kunstmaan/FormBundle/Controller/FormSubmissionsController.php
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/Controller/CategoryAdminListController.php
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/Controller/TagAdminListController.php
- src/Kunstmaan/RedirectBundle/Controller/RedirectAdminListController.php
> [AdminListBundle] add ods in requirements format since its now supported

- UPGRADE-5.0.md
> [Docs] Add liipimagine changes to upgrade guide

- UPGRADE-5.0.md
| Deprecations? | yes - but just docs on upgrading 
| Fixed tickets | #1747
> [AllBundles] Upgrade docs for deprecated form types

- src/Kunstmaan/AdminBundle/Resources/views/Resetting/reset_content.html.twig
> [AdminBundle] Fix styling of reset password form

- src/Kunstmaan/AdminBundle/Resources/ui/scss/default-theme/components/vendors/_select2.scss
> [AdminBundle] Hide wrapping content of large value

- src/Kunstmaan/AdminListBundle/Resources/views/AdminListTwigExtension/thumbwidget.html.twig
- src/Kunstmaan/AdminListBundle/Twig/AdminListTwigExtension.php
- src/Kunstmaan/MediaBundle/Resources/views/Folder/show.html.twig
> Filter in Media Thumbnail View

- UPGRADE-5.0.md
- composer.json
> [AllBundles] Set minimum symfony version to 3.4

- src/Kunstmaan/UtilitiesBundle/Helper/Shell/Shell.php
- src/Kunstmaan/UtilitiesBundle/Helper/Shell/ShellInterface.php
| Bug fix?      | Yes (nohup)
| New feature?  | Improvment
| BC breaks?    | No
| Deprecations? | No
| Fixed tickets | #931
> [UtilitiesBundle] Using Symfony Process in Shell Class

- src/Kunstmaan/NodeBundle/Form/Type/URLChooserType.php
> [NodeBundle] fixed error bubbling for URLChooser

- src/Kunstmaan/AdminBundle/AdminList/ExceptionAdminListConfigurator.php
- src/Kunstmaan/AdminBundle/Controller/ExceptionController.php
- src/Kunstmaan/AdminBundle/Repository/ExceptionRepository.php
- src/Kunstmaan/AdminBundle/Resources/translations/messages.en.yml
- src/Kunstmaan/AdminBundle/Resources/views/Settings/button_resolve_all.html.twig
> [AdminBundle][Feature] Resolve all exceptions

- src/Kunstmaan/RedirectBundle/Tests/Form/RedirectAdminTypeTest.php
> [RedirectBundle] update test  to reflect fix for #1745

- src/Kunstmaan/AdminListBundle/AdminList/Configurator/AbstractPageAdminListConfigurator.php
> [AdminListBundle] Fix property visibility

- src/Kunstmaan/AdminListBundle/AdminList/Configurator/AbstractDoctrineORMAdminListConfigurator.php
> [AdminListBundle] Interface instead class as argument type

- UPGRADE-5.0.md
- src/Kunstmaan/FormBundle/Entity/FormSubmissionField.php
> [FormBundle] removed discriminator map from submission field

- src/Kunstmaan/AdminListBundle/Resources/views/Default/list.html.twig
Button groups are not correctly closed in the HTML structure.
> [AdminListBundle]: fix divs

- src/Kunstmaan/SeoBundle/Form/SeoType.php
> [SeoBundle] Refactor seo description to be longer according to google's new length

- src/Kunstmaan/AdminBundle/Resources/views/Default/layout.html.twig
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/defaultsite/Resources/views/PageParts/PageBannerPagePart/view.html.twig
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/defaultsite/Resources/views/PageParts/ServicePagePart/view.html.twig
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/Resources/views/Layout/_footer.html.twig
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/Resources/views/Layout/_outdatedbrowser.html.twig
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/pagepart/Resources/views/PageParts/ButtonPagePart/view.html.twig
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/pagepart/Resources/views/PageParts/ImagePagePart/view.html.twig
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/pagepart/Resources/views/PageParts/LinkPagePart/view.html.twig
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/pagepart/Resources/views/PageParts/VideoPagePart/view.html.twig
| Deprecations? | 
https://jakearchibald.com/2016/performance-benefits-of-rel-noopener/
> [GeneratorBundle] Add rel="noopener" if target is new window

- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/Resources/views/Pages/OverviewPage/pagetemplate.html.twig
> [GeneratorBundle] twig files should use the generated article class name

- src/Kunstmaan/ArticleBundle/Form/AbstractArticlePageAdminType.php
> [ArticleBundle]: set correct translation

- src/Kunstmaan/NodeBundle/Repository/NodeRepository.php
> [NodeBundle] fixed triple page tree

- src/Kunstmaan/AdminBundle/Resources/ui/scss/default-theme/config/vendors/bootstrap/_bootstrap-vars.scss
> [AdminBundle] fixed z-index of modal

- src/Kunstmaan/AdminBundle/Helper/Security/Acl/AclHelper.php
- src/Kunstmaan/AdminBundle/Helper/Security/Acl/AclNativeHelper.php
- src/Kunstmaan/AdminBundle/Tests/Helper/Security/Acl/AclHelperTest.php
- src/Kunstmaan/AdminBundle/Tests/Helper/Security/Acl/AclNativeHelperTest.php
- src/Kunstmaan/AdminListBundle/AdminList/Configurator/AbstractPageAdminListConfigurator.php
- src/Kunstmaan/AdminListBundle/Helper/DoctrineDBALAdapter.php
- src/Kunstmaan/ArticleBundle/AdminList/AbstractArticlePageAdminListConfigurator.php
- src/Kunstmaan/ArticleBundle/Repository/AbstractArticleOverviewPageRepository.php
- src/Kunstmaan/MediaBundle/AdminList/MediaAdminListConfigurator.php
- src/Kunstmaan/MenuBundle/Form/MenuItemAdminType.php
- src/Kunstmaan/MenuBundle/Repository/MenuItemRepository.php
- src/Kunstmaan/NodeBundle/AdminList/NodeAdminListConfigurator.php
- src/Kunstmaan/NodeBundle/Form/NodeChoiceType.php
- src/Kunstmaan/NodeBundle/Repository/NodeRepository.php
- src/Kunstmaan/NodeBundle/Repository/NodeTranslationRepository.php
- src/Kunstmaan/TranslatorBundle/AdminList/TranslationAdminListConfigurator.php
- src/Kunstmaan/TranslatorBundle/Repository/TranslationRepository.php
This reverts commit 2027349c165788d55972f0f6a1e95205f2bf9542.
The PR for postgres fixes breaks a lot of stuff and needs to be reverted. @acrobat will check everything again and will create a optimized PR for this. But for now we need a stable version.
> [AllBundles] Revert "Postgres compatibility fixes (#1778)"

- src/Kunstmaan/AdminBundle/EventListener/ToolbarListener.php
> [KunstmaanAdminBundle] change php7 to php5 code

- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/Resources/views/Pages/OverviewPage/_filter-category.html.twig
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/Resources/views/Pages/OverviewPage/_filter-tag.html.twig
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/Resources/views/Pages/OverviewPage/pagetemplate.html.twig
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/Resources/ui/scss/components/_components.scss
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/Resources/ui/scss/components/structures/_filters.scss
> [GeneratorBundle] style blog filters

- src/Kunstmaan/NodeBundle/Resources/views/NodeAdmin/edit.html.twig
> [KunstmaanNodeBundle] admin styles no longer have .min extension

- src/Kunstmaan/AdminBundle/Resources/ui/js/_pagepart-editor.js
| Fixed tickets | NA
Big thank you @dbeerten for helping me out with this one!
> [AdminBundle] fixed delete pagepart modal issue

- src/Kunstmaan/AdminBundle/Form/MediaTokenTransformer.php
| Fixed tickets | https://github.com/Kunstmaan/KunstmaanBundlesCMS/issues/1826
> [AdminBundle] refactor media token transformer

- src/Kunstmaan/AdminBundle/Resources/views/Default/layout.html.twig
> [AdminBundle]: re-add the extrajavascript block

- src/Kunstmaan/MediaBundle/Controller/MediaController.php
> [MediaBundle] Bulk file upload fix

- src/Kunstmaan/AdminListBundle/Twig/AdminListTwigExtension.php
> [AdminListBundle]: ->loadTemplate() is only for internal use..

- src/Kunstmaan/LeadGenerationBundle/Resources/public/js/popup/Popup.js
- src/Kunstmaan/LeadGenerationBundle/Resources/public/js/popup/PopupManager.js
- src/Kunstmaan/LeadGenerationBundle/Resources/public/js/rule/AfterXScrollPercentRule.js
- src/Kunstmaan/LeadGenerationBundle/Resources/views/Newsletter/thanks.html.twig
Reset event listeners after submit + fixed serialization of form data
Add extras
| Fixed tickets | #1853
> [LeadGenerationBundle]: remove jquery dependency leadgeneration bundle

- src/Kunstmaan/AdminBundle/Security/OAuthAuthenticator.php
> [AdminBundle]: redirect to previous page when logging in with Google

- src/Kunstmaan/ArticleBundle/Router/TagCategoryRouter.php
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/Entity/Pages/Page.php
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/Form/Pages/PageAdminTypePartial.php.twig
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/Resources/views/Pages/OverviewPage/pagetemplate.html.twig
> [GeneratorBundle]: fixes for article generator

- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/Resources/config/pageparts/main.yml
> [GeneratorBundle] Fixed bundle namespace in article generator pagepart config

- src/Kunstmaan/AdminBundle/Helper/Security/Acl/Permission/PermissionAdmin.php
The current working directory is /web here so this command fails actually.
> [KunstmaanAdminBundle]: fix permissions

- groundcontrol/admin-bundle.tasks.js
- groundcontrol/dashboard-bundle.tasks.js
- groundcontrol/media-bundle.tasks.js
- groundcontrol/translator-bundle.tasks.js
- gulpfile.babel.js
Change the eslint config for the AdminBundle to make it lint the code inside the jsnext folder instead of the js folder
Remove all other eslint / stylelint config
| Fixed tickets | #1866
> [All] Linting changes

- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/Repository/PageRepositoryPartial.php.twig
> [GeneratorBundle] Fixed limit in generated article repository

- src/Kunstmaan/LeadGenerationBundle/Entity/Rule/RecurringEveryXTimeRule.php
> [LeadGenerationBundle]: times should not be blank

- UPGRADE-5.1.md
- src/Kunstmaan/NodeBundle/Helper/Menu/PageMenuAdaptor.php
- src/Kunstmaan/NodeBundle/Helper/PagesConfiguration.php
- src/Kunstmaan/NodeBundle/Helper/TreeIconInterface.php
The possibility already exists to change the icon in the sidebar tree of your page. This was already available by yml configuration. I've added a new interface, TreeIconInterface that can be implemented and that will return the icon that should be used. 
I've also changed some code formatting while on it.
> [NodeBundle] allow to set icon for tree

- src/Kunstmaan/FormBundle/AdminList/FormSubmissionExportListConfigurator.php
When exporting a large form submissions admin list, the export will timeout because the Objectmanager is getting full. Therefore i've added a batchsize option to the configurator. By default, it will clear the entitymanager every 20 iterates.
> [FormBundle]: add batchsize to export list

- src/Kunstmaan/NodeBundle/Toolbar/NodeDataCollector.php
> [NodeBundle]: node data collector should go to node id

- src/Kunstmaan/GeneratorBundle/Command/GenerateArticleCommand.php
- src/Kunstmaan/GeneratorBundle/Command/GenerateDefaultSiteCommand.php
> [GeneratorBundle] Fix article generator for no-interaction

- src/Kunstmaan/AdminBundle/Resources/translations/messages.en.yml
> [AdminBundle] Update add new translation

- src/Kunstmaan/AdminBundle/DependencyInjection/Configuration.php
> [AdminBundle] Change default value enable toolbar helper

- src/Kunstmaan/GeneratorBundle/Tests/data/app/config/config.yml
- src/Kunstmaan/TranslatorBundle/Tests/app/config/config.yml
> [Generator][[Translator] Trusted proxies is deprecated

- UPGRADE-5.0.md
> [Documentation] remove addition to upgrade guide that was merged in incorrectly

- src/Kunstmaan/MenuBundle/Form/MenuItemAdminType.php
> [MenuBundle] Change new window required

- src/Kunstmaan/FormBundle/Form/ChoicePagePartAdminType.php
> [FormBundle] Change label required for choice pagepart

- src/Kunstmaan/FormBundle/Resources/translations/messages.de.yml
- src/Kunstmaan/FormBundle/Resources/translations/messages.en.yml
- src/Kunstmaan/FormBundle/Resources/translations/messages.es.yml
- src/Kunstmaan/FormBundle/Resources/translations/messages.fr.yml
- src/Kunstmaan/FormBundle/Resources/translations/messages.it.yml
- src/Kunstmaan/FormBundle/Resources/translations/messages.nl.yml
- src/Kunstmaan/FormBundle/Resources/translations/messages.pl.yml
> [Form] Update regex translation

- src/Kunstmaan/TranslatorBundle/Command/ImportTranslationsCommand.php
- src/Kunstmaan/TranslatorBundle/Command/ImportTranslationsFromFileCommand.php
- src/Kunstmaan/TranslatorBundle/Controller/TranslatorController.php
- src/Kunstmaan/TranslatorBundle/DependencyInjection/KunstmaanTranslatorExtension.php
- src/Kunstmaan/TranslatorBundle/Form/TranslationsFileUploadType.php
- src/Kunstmaan/TranslatorBundle/Resources/config/commands.yml
- src/Kunstmaan/TranslatorBundle/Resources/translations/messages.en.yml
- src/Kunstmaan/TranslatorBundle/Resources/views/Translator/list.html.twig
- src/Kunstmaan/TranslatorBundle/Service/Command/Exporter/CSVFileExporter.php
- src/Kunstmaan/TranslatorBundle/Service/Command/Importer/ImportCommandHandler.php
- src/Kunstmaan/TranslatorBundle/Service/Command/Importer/Importer.php
Allow importing translations from an external xlsx, ods, csv file.
This is a basic just works implementation I made for an internal project. Should I refactor this code more for the bundles or/and should I provide an upload button on the translations page of the cms?
> [TranslatorBundle] Allow importing translations from an external xlsx, ods, csv file.

- src/Kunstmaan/MediaBundle/Helper/Imagine/CacheManager.php
There is an inconsistency when generating the hash in image paths when using a runtime config and the filter extension is not the same as the original image extension. This results in a hash mismatch in Liip\ImagineBundle\Controller\ImagineController. The hash needs to be made with the original image path to be consistent.
I don't think this solution is ideal, but it sketches the problem a bit. Any opinions/suggestions?
> [MediaBundle] Create runtime config hash using the original image path

- .travis.yml
- src/Kunstmaan/AdminBundle/Tests/Helper/Security/OAuth/OAuthUserCreatorTest.php
- src/Kunstmaan/FormBundle/AdminList/FormSubmissionExportListConfigurator.php
> [Travis][Tests] fix tests + update travis config

- .sensiolabs.yml
> [SensioInsights] adjust sensiolabs config

- README.md
Adds a link to our newly created Slack channel!
> [Docs] Add slack channel to README.md

- src/Kunstmaan/AdminListBundle/Resources/translations/messages.en.yml
> [AdminListBundle] Fixed incorrect indentation

- docs/bundles/adminlist-bundle/configuring-adminlists.md
- src/Kunstmaan/AdminListBundle/AdminList/Configurator/ChangeableLimitInterface.php
- src/Kunstmaan/AdminListBundle/Resources/translations/messages.en.yml
- src/Kunstmaan/AdminListBundle/Resources/views/AdminListTwigExtension/limit.html.twig
- src/Kunstmaan/AdminListBundle/Resources/views/AdminListTwigExtension/widget.html.twig
- src/Kunstmaan/AdminListBundle/Traits/ChangeableLimitTrait.php
- src/Kunstmaan/MediaBundle/AdminList/MediaAdminListConfigurator.php
- src/Kunstmaan/MediaBundle/Resources/views/Folder/show.html.twig
| Fixed tickets | #1900 #1893 
Fixes above tickets and implements changeablelimitinterface in bundles.
> [AdminlistBundle] [MediaBundle] Changeablelimitinterface implemented and fixes some bugs

- src/Kunstmaan/NodeSearchBundle/Helper/ElasticSearchUtil.php
should check the running version of elasticsearch (#1940)
Cache es version info
Change check priority
(cherry picked from commit 6c4503c6ff9791e0ef224d023e879e66c0ec5933)
> [NodeSearchBundle]: elasticsearch util improvement

- src/Kunstmaan/AdminListBundle/Twig/AdminListTwigExtension.php
> [AdminListBundle] fixes forgotten commit new feature changeablelimitinterface

- src/Kunstmaan/FormBundle/AdminList/FormSubmissionExportListConfigurator.php
> [KunstmaanFormBundle] batchsize is not initialized

- src/Kunstmaan/FormBundle/Form/CheckboxPagePartAdminType.php
- src/Kunstmaan/FormBundle/Form/EmailPagePartAdminType.php
- src/Kunstmaan/FormBundle/Form/MultiLineTextPagePartAdminType.php
- src/Kunstmaan/FormBundle/Form/SingleLineTextPagePartAdminType.php
- src/Kunstmaan/FormBundle/Form/SubmitButtonPagePartAdminType.php
Same as https://github.com/Kunstmaan/KunstmaanBundlesCMS/pull/1934
> [FormBundle] Change form labels to required

- UPGRADE-5.1.md
- src/Kunstmaan/SearchBundle/Command/DeleteIndexCommand.php
- src/Kunstmaan/SearchBundle/Command/PopulateIndexCommand.php
- src/Kunstmaan/SearchBundle/Command/SetupIndexCommand.php
- src/Kunstmaan/SearchBundle/Resources/config/services.yml
> [SearchBundle] Deprecate service container usage in commands

- UPGRADE-5.1.md
- src/Kunstmaan/MediaBundle/Command/CleanDeletedMediaCommand.php
- src/Kunstmaan/MediaBundle/Command/CreatePdfPreviewCommand.php
- src/Kunstmaan/MediaBundle/Command/RebuildFolderTreeCommand.php
- src/Kunstmaan/MediaBundle/Command/RenameSoftDeletedCommand.php
- src/Kunstmaan/MediaBundle/Resources/config/pdf_preview.yml
- src/Kunstmaan/MediaBundle/Resources/config/services.yml
Follow-up pr that deprecates container access in the commands of the media bundle
> [MediaBundle] Deprecate service container usage in commands

- src/Kunstmaan/AdminBundle/Resources/config/services.yml
- src/Kunstmaan/NodeBundle/DependencyInjection/KunstmaanNodeExtension.php
- src/Kunstmaan/NodeBundle/Resources/config/services.yml
- src/Kunstmaan/NodeSearchBundle/Resources/config/services.yml
- src/Kunstmaan/TranslatorBundle/Resources/config/services.yml
> [AllBundles] Mark services used in controllers as public

- src/Kunstmaan/AdminBundle/Resources/config/services.yml
> [AdminBundle] marked service as public

- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/groundcontrol/package.json
> [GeneratorBundle] Update gulp version

- src/Kunstmaan/UserManagementBundle/DependencyInjection/Compiler/FixUserManagerPass.php
- src/Kunstmaan/UserManagementBundle/KunstmaanUserManagementBundle.php
> [UserManagementBundle] marked service as public using compilerpass

- UPGRADE-5.1.md
- src/Kunstmaan/NodeBundle/Entity/AbstractPage.php
- src/Kunstmaan/NodeBundle/Entity/PageInterface.php
| Fixed tickets | #1980 
I've improved the deprecation message so the end-user actually knows how to fix the deprecation.
> [NodeBundle] Reword deprecation message and provide alternative to the end-user

- src/Kunstmaan/AdminBundle/Command/UpdateAclCommand.php
- src/Kunstmaan/AdminBundle/Resources/config/services.yml
- src/Kunstmaan/AdminBundle/Service/AclManager.php
Attention, this PR can't be merged until PR #1999 with the initial AclManager setup is merged.
> [AdminBundle] updated aclUpdateCommand to use AclManager

- UPGRADE-5.1.md
- src/Kunstmaan/AdminBundle/Command/ApplyAclCommand.php
- src/Kunstmaan/AdminBundle/Resources/config/services.yml
- src/Kunstmaan/AdminBundle/Service/AclManager.php
Attention, this PR can't be merged until PR #1999 & #2001 with the initial AclManager setup is merged.
> [AdminBundle] updated aclApplyCommand to use AclManager

- src/Kunstmaan/AdminBundle/Command/CreateUserCommand.php
> [AdminBundle] fixed create user command #1995

- README.md
> [Docs] set correct paths

- src/Kunstmaan/MediaBundle/Resources/views/Media/File/show.html.twig
- src/Kunstmaan/MediaBundle/Resources/views/Media/Image/show.html.twig
> [MediaBundle] Add target blank to download link

- src/Kunstmaan/AdminBundle/Command/CreateUserCommand.php
> [AdminBundle] fixed BC break in CreateUserCommand

- UPGRADE-5.1.md
- src/Kunstmaan/MediaBundle/Helper/Imagine/BackgroundFilterLoader.php
> [MediaBundle] fixed BackgroundFilterLoader issue

- UPGRADE-5.1.md
- composer.json
> [composer] readd swiftmailer bundle

- UPGRADE-5.1.md
- src/Kunstmaan/NodeBundle/DependencyInjection/Configuration.php
- src/Kunstmaan/NodeBundle/DependencyInjection/KunstmaanNodeExtension.php
- src/Kunstmaan/NodeBundle/Helper/Menu/ActionsMenuBuilder.php
- src/Kunstmaan/NodeBundle/Resources/config/services.yml
- src/Kunstmaan/NodeBundle/Tests/DependencyInjection/ConfigurationTest.php
- src/Kunstmaan/NodeBundle/Tests/DependencyInjection/KunstmaanNodeExtensionTest.php
> [KunstmaanNodeBundle] add configuration option for export page template

- src/Kunstmaan/AdminBundle/Command/ApplyAclCommand.php
- src/Kunstmaan/AdminBundle/Command/UpdateAclCommand.php
- src/Kunstmaan/AdminBundle/Resources/config/commands.yml
- src/Kunstmaan/AdminBundle/Resources/config/services.yml
Improved code, to work the same as the other commands
> [AdminBundle] moved acl commands service registrations to commands.yml

- src/Kunstmaan/MediaBundle/Helper/Imagine/BackgroundFilterLoader.php
> [MediaBundle] add return to load function

- src/Kunstmaan/NodeSearchBundle/DependencyInjection/Configuration.php
- src/Kunstmaan/NodeSearchBundle/DependencyInjection/KunstmaanNodeSearchExtension.php
- src/Kunstmaan/NodeSearchBundle/Helper/ElasticSearchUtil.php
> [KunstmaanNodeSearchBundle] use hosts in useVersion6 check

- src/Kunstmaan/TranslatorBundle/Resources/translations/messages.de.yml
- src/Kunstmaan/TranslatorBundle/Resources/translations/messages.es.yml
- src/Kunstmaan/TranslatorBundle/Resources/translations/messages.fr.yml
- src/Kunstmaan/TranslatorBundle/Resources/translations/messages.hu.yml
- src/Kunstmaan/TranslatorBundle/Resources/translations/messages.it.yml
- src/Kunstmaan/TranslatorBundle/Resources/translations/messages.nl.yml
- src/Kunstmaan/TranslatorBundle/Resources/translations/messages.pl.yml
> [Translations] New Crowdin translations

- src/Kunstmaan/FormBundle/Entity/FormSubmissionFieldTypes/FileFormSubmissionField.php
> [FormBundle] Show full path to file in form export

- src/Kunstmaan/NodeBundle/Resources/views/NodeAdmin/Modals/_publish.html.twig
> [NodeBundle] Fixed issue where date in passed could be selected when publishing later

- src/Kunstmaan/AdminBundle/Resources/views/Default/sidebar.html.twig
> [AdminBundle] Remove duplicate set in sidebar template

- .github/CONTRIBUTING.md
> [Docs] Fix the links in the github contributing.md file

- src/Kunstmaan/TranslatorBundle/AdminList/TranslationAdminListConfigurator.php
> [TranslatorBundle] fix non-unique locales in TranslationAdminConfigurator

- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/defaultsite/Resources/views/Layout/submenu.html.twig
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/defaultsite/Resources/views/Pages/SearchPage/pagetemplate.html.twig
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/Resources/views/Error/layout.html.twig
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/Resources/views/Layout/_breadcrumbs.html.twig
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/Resources/views/Layout/_footer.html.twig
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/Resources/views/Layout/_header.html.twig
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/Resources/views/Layout/_mobile-nav.html.twig
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/Resources/views/Layout/layout.html.twig
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/searchpage/Resources/views/Pages/SearchPage/view.html.twig
The specified roles are either redundant or specify invalid values. 
(You can verify this in the w3c validator of the default site: https://validator.w3.org/nu/?doc=http%3A%2F%2Fdemo.bundles.kunstmaan.be%2Fen%2F)
> [GeneratorBundle] Remove unnecessary roles on dom nodes

- .styleci.yml
Prepare styleci activation but disable checks on the 5.0 branch. We will only activate/start using it on master (5.1)
> [AllBundles] Disable styleci checks for 5.0

- src/Kunstmaan/MediaBundle/Resources/views/Chooser/chooserShowFolder.html.twig
> [MediaBundle] Added image sizes to media chooser

- src/Kunstmaan/FormBundle/Resources/config/services.yml
> [FormBundle] Mark services used in controllers as public

- src/Kunstmaan/AdminBundle/Controller/DefaultController.php
- src/Kunstmaan/AdminBundle/Controller/ModulesController.php
- src/Kunstmaan/AdminBundle/Controller/SettingsController.php
- src/Kunstmaan/DashboardBundle/Controller/GoogleAnalyticsController.php
- src/Kunstmaan/TaggingBundle/Controller/TagAdminListController.php
> [DashboardBundle] Set correct template path for widget action

- UPGRADE-5.1.md
- src/Kunstmaan/ArticleBundle/Entity/AbstractAuthor.php
- src/Kunstmaan/ArticleBundle/Entity/AbstractCategory.php
- src/Kunstmaan/ArticleBundle/Entity/AbstractTag.php
Deprecations should be silenced by default. Also reworded the message and added the missing line to the upgrade doc
> [ArticleBundle] Improve deprecation messages and add missing line in upgrade doc

- src/Kunstmaan/NodeSearchBundle/Resources/config/services.yml
> [NodeSearchBundle] Mark search service public for use in search commands

- src/Kunstmaan/AdminBundle/Security/OAuthAuthenticator.php
> [AdminBundle] fixed sf4 deprecation in OAuthAuthenticator

- src/Kunstmaan/GeneratorBundle/Command/KunstmaanGenerateCommand.php
- src/Kunstmaan/GeneratorBundle/DataFixtures/ORM/UserFixtures.php
- src/Kunstmaan/GeneratorBundle/Generator/KunstmaanGenerator.php
- src/Kunstmaan/GeneratorBundle/Helper/Sf4AppBundle.php
- src/Kunstmaan/MediaBundle/Resources/config/handlers.yml
- src/Kunstmaan/MediaBundle/Resources/config/services.yml
- src/Kunstmaan/NodeBundle/Resources/config/services.yml
- src/Kunstmaan/PagePartBundle/Resources/config/services.yml
- src/Kunstmaan/UtilitiesBundle/Resources/config/services.yml
> [GeneratorBundle] Prepare generators for sf4 support

- src/Kunstmaan/GeneratorBundle/Command/KunstmaanGenerateCommand.php
- src/Kunstmaan/GeneratorBundle/Generator/DefaultPagePartGenerator.php
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/pagepart/Entity/PageParts/AbstractFormPagePart/AbstractFormPagePart.php
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/pagepart/Entity/PageParts/AudioPagePart/AudioPagePart.php
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/pagepart/Entity/PageParts/ButtonPagePart/ButtonPagePart.php
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/pagepart/Entity/PageParts/CheckboxPagePart/CheckboxPagePart.php
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/pagepart/Entity/PageParts/ChoicePagePart/ChoicePagePart.php
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/pagepart/Entity/PageParts/DownloadPagePart/DownloadPagePart.php
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/pagepart/Entity/PageParts/EmailPagePart/EmailPagePart.php
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/pagepart/Entity/PageParts/ExtraFunctions.php
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/pagepart/Entity/PageParts/FileUploadPagePart/FileUploadPagePart.php
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/pagepart/Entity/PageParts/HeaderPagePart/HeaderPagePart.php
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/pagepart/Entity/PageParts/ImagePagePart/ImagePagePart.php
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/pagepart/Entity/PageParts/IntroTextPagePart/IntroTextPagePart.php
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/pagepart/Entity/PageParts/LinePagePart/LinePagePart.php
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/pagepart/Entity/PageParts/LinkPagePart/LinkPagePart.php
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/pagepart/Entity/PageParts/MultiLineTextPagePart/MultiLineTextPagePart.php
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/pagepart/Entity/PageParts/RawHtmlPagePart/RawHtmlPagePart.php
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/pagepart/Entity/PageParts/SingleLineTextPagePart/SingleLineTextPagePart.php
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/pagepart/Entity/PageParts/SubmitButtonPagePart/SubmitButtonPagePart.php
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/pagepart/Entity/PageParts/TextPagePart/TextPagePart.php
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/pagepart/Entity/PageParts/ToTopPagePart/ToTopPagePart.php
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/pagepart/Entity/PageParts/TocPagePart/TocPagePart.php
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/pagepart/Entity/PageParts/VideoPagePart/VideoPagePart.php
Code changes for both sf3.4/sf4 support in the default pagepart generator
> [GeneratorBundle] Symfony 4 support for default pagepart generator

- src/Kunstmaan/GeneratorBundle/Generator/ArticleGenerator.php
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/AdminList/PageAdminListConfigurator.php
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/Controller/AuthorAdminListController.php
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/Controller/CategoryAdminListController.php
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/Controller/PageAdminListController.php
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/Controller/TagAdminListController.php
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/DataFixtures/ORM/ArticleGenerator/ArticleFixtures.php
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/Entity/Pages/OverviewPage.php
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/Entity/Pages/Page.php
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/Helper/Menu/MenuAdaptor.php
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/Resources/config/pageparts/main.yml
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/Resources/config/pagetemplates/overviewpage.yml
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/Resources/config/pagetemplates/page.yml
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/Resources/views/Pages/OverviewPage/pagetemplate.html.twig
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/Resources/views/Pages/OverviewPage/view.html.twig
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/Resources/views/Pages/Page/view.html.twig
**PR must be rebased after #2218 is merged**
Code changes for both sf3.4/sf4 support in the article generator
> [GeneratorBundle] Symfony 4 support for the article generator

- src/Kunstmaan/GeneratorBundle/Command/GenerateLayoutCommand.php
- src/Kunstmaan/GeneratorBundle/Generator/LayoutGenerator.php
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/Resources/views/Default/index.html.twig
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/Resources/views/Error/layout.html.twig
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/Resources/views/Layout/_header.html.twig
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/Resources/views/Layout/layout.html.twig
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/Resources/views/Page/layout.html.twig
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/groundcontrol/bin/config/webpack.config.admin-extra.js
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/groundcontrol/bin/config/webpack.config.app.js
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/groundcontrol/bin/config/webpack.config.styleguide.js
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/groundcontrol/bin/configured-tasks.js
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/groundcontrol/gulpfile.babel.js
**PR must be rebased after #2218 is merged**
Code changes for both sf3.4/sf4 support in the layout generator
> [GeneratorBundle] Sf4 support for generate layout

- src/Kunstmaan/GeneratorBundle/composer.json
> [GeneratorBundle] Fixed broken composer.json

- src/Kunstmaan/GeneratorBundle/Generator/KunstmaanGenerator.php
Generating an entity with repository class was broken on sf4
> [GeneratorBunde] Fix entity generator with repository class creation for sf4

- src/Kunstmaan/AdminBundle/Security/OAuthAuthenticator.php
- src/Kunstmaan/NodeBundle/Entity/PageTabInterface.php
- src/Kunstmaan/NodeBundle/EventListener/EntityTabListener.php
- src/Kunstmaan/NodeBundle/EventListener/NodeListener.php
- src/Kunstmaan/NodeBundle/EventListener/NodeTabListener.php
- src/Kunstmaan/NodeBundle/Tests/unit/Entity/NodeTest.php
- src/Kunstmaan/NodeBundle/Tests/unit/Helper/NodeHelperTest.php
- src/Kunstmaan/NodeBundle/ValueObject/PageTab.php
Some pr's were merged into master with still some code style issues. This pr makes styleci happy again :)
> [AllBundles] Fix code style issues merged in the master branch

- src/Kunstmaan/NodeBundle/Helper/URLHelper.php
- src/Kunstmaan/NodeBundle/Validation/URLValidator.php
> [NodeBundle] Fixed url chooser for multidomain

- src/Kunstmaan/GeneratorBundle/Command/GeneratePageCommand.php
- src/Kunstmaan/GeneratorBundle/Command/KunstmaanGenerateCommand.php
- src/Kunstmaan/GeneratorBundle/Generator/KunstmaanGenerator.php
- src/Kunstmaan/GeneratorBundle/Generator/PageGenerator.php
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/page/Entity/Pages/ExtraFunctions.php
- src/Kunstmaan/GeneratorBundle/Resources/config/services.yml
> [GeneratorBundle] refactored page generator

- src/Kunstmaan/GeneratorBundle/Command/GenerateEntityCommand.php
- src/Kunstmaan/GeneratorBundle/Command/KunstmaanGenerateCommand.php
> [GeneratorBundle] refactored entity generator

- src/Kunstmaan/RedirectBundle/Router/RedirectRouter.php
> [RedirectBundle] Removed Redirect entity update bug in RedirectRouter

- src/Kunstmaan/GeneratorBundle/Command/GenerateArticleCommand.php
- src/Kunstmaan/GeneratorBundle/Generator/ArticleGenerator.php
> [GeneratorBundle] update parent regex in article generator

- src/Kunstmaan/GeneratorBundle/Command/GenerateSearchPageCommand.php
- src/Kunstmaan/GeneratorBundle/Generator/SearchPageGenerator.php
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/searchpage/Entity/Pages/SearchPage.php
- src/Kunstmaan/GeneratorBundle/Resources/config/services.yml
Code changes for both sf3.4/sf4 support in the searchpage generator
> [GeneratorBundle] Sf4 support for searchpage generator

- src/Kunstmaan/UtilitiesBundle/composer.json
> [UtilitiesBundle] Update composer json

- src/Kunstmaan/AdminBundle/composer.json
> [AdminBundle] update composer

- src/Kunstmaan/AdminBundle/composer.json
- src/Kunstmaan/AdminListBundle/composer.json
- src/Kunstmaan/BehatBundle/composer.json
- src/Kunstmaan/ConfigBundle/composer.json
- src/Kunstmaan/MediaBundle/composer.json
- src/Kunstmaan/NodeBundle/composer.json
- src/Kunstmaan/PagePartBundle/composer.json
> [Composer] Fix composer json for admin/adminlist/behat/media/node/pagepart bundle

- src/Kunstmaan/UtilitiesBundle/composer.json
> [UtilitiesBundle] Fix missing dependency 

- src/Kunstmaan/NodeBundle/composer.json
> [NodeBundle] Fix missing dependency

- src/Kunstmaan/ArticleBundle/composer.json
> [ArticleBundle] Fix article deps

- src/Kunstmaan/FormBundle/composer.json
> [FormBundle] Fix dependencies

- src/Kunstmaan/MediaPagePartBundle/composer.json
> [MediaPagePartBundle] Fix dependencies

- src/Kunstmaan/DashboardBundle/composer.json
> [DashboardBundle] Fix dependencies

- src/Kunstmaan/CacheBundle/composer.json
> [CacheBundle] Added composer json

- src/Kunstmaan/GeneratorBundle/composer.json
> [GeneratorBundle] Fix dependencies

- src/Kunstmaan/UserManagementBundle/composer.json
> [UserManagementBundle] updated composer dependencies

- src/Kunstmaan/MenuBundle/composer.json
> [MenuBundle] Fixed dependencies

- src/Kunstmaan/MultiDomainBundle/.gitignore
- src/Kunstmaan/MultiDomainBundle/composer.json
> [MultiDominBundle] Added composer json + gitignore

- src/Kunstmaan/SearchBundle/composer.json
> [SearchBundle] Fix dependencies

- src/Kunstmaan/VotingBundle/composer.json
> [VotingBundle] updated dependencies

- src/Kunstmaan/SearchBundle/composer.json
> [SearchBundle] Fix wrong dependency

- src/Kunstmaan/NodeSearchBundle/composer.json
> [NodeSearchBundle] Fix dependencies

- src/Kunstmaan/MediaBundle/composer.json
> [MediaBundle] Fix wrong dependency

- src/Kunstmaan/SeoBundle/Tests/unit/Entity/SeoTest.php
- src/Kunstmaan/SeoBundle/composer.json
> [SeoBundle] Fix dependencies + remove wrong test

- src/Kunstmaan/RedirectBundle/composer.json
> [RedirectBundle] Fix dependencies

- src/Kunstmaan/LeadGenerationBundle/composer.json
> [LeadGenerationBundle] update dependencies + fix autoload

- src/Kunstmaan/FixturesBundle/composer.json
> [FixturesBundle] Update dependencies

- src/Kunstmaan/AdminBundle/Tests/unit/EventListener/ConsoleExceptionListenerTest.php
- src/Kunstmaan/AdminBundle/composer.json
> [AdminBundle] composer update

- src/Kunstmaan/AdminBundle/composer.json
> [AdminBundle] fixed bad merge in composer.json

- src/Kunstmaan/BehatBundle/composer.json
> [BehatBundle] upgraded dev dependencies

- src/Kunstmaan/NodeSearchBundle/Tests/unit/DependencyInjection/Compiler/NodeSearcherCompilerPassTest.php
- src/Kunstmaan/NodeSearchBundle/Tests/unit/DependencyInjection/ConfigurationTest.php
- src/Kunstmaan/NodeSearchBundle/Tests/unit/DependencyInjection/KunstmaanNodeSearchExtensionTest.php
- src/Kunstmaan/NodeSearchBundle/Tests/unit/Entity/AbstractSearchPageTest.php
- src/Kunstmaan/NodeSearchBundle/Tests/unit/Entity/NodeSearchTest.php
- src/Kunstmaan/NodeSearchBundle/Tests/unit/Event/IndexNodeEventTest.php
- src/Kunstmaan/NodeSearchBundle/Tests/unit/EventListener/NodeIndexUpdateEventListenerTest.php
- src/Kunstmaan/NodeSearchBundle/Tests/unit/Services/SearchServiceTest.php
- src/Kunstmaan/NodeSearchBundle/composer.json
> [NodeSearchBundle] upgraded dev dependencies

- src/Kunstmaan/SearchBundle/Tests/unit/DependencyInjection/Configuration/SearchConfigurationChainTest.php
- src/Kunstmaan/SearchBundle/Tests/unit/DependencyInjection/KunstmaanSearchExtensionTest.php
- src/Kunstmaan/SearchBundle/composer.json
> [SearchBundle] upgraded dev dependencies

- src/Kunstmaan/TaggingBundle/.gitignore
- src/Kunstmaan/TaggingBundle/Tests/unit/DependencyInjection/ConfigurationTest.php
- src/Kunstmaan/TaggingBundle/Tests/unit/Entity/TagManagerTest.php
- src/Kunstmaan/TaggingBundle/Tests/unit/Entity/TagTest.php
- src/Kunstmaan/TaggingBundle/Tests/unit/Entity/TaggableTraitTest.php
- src/Kunstmaan/TaggingBundle/Tests/unit/Entity/TaggingTest.php
- src/Kunstmaan/TaggingBundle/composer.json
> [TaggingBundle] upgraded dev dependencies

- src/Kunstmaan/UserManagementBundle/Tests/unit/DependencyInjection/ConfigurationTest.php
- src/Kunstmaan/UserManagementBundle/Tests/unit/DependencyInjection/KunstmaanUserManagementExtensionTest.php
- src/Kunstmaan/UserManagementBundle/composer.json
> [UserManagementBundle] upgraded dev dependencies

- src/Kunstmaan/CacheBundle/.gitignore
- src/Kunstmaan/CacheBundle/composer.json
> [CacheBundle] updated dev dependencies

- src/Kunstmaan/FixturesBundle/.gitignore
- src/Kunstmaan/FixturesBundle/Tests/unit/DependencyInjection/ConfigurationTest.php
- src/Kunstmaan/FixturesBundle/Tests/unit/DependencyInjection/KunstmaanFixturesExtensionTest.php
- src/Kunstmaan/FixturesBundle/composer.json
> [FixturesBundle] upgraded dev requirements

- src/Kunstmaan/AdminListBundle/Tests/unit/AdminList/AdminListTest.php
- src/Kunstmaan/AdminListBundle/Tests/unit/Model/ConcreteConfigurator.php
Refactored/simplified the AdminListTest to remove the dependencies on other kuma bundles and make it more "unit test".
> [AdminListBundle] refactored/simplified  AdminListTest

- src/Kunstmaan/SearchBundle/DependencyInjection/Configuration.php
> [SearchBundle] Don't require value if we provide a default value

- src/Kunstmaan/MenuBundle/Resources/config/services.yml
> [MenuBundle] Mark menu service as public

- src/Kunstmaan/MediaPagePartBundle/Tests/unit/DependencyInjection/ConfigurationTest.php
Fixed class extend we missed in #2317
> [MediaPagePartBundle] Fixed last remaining extend of old phpunit testcase class

- UPGRADE-5.2.md
- src/Kunstmaan/TranslatorBundle/Command/MigrationsDiffCommand.php
- src/Kunstmaan/TranslatorBundle/Resources/config/services.yml
- src/Kunstmaan/TranslatorBundle/Service/Command/DiffCommand.php
> [TranslatorBundle] Deprecated the MigrationsDiffCommand & DiffCommand

- src/Kunstmaan/AdminBundle/DependencyInjection/Configuration.php
- src/Kunstmaan/AdminListBundle/DependencyInjection/Configuration.php
- src/Kunstmaan/ArticleBundle/DependencyInjection/Configuration.php
- src/Kunstmaan/ConfigBundle/DependencyInjection/Configuration.php
- src/Kunstmaan/DashboardBundle/DependencyInjection/Configuration.php
- src/Kunstmaan/FixturesBundle/DependencyInjection/Configuration.php
- src/Kunstmaan/FormBundle/DependencyInjection/Configuration.php
- src/Kunstmaan/LeadGenerationBundle/DependencyInjection/Configuration.php
- src/Kunstmaan/MediaBundle/DependencyInjection/Configuration.php
- src/Kunstmaan/MediaPagePartBundle/DependencyInjection/Configuration.php
- src/Kunstmaan/MenuBundle/DependencyInjection/Configuration.php
- src/Kunstmaan/MultiDomainBundle/DependencyInjection/Configuration.php
- src/Kunstmaan/NodeBundle/DependencyInjection/Configuration.php
- src/Kunstmaan/NodeSearchBundle/DependencyInjection/Configuration.php
- src/Kunstmaan/PagePartBundle/DependencyInjection/Configuration.php
- src/Kunstmaan/RedirectBundle/DependencyInjection/Configuration.php
- src/Kunstmaan/SearchBundle/DependencyInjection/Configuration.php
- src/Kunstmaan/SeoBundle/DependencyInjection/Configuration.php
- src/Kunstmaan/SitemapBundle/DependencyInjection/Configuration.php
- src/Kunstmaan/TaggingBundle/DependencyInjection/Configuration.php
- src/Kunstmaan/TranslatorBundle/DependencyInjection/Configuration.php
- src/Kunstmaan/UserManagementBundle/DependencyInjection/Configuration.php
- src/Kunstmaan/UtilitiesBundle/DependencyInjection/Configuration.php
- src/Kunstmaan/VotingBundle/DependencyInjection/Configuration.php
> [AllBundles] Fix sf4 rootNode deprecation

- src/Kunstmaan/AdminBundle/Resources/views/Form/fields.html.twig
| Fixed tickets | #2282, #2157
The change in PR #2049 broke the order functionality of sub entities of a pagepart. This PR reverts the change.
@SpadXIII what was the actual issue you fixed in your PR? So we can try to find a solution for both issues!
> [AdminBundle] Revert PR #2049 changes

- UPGRADE-5.2.md
Added missing items to the upgrade doc
> [AllBundles] Added missing items in upgrade doc for 5.2

- src/Kunstmaan/AdminBundle/Tests/unit/EventListener/CloneListenerTest.php
- src/Kunstmaan/AdminBundle/Tests/unit/Validator/Constraints/PasswordRestrictionsValidatorTest.php
- src/Kunstmaan/AdminBundle/composer.json
Refactored test to remove dependency on the KunstmaanMediaBundle
> [AdminBundle] refactored the CloneListenerTest

- src/Kunstmaan/AdminBundle/Tests/unit/Helper/Menu/ModulesMenuAdaptorTest.php
> [AdminBundle] added ModulesMenuAdaptorTest

- src/Kunstmaan/MediaBundle/DependencyInjection/KunstmaanMediaExtension.php
- src/Kunstmaan/SearchBundle/Resources/config/services.yml
> [MediaBundle][SearchBundle] Provide default config for bundles to work on sf4

- src/Kunstmaan/AdminBundle/Helper/Menu/SimpleMenuAdaptor.php
- src/Kunstmaan/AdminBundle/Tests/unit/Helper/Menu/SimpleMenuAdaptorTest.php
> [AdminBundle] added SimpleMenuAdaptorTest

- src/Kunstmaan/AdminBundle/Tests/unit/Helper/Menu/MenuBuilderTest.php
- src/Kunstmaan/AdminBundle/composer.json
Refactored test to remove dependency on the KunstmaanMenuBundle
> [AdminBundle] refactored the MenuBuilderTest

- src/Kunstmaan/AdminBundle/Helper/Menu/SettingsMenuAdaptor.php
- src/Kunstmaan/AdminBundle/Tests/unit/Helper/Menu/SettingsMenuAdaptorTest.php
> [AdminBundle] added SettingsMenuAdaptorTest

- src/Kunstmaan/AdminListBundle/Tests/unit/AdminList/AdminListTest.php
- src/Kunstmaan/AdminListBundle/Tests/unit/AdminList/ExportListTest.php
This should be merged last of all the AdminListBundle test refactors, as it removes another set of bundles from the dev dependencies.
> [AdminListBundle] Refactored exportlist test

- src/Kunstmaan/TranslatorBundle/DependencyInjection/Configuration.php
- src/Kunstmaan/TranslatorBundle/DependencyInjection/KunstmaanTranslatorExtension.php
- src/Kunstmaan/TranslatorBundle/README.md
- src/Kunstmaan/TranslatorBundle/Tests/unit/DependencyInjection/KunstmaanTranslatorExtensionTest.php
> [TranslatorBundle] fixed sf4 translations issue

- src/Kunstmaan/GeneratorBundle/Command/GenerateAdminListCommand.php
Fixed the messages for the adminlist generator when SF4 is used.
> [GeneratorBundle] fixed adminlist generator messages

- src/Kunstmaan/NodeBundle/Resources/config/routing.yml
> [NodeBundle] Fix incorrect routing config for controller-as-service

- src/Kunstmaan/GeneratorBundle/Command/GenerateArticleCommand.php
> [GeneratorBundle] fixed multilanguage parameter in article generator

- src/Kunstmaan/NodeBundle/Controller/WidgetsController.php
> [NodeBundle] fixed multilanguage parameter in WidgetController

- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/Entity/Category.php
> [GeneratorBundle] Fix typo in table name of article generator

- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/Resources/ui/js/app.js
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/groundcontrol/package.json
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/pagepart/Resources/views/PageParts/ImagePagePart/view.html.twig
> [GeneratorBundle] fix image-pp & add srcset polyfill for IE11

- src/Kunstmaan/MediaBundle/Resources/views/Folder/show.html.twig
> [MediaBundle] Add image width and height to media module as done in PP media chooser

- src/Kunstmaan/GeneratorBundle/Command/InstallCommand.php
> [GeneratorBundle] Fix null check

- src/Kunstmaan/AdminBundle/Resources/views/Default/_css.html.twig
> [AdminBundle] fix typo in filename of wordcount

- src/Kunstmaan/NodeBundle/Helper/Services/PageCreatorService.php
> [NodeBundle] Allow entity as creator

- src/Kunstmaan/GeneratorBundle/Generator/AdminTestsGenerator.php
> [GeneratorBundle] fix admin test generator

- src/Kunstmaan/RedirectBundle/Router/RedirectRouter.php
The upmerge of #2239 partially reverted the fix from #1961. This PR fixes this regression.
> [RedirectBundle] Re-add utf8 route fix

- src/Kunstmaan/GeneratorBundle/Generator/DefaultSiteGenerator.php
- src/Kunstmaan/GeneratorBundle/Tests/unit/Generator/DefaultSiteGeneratorTest.php
> [GeneratorBundle] Fix default generator twig override paths

- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/pagepart/Resources/views/PageParts/ImagePagePart/view.html.twig
After the changes in #2406 the media pp view was broken when adding a new media pp
> [GeneratorBundle] Fix error in media pp twig view for new pp's

- src/Kunstmaan/NodeSearchBundle/Configuration/NodePagesConfiguration.php
> [NodeSearchBundle] Correctly index page with utf8 characters

- .travis.yml
Install imagick and ghostscript to skip less tests during the phpunit run.
> [AllBundles] Install imagick extension/ghostscript to skip less unit tests

- .travis.yml
This fix was lost during the upmerge. See #2278
> [AllBundles] Remove php 7.3 check as php-cs-fixer supports it now

- src/Kunstmaan/NodeBundle/Controller/WidgetsController.php
- src/Kunstmaan/NodeSearchBundle/EventListener/NodeIndexUpdateEventListener.php
Some pr's were merged without styleci passing. This pr fixes the remaining code style issues
> [NodeBundle][NodeSearchBundle] Fix code style issues

- src/Kunstmaan/ConfigBundle/Controller/ConfigController.php
- src/Kunstmaan/ConfigBundle/DependencyInjection/Compiler/KunstmaanConfigConfigurationPass.php
- src/Kunstmaan/ConfigBundle/DependencyInjection/Configuration.php
- src/Kunstmaan/ConfigBundle/Helper/Menu/ConfigMenuAdaptor.php
- src/Kunstmaan/ConfigBundle/Tests/unit/DependencyInjection/Compiler/DeprecateClassParametersPassTest.php
- src/Kunstmaan/ConfigBundle/Tests/unit/Entity/AbstractConfigTest.php
- src/Kunstmaan/ConfigBundle/Twig/ConfigTwigExtension.php
> [ConfigBundle] Code improvement found by static code analysis

- src/Kunstmaan/FixturesBundle/Resources/config/services.yml
These services are accessed directly from the container so should be public for sf4.
> [FixturesBundle] Mark services as public

- src/Kunstmaan/DashboardBundle/Resources/config/services.yml
> [Dashboardbundle] Mark service as public for sf4 compatibility

- src/Kunstmaan/RedirectBundle/Helper/Menu/RedirectMenuAdaptor.php
- src/Kunstmaan/RedirectBundle/Router/RedirectRouter.php
- src/Kunstmaan/RedirectBundle/Tests/unit/AdminList/RedirectAdminListConfiguratorTest.php
- src/Kunstmaan/RedirectBundle/Tests/unit/DependencyInjection/Compiler/DeprecateClassParametersPassTest.php
- src/Kunstmaan/RedirectBundle/Tests/unit/Entity/RedirectTest.php
- src/Kunstmaan/RedirectBundle/Tests/unit/Form/RedirectAdminTypeTest.php
- src/Kunstmaan/RedirectBundle/Tests/unit/Router/RedirectRouterTest.php
> [RedirectBundle] Code improvement found by static code analysis

- src/Kunstmaan/SearchBundle/Command/SetupIndexCommand.php
- src/Kunstmaan/SearchBundle/Configuration/SearchConfigurationChain.php
- src/Kunstmaan/SearchBundle/DependencyInjection/KunstmaanSearchExtension.php
- src/Kunstmaan/SearchBundle/Provider/SearchProviderChain.php
- src/Kunstmaan/SearchBundle/Tests/unit/DependencyInjection/Compiler/DeprecateClassParametersPassTest.php
- src/Kunstmaan/SearchBundle/Tests/unit/DependencyInjection/KunstmaanSearchExtensionTest.php
> [SearchBundle] Code improvement found by static code analysis

- src/Kunstmaan/VotingBundle/Controller/VotingController.php
- src/Kunstmaan/VotingBundle/DependencyInjection/KunstmaanVotingExtension.php
- src/Kunstmaan/VotingBundle/Repository/AbstractVoteRepository.php
- src/Kunstmaan/VotingBundle/Tests/unit/DependencyInjection/KunstmaanVotingExtensionTest.php
- src/Kunstmaan/VotingBundle/Tests/unit/EventListener/Security/MaxNumberByIpEventListenerTest.php
- src/Kunstmaan/VotingBundle/Tests/unit/Services/RepositoryResolverTest.php
> [VotingBundle] Code improvement found by static code analysis

- src/Kunstmaan/UserManagementBundle/Controller/GroupsController.php
- src/Kunstmaan/UserManagementBundle/Controller/RolesController.php
- src/Kunstmaan/UserManagementBundle/Controller/UsersController.php
- src/Kunstmaan/UserManagementBundle/Helper/Menu/UserManagementMenuAdaptor.php
- src/Kunstmaan/UserManagementBundle/Tests/unit/DependencyInjection/Compiler/DeprecateClassParametersPassTest.php
> [UserManagementBundle] Code improvement found by static code analysis

- src/Kunstmaan/TaggingBundle/Entity/TagManager.php
- src/Kunstmaan/TaggingBundle/Entity/TaggableTrait.php
- src/Kunstmaan/TaggingBundle/Helper/Menu/TagMenuAdaptor.php
- src/Kunstmaan/TaggingBundle/Tests/unit/Entity/TagManagerTest.php
> [TaggingBundle] Code improvement found by static code analysis

- src/Kunstmaan/SeoBundle/EventListener/CloneListener.php
- src/Kunstmaan/SeoBundle/Form/SeoType.php
- src/Kunstmaan/SeoBundle/Helper/Menu/SeoManagementMenuAdaptor.php
- src/Kunstmaan/SeoBundle/Helper/Order.php
- src/Kunstmaan/SeoBundle/Helper/OrderConverter.php
- src/Kunstmaan/SeoBundle/Helper/OrderItem.php
- src/Kunstmaan/SeoBundle/Helper/OrderPreparer.php
- src/Kunstmaan/SeoBundle/Repository/SeoRepository.php
- src/Kunstmaan/SeoBundle/Tests/unit/Twig/TwigExtensionTest.php
- src/Kunstmaan/SeoBundle/Twig/GoogleAnalyticsTwigExtension.php
- src/Kunstmaan/SeoBundle/Twig/SeoTwigExtension.php
> [SeoBundle] Code improvement found by static code analysis

- src/Kunstmaan/MultiDomainBundle/Controller/SiteSwitchController.php
- src/Kunstmaan/MultiDomainBundle/DependencyInjection/KunstmaanMultiDomainExtension.php
- src/Kunstmaan/MultiDomainBundle/Helper/DomainConfiguration.php
- src/Kunstmaan/MultiDomainBundle/Router/DomainBasedLocaleRouter.php
- src/Kunstmaan/MultiDomainBundle/Tests/unit/DependencyInjection/Compiler/DeprecateClassParametersPassTest.php
- src/Kunstmaan/MultiDomainBundle/Tests/unit/EventListener/HostOverrideListenerTest.php
- src/Kunstmaan/MultiDomainBundle/Tests/unit/Helper/DomainConfigurationTest.php
- src/Kunstmaan/MultiDomainBundle/Tests/unit/Router/DomainBasedLocaleRouterTest.php
> [MultiDomainBundle] Code improvement found by static code analysis

- src/Kunstmaan/TranslatorBundle/Service/Translator/CacheValidator.php
- src/Kunstmaan/TranslatorBundle/Tests/unit/Service/Translator/CacheValidatorTest.php
> [TranslatorBundle] Remove useless loop that doesn't loop

- src/Kunstmaan/MenuBundle/AdminList/MenuItemAdminListConfigurator.php
- src/Kunstmaan/MenuBundle/Entity/BaseMenuItem.php
- src/Kunstmaan/MenuBundle/Service/MenuAdaptor.php
- src/Kunstmaan/MenuBundle/Service/MenuService.php
- src/Kunstmaan/MenuBundle/Tests/unit/DependencyInjection/Compiler/DeprecateClassParametersPassTest.php
- src/Kunstmaan/MenuBundle/Tests/unit/Entity/MenuItemTest.php
- src/Kunstmaan/MenuBundle/Twig/MenuTwigExtension.php
> [MenuBundle] Code improvement found by static code analysis

- src/Kunstmaan/DashboardBundle/Command/GoogleAnalyticsConfigsListCommand.php
- src/Kunstmaan/DashboardBundle/Command/GoogleAnalyticsDataCollectCommand.php
- src/Kunstmaan/DashboardBundle/Command/GoogleAnalyticsOverviewsGenerateCommand.php
- src/Kunstmaan/DashboardBundle/Command/GoogleAnalyticsOverviewsListCommand.php
- src/Kunstmaan/DashboardBundle/Command/GoogleAnalyticsSegmentsListCommand.php
- src/Kunstmaan/DashboardBundle/Command/Helper/Analytics/AbstractAnalyticsCommandHelper.php
- src/Kunstmaan/DashboardBundle/Command/Helper/Analytics/ChartDataCommandHelper.php
- src/Kunstmaan/DashboardBundle/Command/Helper/Analytics/GoalCommandHelper.php
- src/Kunstmaan/DashboardBundle/Command/Helper/Analytics/MetricsCommandHelper.php
- src/Kunstmaan/DashboardBundle/Command/Helper/Analytics/UsersCommandHelper.php
- src/Kunstmaan/DashboardBundle/Controller/DashboardController.php
- src/Kunstmaan/DashboardBundle/Controller/GoogleAnalyticsController.php
- src/Kunstmaan/DashboardBundle/Entity/AnalyticsConfig.php
- src/Kunstmaan/DashboardBundle/Entity/AnalyticsOverview.php
- src/Kunstmaan/DashboardBundle/Entity/AnalyticsSegment.php
- src/Kunstmaan/DashboardBundle/Helper/Google/Analytics/ConfigHelper.php
- src/Kunstmaan/DashboardBundle/Repository/AnalyticsConfigRepository.php
- src/Kunstmaan/DashboardBundle/Repository/AnalyticsSegmentRepository.php
- src/Kunstmaan/DashboardBundle/Tests/unit/DependencyInjection/Compiler/DeprecateClassParametersPassTest.php
- src/Kunstmaan/DashboardBundle/Tests/unit/Entity/AnalyticsConfigTest.php
- src/Kunstmaan/DashboardBundle/Tests/unit/Entity/AnalyticsOverviewTest.php
- src/Kunstmaan/DashboardBundle/Tests/unit/Entity/AnalyticsSegmentTest.php
> [DashboardBundle] Code improvement found by static code analysis

- src/Kunstmaan/FormBundle/Controller/FormSubmissionsController.php
- src/Kunstmaan/FormBundle/Entity/AbstractFormPage.php
- src/Kunstmaan/FormBundle/Entity/FormSubmissionFieldTypes/BooleanFormSubmissionField.php
- src/Kunstmaan/FormBundle/Entity/FormSubmissionFieldTypes/ChoiceFormSubmissionField.php
- src/Kunstmaan/FormBundle/Entity/FormSubmissionFieldTypes/FileFormSubmissionField.php
- src/Kunstmaan/FormBundle/Helper/FormHandler.php
- src/Kunstmaan/FormBundle/Tests/unit/AdminList/FormPageAdminListConfiguratorTest.php
- src/Kunstmaan/FormBundle/Tests/unit/AdminList/FormSubmissionAdminListConfiguratorTest.php
- src/Kunstmaan/FormBundle/Tests/unit/DependencyInjection/Compiler/DeprecateClassParametersPassTest.php
- src/Kunstmaan/FormBundle/Tests/unit/Entity/AbstractFormPageTest.php
- src/Kunstmaan/FormBundle/Tests/unit/Entity/FormSubmissionFieldTypes/ChoiceFormSubmissionFieldTest.php
- src/Kunstmaan/FormBundle/Tests/unit/Entity/FormSubmissionFieldTypes/EmailFormSubmissionFieldTest.php
- src/Kunstmaan/FormBundle/Tests/unit/Entity/FormSubmissionFieldTypes/FileFormSubmissionFieldTest.php
- src/Kunstmaan/FormBundle/Tests/unit/Entity/FormSubmissionFieldTypes/StringFormSubmissionFieldTest.php
- src/Kunstmaan/FormBundle/Tests/unit/Entity/FormSubmissionFieldTypes/TextFormSubmissionFieldTest.php
- src/Kunstmaan/FormBundle/Tests/unit/Entity/FormSubmissionTest.php
- src/Kunstmaan/FormBundle/Tests/unit/Entity/PageParts/AbstractFormPagePartTest.php
- src/Kunstmaan/FormBundle/Tests/unit/Entity/PageParts/CheckboxPagePartTest.php
- src/Kunstmaan/FormBundle/Tests/unit/Entity/PageParts/ChoicePagePartTest.php
- src/Kunstmaan/FormBundle/Tests/unit/Entity/PageParts/EmailPagePartTest.php
- src/Kunstmaan/FormBundle/Tests/unit/Entity/PageParts/FileUploadPagePartTest.php
- src/Kunstmaan/FormBundle/Tests/unit/Entity/PageParts/MultiLineTextPagePartTest.php
- src/Kunstmaan/FormBundle/Tests/unit/Entity/PageParts/SingleLineTextPagePartTest.php
- src/Kunstmaan/FormBundle/Tests/unit/Entity/PageParts/SubmitButtonPagePartTest.php
> [FormBundle] Code improvement found by static code analysis

- src/Kunstmaan/LeadGenerationBundle/Entity/Popup/AbstractPopup.php
- src/Kunstmaan/LeadGenerationBundle/Entity/Rule/AbstractRule.php
- src/Kunstmaan/LeadGenerationBundle/Service/MenuAdaptor.php
- src/Kunstmaan/LeadGenerationBundle/Service/PopupManager.php
- src/Kunstmaan/LeadGenerationBundle/Tests/unit/DependencyInjection/Compiler/DeprecateClassParametersPassTest.php
- src/Kunstmaan/LeadGenerationBundle/Tests/unit/Entity/Rule/AfterXScrollPercentRuleTest.php
- src/Kunstmaan/LeadGenerationBundle/Tests/unit/Entity/Rule/AfterXSecondsRuleTest.php
- src/Kunstmaan/LeadGenerationBundle/Tests/unit/Entity/Rule/LocaleBlacklistRuleTest.php
- src/Kunstmaan/LeadGenerationBundle/Tests/unit/Entity/Rule/LocaleWhitelistRuleTest.php
- src/Kunstmaan/LeadGenerationBundle/Tests/unit/Entity/Rule/MaxXTimesRuleTest.php
- src/Kunstmaan/LeadGenerationBundle/Tests/unit/Entity/Rule/OnExitIntentRuleTest.php
- src/Kunstmaan/LeadGenerationBundle/Tests/unit/Entity/Rule/RecurringEveryXTimeRuleTest.php
- src/Kunstmaan/LeadGenerationBundle/Tests/unit/Entity/Rule/UrlBlacklistRuleTest.php
- src/Kunstmaan/LeadGenerationBundle/Tests/unit/Entity/Rule/UrlWhitelistRuleTest.php
- src/Kunstmaan/LeadGenerationBundle/Twig/PopupTwigExtension.php
> [LeadGenerationBundle] Code improvement found by static code analysis

- src/Kunstmaan/NodeSearchBundle/Configuration/NodePagesConfiguration.php
- src/Kunstmaan/NodeSearchBundle/DependencyInjection/KunstmaanNodeSearchExtension.php
- src/Kunstmaan/NodeSearchBundle/EventListener/NodeIndexUpdateEventListener.php
- src/Kunstmaan/NodeSearchBundle/PagerFanta/Adapter/SearcherRequestAdapter.php
- src/Kunstmaan/NodeSearchBundle/Search/AbstractElasticaSearcher.php
- src/Kunstmaan/NodeSearchBundle/Search/NodeSearcher.php
- src/Kunstmaan/NodeSearchBundle/Services/SearchService.php
- src/Kunstmaan/NodeSearchBundle/Tests/unit/DependencyInjection/Compiler/DeprecateClassParametersPassTest.php
- src/Kunstmaan/NodeSearchBundle/Tests/unit/Entity/AbstractSearchPageTest.php
- src/Kunstmaan/NodeSearchBundle/Tests/unit/Event/IndexNodeEventTest.php
- src/Kunstmaan/NodeSearchBundle/Tests/unit/EventListener/NodeIndexUpdateEventListenerTest.php
- src/Kunstmaan/NodeSearchBundle/Twig/KunstmaanNodeSearchTwigExtension.php
> [NodeSearchBundle] Code improvement found by static code analysis

- src/Kunstmaan/PagePartBundle/Controller/PagePartAdminController.php
- src/Kunstmaan/PagePartBundle/DependencyInjection/Configuration.php
- src/Kunstmaan/PagePartBundle/Entity/PageTemplateConfiguration.php
- src/Kunstmaan/PagePartBundle/EventListener/NodeListener.php
- src/Kunstmaan/PagePartBundle/Helper/FormWidgets/PagePartWidget.php
- src/Kunstmaan/PagePartBundle/Helper/FormWidgets/PageTemplateWidget.php
- src/Kunstmaan/PagePartBundle/Helper/Services/PagePartCreatorService.php
- src/Kunstmaan/PagePartBundle/PagePartAdmin/PagePartAdmin.php
- src/Kunstmaan/PagePartBundle/PagePartConfigurationReader/PagePartConfigurationParser.php
- src/Kunstmaan/PagePartBundle/PagePartConfigurationReader/PagePartConfigurationReader.php
- src/Kunstmaan/PagePartBundle/PageTemplate/PageTemplateConfigurationParser.php
- src/Kunstmaan/PagePartBundle/PageTemplate/PageTemplateConfigurationReader.php
- src/Kunstmaan/PagePartBundle/Repository/PagePartRefRepository.php
- src/Kunstmaan/PagePartBundle/Tests/unit/DependencyInjection/Compiler/DeprecateClassParametersPassTest.php
- src/Kunstmaan/PagePartBundle/Tests/unit/Entity/PagePartRefTest.php
- src/Kunstmaan/PagePartBundle/Tests/unit/Entity/PageTemplateConfigurationTest.php
- src/Kunstmaan/PagePartBundle/Tests/unit/EventListener/CloneListenerTest.php
- src/Kunstmaan/PagePartBundle/Twig/Extension/PagePartTwigExtension.php
> [PagePartBundle] Code improvement found by static code analysis

- src/Kunstmaan/MediaBundle/Command/RenameSoftDeletedCommand.php
- src/Kunstmaan/MediaBundle/Controller/FolderController.php
- src/Kunstmaan/MediaBundle/Controller/MediaController.php
- src/Kunstmaan/MediaBundle/EventListener/DoctrineMediaListener.php
- src/Kunstmaan/MediaBundle/Form/RemoteVideo/RemoteVideoType.php
- src/Kunstmaan/MediaBundle/Form/Type/IdToMediaTransformer.php
- src/Kunstmaan/MediaBundle/Helper/File/FileHandler.php
- src/Kunstmaan/MediaBundle/Helper/File/FileHelper.php
- src/Kunstmaan/MediaBundle/Helper/IconFont/DefaultIconFontLoader.php
- src/Kunstmaan/MediaBundle/Helper/IconFont/IconFontManager.php
- src/Kunstmaan/MediaBundle/Helper/Image/ImageHandler.php
- src/Kunstmaan/MediaBundle/Helper/Menu/MediaMenuAdaptor.php
- src/Kunstmaan/MediaBundle/Helper/RemoteAudio/RemoteAudioHandler.php
- src/Kunstmaan/MediaBundle/Helper/RemoteSlide/RemoteSlideHandler.php
- src/Kunstmaan/MediaBundle/Helper/RemoteVideo/RemoteVideoHandler.php
- src/Kunstmaan/MediaBundle/Repository/FolderRepository.php
- src/Kunstmaan/MediaBundle/Tests/unit/DependencyInjection/Compiler/DeprecateClassParametersPassTest.php
- src/Kunstmaan/MediaBundle/Tests/unit/Helper/File/PdfHandlerTest.php
- src/Kunstmaan/MediaBundle/Tests/unit/Helper/FolderManagerTest.php
- src/Kunstmaan/MediaBundle/Tests/unit/Helper/MediaManagerTest.php
- src/Kunstmaan/MediaBundle/Tests/unit/Helper/Transformer/PdfTransformerTest.php
- src/Kunstmaan/MediaBundle/Validator/Constraints/HasGuessableExtensionValidator.php
> [MediaBundle] Code improvement found by static code analysis

- composer.json
- src/Kunstmaan/FixturesBundle/Builder/PageBuilder.php
- src/Kunstmaan/FixturesBundle/Resources/config/services.yml
> [FixtureBundle] Inject the User Entity class name so the correct Repository can be used

- src/Kunstmaan/NodeBundle/Resources/doc/Locking.md
> [NodeBundle] Fix incorrect step in documentation

- src/Kunstmaan/NodeBundle/Resources/translations/messages.pl.yml
> [NodeBundle] Fix translation typos

- .travis.yml
The imagick config on travis changed recently causing the builds to fail on a permission error.
> [AllBundles] Allow Imagegick pdf read/write to fix travis tests

- src/Kunstmaan/NodeSearchBundle/DependencyInjection/Configuration.php
> [NodeSearchBundle] Fix missing geopoint option for elastic mapping

- src/Kunstmaan/FormBundle/DependencyInjection/KunstmaanFormExtension.php
- src/Kunstmaan/FormBundle/Tests/unit/DependencyInjection/KunstmaanFormExtensionTest.php
> [FormBundle] Fix sf4 compatibility in the form submission directory

- src/Kunstmaan/AdminBundle/Helper/Security/Acl/AclHelper.php
- src/Kunstmaan/AdminBundle/Helper/Security/Acl/AclNativeHelper.php
- src/Kunstmaan/AdminBundle/Tests/unit/Helper/Security/Acl/AclHelperTest.php
- src/Kunstmaan/AdminBundle/Tests/unit/Helper/Security/Acl/AclNativeHelperTest.php
> [AdminBundle] rewrite method in aclhelpers to fix deprecation message

- src/Kunstmaan/MediaBundle/Helper/Imagine/CacheManager.php
> [MediaBundle] Fixed compatibility with new LiipImagine generateUrl() function

- src/Kunstmaan/TranslatorBundle/Service/Command/Importer/ImportCommandHandler.php
> [TranslatorBundle] Fix import translations on symfony 3.4 installations

- src/Kunstmaan/MediaBundle/Resources/views/Folder/delete-modal.html.twig
- src/Kunstmaan/MediaBundle/Resources/views/Folder/empty-modal.html.twig
- src/Kunstmaan/MediaBundle/Resources/views/Media/bulkUpload.html.twig
- src/Kunstmaan/MediaBundle/Resources/views/Media/create.html.twig
Translations are only text here, so no need for the raw filter
> [MediaBundle] Remove unnecessary raw filter on translations

- src/Kunstmaan/UserManagementBundle/Controller/GroupsController.php
- src/Kunstmaan/UserManagementBundle/Controller/RolesController.php
- src/Kunstmaan/UserManagementBundle/Controller/UsersController.php
> [UserManagementBundle] The delete route should only allow post requests

- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/defaultsite/Form/Pages/HomePageAdminType.php
> [GeneratorBundle] Remove incorrect docblock text

- UPGRADE-5.4.md
- src/Kunstmaan/ConfigBundle/Controller/ConfigController.php
- src/Kunstmaan/ConfigBundle/Resources/config/services.yml
- src/Kunstmaan/FormBundle/Helper/FormMailer.php
- src/Kunstmaan/FormBundle/Resources/config/services.yml
- src/Kunstmaan/FormBundle/Tests/unit/Helper/FormMailerTest.php
| Fixed tickets | related to #2555
> [AllBundles] Deprecate remaining usages of symfony/templating

- src/Kunstmaan/AdminBundle/Helper/Security/Acl/Permission/PermissionAdmin.php
- src/Kunstmaan/AdminListBundle/AdminList/Configurator/AbstractDoctrineDBALAdminListConfigurator.php
- src/Kunstmaan/NodeBundle/Controller/SlugController.php
- src/Kunstmaan/NodeBundle/Helper/PagesConfiguration.php
Some codecleanup of old @noinspection docblock which are unused in the current setup
> [AllBundles] Cleanup old @noinspection docblocks

- src/Kunstmaan/AdminBundle/Helper/Security/Acl/AclHelper.php
- src/Kunstmaan/AdminBundle/Helper/Security/Acl/AclNativeHelper.php
- src/Kunstmaan/AdminBundle/Tests/unit/Helper/Security/Acl/AclHelperTest.php
- src/Kunstmaan/AdminBundle/Tests/unit/Helper/Security/Acl/AclNativeHelperTest.php
> [AdminBundle] Forward compatible fix for the deprecated roles methods

- src/Kunstmaan/UtilitiesBundle/Helper/Cipher/UrlSafeCipher.php
- src/Kunstmaan/UtilitiesBundle/Helper/ClassLookup.php
- src/Kunstmaan/UtilitiesBundle/Helper/Shell/Shell.php
- src/Kunstmaan/UtilitiesBundle/Tests/unit/DependencyInjection/Compiler/DeprecateClassParametersPassTest.php
- src/Kunstmaan/UtilitiesBundle/Twig/UtilitiesTwigExtension.php
> [UtilitiesBundle] Code improvement found by static code analysis

- src/Kunstmaan/TranslatorBundle/AdminList/TranslationAdminListConfigurator.php
- src/Kunstmaan/TranslatorBundle/Command/TranslationCacheCommand.php
- src/Kunstmaan/TranslatorBundle/Controller/TranslatorController.php
- src/Kunstmaan/TranslatorBundle/DependencyInjection/Compiler/KunstmaanTranslatorCompilerPass.php
- src/Kunstmaan/TranslatorBundle/DependencyInjection/KunstmaanTranslatorExtension.php
- src/Kunstmaan/TranslatorBundle/Entity/Translation.php
- src/Kunstmaan/TranslatorBundle/Model/Translation.php
- src/Kunstmaan/TranslatorBundle/Model/Translation/TranslationGroup.php
- src/Kunstmaan/TranslatorBundle/Repository/TranslationRepository.php
- src/Kunstmaan/TranslatorBundle/Service/Command/AbstractCommandHandler.php
- src/Kunstmaan/TranslatorBundle/Service/Command/Exporter/CSVFileExporter.php
- src/Kunstmaan/TranslatorBundle/Service/Command/Exporter/YamlFileExporter.php
- src/Kunstmaan/TranslatorBundle/Service/Command/Importer/ImportCommandHandler.php
- src/Kunstmaan/TranslatorBundle/Service/Command/Importer/Importer.php
- src/Kunstmaan/TranslatorBundle/Service/Menu/TranslatorMenuAdaptor.php
- src/Kunstmaan/TranslatorBundle/Service/Migrations/MigrationsService.php
- src/Kunstmaan/TranslatorBundle/Service/Translator/CacheValidator.php
- src/Kunstmaan/TranslatorBundle/Service/Translator/Translator.php
- src/Kunstmaan/TranslatorBundle/Tests/unit/DependencyInjection/Compiler/DeprecateClassParametersPassTest.php
- src/Kunstmaan/TranslatorBundle/Tests/unit/Repository/TranslationRepositoryTest.php
- src/Kunstmaan/TranslatorBundle/Tests/unit/Service/Migrations/MigrationsServiceTest.php
> [TranslatorBundle] Code improvement found by static code analysis

- .travis.yml
Prepare for the upcoming php 7.4 release by testing our code against it.
> [AllBundles] Enable testing against php 7.4

- src/Kunstmaan/AdminListBundle/Resources/views/AdminListTwigExtension/limit.html.twig
> [AdminListBundle] Added missing limit dropdown caret

- src/Kunstmaan/AdminBundle/DependencyInjection/KunstmaanAdminExtension.php
> [AdminBundle] Switch fos_user mailer to twig mailer

- src/Kunstmaan/SeoBundle/Tests/unit/DependencyInjection/KunstmaanSeoExtensionTest.php
- src/Kunstmaan/TranslatorBundle/Tests/unit/DependencyInjection/Compiler/KunstmaanTranslatorCompilerPassTest.php
> [AllBundles] Fix symfony 4.4 test failures

- .travis.yml
- src/Kunstmaan/AdminBundle/Tests/unit/EventListener/MappingListenerTest.php
- src/Kunstmaan/AdminListBundle/Tests/unit/AdminList/FilterBuilderTest.php
- src/Kunstmaan/MultiDomainBundle/Router/DomainBasedLocaleRouter.php
- src/Kunstmaan/TaggingBundle/Tests/unit/Entity/TagManagerTest.php
> [AllBundles] PHP 7.4 compatibility fixes

- .travis.yml
- composer.json
- src/Kunstmaan/AdminBundle/Tests/unit/DependencyInjection/ConfigurationTest.php
- src/Kunstmaan/AdminBundle/composer.json
- src/Kunstmaan/SearchBundle/composer.json
- src/Kunstmaan/VotingBundle/composer.json
> [AllBundles] Use symfony/flex in travis build suite and improve test version ranges

- src/Kunstmaan/MediaBundle/AdminList/ItemAction/MediaSelectItemAction.php
> [MediaBundle] Fix typo in template path

- composer.json
- src/Kunstmaan/AdminBundle/Resources/views/Form/fields.html.twig
- src/Kunstmaan/AdminBundle/Resources/views/PermissionsAdminTwigExtension/widget.html.twig
- src/Kunstmaan/AdminBundle/composer.json
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/Resources/views/Error/layout.html.twig
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/Resources/views/Form/fields.html.twig
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/Resources/views/Layout/layout.html.twig
- src/Kunstmaan/MediaBundle/Resources/views/Form/formWidgets.html.twig
- src/Kunstmaan/NodeBundle/Resources/views/Form/formWidgets.html.twig
- src/Kunstmaan/PagePartBundle/Resources/views/PagePartAdminTwigExtension/widget.html.twig
- src/Kunstmaan/TaggingBundle/Resources/views/Form/fields.html.twig
Replaced deprecated `{% spaceless %}` tag with the recommended `{% apply spaceless %}` replacement.
> [AllBundles] Replaced deprecated spaceless tag

- UPGRADE-5.4.md
- src/Kunstmaan/FormBundle/Helper/FormMailer.php
- src/Kunstmaan/FormBundle/Tests/unit/Helper/FormMailerTest.php
> [FormBundle] Deprecate and replace container injection in form mailer

- src/Kunstmaan/AdminBundle/EventListener/AdminLocaleListener.php
- src/Kunstmaan/AdminBundle/EventListener/ExceptionSubscriber.php
- src/Kunstmaan/AdminBundle/EventListener/PasswordCheckListener.php
- src/Kunstmaan/AdminBundle/EventListener/SessionSecurityListener.php
- src/Kunstmaan/AdminBundle/EventListener/ToolbarListener.php
- src/Kunstmaan/MultiDomainBundle/EventListener/HostOverrideListener.php
- src/Kunstmaan/NodeBundle/EventListener/RenderContextListener.php
- src/Kunstmaan/NodeBundle/EventListener/SlugListener.php
> [AllBundles] BC layer for deprecated event classes

- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/adminlist/AdminList/AdminListConfigurator.php
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/adminlist/Controller/EntityAdminListController.php
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/adminlist/Form/EntityAdminType.php
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/AdminList/AuthorAdminListConfigurator.php
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/AdminList/CategoryAdminListConfigurator.php
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/AdminList/PageAdminListConfigurator.php
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/AdminList/TagAdminListConfigurator.php
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/Controller/AuthorAdminListController.php
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/Controller/CategoryAdminListController.php
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/Controller/PageAdminListController.php
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/Controller/TagAdminListController.php
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/Entity/Author.php
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/Entity/Category.php
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/Entity/Pages/Category.php
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/Entity/Pages/OverviewPage.php
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/Entity/Pages/Page.php
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/Entity/Tag.php
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/Form/AuthorAdminType.php
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/Form/CategoryAdminType.php
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/Form/Pages/OverviewPageAdminType.php
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/Form/Pages/PageAdminType.php
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/Form/TagAdminType.php
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/Helper/Menu/MenuAdaptor.php
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/Repository/OverviewPageRepository.php
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/Repository/PageRepositoryPartial.php.twig
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/common/Form/EntityAdminType.php
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/entity/Entity.php
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/page/Entity/Pages/ExtraFunctions.php
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/searchpage/Entity/Pages/SearchPage.php
Improved the output of generated classes.
- Removed useless comments
- Added typehints/returntypes and removed those docblocks
> [GeneratorBundle] Improve code style and code quality of generated classes

- src/Kunstmaan/AdminBundle/Event/AdaptSimpleFormEvent.php
- src/Kunstmaan/AdminBundle/Event/BcEvent.php
- src/Kunstmaan/AdminBundle/Event/DeepCloneAndSaveEvent.php
- src/Kunstmaan/AdminListBundle/Event/AdminListEvent.php
- src/Kunstmaan/AdminListBundle/composer.json
- src/Kunstmaan/FormBundle/Event/SubmissionEvent.php
- src/Kunstmaan/FormBundle/composer.json
- src/Kunstmaan/NodeBundle/Event/AdaptFormEvent.php
- src/Kunstmaan/NodeBundle/Event/ConfigureActionMenuEvent.php
- src/Kunstmaan/NodeBundle/Event/NodeEvent.php
- src/Kunstmaan/NodeBundle/Event/SlugEvent.php
- src/Kunstmaan/NodeBundle/Event/SlugSecurityEvent.php
- src/Kunstmaan/NodeBundle/composer.json
- src/Kunstmaan/NodeSearchBundle/Event/IndexNodeEvent.php
- src/Kunstmaan/NodeSearchBundle/composer.json
- src/Kunstmaan/PagePartBundle/Event/PagePartEvent.php
- src/Kunstmaan/PagePartBundle/composer.json
- src/Kunstmaan/VotingBundle/Event/AbstractVoteEvent.php
> [AllBundles] Fix symfony event class deprecation

- UPGRADE-5.4.md
- src/Kunstmaan/AdminBundle/Twig/AdminBundleTwigExtension.php
- src/Kunstmaan/AdminBundle/Twig/AdminPermissionsTwigExtension.php
- src/Kunstmaan/AdminBundle/Twig/AdminRouteHelperTwigExtension.php
- src/Kunstmaan/AdminBundle/Twig/DateByLocaleExtension.php
- src/Kunstmaan/AdminBundle/Twig/FormToolsExtension.php
- src/Kunstmaan/AdminBundle/Twig/GoogleSignInTwigExtension.php
- src/Kunstmaan/AdminBundle/Twig/LocaleSwitcherTwigExtension.php
- src/Kunstmaan/AdminBundle/Twig/MenuTwigExtension.php
- src/Kunstmaan/AdminBundle/Twig/MultiDomainAdminTwigExtension.php
- src/Kunstmaan/AdminBundle/Twig/SidebarTwigExtension.php
- src/Kunstmaan/AdminBundle/Twig/TabsTwigExtension.php
- src/Kunstmaan/AdminBundle/Twig/ToolbarTwigExtension.php
- src/Kunstmaan/AdminListBundle/Twig/AdminListTwigExtension.php
- src/Kunstmaan/ArticleBundle/Twig/ArticleTwigExtension.php
- src/Kunstmaan/ConfigBundle/Twig/ConfigTwigExtension.php
- src/Kunstmaan/LeadGenerationBundle/Twig/PopupTwigExtension.php
- src/Kunstmaan/MenuBundle/Twig/MenuTwigExtension.php
- src/Kunstmaan/MultiDomainBundle/Twig/MultiDomainTwigExtension.php
- src/Kunstmaan/NodeBundle/Twig/NodeTwigExtension.php
- src/Kunstmaan/NodeBundle/Twig/PagesConfigurationTwigExtension.php
- src/Kunstmaan/NodeBundle/Twig/UrlReplaceTwigExtension.php
- src/Kunstmaan/NodeSearchBundle/Twig/KunstmaanNodeSearchTwigExtension.php
- src/Kunstmaan/PagePartBundle/Twig/Extension/PagePartAdminTwigExtension.php
- src/Kunstmaan/PagePartBundle/Twig/Extension/PagePartTwigExtension.php
- src/Kunstmaan/PagePartBundle/Twig/Extension/PageTemplateTwigExtension.php
- src/Kunstmaan/SeoBundle/Twig/GoogleAnalyticsTwigExtension.php
- src/Kunstmaan/SeoBundle/Twig/SeoTwigExtension.php
- src/Kunstmaan/SitemapBundle/Twig/SitemapTwigExtension.php
- src/Kunstmaan/UtilitiesBundle/Twig/UtilitiesTwigExtension.php
This PR prepares our code for twig 3. As there are some changes in the twig codebase that would make it impossible to support v3 without bc breaks in our code. By marking the twig classes as final we will be able to do the necessary changes in the future.
> [AllBundles] Mark classes extending twig final

- src/Kunstmaan/MediaBundle/Resources/config/services.yml
- src/Kunstmaan/NodeBundle/Resources/config/services.yml
- src/Kunstmaan/NodeSearchBundle/Resources/config/services.yml
Some classes you might need to inject from time to time, so let's make it easier to autowire these classes by providing an alias
> [AllBundles] Provide autowire aliases for frequently injected classes

- src/Kunstmaan/FormBundle/AdminList/FormSubmissionExportListConfigurator.php
[FormBundle] fix export formsubmissions if pagepart order got changed on the form page
> [FormBundle] fix export formsubmissions if pagepart order got changed on the form page

- src/Kunstmaan/FormBundle/AdminList/FormSubmissionExportListConfigurator.php
> [FormBundle] previous bugfix to avoid empty rows caused another bug

- src/Kunstmaan/AdminListBundle/Service/ExportService.php
> [AdminListBundle] Fixed missing translator property set in constructor

- src/Kunstmaan/NodeBundle/Form/Type/SlugType.php
| Fixed tickets | fixes #2620  
Fixed issue caused by #2529
> [NodeBundle] Always defined the prefix variable

- src/Kunstmaan/AdminBundle/Helper/DomainConfigurationInterface.php
- src/Kunstmaan/NodeBundle/Controller/WidgetsController.php
- src/Kunstmaan/NodeBundle/Helper/URLHelper.php
| Fixed tickets | fixes #2628 
I've also added the correct return typehints on the `DomainConfigurationInterface`
> [NodeBundle] Fix php 7.4 incompatibilities in the url chooser

- docs/bundles/admin-bundle/extending-admin-user.md
| Fixed tickets | copy some documentation from blog
> [documentation] move blogpost to docs

- src/Kunstmaan/AdminBundle/DependencyInjection/KunstmaanAdminExtension.php
- src/Kunstmaan/AdminBundle/Helper/VersionCheck/VersionChecker.php
- src/Kunstmaan/AdminBundle/Resources/config/services.yml
- src/Kunstmaan/AdminBundle/Tests/unit/DependencyInjection/KunstmaanAdminExtensionTest.php
- src/Kunstmaan/AdminBundle/Tests/unit/Helper/VersionCheck/VersionCheckTest.php
> [AdminBundle] Translate website title for versionchecker

- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/Entity/Pages/Page.php
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/page/Entity/Pages/ExtraFunctions.php
Fixed incorrect returntypes introduced in #2549
> [GeneratorBundle] Fix incorrect return types in generated classes

- README.md
> [AllBundles] Update slack invite url and replace old bundles site references

- src/Kunstmaan/AdminBundle/Helper/VersionCheck/VersionChecker.php
- src/Kunstmaan/AdminBundle/Tests/unit/Helper/VersionCheck/VersionCheckTest.php
> [AdminBundle] Fix symfony 3.4 translator incompatibility

- src/Kunstmaan/MultiDomainBundle/Router/DomainBasedLocaleRouter.php
- src/Kunstmaan/NodeBundle/Router/SlugRouter.php
> [AllBundles] Replace deprecated controller routing notation with fqcn

- src/Kunstmaan/UtilitiesBundle/Helper/Cipher/UrlSafeCipher.php
- src/Kunstmaan/UtilitiesBundle/Tests/unit/Helper/Cipher/UrlSafeCipherTest.php
> [UtilitiesBundle] Deprecated hex2bin polyfill method

- .styleci.yml
> [AllBundles] Tweak styleci config

- src/Kunstmaan/AdminBundle/Twig/AdminRouteHelperTwigExtension.php
- src/Kunstmaan/DashboardBundle/Command/GoogleAnalyticsDataCollectCommand.php
- src/Kunstmaan/DashboardBundle/Command/GoogleAnalyticsOverviewsGenerateCommand.php
- src/Kunstmaan/DashboardBundle/Command/GoogleAnalyticsOverviewsListCommand.php
- src/Kunstmaan/DashboardBundle/Command/GoogleAnalyticsSegmentsListCommand.php
- src/Kunstmaan/DashboardBundle/Command/Helper/Analytics/AbstractAnalyticsCommandHelper.php
- src/Kunstmaan/DashboardBundle/Helper/Google/Analytics/ConfigHelper.php
- src/Kunstmaan/DashboardBundle/Helper/Google/Analytics/ServiceHelper.php
- src/Kunstmaan/LeadGenerationBundle/Service/Rule/LocaleRuleService.php
- src/Kunstmaan/MediaBundle/Helper/FolderManager.php
- src/Kunstmaan/MediaBundle/Helper/Remote/AbstractRemoteHelper.php
- src/Kunstmaan/NodeBundle/Form/NodeChoiceType.php
- src/Kunstmaan/NodeBundle/Tests/unit/Helper/NodeHelperTest.php
- src/Kunstmaan/NodeSearchBundle/EventListener/NodeListener.php
- src/Kunstmaan/NodeSearchBundle/Helper/FormWidgets/SearchFormWidget.php
- src/Kunstmaan/SearchBundle/Provider/ElasticaProvider.php
- src/Kunstmaan/TaggingBundle/Tests/unit/Entity/TagManagerTest.php
> [AllBundles] Apply remaining styleci fixes after config change

- src/Kunstmaan/AdminBundle/.gitattributes
- src/Kunstmaan/AdminListBundle/.gitattributes
- src/Kunstmaan/ArticleBundle/.gitattributes
- src/Kunstmaan/BehatBundle/.gitattributes
- src/Kunstmaan/CacheBundle/.gitattributes
- src/Kunstmaan/ConfigBundle/.gitattributes
- src/Kunstmaan/DashboardBundle/.gitattributes
- src/Kunstmaan/FixturesBundle/.gitattributes
- src/Kunstmaan/FormBundle/.gitattributes
- src/Kunstmaan/GeneratorBundle/.gitattributes
- src/Kunstmaan/LeadGenerationBundle/.gitattributes
- src/Kunstmaan/MediaBundle/.gitattributes
- src/Kunstmaan/MediaPagePartBundle/.gitattributes
- src/Kunstmaan/MenuBundle/.gitattributes
- src/Kunstmaan/MultiDomainBundle/.gitattributes
- src/Kunstmaan/NodeBundle/.gitattributes
- src/Kunstmaan/NodeSearchBundle/.gitattributes
- src/Kunstmaan/PagePartBundle/.gitattributes
- src/Kunstmaan/RedirectBundle/.gitattributes
- src/Kunstmaan/SearchBundle/.gitattributes
- src/Kunstmaan/SeoBundle/.gitattributes
- src/Kunstmaan/SitemapBundle/.gitattributes
- src/Kunstmaan/TaggingBundle/.gitattributes
- src/Kunstmaan/TranslatorBundle/.gitattributes
- src/Kunstmaan/UserManagementBundle/.gitattributes
- src/Kunstmaan/UtilitiesBundle/.gitattributes
- src/Kunstmaan/VotingBundle/.gitattributes
Tests have no use in dist packages, this will also make them smaller in size.
> [AllBundles] Adding .gitattributes to remove Tests directory from "dist" package

- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/defaultsite/Controller/DefaultController.php
> [GeneratorBundle] Replace deprecated Controller base class in DefaultController

- src/Kunstmaan/SeoBundle/Resources/views/SeoTwigExtension/metadata.html.twig
> [SeoBundle] Use correct nodetranslation property to generate slug url

- src/Kunstmaan/AdminBundle/DependencyInjection/KunstmaanAdminExtension.php
> [AdminBundle] Remove monolog main handler configuration

- .travis.yml
This PR reworks the travis test suite to a stage style approach and it's changes the executed command so only the minimal required commands are executed. Forexample no npm install/npm run build during php builds and no php stuff during the npm build
This reduces the build time of travis builds from +/- 12,5 min to +/- 4,5min, so this will reduce the feedback loop on pullrequests.
> [AllBundles] Rework travis-ci test setup

- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/Resources/views/Layout/_webfonts.html.twig
> [GeneratorBundle] Use https by default to avoid any mixed content errors

- src/Kunstmaan/NodeBundle/Controller/NodeAdminController.php
- src/Kunstmaan/NodeBundle/DependencyInjection/Configuration.php
- src/Kunstmaan/NodeBundle/DependencyInjection/KunstmaanNodeExtension.php
- src/Kunstmaan/NodeBundle/Entity/DuplicateSubPageInterface.php
- src/Kunstmaan/NodeBundle/Entity/IgnoreDuplicateAsChildInterface.php
- src/Kunstmaan/NodeBundle/Entity/Node.php
- src/Kunstmaan/NodeBundle/Event/Events.php
- src/Kunstmaan/NodeBundle/Event/NodeDuplicateEvent.php
- src/Kunstmaan/NodeBundle/Helper/Menu/ActionsMenuBuilder.php
- src/Kunstmaan/NodeBundle/Helper/PageCloningHelper.php
- src/Kunstmaan/NodeBundle/Repository/NodeRepository.php
- src/Kunstmaan/NodeBundle/Resources/config/services.yml
- src/Kunstmaan/NodeBundle/Resources/translations/messages.en.yml
- src/Kunstmaan/NodeBundle/Resources/views/NodeAdmin/Modals/_duplicate_with_children.html.twig
- src/Kunstmaan/NodeBundle/Resources/views/NodeAdmin/_modals.html.twig
- src/Kunstmaan/NodeBundle/Tests/unit/DependencyInjection/ConfigurationTest.php
allow duplicates to be made with children
> [NodeBundle] Allow duplicate with children 

- src/Kunstmaan/NodeBundle/Event/PostNodeDuplicateEvent.php
- src/Kunstmaan/NodeBundle/Event/PreNodeDuplicateEvent.php
- src/Kunstmaan/NodeBundle/Helper/PageCloningHelper.php
Breaks current version of the feature but that has not yet been released.
> [NodeBundle] Refactored duplicate events for better usage

- src/Kunstmaan/MediaBundle/Resources/doc/MediaBundle.md
It seems to have dissappeared in 2018. I didn't look at the code, but thought we at least could update the docs :)
> [MediaBundle] Aviariy does not exist anymore

- src/Kunstmaan/FormBundle/Entity/FormSubmission.php
- src/Kunstmaan/FormBundle/Entity/FormSubmissionField.php
Also remove the form submission fields when removing a form submission
> [FormBundle] Cascade delete form submission fields when removing a form submission

- .travis.yml
- composer.json
- phpstan.neon
- src/Kunstmaan/AdminBundle/Controller/ExceptionController.php
- src/Kunstmaan/AdminBundle/Helper/AdminRouteHelper.php
- src/Kunstmaan/AdminBundle/Helper/FormWidgets/Tabs/TabPane.php
- src/Kunstmaan/AdminBundle/Helper/Security/Acl/AclNativeHelper.php
- src/Kunstmaan/AdminBundle/Helper/VersionCheck/VersionChecker.php
- src/Kunstmaan/AdminListBundle/AdminList/FieldAlias.php
- src/Kunstmaan/DashboardBundle/Controller/GoogleAnalyticsController.php
- src/Kunstmaan/GeneratorBundle/Command/GenerateAdminListCommand.php
- src/Kunstmaan/GeneratorBundle/Command/GeneratePageCommand.php
- src/Kunstmaan/GeneratorBundle/Generator/Symfony4EntityRepositoryGenerator.php
- src/Kunstmaan/MultiDomainBundle/Helper/DomainConfiguration.php
- src/Kunstmaan/NodeBundle/Helper/Menu/PageMenuAdaptor.php
- src/Kunstmaan/NodeBundle/Helper/NodeMenu.php
- src/Kunstmaan/NodeSearchBundle/Configuration/NodePagesConfiguration.php
- src/Kunstmaan/TranslatorBundle/AdminList/TranslationAdminListConfigurator.php
- src/Kunstmaan/TranslatorBundle/Service/Translator/CacheValidator.php
**To be merged after #2659** 
This PR runs phpstan during the travis build with check level 1, from here on we can start moving up the levels to improve the code even more.
> [AllBundles] Integrate phpstan in travis build suite

- src/Kunstmaan/AdminBundle/Resources/config/services.yml
- src/Kunstmaan/AdminListBundle/Service/ExportService.php
Fix tag in services for adminlocalelistener and hardcode export header translations so it doesn't break import on cms without an english admin
> [AdminBundle][AdminListBundle] translation in admin fixes

- .build/validate-composer.sh
- .gitattributes
- .travis.yml
- composer.json
> [AllBundles] Validate composer.json files in travis build

- .travis.yml
Newest version of phpstan fails, allow it to fail for now so we can fix the actual issue or report it to phpstan
> [AllBundles] Allow phpstan to fail for now

- src/Kunstmaan/SearchBundle/composer.json
> [SearchBundle] Updated ruflin/elastic version constraint in search bundle package

- src/Kunstmaan/DashboardBundle/Repository/AnalyticsSegmentRepository.php
- src/Kunstmaan/NodeBundle/Helper/Menu/PageMenuAdaptor.php
The nodebundle missing use was caused by #2662. Both issues were found by phpstan.
> [AllBundles] Fix missing use statements

- .travis.yml
- src/Kunstmaan/MediaBundle/Repository/MediaRepository.php
- src/Kunstmaan/SearchBundle/Provider/ElasticaProvider.php
> [AllBundles] Fix remaining phpstan issues

- src/Kunstmaan/NodeBundle/Repository/NodeRepository.php
> [NodeBundle] Fix NodeRepository getNodeByInternalName return typehint

- src/Kunstmaan/AdminBundle/DependencyInjection/KunstmaanAdminExtension.php
> [AdminBundle] Manually register the twig KunstmaanAdminBundle override directory

- src/Kunstmaan/NodeBundle/Controller/NodeAdminController.php
> [NodeBundle] Sort node versions DESC

- src/Kunstmaan/MediaBundle/Controller/ChooserController.php
> [MediaBundle] Fix remote media not shown in icon view

- src/Kunstmaan/UserManagementBundle/DependencyInjection/Compiler/DeprecateClassParametersPass.php
- src/Kunstmaan/UserManagementBundle/Tests/unit/DependencyInjection/Compiler/DeprecateClassParametersPassTest.php
> [UserManagementBundle] Remove incorrect class parameter deprecation

- src/Kunstmaan/MediaBundle/Resources/views/Folder/bulk-move-modal.html.twig
> [MediaBundle] Fix deprecated twig controller render notation

- src/Kunstmaan/AdminBundle/Helper/Security/Acl/Permission/PermissionAdmin.php
- src/Kunstmaan/AdminBundle/Tests/unit/Helper/Security/Acl/Permission/PermissionAdminTest.php
- src/Kunstmaan/GeneratorBundle/Command/GenerateSearchPageCommand.php
- src/Kunstmaan/MediaBundle/DependencyInjection/KunstmaanMediaExtension.php
- src/Kunstmaan/MediaBundle/Helper/File/PdfHandler.php
- src/Kunstmaan/MediaBundle/Resources/config/pdf_preview.yml
> [AdminBundle] Replace deprecated getRootDir call

- src/Kunstmaan/AdminBundle/EventListener/AdminLocaleListener.php
| Fixed tickets | Related to #1873 #2691 #2714
@dannyvw @krewetka Can you verify is this changes fixes your problem?
> [AdminBundle] Change admin locale listener priority to after firewall listener

- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/defaultsite/Controller/DefaultController.php
> [GeneratorBundle] Preserve query parameters during redirect

- src/Kunstmaan/FormBundle/Resources/config/services.yml
| Fixed tickets | https://github.com/Kunstmaan/KunstmaanBundlesCMS/issues/2753
> [FormBundle] Inject correct service in form mailer

- src/Kunstmaan/MediaBundle/Resources/translations/messages.en.yml
- src/Kunstmaan/MediaBundle/Resources/views/Media/show.html.twig
> [MediaBundle] Add width and height to media show

- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/searchpage/Resources/views/Pages/SearchPage/view.html.twig
| Fixed tickets | related to #2725 
This is the same approach as in the default site generator search page template
> [GeneratorBundle] Replace deprecation transchoice filter

- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/DataFixtures/ORM/ArticleGenerator/ArticleFixtures.php
> [GeneratorBundle] Fix article fixture for articles without authors

- src/Kunstmaan/MediaBundle/Resources/translations/messages.de.yml
- src/Kunstmaan/MediaBundle/Resources/translations/messages.en.yml
- src/Kunstmaan/MediaBundle/Resources/translations/messages.es.yml
- src/Kunstmaan/MediaBundle/Resources/translations/messages.fr.yml
- src/Kunstmaan/MediaBundle/Resources/translations/messages.hu.yml
- src/Kunstmaan/MediaBundle/Resources/translations/messages.it.yml
- src/Kunstmaan/MediaBundle/Resources/translations/messages.nl.yml
- src/Kunstmaan/MediaBundle/Resources/translations/messages.pl.yml
> [MediaBundle] Update bulk move translations

- composer.json
- src/Kunstmaan/FixturesBundle/composer.json
- src/Kunstmaan/GeneratorBundle/Resources/config/services.yml
- src/Kunstmaan/MediaBundle/Resources/config/services.yml
- src/Kunstmaan/TranslatorBundle/Resources/config/services.yml
Prepare code to support symfony 5
> [AllBundles] Bump doctrine/fixture-bundle to support symfony 5

- UPGRADE-5.7.md
- src/Kunstmaan/AdminBundle/DependencyInjection/KunstmaanAdminExtension.php
- src/Kunstmaan/NodeSearchBundle/Configuration/NodePagesConfiguration.php
- src/Kunstmaan/NodeSearchBundle/Resources/config/services.yml
- src/Kunstmaan/NodeSearchBundle/Services/SearchViewRenderer.php
- src/Kunstmaan/NodeSearchBundle/Tests/unit/Services/SearchViewRendererTest.php
> [NodeSearchBundle] Introduce SearchViewRenderer service to deprecate/remove remaining templating usages

- src/Kunstmaan/AdminBundle/Resources/ui/js/_app-urlchooser-tree.js
| Fixed tickets | #2734 
This was added in https://github.com/Kunstmaan/KunstmaanBundlesCMS/commit/c5c43667d97c2f5533b9641be9f4c2c9d2d04711#diff-b4e32d0791eb3212840817f5fa019f37 and removed in https://github.com/Kunstmaan/KunstmaanBundlesCMS/commit/8aa8daf58744440332ac004ddfed991493186b3e#diff-b4e32d0791eb3212840817f5fa019f37
> [AdminBundle] Fix icons in url chooser

- src/Kunstmaan/MediaBundle/Resources/views/Form/formWidgets.html.twig
Remove duplicate "," to avoid empty srcset.
> [MediaBundle] Remove empty src set

- src/Kunstmaan/AdminBundle/Helper/Menu/MenuAdaptorInterface.php
This is needed to make static code analyzers happy
> [AdminBundle] Fix wrong PHPDoc

- src/Kunstmaan/NodeBundle/Repository/NodeTranslationRepository.php
> [NodeBundle] Remove duplicate query order by

- composer.json
- src/Kunstmaan/AdminBundle/composer.json
> [AdminBundle] Allow symfony/acl-bundle 2.0

- src/Kunstmaan/GeneratorBundle/Command/InstallCommand.php
Ask as few questions as possible during the install to make to process easier for new users
> [GeneratorBundle] Avoid extra questions during install command

- src/Kunstmaan/MultiDomainBundle/Helper/DomainConfiguration.php
```php
$rootNodeHost1 = $domainConfig->getRootNode('host1');
// The first rootnode is "cached" and won't return the correct result for host2
$rootNodeHost2 = $domainConfig->getRootNode('host2');
```
> [MultidomainBundle] Fix getRootNode method to handle multiple calls with different hosts

- src/Kunstmaan/MediaBundle/Resources/views/Folder/show.html.twig
> [MediaBundle] Position sort by and limit

- composer.json
> [AllBundles] Removed the unused ddeboer/data-import-bundle dependency

- UPGRADE-5.7.md
- composer.json
- src/Kunstmaan/AdminBundle/Command/CreateUserCommand.php
- src/Kunstmaan/AdminBundle/Entity/BaseUser.php
- src/Kunstmaan/GeneratorBundle/DataFixtures/ORM/UserFixtures.php
- src/Kunstmaan/NodeBundle/Tests/unit/Helper/NodeHelperTest.php
- src/Kunstmaan/UserManagementBundle/Controller/UsersController.php
- src/Kunstmaan/UserManagementBundle/Event/AfterUserDeleteEvent.php
- src/Kunstmaan/UserManagementBundle/Event/UserEvents.php
- src/Kunstmaan/UserManagementBundle/EventSubscriber/UserDeleteEventSubscriber.php
- src/Kunstmaan/UserManagementBundle/Resources/config/services.yml
- src/Kunstmaan/UserManagementBundle/composer.json
This PR adds some extra info regarding when/by who the user was created and logs by who the user was deleted to have an extra audit trail.
> [AdminBundle][UserManagementBundle] Improve audit log for creating/deleting users

- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/defaultsite/Form/Pages/ContentPageAdminType.php
> [SensioGeneratorBundle] Fixed typo in form class name

- src/Kunstmaan/DashboardBundle/DependencyInjection/KunstmaanDashboardExtension.php
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/defaultsite/DataFixtures/ORM/DefaultSiteGenerator/DefaultSiteFixtures.php
This will enable the dashboard bundle route as the default route when the dashboard bundle is installed. Also remove fixture data for the old dashboard setup
> [DashboardBundle] Improve dashboarbundle dx

- UPGRADE-5.7.md
- src/Kunstmaan/NodeBundle/Helper/Services/ACLPermissionCreatorService.php
- src/Kunstmaan/NodeBundle/Helper/Services/PageCreatorService.php
- src/Kunstmaan/NodeBundle/Resources/config/services.yml
> [NodeBundle] Replace setter injection in node helper services

- docs/bundles/admin-bundle/customizing-the-top-menu.md
> [AdminBundleList] Enhancement: Better readability

- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/DataFixtures/ORM/ArticleGenerator/ArticleFixtures.php
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/defaultsite/DataFixtures/ORM/DefaultSiteGenerator/DefaultSiteFixtures.php
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/defaultsite/DataFixtures/ORM/DefaultSiteGenerator/SitemapFixtures.php
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/searchpage/DataFixtures/ORM/SearchPageGenerator/SearchFixtures.php
> [GeneratorBundle] Add missing interface to generated fixtures for auto service registration

- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/groundcontrol/bin/tasks/bundle.js
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/groundcontrol/bin/tasks/css.js
> [GeneratorBundle] exit build if a build task throws an error

- docs/cookbook/using-the-leadgenerationbundle.md
> [LeadGenerationBundle] fixed doc, getAdminType should be string

- src/Kunstmaan/AdminBundle/Resources/ui/js/_advanced-select.js
https://select2.org/dropdown#forcing-the-dropdown-to-remain-open-after-selection
> [AdminBundle] Force dropdown to remain open after selection

- src/Kunstmaan/NodeSearchBundle/Twig/KunstmaanNodeSearchTwigExtension.php
Because in a private project we had run into this as a problem in the admin view and had to make our own twig function. It would be easier if this was an option straight out of the box.
> [NodeSearchBundle] Allow include offline option get_parent twig function.

- src/Kunstmaan/AdminBundle/Form/WysiwygType.php
- src/Kunstmaan/AdminBundle/Resources/config/services.yml
- src/Kunstmaan/AdminBundle/Tests/unit/Form/WysiwygTypeTest.php
- src/Kunstmaan/FormBundle/Tests/unit/Form/AbstractFormPageAdminTypeTest.php
This allows to define a custom media token transformer.
> [AdminBundle] Add media token transformer as service

- package-lock.json
- package.json
- src/Kunstmaan/AdminBundle/Resources/ui/scss/default-theme/components/forms/_form-group.scss
- src/Kunstmaan/AdminBundle/Resources/views/Form/fields.html.twig
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/pagepart/Form/PageParts/RawHtmlPagePart/RawHtmlPagePartAdminType.php
| Fixed tickets | fixes #2732 closes #2750
By default:
- Textarea: max-width
- Wysiwyg: no max-width
no-max-width attribute can be set in the form builder to create full-width textarea's (example in RawHtmlPagePartAdminType)
Screenshots:
> [AdminBundle] fix max-width textarea/wysiwyg

- groundcontrol/admin-bundle.tasks.js
> [AdminBundle] fix path of sortablejs - fixes broken build

- .php_cs.dist
- .styleci.yml
> [AllBundles] Enhancement: Sort PHP-CS-Fixer rules alphabetically

- src/Kunstmaan/AdminBundle/EventListener/ConsoleExceptionListener.php
> [AdminBundle] Enhancement: Remove useless PHPDoc

- src/Kunstmaan/AdminBundle/Form/UserType.php
> [AdminBundle] Fix: Indention

- src/Kunstmaan/NodeBundle/EventListener/NodeTranslationListener.php
> [NodeBundle] Fix: Wrong variable in PHPDoc

- .flintci.yml
This will simplify the code style config as flintci uses the php-cs-fixer config
> [AllBundles] Switch from styleci to flintci

- .github/workflows/ci.yml
- src/Kunstmaan/FormBundle/Tests/unit/Entity/FormSubmissionFieldTypes/FileFormSubmissionFieldTest.php
> [AllBundles] Fix test failure for stable deps

- src/Kunstmaan/AdminBundle/Helper/CloneHelper.php
- src/Kunstmaan/AdminBundle/Tests/Helper/VersionCheck/VersionCheckTest.php
- src/Kunstmaan/AdminBundle/Toolbar/BundleVersionDataCollector.php
- src/Kunstmaan/AdminListBundle/Controller/AdminListController.php
- src/Kunstmaan/FixturesBundle/Builder/MediaBuilder.php
- src/Kunstmaan/FormBundle/Helper/FormHandler.php
- src/Kunstmaan/MediaBundle/Helper/File/FileHandler.php
- src/Kunstmaan/MediaBundle/Helper/Image/ImageHandler.php
- src/Kunstmaan/MediaBundle/Validator/Constraints/HasGuessableExtensionValidator.php
- src/Kunstmaan/NodeBundle/Controller/NodeAdminController.php
- src/Kunstmaan/NodeBundle/Controller/SlugController.php
- src/Kunstmaan/NodeBundle/EventListener/SlugListener.php
- src/Kunstmaan/NodeBundle/Helper/Menu/ActionsMenuBuilder.php
- src/Kunstmaan/NodeBundle/Helper/NodeAdmin/NodeAdminPublisher.php
- src/Kunstmaan/NodeBundle/Helper/NodeHelper.php
- src/Kunstmaan/NodeBundle/Helper/PageCloningHelper.php
- src/Kunstmaan/NodeBundle/Helper/Services/ACLPermissionCreatorService.php
- src/Kunstmaan/NodeSearchBundle/Configuration/NodePagesConfiguration.php
- src/Kunstmaan/NodeSearchBundle/Services/SearchViewRenderer.php
- src/Kunstmaan/PagePartBundle/PagePartAdmin/PagePartAdmin.php
- src/Kunstmaan/SitemapBundle/Controller/SitemapController.php
- src/Kunstmaan/TranslatorBundle/Service/Command/DiffCommand.php
- src/Kunstmaan/UserManagementBundle/Controller/UsersController.php
- src/Kunstmaan/UserManagementBundle/Event/AfterUserDeleteEvent.php
- src/Kunstmaan/VotingBundle/Controller/VotingController.php
- src/Kunstmaan/VotingBundle/Event/AbstractVoteEvent.php
> [AllBundles] Fix issues after 5.6 upmerge

- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/defaultsite/Resources/views/Pages/FormPage/pagetemplate.html.twig
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/formpage/Resources/views/Pages/FormPage/pagetemplate.html.twig
The form role is unnecessary for element form
> [GeneratorBundle] Remove unnecessary form role

- src/Kunstmaan/AdminBundle/.gitignore
- src/Kunstmaan/AdminListBundle/.gitignore
- src/Kunstmaan/ArticleBundle/.gitignore
- src/Kunstmaan/BehatBundle/.gitignore
- src/Kunstmaan/CacheBundle/.gitignore
- src/Kunstmaan/ConfigBundle/.gitignore
- src/Kunstmaan/DashboardBundle/.gitignore
- src/Kunstmaan/FixturesBundle/.gitignore
- src/Kunstmaan/FormBundle/.gitignore
- src/Kunstmaan/GeneratorBundle/.gitignore
- src/Kunstmaan/LeadGenerationBundle/.gitignore
- src/Kunstmaan/MediaBundle/.gitignore
- src/Kunstmaan/MediaPagePartBundle/.gitignore
- src/Kunstmaan/MenuBundle/.gitignore
- src/Kunstmaan/MultiDomainBundle/.gitignore
- src/Kunstmaan/NodeBundle/.gitignore
- src/Kunstmaan/NodeSearchBundle/.gitignore
- src/Kunstmaan/PagePartBundle/.gitignore
- src/Kunstmaan/RedirectBundle/.gitignore
- src/Kunstmaan/SearchBundle/.gitignore
- src/Kunstmaan/SeoBundle/.gitignore
- src/Kunstmaan/SitemapBundle/.gitignore
- src/Kunstmaan/TranslatorBundle/.gitignore
- src/Kunstmaan/UserManagementBundle/.gitignore
- src/Kunstmaan/VotingBundle/.gitignore
Those should be ignored using the users global .gitignore file.
| Fixed tickets | --
> [AllBundles] Enhancement: Remove .idea/ and .DS_Store from .gitignore files

- groundcontrol/admin-bundle.tasks.js
- package-lock.json
- package.json
> [AdminBundle] update frontend packages

- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/defaultsite/Form/PageParts/PageBannerPagePartAdminType.php
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/defaultsite/Form/PageParts/ServicePagePartAdminType.php
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/defaultsite/Form/PageParts/UspPagePartAdminType.php
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/defaultsite/Form/UspItemAdminType.php
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/pagepart/Form/PageParts/AudioPagePart/AudioPagePartAdminType.php
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/pagepart/Form/PageParts/DownloadPagePart/DownloadPagePartAdminType.php
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/pagepart/Form/PageParts/ImagePagePart/ImagePagePartAdminType.php
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/pagepart/Form/PageParts/VideoPagePart/VideoPagePartAdminType.php
- src/Kunstmaan/NodeBundle/Command/CronUpdateNodeCommand.php
Fixed issues introduced in #2833
> [GeneratorBundle] Fix php syntax errors in generator skeleton files

- .build/deprecations-baseline.json
- .github/workflows/ci.yml
- composer.json
> [AllBundles] Setup deprecations baseline

- src/Kunstmaan/NodeBundle/Resources/views/NodeAdmin/Modals/_unpublish.html.twig
> [NodeBundle] fixed unpublish later

- composer.json
- src/Kunstmaan/FormBundle/composer.json
- src/Kunstmaan/MediaBundle/composer.json
- src/Kunstmaan/NodeBundle/composer.json
> [AllBundles] Bump minimum stof/doctrine-extensions-bundle version

- src/Kunstmaan/RedirectBundle/Router/RedirectRouter.php
- src/Kunstmaan/RedirectBundle/Tests/Router/RedirectRouterTest.php
> [RedirectBundle] Fix broken wildcard redirects

- docs/introduction/index.md
| Fixed tickets | empty
small grammatical error in a documentation file - non critical
> [Kuma docs] Update docs/introduction/index.md

- composer.json
- src/Kunstmaan/GeneratorBundle/Generator/KunstmaanGenerator.php
- src/Kunstmaan/GeneratorBundle/composer.json
| Fixed tickets | related to #2723
> [GeneratorBundle] Switch to new doctrine inflector api

- UPGRADE-5.9.md
- src/Kunstmaan/UserManagementBundle/DependencyInjection/Configuration.php
- src/Kunstmaan/UserManagementBundle/DependencyInjection/KunstmaanUserManagementExtension.php
- src/Kunstmaan/UserManagementBundle/Resources/config/services.yml
- src/Kunstmaan/UserManagementBundle/Tests/DependencyInjection/ConfigurationTest.php
- src/Kunstmaan/UserManagementBundle/Tests/DependencyInjection/KunstmaanUserManagementExtensionTest.php
> [UserManagementBundle] Move user adminlist configurator class override to config

- UPGRADE-5.9.md
- src/Kunstmaan/RedirectBundle/DependencyInjection/Configuration.php
- src/Kunstmaan/RedirectBundle/DependencyInjection/KunstmaanRedirectExtension.php
- src/Kunstmaan/RedirectBundle/Resources/config/services.yml
- src/Kunstmaan/RedirectBundle/Tests/DependencyInjection/ConfigurationTest.php
- src/Kunstmaan/RedirectBundle/Tests/DependencyInjection/KunstmaanRedirectExtensionTest.php
> [RedirectBundle] Move redirect entity class override to config

- src/Kunstmaan/AdminBundle/Tests/EventListener/AdminLocaleListenerTest.php
- src/Kunstmaan/FormBundle/AdminList/FormSubmissionExportListConfigurator.php
- src/Kunstmaan/MultiDomainBundle/EventListener/HostOverrideListener.php
- src/Kunstmaan/MultiDomainBundle/Tests/DependencyInjection/ConfigurationTest.php
- src/Kunstmaan/MultiDomainBundle/Tests/EventListener/HostOverrideListenerTest.php
- src/Kunstmaan/TranslatorBundle/Tests/app/config/config.yml
> [AllBundles] Forward compatibility fixes for symfony 5

- src/Kunstmaan/SeoBundle/Resources/views/SeoTwigExtension/metadata.html.twig
> [SeoBundle] Don't render empty og:title

- src/Kunstmaan/TranslatorBundle/Entity/Translation.php
> [TranslatorBundle] Increase max length for translation domain

- src/Kunstmaan/MediaBundle/Helper/RemoteVideo/RemoteVideoHandler.php
> [MediaBundle] Use oembed url for vimeo thumbnail

- package.json
> [AllBundles] Update sortablejs back to 1.8.1

- phpstan.neon
- src/Kunstmaan/AdminBundle/Entity/BaseUser.php
- src/Kunstmaan/DashboardBundle/Command/GoogleAnalyticsOverviewsGenerateCommand.php
- src/Kunstmaan/GeneratorBundle/Command/GenerateBundleCommand.php
- src/Kunstmaan/RedirectBundle/Entity/Redirect.php
> [AllBundles] Fix phpstan errors for checks added in 0.12.92

- src/Kunstmaan/AdminBundle/composer.json
- src/Kunstmaan/AdminListBundle/composer.json
- src/Kunstmaan/ArticleBundle/composer.json
- src/Kunstmaan/BehatBundle/composer.json
- src/Kunstmaan/CacheBundle/composer.json
- src/Kunstmaan/ConfigBundle/composer.json
- src/Kunstmaan/DashboardBundle/composer.json
- src/Kunstmaan/FixturesBundle/composer.json
- src/Kunstmaan/FormBundle/composer.json
- src/Kunstmaan/GeneratorBundle/composer.json
- src/Kunstmaan/LeadGenerationBundle/composer.json
- src/Kunstmaan/MediaBundle/composer.json
- src/Kunstmaan/MediaPagePartBundle/composer.json
- src/Kunstmaan/MenuBundle/composer.json
- src/Kunstmaan/MultiDomainBundle/composer.json
- src/Kunstmaan/NodeBundle/composer.json
- src/Kunstmaan/NodeSearchBundle/composer.json
- src/Kunstmaan/PagePartBundle/composer.json
- src/Kunstmaan/RedirectBundle/composer.json
- src/Kunstmaan/SearchBundle/composer.json
- src/Kunstmaan/SeoBundle/composer.json
- src/Kunstmaan/SitemapBundle/composer.json
- src/Kunstmaan/TaggingBundle/composer.json
- src/Kunstmaan/TranslatorBundle/composer.json
- src/Kunstmaan/UserManagementBundle/composer.json
- src/Kunstmaan/UtilitiesBundle/composer.json
- src/Kunstmaan/VotingBundle/composer.json
> [AllBundles] Fix branch alias of separate packages

- phpstan.neon
- src/Kunstmaan/DashboardBundle/Command/GoogleAnalyticsOverviewsGenerateCommand.php
- src/Kunstmaan/GeneratorBundle/Command/GenerateBundleCommand.php
- src/Kunstmaan/RedirectBundle/Entity/Redirect.php
> [AllBundles] Backport phpstan 0.12.92 fixes

- UPGRADE-5.9.md
- composer.json
- src/Kunstmaan/FixturesBundle/composer.json
- src/Kunstmaan/GeneratorBundle/composer.json
- src/Kunstmaan/TranslatorBundle/Tests/Fixtures/TranslationDataFixture.php
- src/Kunstmaan/TranslatorBundle/Tests/WebTestCase.php
- src/Kunstmaan/TranslatorBundle/composer.json
Also replaces the nelmio/alice test requirement by a standard doctrine fixture. Failing lowest deps test is fixed with #2899
> [AllBundle] Replace abanoned faker package

- composer.json
- src/Kunstmaan/AdminBundle/Tests/Helper/Security/Acl/AclWalkerTest.php
- src/Kunstmaan/MediaBundle/DependencyInjection/KunstmaanMediaExtension.php
- src/Kunstmaan/MediaBundle/composer.json
- src/Kunstmaan/NodeBundle/composer.json
PHPStan error's are fixed in #2899
> [AllBundles] Bump gedmo/doctrine-extensions to prepare for php8 support

- src/Kunstmaan/AdminBundle/EventListener/PasswordCheckListener.php
> [AdminBundle] Fix redirect loop for installation without new authentication setup

- src/Kunstmaan/NodeSearchBundle/Services/SearchService.php
> [NodeSearchBundle] Add missing deprecation for change in searcher lookup

- src/Kunstmaan/AdminBundle/Tests/Helper/Creators/ACLPermissionCreatorTest.php
> [AdminBundle] Fix symfony/security-acl 3.2 test errors

- src/Kunstmaan/AdminListBundle/Service/EntityVersionLockService.php
- src/Kunstmaan/AdminListBundle/Service/ExportService.php
- src/Kunstmaan/AdminListBundle/Tests/Service/EntityVersionLockServiceTest.php
- src/Kunstmaan/AdminListBundle/Tests/Service/ExportServiceTest.php
> [AdminListBundle] Remove deprecated code

- src/Kunstmaan/MultiDomainBundle/Helper/DomainConfiguration.php
> [MultiDomainBundle] Remove deprecated code

- src/Kunstmaan/NodeBundle/Helper/Services/ACLPermissionCreatorService.php
> [NodeBundle] Remove deprecated code

- src/Kunstmaan/UserManagementBundle/Controller/UsersController.php
> [UserManagementBundle] Remove deprecated code

- src/Kunstmaan/UtilitiesBundle/Helper/Cipher/UrlSafeCipher.php
- src/Kunstmaan/UtilitiesBundle/Tests/Helper/Cipher/UrlSafeCipherTest.php
> [UtilitiesBundle] Remove deprecated code

- src/Kunstmaan/AdminBundle/Command/ApplyAclCommand.php
- src/Kunstmaan/AdminBundle/Command/CreateGroupCommand.php
- src/Kunstmaan/AdminBundle/Command/CreateRoleCommand.php
- src/Kunstmaan/AdminBundle/Command/CreateUserCommand.php
- src/Kunstmaan/AdminBundle/Command/ExceptionCommand.php
- src/Kunstmaan/AdminBundle/Command/UpdateAclCommand.php
- src/Kunstmaan/DashboardBundle/Command/DashboardCommand.php
- src/Kunstmaan/DashboardBundle/Command/GoogleAnalyticsConfigFlushCommand.php
- src/Kunstmaan/DashboardBundle/Command/GoogleAnalyticsConfigsListCommand.php
- src/Kunstmaan/DashboardBundle/Command/GoogleAnalyticsDataCollectCommand.php
- src/Kunstmaan/DashboardBundle/Command/GoogleAnalyticsDataFlushCommand.php
- src/Kunstmaan/DashboardBundle/Command/GoogleAnalyticsOverviewsGenerateCommand.php
- src/Kunstmaan/DashboardBundle/Command/GoogleAnalyticsOverviewsListCommand.php
- src/Kunstmaan/DashboardBundle/Command/GoogleAnalyticsSegmentsListCommand.php
- src/Kunstmaan/MediaBundle/Command/CleanDeletedMediaCommand.php
- src/Kunstmaan/MediaBundle/Command/CreatePdfPreviewCommand.php
- src/Kunstmaan/MediaBundle/Command/RebuildFolderTreeCommand.php
- src/Kunstmaan/MediaBundle/Command/RenameSoftDeletedCommand.php
- src/Kunstmaan/NodeBundle/Command/CronUpdateNodeCommand.php
- src/Kunstmaan/NodeBundle/Command/InitAclCommand.php
- src/Kunstmaan/SearchBundle/Command/DeleteIndexCommand.php
- src/Kunstmaan/SearchBundle/Command/PopulateIndexCommand.php
- src/Kunstmaan/SearchBundle/Command/SetupIndexCommand.php
- src/Kunstmaan/TranslatorBundle/Command/ExportTranslationsCommand.php
- src/Kunstmaan/TranslatorBundle/Command/ImportTranslationsCommand.php
- src/Kunstmaan/TranslatorBundle/Command/TranslationCacheCommand.php
- src/Kunstmaan/TranslatorBundle/Command/TranslationFlagCommand.php
- src/Kunstmaan/UtilitiesBundle/Command/CipherCommand.php
> [AllBundles] Remove deprecated ContainerAwareCommand usages

- src/Kunstmaan/AdminBundle/Helper/VersionCheck/VersionChecker.php
- src/Kunstmaan/AdminBundle/Tests/Helper/VersionCheck/VersionCheckTest.php
- src/Kunstmaan/AdminBundle/Toolbar/BundleVersionDataCollector.php
> [AdminBundle] Remove deprecated code from version collector classes

- src/Kunstmaan/RedirectBundle/DependencyInjection/KunstmaanRedirectExtension.php
- src/Kunstmaan/RedirectBundle/Tests/DependencyInjection/KunstmaanRedirectExtensionTest.php
> [RedirectBundle] Remove deprecated code

- src/Kunstmaan/TranslatorBundle/Resources/config/services.yml
> [TranslatorBundle] Remove deprecated code

- src/Kunstmaan/FormBundle/Helper/FormMailer.php
- src/Kunstmaan/FormBundle/Tests/Helper/FormMailerTest.php
> [FormBundle] Remove deprecated code

- src/Kunstmaan/DashboardBundle/DependencyInjection/Configuration.php
- src/Kunstmaan/DashboardBundle/DependencyInjection/KunstmaanDashboardExtension.php
- src/Kunstmaan/DashboardBundle/Tests/DependencyInjection/KunstmaanDashboardExtensionTest.php
> [DashboardBundle] Remove deprecated code

- src/Kunstmaan/ConfigBundle/Controller/ConfigController.php
> [ConfigBundle] Remove deprecated code

- src/Kunstmaan/ArticleBundle/Entity/AbstractAuthor.php
- src/Kunstmaan/ArticleBundle/Entity/AbstractCategory.php
- src/Kunstmaan/ArticleBundle/Entity/AbstractTag.php
- src/Kunstmaan/ArticleBundle/Tests/Entity/AbstractAuthorTest.php
- src/Kunstmaan/ArticleBundle/Twig/ArticleTwigExtension.php
> [ArticleBundle] Remove deprecated code

- src/Kunstmaan/FixturesBundle/Resources/config/services.yml
> [FixturesBundle] Remove deprecated code

- src/Kunstmaan/MediaBundle/Resources/config/services.yml
- src/Kunstmaan/NodeBundle/Command/CronUpdateNodeCommand.php
- src/Kunstmaan/SearchBundle/Resources/config/services.yml
> [AllBundle] Fix command service definitions errors after cleanup

- src/Kunstmaan/MediaBundle/Resources/views/AdminList/ItemAction/select.html.twig
Fixes broken view for urlchooser
> [MediaBundle] fix broken view for urlchooser

- composer.json
- src/Kunstmaan/MediaBundle/composer.json
> [MediaBundle] Remove unused imagine/imagine dependency

- src/Kunstmaan/AdminBundle/Tests/Helper/Security/OAuth/OAuthUserFinderTest.php
- src/Kunstmaan/DashboardBundle/Tests/Entity/AnalyticsConfigTest.php
- src/Kunstmaan/DashboardBundle/Tests/Entity/AnalyticsGoalTest.php
- src/Kunstmaan/DashboardBundle/Tests/Entity/AnalyticsOverviewTest.php
- src/Kunstmaan/DashboardBundle/Tests/Entity/AnalyticsSegmentTest.php
- src/Kunstmaan/FormBundle/Tests/Entity/PageParts/EmailPagePartTest.php
- src/Kunstmaan/NodeBundle/Tests/Helper/Validation/UrlValidatorTest.php
- src/Kunstmaan/NodeSearchBundle/Tests/Event/IndexNodeEventTest.php
- src/Kunstmaan/NodeSearchBundle/Tests/Services/SearchViewRendererTest.php
- src/Kunstmaan/PagePartBundle/Tests/PageTemplate/PageTemplateConfigurationParserTest.php
- src/Kunstmaan/SeoBundle/Tests/Twig/TwigExtensionTest.php
- src/Kunstmaan/TranslatorBundle/Tests/Entity/TranslationTest.php
- src/Kunstmaan/TranslatorBundle/Tests/Repository/TranslationRepositoryTest.php
- src/Kunstmaan/UtilitiesBundle/Tests/Helper/SlugifierTest.php
- src/Kunstmaan/VotingBundle/Tests/Event/Facebook/FacebookLikeEventTest.php
- src/Kunstmaan/VotingBundle/Tests/Event/Facebook/FacebookSendEventTest.php
- src/Kunstmaan/VotingBundle/Tests/Event/LinkedIn/LinkedInShareEventTest.php
- src/Kunstmaan/VotingBundle/Tests/Event/UpDown/DownVoteEventTest.php
- src/Kunstmaan/VotingBundle/Tests/Event/UpDown/UpVoteEventTest.php
> [AllBundles] Fix incorrect namespaces in test classes

- src/Kunstmaan/AdminBundle/Entity/BaseUser.php
> [AdminBundle] Fix User incompatibility after new authentication changes

- src/Kunstmaan/NodeBundle/EventListener/SlugListener.php
> [NodeBundle] Improve slug action deprecation and compatibility with old setup

- src/Kunstmaan/AdminListBundle/Controller/AbstractAdminListController.php
> [AdminListBundle] Improve new AbstractAdminList servicesubscriber setup

- composer.json
- src/Kunstmaan/NodeSearchBundle/Configuration/NodePagesConfiguration.php
- src/Kunstmaan/NodeSearchBundle/Entity/AbstractSearchPage.php
- src/Kunstmaan/NodeSearchBundle/EventListener/NodeIndexUpdateEventListener.php
- src/Kunstmaan/NodeSearchBundle/Exception/SearcherServiceNotFoundException.php
- src/Kunstmaan/NodeSearchBundle/Search/AbstractElasticaSearcher.php
- src/Kunstmaan/NodeSearchBundle/Search/SearcherInterface.php
- src/Kunstmaan/NodeSearchBundle/Services/SearchService.php
- src/Kunstmaan/NodeSearchBundle/Services/SearchViewRenderer.php
- src/Kunstmaan/NodeSearchBundle/Tests/Entity/AbstractSearchPageTest.php
- src/Kunstmaan/NodeSearchBundle/Tests/EventListener/NodeIndexUpdateEventListenerTest.php
- src/Kunstmaan/NodeSearchBundle/Tests/Services/SearchServiceTest.php
- src/Kunstmaan/NodeSearchBundle/Tests/Services/SearchViewRendererTest.php
- src/Kunstmaan/NodeSearchBundle/composer.json
- src/Kunstmaan/SearchBundle/composer.json
> [NodeSearchBundle] Remove deprecated code

- src/Kunstmaan/AdminBundle/Resources/config/services.yml
> [AdminBundle] Add autowire alias

- src/Kunstmaan/AdminBundle/Tests/Helper/Security/Acl/AclWalkerTest.php
> [AdminBundle] Fix incorrect class mock in AclWalker test

- src/Kunstmaan/AdminBundle/Resources/config/services.yml
- src/Kunstmaan/NodeBundle/Resources/config/services.yml
> [AllBundles] Extra service aliases

- src/Kunstmaan/NodeBundle/Resources/config/services.yml
> [NodeBundkle] Remove service config for removed class

- src/Kunstmaan/UserManagementBundle/Controller/UsersController.php
> [UserManagementBundle] Add missing final keyword to controller

- UPGRADE-5.9.md
- src/Kunstmaan/AdminBundle/Security/OAuthAuthenticator.php
- src/Kunstmaan/NodeBundle/Controller/NodeAdminController.php
- src/Kunstmaan/NodeBundle/EventListener/FixDateListener.php
- src/Kunstmaan/NodeBundle/Helper/NodeAdmin/NodeAdminPublisher.php
- src/Kunstmaan/NodeBundle/Resources/config/services.yml
- src/Kunstmaan/TranslatorBundle/Command/ImportTranslationsFromFileCommand.php
- src/Kunstmaan/TranslatorBundle/Service/Translator/Translator.php
> [AllBundles] Extra sf5 forward compatibility

- src/Kunstmaan/AdminBundle/Security/OAuthAuthenticator.php
- src/Kunstmaan/AdminBundle/Tests/Helper/VersionCheck/VersionCheckTest.php
- src/Kunstmaan/AdminListBundle/Controller/EntityLockCheckController.php
- src/Kunstmaan/AdminListBundle/Service/ExportService.php
- src/Kunstmaan/AdminListBundle/Tests/Service/ExportServiceTest.php
- src/Kunstmaan/ArticleBundle/Router/TagCategoryRouter.php
- src/Kunstmaan/FormBundle/AdminList/FormSubmissionExportListConfigurator.php
- src/Kunstmaan/FormBundle/Controller/FormSubmissionsController.php
- src/Kunstmaan/MediaBundle/Controller/FolderController.php
- src/Kunstmaan/MediaBundle/Controller/MediaController.php
- src/Kunstmaan/MultiDomainBundle/EventListener/HostOverrideListener.php
- src/Kunstmaan/NodeBundle/Controller/NodeAdminController.php
- src/Kunstmaan/NodeBundle/Helper/NodeAdmin/NodeAdminPublisher.php
- src/Kunstmaan/SeoBundle/Controller/Admin/SettingsController.php
- src/Kunstmaan/TranslatorBundle/Command/ImportTranslationsFromFileCommand.php
- src/Kunstmaan/TranslatorBundle/Controller/TranslatorCommandController.php
- src/Kunstmaan/TranslatorBundle/Controller/TranslatorController.php
- src/Kunstmaan/UserManagementBundle/Controller/GroupsController.php
- src/Kunstmaan/UserManagementBundle/Controller/RolesController.php
- src/Kunstmaan/UserManagementBundle/Controller/UsersController.php
> [AllBundles] Sf3 compatibility layer cleanup

- src/Kunstmaan/NodeBundle/Event/PostNodeDuplicateEvent.php
- src/Kunstmaan/NodeBundle/Event/PreNodeDuplicateEvent.php
- src/Kunstmaan/SitemapBundle/Event/PreSitemapRenderEvent.php
- src/Kunstmaan/SitemapBundle/composer.json
- src/Kunstmaan/UserManagementBundle/Event/AfterUserDeleteEvent.php
> [AllBundles] Sf5 event forward compatibilty

- src/Kunstmaan/TranslatorBundle/DependencyInjection/KunstmaanTranslatorExtension.php
- src/Kunstmaan/TranslatorBundle/Resources/config/services.yml
> [TranslatorBundle] Remaining translator cleanup

- src/Kunstmaan/CookieBundle/Resources/views/Components/TabBarContentPanel.html.twig
- src/Kunstmaan/FormBundle/Controller/FormSubmissionsController.php
> [AllBundles] Remove deprecated code

- src/Kunstmaan/CookieBundle/DependencyInjection/Configuration.php
- src/Kunstmaan/CookieBundle/EventSubscriber/CookieBarEventSubscriber.php
> [CookieBundle] Remove remaining sf3 bc layers
