- src/Kunstmaan/GeneratorBundle/Command/KunstmaanGenerateCommand.php
When working with Bundles with a namespace depth greater than 1, the kuma:generate:page command will fail with: (in this example, the root namespace is "Ten24\SaskTheatre\WebsiteBundle")
```php
[InvalidArgumentException]
Bundle "Ten24SaskTheatre" does not exist or it is not enabled. Maybe you forgot to add it in the registerBundles() metho
d of your AppKernel.php file?
Exception trace:
() at F:\Users\blair\workspace\sasktheatre\app\bootstrap.php.cache:2386
Symfony\Component\HttpKernel\Kernel->getBundle() at F:\Users\blair\workspace\sasktheatre\vendor\kunstmaan\bundles-cms\src\Ku
nstmaan\GeneratorBundle\Command\KunstmaanGenerateCommand.php:253
Kunstmaan\GeneratorBundle\Command\KunstmaanGenerateCommand->askForBundleName() at F:\Users\blair\workspace\sasktheatre\vendo …
```
> Fix for issue when namespace depth > 1 in KunstmaanGenerateCommand

- src/Kunstmaan/AdminBundle/Resources/public/js/script.js
solution for https://github.com/Kunstmaan/KunstmaanBundlesCMS/issues/52
Slightly adapted from the original proposal for esthetic reasons; now **all** buttons in the main controls will be disabled on submit.
> added DisableButtonsOnSubmit function

- src/Kunstmaan/ArticleBundle/Controller/AbstractArticleAuthorAdminListController.php
- src/Kunstmaan/ArticleBundle/Controller/AbstractArticlePageAdminListController.php
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/defaultsite/Controller/SatelliteAdminListController.php
- src/Kunstmaan/RedirectBundle/Controller/RedirectAdminListController.php
I noticed the 'Add Redirect' action was broken in the admin interface (_illegal offset error_), and it turns out the `RedirectAdminListController` makes a wrong call to `AdminListController::doAddAction` [[1]].
This was also the case in some other controllers, which I also fixed.
```php
// RedirectAdminListController.php
public function addAction(Request $request)
{
return parent::doAddAction($this->getAdminListConfigurator(), $request);
}
```
But the method signature has `$type` as the second parameter:
```php
/**
* Creates and processes the form to add a new Entity
*
* @param AbstractAdminListConfigurator $configurator The adminlist configurator
* @param string                        $type         The type to add
*
* @return array
*/
protected function …
```
> Fix redirect add admin action and possible others.

- src/Kunstmaan/AdminBundle/Resources/public/scss/_vars.scss
- src/Kunstmaan/AdminBundle/Resources/views/Default/layout.html.twig
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/Resources/public/scss/config/_paths.scss
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/Resources/views/Layout/_css.html.twig
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/Resources/views/Layout/_js_footer.html.twig
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/Resources/views/Layout/_js_header.html.twig
This allows a Kunstmaan protect to be run (tested out) from a non-root web path e.g. `http://hostname/projects/kunstmaan-project/web/`
There are still some issues with the views in the `MediaBundle` and `MediaPagePartBundle`, these use different ways to render the (image) urls in multiple places:
* [`KunstmaanMediaBundle:Media:Image/show`](https://github.com/kunstmaan/KunstmaanBundlesCMS/blob/bc779e3471541195373e5df89905a591e3a6a991/src/Kunstmaan/MediaBundle/Resources/views/Media/Image/show.html.twig#L39)
* [`KunstmaanMediaPagePartBundle:ImagePagePart:view`](https://github.com/Kunstmaan/KunstmaanBundlesCMS/blob/bc779e3471541195373e5df89905a591e3a6a991/src/Kunstmaan/MediaPagePartBundle/Resources/views/ImagePagePart/view.html.twig#L5)
* [`KunstmaanGeneratorBundle` demosite skeleton …
> Use relative asset paths in stylesheets and asset() twig function

- src/Kunstmaan/MediaBundle/Resources/views/Chooser/chooserShowFolder.html.twig
Last fix didn't take into account the imgpath is sent back to the opener (chooser widget)
> Moved if block location so imageurl is available to the click listener

- src/Kunstmaan/AdminBundle/Entity/Group.php
- src/Kunstmaan/AdminBundle/Form/GroupType.php
Hello,
I have to add a new user group from admin and upon the save I get the following error
Catchable Fatal Error: Argument 1 passed to Kunstmaan\AdminBundle\Entity\Group::isGroupValid() must be an instance of Symfony\Component\Validator\ExecutionContext, instance of Symfony\Component\Validator\Context\LegacyExecutionContext given in .../vendor/kunstmaan/admin-bundle/Kunstmaan/AdminBundle/Entity/Group.php line 236
I tracked down the problem and I replaced the line 8
`use Symfony\Component\Validator\ExecutionContext;`
with
`use Symfony\Component\Validator\Context\LegacyExecutionContext as ExecutionContext;`
and the group was saved. 
By the way, both ExecutionContext and LegacyExecutionConext are deprecated in symfony 2.4.
Keep up the good work!
Iulian
> Can't add new user group from the admin interface

- src/Kunstmaan/MediaBundle/Command/CreatePdfPreviewCommand.php
- src/Kunstmaan/MediaBundle/DependencyInjection/Configuration.php
- src/Kunstmaan/MediaBundle/DependencyInjection/KunstmaanMediaExtension.php
- src/Kunstmaan/MediaBundle/README.md
- src/Kunstmaan/MediaBundle/Resources/config/handlers.yml
- src/Kunstmaan/MediaBundle/Resources/config/pdf_preview.yml
- src/Kunstmaan/MediaBundle/Resources/config/services.yml
`composer create-project kunstmaan/bundles-standard-edition /my/path -s dev` returns an error: `PHP Fatal error:  Class 'Imagick' not found in /.../www/km-poc/app/cache/dev/appDevDebugProjectContainer.php on line 3408`
Either change the base requirements in the installation instruction or handle the case when Imagick is not available (better).
> Imagick must be installed prior to installation, even if you don't plan to use KunstmaanMediaBundle

- src/Kunstmaan/AdminBundle/Resources/public/js/script.js
- src/Kunstmaan/AdminBundle/Resources/public/scss/_main.scss
- src/Kunstmaan/AdminBundle/Resources/views/TabsTwigExtension/widget.html.twig
> fix more dropdown tab in nav if necessary

- src/Kunstmaan/PagePartBundle/Twig/Extension/PageTemplateTwigExtension.php
- Merge passed parameters with the current twig context - allows passing of view variables when calling render_pagetemplate()
- Argument was previously unused
> Bugfix for render_pagetemplate()

- src/Kunstmaan/LiveReloadBundle/composer.json
This makes it easier to use in other projects that use symfony parts
> [LiveReloadBundle] require framework-bundle only, not symfony/symfony

- src/Kunstmaan/AdminListBundle/Resources/views/AdminListTwigExtension/widget.html.twig
When some rows in the adminlist do not need to have a certain item action, you can just do this:
```php
$create_route = function ($item) {
if (!$item->foo()) {
return null;
} else {
return array(
'path'   => 'mybundle_admin_projects',
'params' => array('id' => $item->getSlug())
);
}
};
$ia = new \Kunstmaan\AdminListBundle\AdminList\ItemAction\SimpleItemAction($create_route, "eye-open", "Preview");
$this->addItemAction($ia);
```
> make it possible to have no item actions for some records

- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/defaultsite/DataFixtures/ORM/DefaultSiteGenerator/DefaultSiteFixtures.php
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/defaultsite/DataFixtures/ORM/DefaultSiteGenerator/SitemapFixtures.php
The username of the admin is not capitialized, but just lowercase (as you can see in the user datafixture: https://github.com/Kunstmaan/KunstmaanBundlesCMS/blob/master/src/Kunstmaan/AdminBundle/DataFixtures/ORM/UserFixtures.php#L41 ).
> Fixed generated datafixtures to use correct textcase

- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/Resources/views/Form/fields.html.twig
Currently labels of required fields get the col-md-2 and control-label classes, and other field don't get these classes. As a result, the labels of required fields are on the left side of a field, and other labels appear on the right side of fields. 
This fix gives all labels the col-md-2 and control-label class.
> Fix layout of labels in form by adding default classes

- src/Kunstmaan/UtilitiesBundle/Helper/Slugifier.php
Aren't //IGNORE and //TRANSLIT mutually exclusive?
I was getting a `iconv(): Detected an illegal character in input string` notice with some accented letters.
> changed iconv transliteration setting

- src/Kunstmaan/NodeBundle/EventListener/NodeTranslationListener.php
This listener goes into infinite recursion when saving a Page, if that Page is a structure node, but does not extend `StructureNode` class for whatever reason.
I think it's better to check if it's a structure node by using `isStructureNode()` of `HasNodeInterface`, because one might not want to extend `StructureNode` and `AbstractPage` (which StructureNode extends from) just because of this listener.
> fixes infinite recursion problem in NodeTranslationListener

- src/Kunstmaan/AdminBundle/Resources/public/js/script.js
- src/Kunstmaan/NodeBundle/Helper/Menu/ActionsMenuBuilder.php
Setting `disabled=disabled` on the "Save as draft" button prevents submitting the "saveasdraft" parameter.
This also unsets `data-toggle=modal` on "Publish/Unpublish" and "Add subpage" links, just in case.
> Fix actions menu

- src/Kunstmaan/AdminBundle/Helper/Security/Acl/AclNativeHelper.php
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/admintests/Features/Context/FeatureContext.php
Fixes syntax error created by commit: https://github.com/Kunstmaan/KunstmaanBundlesCMS/commit/b72a8f982605ccd068b8957831693bc8eaf6675d (Do not prefix database when using SQLite).
> SQL syntax error in admin pages

- src/Kunstmaan/UtilitiesBundle/Helper/Slugifier.php
In case a user insert a text with special characters in a page the method slugify would break without this change.
Specifically I get the error " iconv: Detected an illegal character in input string ".
Adding the @ silent this notice and all works fine.
> fix issue slugify method

- src/Kunstmaan/FormBundle/AdminList/FormSubmissionExportListConfigurator.php
When exporting all FormSubmissions of a certain NodeTransation, the csv or excel file contains all submissions for all translations of the Node. This results in a file exported with only certain fields filled in (depending on the first language):
This was an export on the Dutch NodeTranslation.
As the method states it should only export all the entries of the NodeTranslation and not the Node. I propose to filter on the NodeTranslation language as well.
> Only export formsubmissions of the same language (aka NodeTranslation)

- src/Kunstmaan/AdminBundle/DependencyInjection/Configuration.php
- src/Kunstmaan/AdminBundle/DependencyInjection/KunstmaanAdminExtension.php
- src/Kunstmaan/AdminBundle/EventListener/ConsoleExceptionListener.php
- src/Kunstmaan/AdminBundle/Resources/config/console_listener.yml
- src/Kunstmaan/AdminBundle/Resources/config/services.yml
added a ConsoleExcetpionListener to the adminBundle, this service can be toggled on or off in the app/config.yml file by adding the line: enable_console_exception_listener: true 
to the kunstmaan_admin section.
> ConsoleExceptionListener

- .travis.yml
> Fix Scrutinizer integration with Travis by disabling fast_finish on Travis

- src/Kunstmaan/MediaBundle/DependencyInjection/Configuration.php
- src/Kunstmaan/MediaBundle/DependencyInjection/KunstmaanMediaExtension.php
- src/Kunstmaan/MediaBundle/Helper/File/FileHandler.php
- src/Kunstmaan/MediaBundle/Resources/config/handlers.yml
| Fixed tickets | #200
With this fix we can keep the original file name without conflicts in case of duplicate filenames. Also via a basic blacklist system we can limit the extensions on disk for security purposes. This blacklist can be extended through the config.yml.
> [MediaBundle] Uploaded files and images should retain their original name and extension

- src/Kunstmaan/NodeBundle/Form/PageAdminType.php
- src/Kunstmaan/SeoBundle/Form/SeoType.php
All the title fields at the page - edit form are confusing. 
I updated the titles and info so that everything will be a bit more clear. 
| Fixed tickets | #248
> [NodeBundle, SeoBundle] Update labels at 'Edit pages' to be more clear

- src/Kunstmaan/PagePartBundle/PagePartAdmin/PagePartAdmin.php
- src/Kunstmaan/PagePartBundle/Repository/PagePartRefRepository.php
| Fixed tickets | #173
Moving pageparts to another region in the back-end caused an internal error. This fix makes it possible to save after transferring pageparts without causing an error.
> Fix issue #173 moving pageparts gives error when saving

- src/Kunstmaan/AdminBundle/Form/WysiwygType.php
- src/Kunstmaan/AdminBundle/Resources/config/services.yml
- src/Kunstmaan/AdminBundle/Resources/ui/js/_rich-editor.js
- src/Kunstmaan/AdminBundle/Resources/views/Form/fields.html.twig
- src/Kunstmaan/GeneratorBundle/Command/KunstmaanGenerateCommand.php
| Fixed tickets | #212
TODO
WHAT
A new wysiwyg form type has been created in the Adminbundle. 
This makes it possible to use 'wysiwig' in the formbuilder as a type and results in a text area with a wysiwyg editor on top. There are two extra options you can pass as a data attribute:
- simple: will only render a basic wysiwyg editor
- full: will render a wysiwyg editor with extra buttons
The wysiwyg formtype also replaces the rich text type when generating a new pagepart using the kunstmaan generatorbundle.
WHY
Before this feature there was:
```php
$builder->add('name', 'textarea',
array(
'attr' => array(
'rows'  => 5,
'cols'  => 600,
'class' => 'js-rich-editor …
```
> Wysiwyg formtype added

- src/Kunstmaan/FormBundle/Entity/FormSubmissionField.php
Make the Kunstmaan CMS compatible with Doctrine ORM 2.5.x
http://doctrine-orm.readthedocs.org/en/latest/changelog/migration_2_5.html#minor-bc-break-all-non-transient-classes-in-an-inheritance-must-be-part-of-the-inheritance-map
| Fixed tickets | #256
> [FormBundle] Fix for the Doctrine ORM BC break in v2.5.0 => base inheritance mapping classes must befined as abstract

- src/Kunstmaan/AdminBundle/Tests/Helper/Security/Acl/AclHelperTest.php
Due to changes in Doctrine, the ACLHelper test was broken. This PR should fix that.
> [AdminBundle] Fix the AclHelper test due to changes in Doctrine 2.5.0

- src/Kunstmaan/UtilitiesBundle/Helper/Slugifier.php
Slugifier tests were broken, this Transliterator seemed to work ok (and since Intl is required for Symfony it should not break anything).
> Use PHP Intl Transliterator to fix slugifier issues

- src/Kunstmaan/NodeBundle/Resources/views/NodeAdmin/edit.html.twig
This adds the classname of the entity as an abbr to the admin is the user has the SUPER_ADMIN role.
> [NodeBundle] Add classname to admin if user is a super admin

- src/Kunstmaan/MediaBundle/Controller/ChooserController.php
- src/Kunstmaan/MediaBundle/Controller/FolderController.php
- src/Kunstmaan/MediaBundle/Resources/views/Chooser/chooserShowFolder.html.twig
| Fixed tickets | #251 
This feature makes it possible to add/delete new folders while inside the media-chooser. This way, you can re-arrange the folder structure without having to exit the media-chooser.
> [MediaBundle] Add add/delete new folders while inside the media-chooser popup

- src/Kunstmaan/AdminBundle/Resources/ui/js/_app-filter.js
- src/Kunstmaan/AdminBundle/Resources/ui/js/_app-loading.js
- src/Kunstmaan/AdminBundle/Resources/ui/js/_page-editor.js
- src/Kunstmaan/AdminBundle/Resources/ui/js/_pagepart-editor.js
- src/Kunstmaan/AdminBundle/Resources/ui/js/app.js
- src/Kunstmaan/AdminBundle/Resources/ui/scss/default-theme/general/_app.scss
- src/Kunstmaan/AdminBundle/Resources/views/Default/_js_footer.html.twig
- src/Kunstmaan/MediaBundle/Resources/views/Folder/addsub-modal.html.twig
- src/Kunstmaan/MediaBundle/Resources/views/Folder/delete-modal.html.twig
- src/Kunstmaan/MediaBundle/Resources/views/Media/addType-modal.html.twig
> [AdminBundle, MediaBundle] Update loading behaviour of app

- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/Entity/OverviewPage.php
- src/Kunstmaan/NodeBundle/Controller/SlugActionInterface.php
- src/Kunstmaan/NodeBundle/Event/Events.php
- src/Kunstmaan/NodeBundle/Event/SlugSecurityEvent.php
- src/Kunstmaan/NodeBundle/EventListener/RenderContextListener.php
- src/Kunstmaan/NodeBundle/EventListener/SlugListener.php
- src/Kunstmaan/NodeBundle/EventListener/SlugSecurityListener.php
- src/Kunstmaan/NodeBundle/Resources/config/services.yml
| Fixed tickets | #211
instead of putting logic in the entity pages (service method), it is now possible to just implement the SlugActionInterface and specify which controller method must be executed. 
You need to remove the service method in your entities and replace them by implementing the SlugActionInterface. Add the method getControllerAction and make it return a callable string.
```php
public function getControllerAction()
{
return 'Bundle:Controller:service';
}
```
In your controller just add the serviceAction method, let it handle the logic and set the renderContext in the request attributes. 
```php
public function serviceAction(Request $request)
{ …
```
> [NodeBundle, GeneratorBundle] Deprecated the service method in Pages in favour of controller methods

- src/Kunstmaan/SeoBundle/Controller/RobotsController.php
- src/Kunstmaan/SeoBundle/Resources/translations/messages.en.yml
- src/Kunstmaan/SeoBundle/Resources/views/Admin/Robots/index.html.twig
- src/Kunstmaan/SeoBundle/Resources/views/Admin/Settings/robotsSettings.html.twig
- Changed the header content type to plain/text for the robot.txt route.
- Added a preview button
- Added a link to the cookbook for additional information
> [SeoBundle] Robots in plain text with extra info and preview button

- UPGRADE-3.1.md
> [Documentation] Add missing upgrade notice for the ArticleBundle

- docs/04-03-creating-a-pagetype.md
> [Documentation] Removed the deprecated service method in favor of controller method

- src/Kunstmaan/GeneratorBundle/Command/GenerateArticleCommand.php
- src/Kunstmaan/GeneratorBundle/Command/GenerateEntityCommand.php
- src/Kunstmaan/GeneratorBundle/Command/KunstmaanGenerateCommand.php
- src/Kunstmaan/GeneratorBundle/Helper/InputAssistant.php
| Fixed tickets | #184 
You no longer can create entities with names that cause errors and database prefixes are now validated on creation.
> [GeneratorBundle] Validate entity names and database prefixes in the generators

- src/Kunstmaan/AdminBundle/Command/CreateUserCommand.php
| Fixed tickets | #317
When creating a new user in the console, you no longer have to type the groups, you can just select them form a list.
> [AdminBundle] Show list of available groups when creating a new admin user via the console 

- src/Kunstmaan/ArticleBundle/Controller/AbstractArticleOverviewPageController.php
- src/Kunstmaan/ArticleBundle/Entity/AbstractArticleOverviewPage.php
- src/Kunstmaan/FormBundle/Controller/AbstractFormPageController.php
- src/Kunstmaan/FormBundle/Entity/AbstractFormPage.php
- src/Kunstmaan/NodeSearchBundle/Controller/AbstractSearchPageController.php
- src/Kunstmaan/NodeSearchBundle/Entity/AbstractSearchPage.php
> [ArticleBundle, FormBundle, NodeSearchBundle] Removed service method in favor of controller methods

- src/Kunstmaan/MediaBundle/Helper/File/FileHandler.php
| Fixed tickets | #309 
Media url path does not contain double slashes anymore.
> [KunstmaanBundlesCMS] [MediaBundle] Fix single slash in media path

- src/Kunstmaan/AdminListBundle/Resources/views/Default/add_or_edit.html.twig
> [AdminListBundle] Re-use the default title logic for adminlists instead of duplicating it

- src/Kunstmaan/SeoBundle/Form/SocialType.php
This fix will make the OG image not required.
| Fixed tickets | #336
> [SeoBundle] Remove the required option from the Open Graph Image field in the social tab

- src/Kunstmaan/MediaBundle/Resources/views/Chooser/chooserShowFolder.html.twig
> [MediaBundle] Media chooser type parameter now filters results correctly

- src/Kunstmaan/FormBundle/Controller/AbstractFormPageController.php
- src/Kunstmaan/NodeBundle/EventListener/RenderContextListener.php
The submission of form pages is broken due to the refactoring of the service method. With these changes it works again.
> [FormBundle] Fix the formpage submissions due to the refactoring of the service method.

- src/Kunstmaan/AdminListBundle/Resources/views/Default/add_or_edit.html.twig
The save button was placed outside the `<form>` tag, so it was not working anymore.
> [AdminListBundle] Fix the save button in adminlists, it was placed outside the <form> tag

- src/Kunstmaan/SeoBundle/Controller/Admin/SettingsController.php
- src/Kunstmaan/SeoBundle/Controller/RobotsController.php
- src/Kunstmaan/SeoBundle/Form/RobotsType.php
- src/Kunstmaan/SeoBundle/Resources/config/parameters.yml
- src/Kunstmaan/SeoBundle/Resources/translations/messages.en.yml
This is a upgrade for the robots.txt. It warns you that no robots.txt has been defined and makes a default suggestion.
> [SeoBundle] Suggest a default value in the robots.txt field when empty

- src/Kunstmaan/MediaBundle/Validator/Constraints/MediaValidator.php
Cleaned up a file that addresses SensioLabs insight major issue.
> [MediaBundle] Fix missing use statement and cleaned file

- src/Kunstmaan/GeneratorBundle/Command/KunstmaanGenerateCommand.php
| Fixed tickets | #353 
Pageparts containing images can now be generated without errors.
> [GeneratorBundle] Fix error when generating pagepart with images

- src/Kunstmaan/AdminBundle/Resources/ui/js/_nested-form.js
- src/Kunstmaan/AdminBundle/Resources/ui/js/_page-editor.js
- src/Kunstmaan/AdminBundle/Resources/ui/js/_pagepart-editor.js
- src/Kunstmaan/AdminBundle/Resources/ui/js/_rich-editor.js
> [AdminBundle] Fix rich-editor issues for pageparts with subentities

- src/Kunstmaan/GeneratorBundle/Command/KunstmaanGenerateCommand.php
| Fixed tickets | N/A 
A bundle may have it’s own name, not composed of it’s namespace.
> [GeneratorBundle] Use real bundle name if it’s not the same as the namespace

- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/pagepart/Form/PageParts/AudioPagePart/AudioPagePartAdminType.php
Missing one part of the namespace.
> [GeneratorBundle] Add missing entity namespace folder in the AudioPagePartAdminType

- src/Kunstmaan/MediaBundle/Controller/MediaController.php
When uploading a file using drag & drop there was an Exception:
```
Catchable Fatal Error: Object of class Symfony\Component\HttpFoundation\File\UploadedFile could not be converted to boolean
```
> [MediaBundle] Fix drag & drop file upload boolean conversion exception

- src/Kunstmaan/NodeBundle/EventListener/RenderContextListener.php
- src/Kunstmaan/NodeSearchBundle/Controller/AbstractSearchPageController.php
> [NodeBundle, NodeSearchBundle] Handle case when RenderContext is not an array but ArrayObject

- src/Kunstmaan/MediaBundle/Controller/FolderController.php
Fixed this error when accessing FolderController:
> [MediaBundle] Fix missing type variable when accessing FolderController

- src/Kunstmaan/GeneratorBundle/Generator/PagePartGenerator.php
Hi, in the correct repo now :) My bad, I was a bit too quick and did not read the contribution guide. Hope everything is allright now.
When generating a pagepart using Kunstmaan v3.1 the check for an AbstractPagePart only contained a string and did not check if the file existed which resulted in an error when trying to generate a pagepart. Added a file_exists to the condition.
> [GeneratorBundle] Added missing check for AbstractPagePart during page part generation

- src/Kunstmaan/SeoBundle/Controller/Admin/SettingsController.php
- src/Kunstmaan/SeoBundle/Form/RobotsType.php
The flash message did not go away after save.
Refactored the code to solve this issue
> [SeoBundle] Fix hanging flash message, it will now disappear after save

- src/Kunstmaan/NodeBundle/EventListener/RenderContextListener.php
> [NodeBundle] Don't BC break nodeTranslation introduced when we depreciated the service method

- src/Kunstmaan/AdminBundle/Event/AdaptSimpleFormEvent.php
- src/Kunstmaan/AdminBundle/Event/Events.php
- src/Kunstmaan/AdminBundle/Form/UserType.php
- src/Kunstmaan/AdminListBundle/Controller/AdminListController.php
- src/Kunstmaan/AdminListBundle/Resources/views/Default/add_or_edit.html.twig
- src/Kunstmaan/UserManagementBundle/Controller/UsersController.php
- src/Kunstmaan/UserManagementBundle/Resources/views/Users/edit.html.twig
| Fixed tickets | #74 
In order to add tabs to admin and user forms, just write a listener that listens for the kunstmaan_admin.adaptSimpleForm Event and implements a method that creates a new TabPane and adds a FormWidget to the event.
public function onAdaptSimpleFormEvent(AdaptSimpleFormEvent $event)
{
$tabPane = new TabPane('TabPane', $event->getRequest(), $this->formFactory);
$widget = new FormWidget();
$widget->addType('Tab',$event->getFormType(),$event->getData());
$tabPane->addTab(new Tab('User', $widget));
$tabPane->buildForm();
$event->setTabPane($tabPane);
}
> [AdminBundle, UserManagmentBundle, AdminListBundle] Added seperate event to add tabs to admin forms and user forms

- src/Kunstmaan/NodeBundle/Controller/SlugController.php
- src/Kunstmaan/NodeBundle/Event/Events.php
- src/Kunstmaan/NodeBundle/Event/SlugEvent.php
> [NodeBundle] Added pre and post event to the slugController

- src/Kunstmaan/AdminListBundle/AdminList/Configurator/ExportListConfiguratorInterface.php
- src/Kunstmaan/AdminListBundle/AdminList/ExportList.php
- src/Kunstmaan/AdminListBundle/Controller/AdminListController.php
> [AdminListBundle] Export should only export the currently selected filters

- src/Kunstmaan/NodeBundle/Event/SlugEvent.php
> [NodeBundle] Fixed error when passing null to slugEvent

- src/Kunstmaan/AdminBundle/Resources/ui/scss/default-theme/general/_login.scss
- src/Kunstmaan/AdminBundle/Resources/views/Resetting/checkEmail.html.twig
- src/Kunstmaan/AdminBundle/Resources/views/Resetting/passwordAlreadyRequested.html.twig
- src/Kunstmaan/AdminBundle/Resources/views/Resetting/request_content.html.twig
- src/Kunstmaan/AdminBundle/Resources/views/layout.html.twig
- src/Kunstmaan/UserManagementBundle/Resources/views/Users/edit.html.twig
> [AdminBundle] Cleanup and fix styling FOS Change Password form

- src/Kunstmaan/MediaBundle/Helper/File/FileHandler.php
- src/Kunstmaan/MediaBundle/Helper/Image/ImageHandler.php
- src/Kunstmaan/MediaBundle/Helper/Media/AbstractMediaHandler.php
- src/Kunstmaan/MediaBundle/Helper/MediaManager.php
- src/Kunstmaan/MediaBundle/Helper/RemoteAudio/RemoteAudioHandler.php
- src/Kunstmaan/MediaBundle/Helper/RemoteVideo/RemoteVideoHandler.php
- src/Kunstmaan/MediaBundle/Resources/config/handlers.yml
- src/Kunstmaan/MediaBundle/Tests/Helper/File/PdfHandlerTest.php
- src/Kunstmaan/MediaBundle/Tests/Helper/MediaManagerTest.php
| Fixed tickets | #188
Handlers with higher priority will be preferred over handlers with lower priority when adding media.
> [MediaBundle] Add priority to media handlers

- src/Kunstmaan/AdminBundle/Resources/views/Default/rectreeview.html.twig
- src/Kunstmaan/NodeBundle/Helper/Menu/PageMenuAdaptor.php
All sub pages of a structured node are always marked as "offline" in the tree, even if they are published. This PR solves this issue.
> [NodeBundle] Fix online/offline indication in the menu tree for child pages of structure nodes

- src/Kunstmaan/TranslatorBundle/Service/Command/Importer/Importer.php
We cannot convert the VARCHAR(255) keyword column to TEXT, because indexes will not work anymore. See http://www.doctrine-project.org/jira/browse/DDC-2802
> [TranslatorBundle] Fix error when importing translations where keyword lenght > 255 characters

- src/Kunstmaan/AdminBundle/Resources/views/Form/fields.html.twig
> [AdminBundle] When an extra css class was added in the FormType, the basic classes where removed

- src/Kunstmaan/NodeBundle/Controller/NodeAdminController.php
- src/Kunstmaan/NodeBundle/Helper/Menu/ActionsMenuBuilder.php
- src/Kunstmaan/NodeBundle/Resources/translations/messages.en.yml
- src/Kunstmaan/NodeBundle/Resources/views/NodeAdmin/_modals.html.twig
| Fixed tickets | #34  
I've added a button to create a duplicate of a page (at the same location in the page tree as the page being duplicated).
> [NodeBundle] Add button to create a duplicate of a page 

- src/Kunstmaan/AdminBundle/Resources/ui/js/_rich-editor.js
- src/Kunstmaan/AdminBundle/Resources/views/Default/_ckeditor_configs.html.twig
| Fixed tickets | #402 
This pull request allows the developer to specify a custom config.js file for the CKEditor instance used in the AdminBundle.
To specify a custom config.js file, the developer should override `KunstmaanAdminBundle:Default:_ckeditor_configs.html.twig` and set the `customConfigFile` variable to the path to their custom config.js file.
> [AdminBundle] Added option to use a custom CKEditor config.js file

- src/Kunstmaan/GeneratorBundle/Command/GeneratePagePartCommand.php
- src/Kunstmaan/GeneratorBundle/Command/KunstmaanGenerateCommand.php
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/common/Form/EntityAdminType.php
Adding validation for media objects in pageparts is no longer obligated. You no longer have to set minimum/maximum dimension values for images if you don't want to. Instead you can skip the validation part and add it later directly into the form files if you want to. This makes for a more userfriendly experience when generating pageparts.
> [GeneratorBundle] Refactor pagepart media validation

- src/Kunstmaan/AdminBundle/Resources/ui/scss/default-theme/general/_app__header.scss
- src/Kunstmaan/AdminBundle/Resources/views/Default/app_header.html.twig
This feature will enable to use logo's instead of plain text in the admin header
> [AdminBundle] Added an option to change the backend site name to a logo

- src/Kunstmaan/AdminBundle/Helper/FormWidgets/Tabs/TabPane.php
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/DataFixtures/ORM/ArticleGenerator/ArticleFixtures.php
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/searchpage/DataFixtures/ORM/SearchPageGenerator/SearchFixtures.php
- src/Kunstmaan/NodeBundle/Entity/NodeTranslation.php
- src/Kunstmaan/NodeBundle/EventListener/NodeTranslationListener.php
- src/Kunstmaan/NodeBundle/Form/Type/SlugType.php
- src/Kunstmaan/NodeBundle/Repository/NodeTranslationRepository.php
- src/Kunstmaan/NodeBundle/Resources/config/services.yml
- src/Kunstmaan/UtilitiesBundle/Helper/Slugifier.php
- src/Kunstmaan/UtilitiesBundle/Helper/SlugifierInterface.php
- src/Kunstmaan/UtilitiesBundle/Resources/config/services.yml
- src/Kunstmaan/UtilitiesBundle/Tests/Helper/SlugifierTest.php
- src/Kunstmaan/UtilitiesBundle/Twig/UtilitiesTwigExtension.php
> [AdminBundle,GeneratorBundle,NodeBundle,UtilitiesBundle] Change slugifier into service

- src/Kunstmaan/GeneratorBundle/Generator/DefaultSiteGenerator.php
| Fixed tickets | [440](https://github.com/Kunstmaan/KunstmaanBundlesCMS/issues/440)
> [GeneratorBundle] remove the obsolete default locale fallback from generator

- src/Kunstmaan/NodeBundle/EventListener/NodeTranslationListener.php
- src/Kunstmaan/NodeBundle/Repository/NodeTranslationRepository.php
- src/Kunstmaan/NodeBundle/Resources/config/services.yml
When you copy a page or use the doctrine fixtures (without setting a slug) the non slugified page title is used as slug.
Because you can't add the slugifier service to the nodetranslation repo this will be handled in the nodetranslation listener on pre persist/update.
> [Nodebunde] Fix not slugified slug

- src/Kunstmaan/SeoBundle/Entity/Seo.php
- src/Kunstmaan/SeoBundle/Tests/Entity/SeoTest.php
> [SeoBundle] Fixed issue that OG image can not be deleted

- src/Kunstmaan/AdminBundle/Command/CreateUserCommand.php
- Fixed issue where a function was being called in a for loop.
- Refactored the console commands that asks for user groups to use select and not askAndValidate.
| Fixed tickets | #435
> [AdminBundle] Usage of a function in loops should be avoided and refactor groups mechanism

- UPGRADE-3.2.md
- src/Kunstmaan/SitemapBundle/Controller/SitemapController.php
- src/Kunstmaan/SitemapBundle/Resources/views/SitemapIndex/view.xml.twig
| Fixed tickets | #4
WHAT
This feature generates one central sitemap.xml file at your document root to define a sub sitemap for each language available.
You can now have up to 50000 urls for each language you define.
As a bonus, you only have to register the sitemap index (/sitemap.xml) at the search engines to register all available languages.
HOW
In order to upgrade, you need a new route in your app/config/routes.yml.
```yml
KunstmaanSitemapBundle_sitemapIndex:
resource: "@KunstmaanSitemapBundle/Controller/SitemapController.php"
type:     annotation
```
TODO
> [SitemapBundle] Make use of a sitemapindex and sub sitemaps

- composer.json
- src/Kunstmaan/GeneratorBundle/Command/GenerateAdminListCommand.php
- src/Kunstmaan/GeneratorBundle/Command/GenerateAdminTestsCommand.php
- src/Kunstmaan/GeneratorBundle/Command/GenerateArticleCommand.php
- src/Kunstmaan/GeneratorBundle/Command/GenerateBundleCommand.php
- src/Kunstmaan/GeneratorBundle/Command/GenerateDefaultPagePartsCommand.php
- src/Kunstmaan/GeneratorBundle/Command/GenerateDefaultSiteCommand.php
- src/Kunstmaan/GeneratorBundle/Command/GenerateEntityCommand.php
- src/Kunstmaan/GeneratorBundle/Command/GenerateLayoutCommand.php
- src/Kunstmaan/GeneratorBundle/Command/GeneratePageCommand.php
- src/Kunstmaan/GeneratorBundle/Command/GeneratePagePartCommand.php
- src/Kunstmaan/GeneratorBundle/Command/GenerateSearchPageCommand.php
- src/Kunstmaan/GeneratorBundle/Command/KunstmaanGenerateCommand.php
- src/Kunstmaan/GeneratorBundle/Generator/AdminListGenerator.php
- src/Kunstmaan/GeneratorBundle/Helper/CommandAssistant.php
- src/Kunstmaan/GeneratorBundle/Helper/GeneratorUtils.php
- src/Kunstmaan/GeneratorBundle/Helper/InputAssistant.php
| Fixed tickets | #71, #88 
This feature replaces all calls to DialogHelper with QuestionHelper in the GeneratorBundle since the DialogHelper is deprecated since Symfony 2.5 .
> [GeneratorBundle] Replace DialogHelper with QuestionHelper

- UPGRADE-3.2.md
- src/Kunstmaan/FormBundle/Controller/FormSubmissionsController.php
- src/Kunstmaan/FormBundle/Entity/FormAdaptorInterface.php
- src/Kunstmaan/FormBundle/Entity/FormSubmission.php
- src/Kunstmaan/FormBundle/Entity/FormSubmissionField.php
- src/Kunstmaan/FormBundle/Entity/PageParts/CheckboxPagePart.php
- src/Kunstmaan/FormBundle/Entity/PageParts/ChoicePagePart.php
- src/Kunstmaan/FormBundle/Entity/PageParts/EmailPagePart.php
- src/Kunstmaan/FormBundle/Entity/PageParts/FileUploadPagePart.php
- src/Kunstmaan/FormBundle/Entity/PageParts/MultiLineTextPagePart.php
- src/Kunstmaan/FormBundle/Entity/PageParts/SingleLineTextPagePart.php
- src/Kunstmaan/FormBundle/Helper/FormHandler.php
- src/Kunstmaan/FormBundle/Helper/FormMailer.php
- src/Kunstmaan/FormBundle/Resources/DoctrineMigrations/Version20150527162434.php
- src/Kunstmaan/FormBundle/Tests/Entity/PageParts/ChoicePagePartTest.php
- src/Kunstmaan/FormBundle/Tests/Entity/PageParts/EmailPagePartTest.php
- src/Kunstmaan/FormBundle/Tests/Entity/PageParts/FileUploadPagePartTest.php
- src/Kunstmaan/FormBundle/Tests/Entity/PageParts/MultiLineTextPagePartTest.php
- src/Kunstmaan/FormBundle/Tests/Entity/PageParts/SingleLineTextPagePartTest.php
- src/Kunstmaan/FormBundle/UPGRADE-3.2.md
- src/Kunstmaan/FormBundle/UPGRADE.md
| Fixed tickets | [445](https://github.com/Kunstmaan/KunstmaanBundlesCMS/issues/445)
> [FormBundle] Order the FormSubmissionFields like their respective PageParts on the FormPage

- UPGRADE-3.2.md
- src/Kunstmaan/SitemapBundle/Entity/SitemapPage.php
- src/Kunstmaan/SitemapBundle/Helper/HiddenFromSitemapInterface.php
- src/Kunstmaan/SitemapBundle/Twig/SitemapTwigExtension.php
Interfaces names should end with "Interface":
Interface HiddenFromSitemap should be named HiddenFromSitemapInterface for better clarity.
**THIS IS A BC BREAK!**
> [SitemapBundle] refactored SitemapInterface

- src/Kunstmaan/SeoBundle/Controller/RobotsController.php
The and operator does not have the same precedence as &&.
This could lead to unexpected behavior, use && instead.
| Fixed tickets | #467
> [SeoBundle] Avoid using "and" operator, using &&

- composer.json
The bundles are not yet compatible with Symfony 2.7. Until then we need to depend on symfony lower then 2.7.
> [Dependencies] Lock on symfony lower then 2.7 (TEMPORARY)

- src/Kunstmaan/DashboardBundle/Resources/views/Dashboard/index.html.twig
- src/Kunstmaan/DashboardBundle/Resources/views/GoogleAnalytics/setupcontainer.html.twig
Q | A
--- | ---
Bug fix? | no
New feature? | no
BC breaks? | no
Deprecations? | no
Fixed tickets | /
previously, dashboard bundle css files were dumped to `web/css`, now they behave like every other bundle and get generated to `web/KunstmaanDashboardBundleAssets/css`, where its JS files already reside
> [DashboardBundle] unified the css output paths for assetic

- UPGRADE-3.2.md
- src/Kunstmaan/NodeSearchBundle/Controller/AbstractSearchPageController.php
- src/Kunstmaan/NodeSearchBundle/Resources/config/services.yml
- src/Kunstmaan/NodeSearchBundle/Services/SearchService.php
> [NodeSearchBundle] Refactored search to seperate service

- src/Kunstmaan/AdminBundle/Entity/BaseUser.php
- src/Kunstmaan/AdminBundle/composer.json
Hello,
I've updated kunstmaan bundles from 3.0 to 3.2.*@dev.
all works great but i have a problem with custom user entity.
i have extended the original entity by this article:
http://bundles.kunstmaan.be/news/extending-the-admin-user-entity
but in new version i have some errors:
1 on user page it tries to show entities from original db table 
2 on add/edit i have this error 
Error: Call to protected method Sandbox\WebsiteBundle\Entity\User::getFormTypeClass() from context 'Kunstmaan\UserManagementBundle\Controller\UsersController' 
and if i change the protected method to public i get 
Attempted to load class "UserType" from namespace "SandBox\WebsiteBundle\Form".
Did you forget a "use" statement for "Kunstmaan\AdminBundle\Form\UserType"?
my method : 
public function getFormTypeClass()
{ …
> Extending the admin User entity 3.2.*@dev

- src/Kunstmaan/AdminBundle/EventListener/AdminLocaleListener.php
Since Symfony 2.6 it seems to be necessary to also update the locale on subrequests. This becomes apparent when viewing a backend pag with a subrequest while the request locale (by virtue of the default locale) is not equal to an admin locale of a backend user. In my case I had my default locale set to Dutch (nl) and the backend locale set to English (en). This resulted in the dashboard page using Dutch translations, while the rest of the backend uses English translations.
Apparently this is caused by a refactor of the TranslatorListener in Symfony 2.6, which also acts on subrequests. I'm not certain if checking for a subrequest is still needed …
> Make AdminLocaleListener also update locale on subrequests

- src/Kunstmaan/AdminBundle/Helper/Security/Acl/Permission/PermissionAdmin.php
saving of permissions was not possible because the fieldname `permissionChanges` getting from request was not set anywhere, but `permissions-hidden-fields` has the required structure.
> [AdminBundle] Fix for failure to save permissions

- src/Kunstmaan/AdminBundle/Helper/FormHelper.php
When looping child forms the errors array is overwriting itself.
> [AdminBundle] Fixed missing error messages due to overwriting the errors array

- src/Kunstmaan/UtilitiesBundle/Helper/Slugifier.php
- src/Kunstmaan/UtilitiesBundle/Tests/Helper/SlugifierTest.php
changed Transliterator behavior to handle polish diacritics
> changed Transliterator behavior to handle polish diacritics

- src/Kunstmaan/MediaBundle/Tests/Validator/Constraints/MediaValidatorTest.php
- src/Kunstmaan/MediaBundle/Validator/Constraints/Media.php
- src/Kunstmaan/MediaBundle/Validator/Constraints/MediaValidator.php
> [MediaBundle] refactored `MediaValidator`, fixed missing `TOO_NARROW_ERROR` constant

- src/Kunstmaan/AdminBundle/Resources/ui/js/_pagepart-editor.js
The `$.select2` widget gets confused when the input is hidden while initializing and uses a wrong width. 
This patch reinitializes the widget on edit the same way as it’s done when adding a PagePart.
> [AdminBundle] reinit advancedSelect when editing a PagePart

- src/Kunstmaan/NodeSearchBundle/Configuration/NodePagesConfiguration.php
Changed all private properties/methods to protected so it's possible to extends and overwrite the NodePagesConfiguration easily.
> [NodeSearchBundle] changed NodePagesConfiguration methods/properties from private to protected to improve extendability

- docs/04-07-configuring-adminlists.md
Had a space in the name and saw it to late. A - is better to include it in the bundles documentation.
> [Documentation] Working with admin lists follow naming conventions

- src/Kunstmaan/AdminBundle/Resources/ui/scss/default-theme/components/structures/_page-actions.scss
- src/Kunstmaan/AdminBundle/Resources/views/TabsTwigExtension/widget.html.twig
fix error label in the main tabs. Changed from text to a number bullet.
> [AdminBundle] fixed styling error labels in page-main-tabs

- src/Kunstmaan/PagePartBundle/Helper/PagePartConfigurationReader.php
If there is a page limit for the page part in the config, add this to the types array.
Kunstmaan already checks on this value in the form widgets. But the pagepart configuration reader didn't add this value to the types array.
| Fixed tickets |  https://github.com/Kunstmaan/KunstmaanBundlesStandardEdition/issues/60
Small change to config if you want to use this function
```
name: PagepartCollection
context: PagepartContext
types:
- { name: PagepartName, class: PagePart, pagelimit: 1 }
```
> [PagepartBundle] Pagepart limits

- src/Kunstmaan/NodeBundle/EventListener/RenderContextListener.php
- src/Kunstmaan/NodeBundle/Resources/config/services.yml
This fixes the admin preview on pages where you bypass the SlugController with the controller as a service method.
> [NodeBundle] Fix admin preview when controller as a service is used

- UPGRADE-3.2.md
Very minor change: improved the upgrade guide for 3.1 to 3.2:
* corrected the name of the routing.yml file
* mentioned the FormBundle so you don't have to search trough all bundles
* mentioned the required schema:update for updating the user table,  because the other database change has a migration.
* improved formatting
> [documentation] improved upgrade guide

- src/Kunstmaan/MediaBundle/Controller/MediaController.php
In the interest of extensibility, this method should be protected, not private.  If you want to extend this bundle and make changes to either this method, or methods that call it, you have to copy large swaths of code because a child class can't access private methods from the parent.  And if you do that, you now can't get updates to the class because you've redefined almost all the methods.
> [MediaBundle] Change MediaController createAndRedirect() from private to protected

- src/Kunstmaan/AdminBundle/EventListener/AdminLocaleListener.php
Whoops, this is a fix for my previous pull request: https://github.com/Kunstmaan/KunstmaanBundlesCMS/pull/499
I will now yell at myself for breaking it :(
Apparently the previous check for subrequests protected against executing the code in AdminLocaleListener in case an exception needs to be handled, most notably a 404. Removing this check results in 404s no longer being handled correctly, as can be seen on your own demosite: http://demo.bundles.kunstmaan.be/en/doesnotexist
I've added an explicit check for the security context to handle this situation. Apologies for breaking this in the first place.
> Add check for presence of security token in AdminLocaleListener

- src/Kunstmaan/AdminListBundle/AdminList/Configurator/AbstractDoctrineDBALAdminListConfigurator.php
The `setCurrentPage ` also checks if the page exists based in the `max items per page`. So if you override it, it checks if the page exists based on the default `max items per page`, because the custom number is only set after the `setCurrentPage ` method call.
> [AdminListBundle] Fix pagination issue for DBAL adminlists

- src/Kunstmaan/NodeBundle/EventListener/RenderContextListener.php
This allows you to define a Controller in the entity and return an array with values that will be available in the twig view, following standard symfony behaviour. This way you don't have to create a new RenderContext object and manually place it in the request attributes (although you _can_ still do that to maintain BC)
> [NodeBundle] Allow more flexible entity controller handling

- src/Kunstmaan/AdminBundle/DependencyInjection/Configuration.php
- src/Kunstmaan/AdminBundle/DependencyInjection/KunstmaanAdminExtension.php
- src/Kunstmaan/AdminBundle/Helper/Menu/SimpleMenuAdaptor.php
- src/Kunstmaan/AdminBundle/Resources/doc/CustomizingTheTopMenu.md
| Fixed tickets | #509 
Add menu items using configuration.
```yaml
kunstmaan_admin:
menu_items:
- route: AcmeBundle_mymodule_list  # your route name
label: FooBaring Module
parent: ~                        # attach it under specified menu item, default: KunstmaanAdminBundle_modules
params: { source: "menuitem" }   # optional, array with custom route parameters
role: ROLE_ADMIN                 # optional, only show for users with this role
```
> [AdminBundle] simple menu adaptor

- src/Kunstmaan/TaggingBundle/Entity/LazyLoadingTaggableInterface.php
- src/Kunstmaan/TaggingBundle/Entity/TagManager.php
- src/Kunstmaan/TaggingBundle/Entity/TaggableTrait.php
- src/Kunstmaan/TaggingBundle/EventListener/TagsListener.php
Don’t load all tags when loading entity — delay it until they are needed.
Also a `Trait` for convenience.
> [TaggingBundle] lazy-load tags

- src/Kunstmaan/AdminBundle/Resources/views/Form/fields.html.twig
For non-compound (for example a doctrine `entity` type) forms the `obj.vars.value` attribute is a scalar, so you cannot get an `id` from it. Use the whole value as a `delete-key`. I didn’t test it on the pageparts, but on the main form it works well and the delete-key isn’t used any way.
Also, the non-compound form does not have children, so the whole thing is dumped using `form_widget()`
> [AdminBundle] allow nesting non-compound forms

- src/Kunstmaan/NodeSearchBundle/Configuration/HasCustomSearchDataInterface.php
- src/Kunstmaan/NodeSearchBundle/Configuration/NodePagesConfiguration.php
- src/Kunstmaan/NodeSearchBundle/DependencyInjection/Configuration.php
- src/Kunstmaan/NodeSearchBundle/DependencyInjection/KunstmaanNodeSearchExtension.php
- src/Kunstmaan/NodeSearchBundle/Event/IndexNodeEvent.php
- src/Kunstmaan/NodeSearchBundle/Helper/IndexablePagePartsService.php
- src/Kunstmaan/NodeSearchBundle/README.md
| Fixed tickets | #411
The index mapping configuration is now in bundle config and can be tweaked by the end user easily. 
In addition, I have restored the `onIndexNode` event as well as added an interface to extend the indexed document by adding custom data.
```yaml
kunstmaan_node_search:
mapping:
average_score:
name: average_score
type: float
index: not_analyzed
tags:
name: tags
type: string
index: analyzed
```
> [NodeSearchBundle] move mapping to symfony config and allow custom data to be indexed

- src/Kunstmaan/AdminBundle/EventListener/AdminLocaleListener.php
The admin locale was lost when `UsernamePaswordToken` turned into `RememberMeToken`
> [AdminBundle] fix admin locale listener on RememberMe token

- src/Kunstmaan/AdminBundle/composer.json
- src/Kunstmaan/AdminListBundle/composer.json
- src/Kunstmaan/ArticleBundle/composer.json
- src/Kunstmaan/FormBundle/composer.json
- src/Kunstmaan/GeneratorBundle/composer.json
- src/Kunstmaan/LeadGenerationBundle/composer.json
- src/Kunstmaan/MediaBundle/composer.json
- src/Kunstmaan/MediaPagePartBundle/composer.json
- src/Kunstmaan/MenuBundle/composer.json
- src/Kunstmaan/NodeBundle/composer.json
- src/Kunstmaan/NodeSearchBundle/composer.json
- src/Kunstmaan/PagePartBundle/composer.json
- src/Kunstmaan/RedirectBundle/composer.json
- src/Kunstmaan/SeoBundle/composer.json
- src/Kunstmaan/SitemapBundle/composer.json
- src/Kunstmaan/TaggingBundle/composer.json
- src/Kunstmaan/TranslatorBundle/composer.json
- src/Kunstmaan/UserManagementBundle/composer.json
When you don't use "kunstmaan/bundles-cms" composer package but require each bundle independently you will get composer conflicts.
The reason of the conflict error is that the composer.json of each bundle has dependencies on kunstmaan bundles on version 3.0.*.
This pull request should fix this.
> Bundle specific kunstmaan dependencies always require 3.0

- src/Kunstmaan/GeneratorBundle/Generator/PagePartGenerator.php
I got errors when using the PagePart generator: 
[InvalidArgumentException]                                                                                    
The "src/Novap/SiteBundle/Entity/Pages/*.php" directory does not exist.  
These changes silenced the errors
> [GeneratorBundle] finder->in(dir) not ->in(dir/glob)

- src/Kunstmaan/AdminBundle/Resources/translations/messages.en.yml
- src/Kunstmaan/AdminBundle/Resources/ui/js/_app-sidebar-tree.js
- src/Kunstmaan/AdminBundle/Resources/views/Default/rectreeview.html.twig
- src/Kunstmaan/AdminBundle/Resources/views/Default/sidebar.html.twig
- src/Kunstmaan/NodeBundle/Controller/NodeAdminController.php
- src/Kunstmaan/NodeBundle/DependencyInjection/Configuration.php
- src/Kunstmaan/NodeBundle/DependencyInjection/KunstmaanNodeExtension.php
- src/Kunstmaan/NodeBundle/Entity/HasNodeInterface.php
- src/Kunstmaan/NodeBundle/Entity/HideFromNodeTreeInterface.php
- src/Kunstmaan/NodeBundle/Entity/NodeVersion.php
- src/Kunstmaan/NodeBundle/Helper/Menu/ActionsMenuBuilder.php
- src/Kunstmaan/NodeBundle/Helper/Menu/PageMenuAdaptor.php
- src/Kunstmaan/NodeBundle/Helper/PagesConfiguration.php
- src/Kunstmaan/NodeBundle/Resources/config/services.yml
- src/Kunstmaan/NodeBundle/Resources/doc/PagesConfiguration.md
- src/Kunstmaan/NodeBundle/Resources/views/NodeAdmin/_modals.html.twig
- src/Kunstmaan/NodeBundle/Tests/Helper/Menu/ActionsMenuBuilderTest.php
- src/Kunstmaan/NodeBundle/Twig/PagesConfigurationTwigExtension.php
- src/Kunstmaan/NodeSearchBundle/Configuration/NodePagesConfiguration.php
- src/Kunstmaan/NodeSearchBundle/Helper/SearchTypeInterface.php
* `SearchTypeInterface`
* `HideFromNodeTreeInterface`
* `HasNodeInterface::getPossibleChildTypes()`
* `PagesConfiguration` — a service responsible for providing static configuration of page types, such as `isIndexable`, `isStructureNode` or `possibleChildTypes`
* JsTree icons can now be changed using configuration (see example in documentation)
* Nodes can be moved outside of their parents in JsTree but only according to `possibleChildTypes` configuration
```yaml
kunstmaan_node:
pages:
AcmeBundle\Entity\Pages\HomePage:
name: Home page
indexable: false
icon: fa fa-home
hidden_from_tree: false
allowed_children:
- …
```
> [AdminBundle, NodeBundle] allow changing nodes parent in sidebar tree

- src/Kunstmaan/NodeBundle/Event/SlugSecurityEvent.php
- src/Kunstmaan/NodeBundle/EventListener/SlugListener.php
- src/Kunstmaan/NodeBundle/EventListener/SlugSecurityListener.php
- src/Kunstmaan/NodeBundle/Resources/config/services.yml
> [NodeBundle] Fix not checking on online status in some cases

- src/Kunstmaan/NodeSearchBundle/Configuration/NodePagesConfiguration.php
By adding a check if the page is a structure node we will be able to index it's children. This was not yet possible.
> [NodeSearchBundle] Fix indexing children of StructureNodes

- src/Kunstmaan/NodeBundle/Entity/NodeTranslation.php
When loading a page which has for example 40 versions, the performance gain is about 20ms. All nodeversions does not have to be loaded anymore, since there is already a link to the latest public nodeversion. Performance is the existence reason of that publicNodeVersion property.
> [NodeBundle] Minor performance tweak on loading the page

- src/Kunstmaan/MediaBundle/Command/CreatePdfPreviewCommand.php
Inability to process a single PDF should not stop the entire process from completing
> [MediaBundle] Don't fail outright on bad pdf

- src/Kunstmaan/NodeBundle/Helper/Menu/PageMenuAdaptor.php
This change reduces the pageload on all backend pages that are not in the page section.
On my local "prod" environment the pageload is reduced with 120ms, so media now loads in 280ms instead of 400, and settings 70ms instead of 190ms
> [NodeBundle] Do not load all nodes when you are not in the page section

- src/Kunstmaan/NodeBundle/Helper/HiddenFromNavInterface.php
- src/Kunstmaan/NodeBundle/Repository/NodeRepository.php
This is needed if you don't want to load those pages in the nodemenu (performance impact).
> [NodeBundle] Possible to create a page type which is default hidden from navigation

- src/Kunstmaan/GeneratorBundle/Command/GeneratePageCommand.php
Generating a new page when your bundle has no Page entities yields an error (maybe it's an edge use case?)
```bash
app/console kuma:generate:page
[....]
Symfony\Component\Debug\Exception\ContextErrorException]                                                                                                                                                                                  
Catchable Fatal Error: Argument 7 passed to Kunstmaan\GeneratorBundle\Generator\PageGenerator::generate() must be of the type array, null given, called in /home/blair/Documents/workspace/my-studio/vendor/kunstmaan/bundles-cms/src/Kun  
stmaan/GeneratorBundle/Command/GeneratePageCommand.php on line 80 and defined
```
PR sets the default value of $parentPages to an empty array in GeneratePageCommand.
> Fix for page generation when there are no Page entities available in a bundle.

- src/Kunstmaan/MediaBundle/Resources/views/Form/formWidgets.html.twig
Trying to load / as image when no image is available in media preview.
> [MediaBundle] Empty media preview is resulting in a request to homepage

- src/Kunstmaan/AdminBundle/EventListener/PasswordCheckListener.php
In case someone overrides authorization checker service. Same goes for `TokenStorage` and `Router`
> [AdminBundle] use `AuthorizationChecker` interface instead of a concrete implementation

- src/Kunstmaan/NodeBundle/Helper/NodeMenu.php
- src/Kunstmaan/NodeBundle/Repository/NodeRepository.php
This is a fix for:
Since 3.2.0 hidden nodes with internalnames were not returning anymore with the NodeMenu.getNodeByInternalName method.
> [NodeBundle] fix loading hidden nodes with internalnames

- UPGRADE-3.2.md
- src/Kunstmaan/NodeBundle/Controller/SlugController.php
- src/Kunstmaan/NodeBundle/Helper/NodeMenu.php
Removing the nodemenu from the rendercontext brought lots of problems in:
* everywhere you need it you first need to check if it's already created. You absolutely don't want to create it twice for one page rendering.
* you had to create it in twig (!= template logic) and you sometimes need it already in the service method where you get it from the rendercontext. So also there you needed to create it
* it's not always possible to create the nodemenu correct because you do not have all parameters (i.e. if it's a preview context or not)
My solution:
* make it default available again, but made the contructor empty and use lazy loading
For the …
> [NodeBundle] Re-add the nodemenu again and make it lazy loading

- src/Kunstmaan/NodeSearchBundle/Configuration/NodePagesConfiguration.php
I noticed that unpublished nodes are kept in the index. If I understant it correctly, a document in elasticsearch is identified by id and type, so the `indexType` needs to be fixed to contain the language for the `delete` operation to succeed.
> [NodeSearchBundle] `indexType` needs to have language appended

- src/Kunstmaan/NodeBundle/Helper/NodeMenu.php
Added 3 new helper methods to NodeMenu:
- getSiblings($node)
- getNextSibling($node)
- getPreviousSibling($node)
Useful for things like linear-style nav (in my case, Next Project/Previous Project), while retaining progressive enhancement.
Some simple template logic, once nodemenu is defined:
```twig
{% set currentNode = nodemenu.getCurrent() %}
{% set nextSibling = nodemenu.getNextSibling(currentNode.node, false) %}
{% set prevSibling = nodemenu.getPreviousSibling(currentNode.node, false) %}
{% if prevSibling %}
<a data-pager="prev"
href="{{ path('_slug', {'url': prevSibling.nodeTranslation.url }) }}">
({{ prevSibling.nodeTranslation.title }}) …
```
> [NodeBundle] Added 3 new helper methods

- src/Kunstmaan/NodeSearchBundle/Search/NodeSearcher.php
Search would fail if the query contained an unmatched quote for an instance.
> [NodeSearchBundle] fix escaping the search query

- src/Kunstmaan/AdminBundle/Resources/ui/js/_nested-form.js
- src/Kunstmaan/AdminBundle/Resources/views/Form/fields.html.twig
When adding a new PagePart that contains a collection the init function of nested-form is called multiple times which results in displaying multiple add buttons.
> [AdminBundle] fixed nested-form multiple add buttons

- composer.json
- src/Kunstmaan/AdminBundle/Helper/UserProcessor.php
The problem was:
In Symfony 2.7 the securitycontext is deprecated and logs a deprecation warning that you should use the security.token_storage which is introduced in 2.6. When logging a deprecation warning in the classloader, there was a circular dependency in the services: the logger has a UserProcessor which need the securitycontext but it was already in the classloading process of the securitycontext.
We do not change to the new security.token_storage because otherwise we cannot support symfony2.5 anymore.
> [Dependencies] Support for symfony2.7

- src/Kunstmaan/AdminBundle/EventListener/AdminLocaleListener.php
The securitycontext getToken method also provides NULL when there is no token found.
> [AdminBundle] Fix admin locale listener for >= Symfony 2.6

- src/Kunstmaan/UtilitiesBundle/Helper/Slugifier.php
- src/Kunstmaan/UtilitiesBundle/Tests/Helper/SlugifierTest.php
| BC breaks?    | yes, the slug is now an empty string if it was null
| Fixed tickets | #575 (part of)
Since we changed the slugifier to a service, the slugifier also applied to pages that were not save through the backend, the homepage for example got an 'n-a' slug after generating it...
This wil fix a lot of tests in the standard edition.
> [Tests] Do not use n-a as default slugified text

- src/Kunstmaan/GeneratorBundle/composer.json
getQuestionHelper vs. getDialogHelper in `sensio/generator-bundle/Sensio/Bundle/GeneratorBundle/Command/GeneratorCommand.php` as they renamed this function and the KunstmaanGeneratorBundle is using the newer `getQuestionHelper`.
should fix this issue:
```
root@67a783839e01:/var/www/app# composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.
Problem 1
- kunstmaan/generator-bundle 3.2.3 requires sensio/generator-bundle >=2.3.0, <2.5.0 -> satisfiable by sensio/generator-bundle[2.4.x-dev].
- kunstmaan/generator-bundle 3.2.3 requires sensio/generator-bundle >=2.3.0, <2.5.0 -> satisfiable by sensio/generator-bundle[2.4.x-dev].
- Removal request for …
```
> sensio/generator-bundle >=2.5.0

- src/Kunstmaan/FixturesBundle/Populator/Populator.php
When a value holds a Fixture, it should get the entity of the fixture. Otherwise the ORM will complain about the association.
```
Expected value of type "Kunstmaan\MediaBundle\Entity\Media" for association field "Demo\WebsiteBundle\Entity\PageParts\HomepageHeaderPagePart#$medi  
a", got "Kunstmaan\FixturesBundle\Loader\Fixture" instead.
```
Fixtures example:
```
\Kunstmaan\MediaBundle\Entity\Media:
image_homepage_header:
folder: image
originalFilename: <image('/tmp/', 1024, 500, 'cats')>
\Demo\WebsiteBundle\Entity\Pages\HomePage:
homepage:
title: 'Homepage'
parameters:
page_internal_name: homepage
set_online: true
hidden_from_nav: false
creator: <adminUser()>
translations:
nl:
title: Demo site
fr:
title: Demo site
\Demo\WebsiteBundle\Entity\PageParts\HomepageHeaderPagePart: …
```
> [FixturesBundle] When a value holds a Fixture, it should get the entity of the fixture.

- src/Kunstmaan/AdminBundle/Command/CreateUserCommand.php
Fixes
```
[Symfony\Component\Debug\Exception\ContextErrorException]  
Notice: Undefined index: Admin 
```
When running:
```
app/console kuma:role:create ROLE_SUPER_ADMIN
app/console kuma:group:create --role="ROLE_SUPER_ADMIN" "Admin"
app/console kuma:user:create user user@demo.be demo en --group="Admin"
```
This could be regression from a FOSUserbundle update.
> [AdminBundle] Fix CreateUserCommand with --group option

- src/Kunstmaan/NodeBundle/Controller/SlugController.php
- src/Kunstmaan/NodeBundle/EventListener/RenderContextListener.php
Currently the RenderContextListener falls through to the kernel.view, but the SlugController didn't do that. This applies the same principle to the SlugController so the kernel.view event is also fired.
> [NodeBundle] Let SlugController fall through to kernel.view

- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/defaultsite/Controller/DefaultController.php
The existing code will cause http://yoursite/app_dev.php to be redirected to http://yoursite/{locale} instead of http://yoursite/app_dev.php/{locale}.  This redirect should preserve the dev environment.
> [GeneratorBundle] Preserve environment in defaultController:indexAction redirect

- composer.json
- src/Kunstmaan/TranslatorBundle/Service/Translator/Translator.php
The WarmableInterface was added in Symfony 2.7 and at a lot of times in the process we don't have a database yet
> [TranslatorBundle] Don't warm up the database translations.

- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/defaultsite/Resources/views/Pages/SearchPage/pagetemplate.html.twig
- src/Kunstmaan/NodeBundle/Entity/StructureNode.php
- src/Kunstmaan/NodeSearchBundle/Configuration/NodePagesConfiguration.php
When the search index gets populated, their was no `_locale` parameter in the `RenderContext` because the command is executed from the command line. The `_locale` parameter is in the context for browser requests, so it is also needed when populating the search index.
Example use case:
When you have this peace of code in twig, it works for browser requests, but not when populating the search index.
```
<a href="{{ path('_slug', { url: nodeTranslation.url }) }}">click here</a>
```
> [SearchBundle] Add the locale to the request context when populating the search index

- src/Kunstmaan/AdminBundle/Resources/doc/FormCollectionAdditions.md
- src/Kunstmaan/AdminBundle/Resources/views/Form/fields.html.twig
| Fixed tickets | #584 (partially)
An option to the `delete-key` from nested form item HTML. This way nested form can handle many-to-many relations: simpli missing the item from the form will remove the relation, but the entity won’t be removed. 
This also partially fixes #584 — when a form is non-compound, but doesn’t have any children either, just print the whole `form_widget()`.
> [AdminBundle] nested form: don’t remove entities in many-to-many relation

- src/Kunstmaan/AdminBundle/Helper/FormWidgets/FormWidget.php
- src/Kunstmaan/PagePartBundle/Helper/FormWidgets/PagePartWidget.php
> [PagePartBundle] Make it possible to override the twig template for a custom PagePartWidget

- src/Kunstmaan/NodeBundle/Resources/views/Admin/online.html.twig
If you wanted to use the 'online template' from the nodebundle, you had to convert the 0 or 1 boolean in database to "true" or "false" strings using.
public function getValue($item, $columnName)
{
if ($columnName == 'online') {
return $item['online'] ? 'true' : 'false';
}
return parent::getValue($item, $columnName);
} 
This is not needed if you just check for the boolean type true or false in the template, and not the string type.
> [NodeBundle] Refactor online template

- docs/05-08-using-the-multi-domain-bundle.md
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/Resources/views/Layout/_header.html.twig
- src/Kunstmaan/MultiDomainBundle/Controller/SiteSwitchController.php
- src/Kunstmaan/MultiDomainBundle/Helper/DomainConfiguration.php
- src/Kunstmaan/MultiDomainBundle/Helper/HostOverrideCleanupHandler.php
- src/Kunstmaan/MultiDomainBundle/Resources/config/services.yml
The host override didn't work because the session was not started, refactored so it uses a cookie instead.
> [MultiDomainBundle] Fix host override

- docs/05-08-using-the-multi-domain-bundle.md
- src/Kunstmaan/MultiDomainBundle/Router/DomainBasedLocaleRouter.php
I removed the extra `_route_params` because if you generate a url/path with the current request  `_route_params` you can expose sensitive information. For example when you have defined different api credentials for each host. 
When you have
```
kunstmaan_multi_domain:
hosts:
main_nl:
host: domain.com
type: single_lang
default_locale: nl
locales:
- { uri_locale: 'nl', locale: 'nl' }
extra: 
api_passwordl: abc123
````
and in twig you do
```{{ url(app.request.attributes.get('_route'), app.request.attributes.get('_route_params')) }}```
visitors will see
`http://domain.com/contact?_extra[api_passwordl]=abc123`
> [MultiDomainBundle] Update the MultiDomainBundle documentation + remove extra parameters from request _route_params

- src/Kunstmaan/SeoBundle/Helper/Menu/SeoManagementMenuAdaptor.php
Logical operators should be avoided
You should use '&&' instead of 'and' and '||' instead of 'or'
> [SeoBundle] Logical operators should be avoided

- UPGRADE-3.3.md
- src/Kunstmaan/NodeBundle/Controller/SlugController.php
- src/Kunstmaan/NodeBundle/EventListener/SlugListener.php
With these changes, it is not possible anymore to use custom route loaders (`LoaderInterface`) for defining extra routes that are handled via the controller of a `Page`. You should use a custom router (`RouterInterface`) instead. This is a BC break!
Example use case:
- `/video` -> VideoOverviewPage with custom controller
- `/video/123` -> no page linked tot this url, **a custom defined route** (`/{url}/{videoid}`) that is also using the controller of the VideoOverviewPage
(as discussed with @kimausloos and @wimvds)
> [NodeBundle] Removed fallback logic for simple route loaders

- docs/05-08-using-the-multi-domain-bundle.md
- src/Kunstmaan/MultiDomainBundle/Controller/SiteSwitchController.php
- src/Kunstmaan/MultiDomainBundle/EventListener/HostOverrideListener.php
- src/Kunstmaan/MultiDomainBundle/Helper/DomainConfiguration.php
- src/Kunstmaan/MultiDomainBundle/Resources/config/services.yml
This PR fixes the override warning, so it doesn't appear multiple times (after redirects & AJAX calls).
Host overrides are restricted to the admin area from now on and the documentation was updated accordingly.
> [MultiDomainBundle] Fix host override warnings

- src/Kunstmaan/AdminBundle/Resources/ui/js/_auto-collapse-tabs.js
* When you click on a tab, the url changes (?currenttab=menu) [new feature]
* When you have the tab in the url, the tab will be activated [this was broken]
* When you submit the form, when the page refreshes, the tab will be opened again [this was broken]
> [NodeBundle] Fix page edit tab logic

- src/Kunstmaan/NodeBundle/Controller/NodeAdminController.php
This fix solve an issue when a user hasn't translated all the pages in a locale and try to reorder them.
> [NodeBundle] fix reorder method in case the node hasn't been translated

- src/Kunstmaan/MediaBundle/Form/FolderType.php
The internalName is already visible for pages (nodes). Now it's also editable for media folders.
> [MediaBundle] Show internal name field for media folders

- src/Kunstmaan/PagePartBundle/Resources/views/FormWidgets/PageTemplateWidget/widget.html.twig
- src/Kunstmaan/PagePartBundle/Resources/views/PagePartAdminTwigExtension/pagepart.html.twig
- src/Kunstmaan/PagePartBundle/Resources/views/PagePartAdminTwigExtension/widget.html.twig
This pull request changes some views in the admin so that the names of pagetemplates and pageparts are run through translations before they are shown. This allows for more clean names such as `contentpage_sidebar` to be used in the code and database, while still having a readable string in the admin.
> [PagePartBundle] Translate PageTemplate and PagePart names

- src/Kunstmaan/FixturesBundle/Parser/Property/Method.php
Currently no arguments are passed to Faker when using its providers in the FixturesBundle. Because Faker uses `__call` to handle calls to its providers, the methods are not found using reflection. The method is however callable, but was called without the parsed arguments. This PR makes sure those arguments are passed.
> [FixturesBundle] Pass arguments to Faker provider

- src/Kunstmaan/PagePartBundle/Helper/FormWidgets/PageTemplateWidget.php
- src/Kunstmaan/PagePartBundle/Helper/PageTemplateConfigurationReader.php
- src/Kunstmaan/PagePartBundle/PageTemplate/Region.php
- src/Kunstmaan/PagePartBundle/Resources/views/FormWidgets/PageTemplateWidget/widget.html.twig
.yml:
```
rows:
- regions:
-
span: 8
regions:
- { name: "main", span: 12 }
- { name: "form", span: 12 }
-
span: 12
regions:
- { name: "test", span: 4 }
- { name: "test2", span: 8 }
- { name: "sidebar", span: 4 }
```
Admin: ![screenshot 2015-08-28 14 03 59](https://cloud.githubusercontent.com/assets/2806404/9545852/d0d79708-4d8d-11e5-8e70-008e18498e54.jpg)
> [PagePartBundle] Pageparts recursive regions

- src/Kunstmaan/FixturesBundle/Populator/Populator.php
If your fixtures contain an array of related entities like this
```
\App\SiteBundle\Entity\Pages\ArticlePage:
article_{1..25}:
categories: [@cat_1, @cat_4]
...
```
You end up with following error, as the entity references in this array are not treated as entities while populatoring: `Expected value of type "Doctrine\Common\Collections\Collection|array" for association field "App\SiteBundle\Entity\Pages\ArticlePage#$categories", got "Kunstmaan\Fixtures
Bundle\Loader\Fixture" instead.
`
This pull request takes care of this, although I guess there might be some prettier way...
> [FixturesBundle] Fix for fixtures populator entity array

- src/Kunstmaan/DashboardBundle/Controller/GoogleAnalyticsController.php
- src/Kunstmaan/DashboardBundle/Resources/views/GoogleAnalytics/connect.html.twig
We don't want to allow normal admins to configure the dashboard, so we added a check to only allow super admins to configure the dashboard.
> [DashboardBundle] Only allow super admin to configure the dashboard

- src/Kunstmaan/MenuBundle/Controller/MenuAdminListController.php
- src/Kunstmaan/MenuBundle/Resources/config/services.yml
- src/Kunstmaan/MenuBundle/Service/MenuService.php
In order to create MenuItems via fixtures, the logic of creating MenuItems should be in a service class instead of the controller.
This PR removes this logic from the controller and moves it into a service. I've created a wrapper function in the controller to avoid BC breaks.
> [MenuBundle] Refactor MenuBundle to use a MenuService

- src/Kunstmaan/NodeBundle/Controller/SlugController.php
- src/Kunstmaan/NodeBundle/EventListener/RenderContextListener.php
- src/Kunstmaan/NodeBundle/EventListener/SlugSecurityListener.php
- src/Kunstmaan/NodeBundle/Resources/config/services.yml
So you don't have to write 5 twig lines or 27 php lines to get it.
See #581 why this is usefull.
> [NodeBundle] Re-add nodemenu again in the rendercontext

- src/Kunstmaan/AdminBundle/Resources/views/Form/fields.html.twig
When you try to build a form with a collection of media you will get a `array to string conversion` warning.
Forms like 'entity' or 'media' are not compound forms but are also tight to entities.
Example code to reproduce this warning:
```
$builder->add('images', 'collection', array(
'type' => 'media',
'allow_add' => true,
'allow_delete' => true,
'by_reference' => false,
'cascade_validation' => true,
'attr' => array(
'nested_form' => true,
'nested_form_min' => 1,
'nested_form_max' => 5,
)
));
```
> [AdminBundle] Warning in collection when using media as type

- src/Kunstmaan/AdminBundle/Resources/views/Default/_ckeditor_configs.html.twig
- src/Kunstmaan/AdminBundle/Resources/views/Default/_ckeditor_configs_extra.html.twig
- src/Kunstmaan/AdminBundle/Resources/views/Default/_css.html.twig
- src/Kunstmaan/AdminBundle/Resources/views/Default/_css_extra.html.twig
- src/Kunstmaan/AdminBundle/Resources/views/Default/_js_footer.html.twig
- src/Kunstmaan/AdminBundle/Resources/views/Default/_js_footer_extra.html.twig
- src/Kunstmaan/AdminBundle/Resources/views/Default/_js_header.html.twig
- src/Kunstmaan/AdminBundle/Resources/views/Default/_js_header_extra.html.twig
Now you can override the extra files which are included after the default configurations. So no need to copy paste the big configuration files if you only have to append one line.
This is a workarround the problem that parent() does not work when you override twig files in your /app folder.
> Make is easier to append javascript/css/CKConfiguration

- src/Kunstmaan/AdminBundle/Resources/views/Form/fields.html.twig
- src/Kunstmaan/RedirectBundle/AdminList/RedirectAdminListConfigurator.php
- src/Kunstmaan/RedirectBundle/Controller/RedirectAdminListController.php
- src/Kunstmaan/RedirectBundle/Entity/Redirect.php
- src/Kunstmaan/RedirectBundle/Form/RedirectAdminType.php
- src/Kunstmaan/RedirectBundle/Helper/Menu/RedirectMenuAdaptor.php
- src/Kunstmaan/RedirectBundle/Resources/config/services.yml
- src/Kunstmaan/RedirectBundle/Resources/translations/messages.en.yml
- src/Kunstmaan/RedirectBundle/Router/RedirectRouter.php
- src/Kunstmaan/RedirectBundle/Tests/AdminList/RedirectAdminListConfiguratorTest.php
- src/Kunstmaan/RedirectBundle/Tests/Entity/RedirectTest.php
- src/Kunstmaan/RedirectBundle/Tests/Form/RedirectAdminTypeTest.php
- src/Kunstmaan/RedirectBundle/Tests/Router/RedirectRouterTest.php
- src/Kunstmaan/RedirectBundle/composer.json
When you have a website that has multiple domains, it was not possible to use the same origin url and point it to a different target url for each domain. This PR solves this by allowing the administrator to choose the domain for which the redirect should work. It is also possible to choose "All domains".
When there is only a single domain configured, the domain input field will not be shown and the domain column will not be visible in the adminlist.
Eg:
domain.com/cola -> domain.com/actions/cola
domain.nl/cola -> domain.nl/acties/cola
> [RedirectBundle] Add domain field when configuring redirects

- src/Kunstmaan/TranslatorBundle/Service/Translator/ResourceCacher.php
| Bug fix?      |  no
*Some* hosting providers block out the `exec` function.
We can use Finder and the native `unlink` function to clear translation cache.
> Clear translation cache without exec but with native unlink function

- src/Kunstmaan/MenuBundle/Service/MenuService.php
- src/Kunstmaan/MenuBundle/composer.json
> [MenuBundle] use DomainConfigurationInterface instead of DomainConfiguration + depend on NodeBundle

- src/Kunstmaan/AdminListBundle/Resources/views/Default/add_or_edit.html.twig
- src/Kunstmaan/AdminListBundle/Twig/AdminListTwigExtension.php
- src/Kunstmaan/TranslatorBundle/Resources/views/Translator/addTranslation.html.twig
- src/Kunstmaan/TranslatorBundle/Resources/views/Translator/editTranslation.html.twig
This deprecates the my_router_params() twig function. Calls should be replaced by request attribute param bag variable '_route_params' which didn't exist in Symfony 2.0.
> [AdminListBundle] Deprecated twig function my_router_params()

- src/Kunstmaan/LeadGenerationBundle/Resources/views/AdminList/popup-edit.html.twig
- src/Kunstmaan/LeadGenerationBundle/Resources/views/AdminList/rules-edit.html.twig
Use the variables defined in the controller and don't rely on the merge of get parameters to the url anymore.
> [LeadGenerationBundle] Add required type parameters as hidden form field

- src/Kunstmaan/NodeBundle/Resources/config/services.yml
```
Catchable Fatal Error: Argument 2 passed to Symfony\Component\DependencyInjection\Definition::addMethodCall() must be of the type array, object given, called in /vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Loader/YamlFileLoader.php on line 253 and defined  
```
This is caused by services.yml in the NodeBundle.
> [Nodebundle] [critical] Fix services.yml error in NodeBundle

- src/Kunstmaan/NodeBundle/Entity/Node.php
- src/Kunstmaan/NodeBundle/Helper/Services/PageCreatorService.php
This will fix performance issues with sites that contain lots of nodes that were created with the page creator. You will still have to run the following query on these projects once after updating though (using a migration or by hand on the DB) : ```UPDATE kuma_nodes SET internal_name = NULL WHERE internal_name = ''```
> [NodeBundle] performance fixes

- src/Kunstmaan/GeneratorBundle/Generator/DefaultSiteGenerator.php
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/defaultsite/Resources/config/services.yml
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/defaultsite/Twig/BikesTwigExtension.php
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/defaultsite/Twig/NodeTranslationTwigExtension.php
- src/Kunstmaan/GeneratorBundle/Tests/Generator/DefaultSiteGeneratorTest.php
- src/Kunstmaan/GeneratorBundle/Tests/data/app/config/config.yml
After generation of the default site with `--demosite` option, the `get_node_trans_by_node_id` Twig function was not available.
> [GeneratorBundle] moved NodeTranslationTwigExtension to separate extension

- src/Kunstmaan/SearchBundle/Configuration/SearchConfigurationChain.php
- src/Kunstmaan/SearchBundle/Tests/DependencyInjection/Configuration/SearchConfigurationChainTest.php
> [SearchBundle] fixed typo in SearchConfigurationChain::getConfiguration

- CHANGELOG.md
- composer.json
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/searchpage/Resources/views/Pages/SearchPage/view.html.twig
- src/Kunstmaan/NodeSearchBundle/PagerFanta/Adapter/SearcherRequestAdapter.php
- src/Kunstmaan/NodeSearchBundle/PagerFanta/Adapter/SearcherRequestAdapterInterface.php
- src/Kunstmaan/NodeSearchBundle/Search/NodeSearcher.php
- src/Kunstmaan/NodeSearchBundle/Services/SearchService.php
- src/Kunstmaan/NodeSearchBundle/composer.json
- src/Kunstmaan/SearchBundle/composer.json
| Fixed tickets | #607 
Upgrade Elastica to 2.3 version
> [NodeSearch][SearchBundle] upgrade Elastica to 2.3 version

- src/Kunstmaan/AdminBundle/Resources/translations/messages.en.yml
- src/Kunstmaan/AdminBundle/Resources/ui/js/_page-editor.js
- src/Kunstmaan/AdminBundle/Resources/views/PermissionsAdminTwigExtension/widget.html.twig
When you selected a new permission to be added or an existing permission to be removed the text "undefined" appeared below the "Apply recursive" dropdown. This PR fixes that, and adds translation labels in the widget view as well.
> [AdminBundle] fix JS undefined issue & add translations in permissions widget

- src/Kunstmaan/AdminBundle/Resources/ui/scss/default-theme/components/vendors/bootstrap-components/_dropdown-menu.scss
The submenu carets were positioned right next to their respective labels instead of on the right side of the menu which made it less clear what items had submenu's. This PR fixes that issue.
> [AdminBundle] Improve submenu caret alignment

- src/Kunstmaan/AdminBundle/Resources/views/Default/_js_footer.html.twig
If I do not do this change, I get the following error in my console:
Uncaught Error: jQuery should be loaded before CKEditor jQuery adapter.
> [AdminBundle] Jquery is required before CKEditor

- src/Kunstmaan/SeoBundle/Resources/views/SeoTwigExtension/metadata.html.twig
Remove a incorrect slash so the html is valid
> [SeoBundle] Remove incorrect slash from image_src tag

- src/Kunstmaan/AdminBundle/Resources/ui/scss/default-theme/components/structures/_pp.scss
Overflow: hidden was removed before for the datepicker.
This broke the block when floated elements were inside.
Clearfix added.
> [AdminBundle] pp view block overflow clearfix fix

- src/Kunstmaan/SeoBundle/Resources/views/SeoTwigExtension/metadata.html.twig
- src/Kunstmaan/SeoBundle/Twig/SeoTwigExtension.php
Added a twig extension to validate the url and add the host.
This way, if you don't pass a valid fqdn, the function will check for a starting '/' and prepend the value passed as host.
> [SeoBundle] Improved ogUrl tag handling

- src/Kunstmaan/SeoBundle/Entity/Seo.php
- src/Kunstmaan/SeoBundle/Form/SocialType.php
- src/Kunstmaan/SeoBundle/Resources/views/Admin/Social/social.html.twig
- src/Kunstmaan/SeoBundle/Resources/views/SeoTwigExtension/metadata.html.twig
This PR adds extra fields to the SEO OG tab. The fields however are conditional. 
They only show up if the user selects "Article" in the OG Type field.
> [SeoBundle] Extra article seo meta tags

- src/Kunstmaan/AdminListBundle/Resources/views/Default/add_or_edit.html.twig
Hello, I run into a problem. If I use list with configurator where I add buttons, they are printed different in [edit page](https://sc-cdn.scaleengine.net/i/8adf431260cf2d7b36f92a06809c5f41.png) than in [items list](https://sc-cdn.scaleengine.net/i/c243c8d21fa8f5a2ac8a2be7a1af81ce.png). I want them to [look the same](https://sc-cdn.scaleengine.net/i/6f4b8dc63a8c8c585e379547ecd5aecd.png).
> [AdminListBundle] Change image button image to icon

- src/Kunstmaan/MenuBundle/Entity/BaseMenu.php
It was causing wrong entities mapping.
https://sc-cdn.scaleengine.net/i/88a67aa62f878104a1121bd12b7e9f3e.png
> [MenuBundle] Define a proper MenuItem entity class

- src/Kunstmaan/DashboardBundle/Resources/views/Dashboard/index.html.twig
Some reverse proxies have problems with ESI tags with absolute https links.
Using a relative path will solve this.
> [DashboardBundle] Fix https render_esi() dashboard problem

- src/Kunstmaan/AdminBundle/composer.json
Complete suite (KunstmaanBundlesCMS) has Symfony version requirement set to "~2.5,<2.8.0" and when installed, it runs on Symfony 2.7. But AdminBundle alone has requirement set "~2.5,<2.7" which makes it imposible install it on Symfony 2.7 project.
> [AdminBundle] Update required Symfony version in AdminBundle

- src/Kunstmaan/MediaBundle/composer.json
Synchronize required version of KnpGaufretteBundle in KunstmaanBundlesCMS and KunstmaanMediaBundle (similar problem as #772).
> [MediaBundle] Update required KnpGaufretteBundle version in MediaBundle

- src/Kunstmaan/MultiDomainBundle/Twig/MultiDomainTwigExtension.php
- src/Kunstmaan/SeoBundle/Resources/views/SeoTwigExtension/metadata.html.twig
Add a twig function to gain access to the defined extra parameters of your multi domain bundle config.
This is useful in case you need to conditionally format templates based on domain.
Also, I noticed a error in the SeoBundle, this has been fixed.
> [MultiDomainBundle] Get Extra Multi Domain data twig extension

- src/Kunstmaan/AdminBundle/Helper/Menu/SimpleMenuAdaptor.php
| Fixed tickets | - 
Currently the `SimpleMenuAdaptor` discards all entries with `null === parent`. With this change it will allow them to be placed in the main menu instead.
> [AdminBundle] Allow `SimpleMenuAdaptor` to create items in main menu

- src/Kunstmaan/MediaBundle/Helper/File/FileHandler.php
| BC breaks?    | unsure
Around ~3.2, the media bundle stopped using uniqid's for filenames, which is good, but now filenames are kept as the original, uploaded filename (user-defined), which can be bad. This PR uses the slugifier utility to ensure web-safe filenames; stripping spaces, and other non-safe characters. When uploading an image with a filename like:
```
my-Nice.imAge(full resolution) 2.5Mb.jpg
```
The current FileHandler saves the media url as
```
/uploads/media/<uniqid>/my-Nice.imAge(full resolution) 2.5Mb.jpg
```
When trying to use that as an og_image, Facebook wasn't loving life (og_image not set/found). This PR will save the media's url as:
``` …
```
> [MediaBundle] Create web safe filenames

- src/Kunstmaan/SeoBundle/Twig/SeoTwigExtension.php
This took me a minute or two: according to the Profiler, I had multiple queries happening to kuma_seo, with the exact same parameters. Turns out I was calling to {{ get_title_for(page) }} twice, and {{ render_seo_for(page) }} once; causing 3 duplicate queries. 
This isn't a true caching mechanism by any means, but a potential fix to limit it to one query per request. 
You can see this in the current layout.html.twig that the GeneratorBundle outputs, which creates 2 queries. (KunstmaanGeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/Resources/views/Layout/layout.html.twig), it calls to get_title_for and render_seo_for.
Maybe not the perfect solution, but you can now call to get_title_for 100 times with no extra queries if you really want to :)
> [SeoBundle] Idea for fix for possible multiple db-query issues

- src/Kunstmaan/MultiDomainBundle/Controller/SiteSwitchController.php
- src/Kunstmaan/MultiDomainBundle/Helper/DomainConfiguration.php
- src/Kunstmaan/MultiDomainBundle/Helper/HostOverrideCleanupHandler.php
- src/Kunstmaan/MultiDomainBundle/Tests/Helper/DomainConfigurationTest.php
- src/Kunstmaan/MultiDomainBundle/Tests/Helper/HostOverrideCleanupHandlerTest.php
I had a problem with the host override cookie was unset by Varnish because it is prefixed with underscore.
As it is a session cookie it is easy replaced by using the request session instead of an extra cookie.
> [MultiDomainBundle] Replaced host override cookie with session

- src/Kunstmaan/FixturesBundle/Builder/MenuItemBuilder.php
- src/Kunstmaan/FixturesBundle/Resources/config/services.yml
Very simple MenuItemBuilder so that MenuItems in fixtures can be easily linked to pages.
It can be used like this:
```
\Kunstmaan\MenuBundle\Entity\Menu:
menu_main:
name: main
locale: nl
\Kunstmaan\MenuBundle\Entity\MenuItem:
menu_item_home:
menu: @menu_main
parameters:
page: @homepage
```
There are no other parameters other than page. All other properties can be set through the default properties functionality of the fixtures.
> [FixturesBundle] Add MenuItemBuilder for MenuItem fixtures

- src/Kunstmaan/MenuBundle/Resources/config/services.yml
- src/Kunstmaan/MenuBundle/Resources/views/menu-item.html.twig
- src/Kunstmaan/MenuBundle/Service/RenderService.php
- src/Kunstmaan/MenuBundle/Twig/MenuTwigExtension.php
Needs some refactoring.
Added the possibility to render the menuItem with twig templates.
There are 2 options:
- set a general template by using the service parameter `kunstmaan_menu.menu.template` 
(defaults to "KunstmaanMenuBundle::menu-item.html.twig")
- set a template per menu by adding the optional template parameter in your menu twig file.
```
{{ get_menu('side', app.request.locale, {
'rootOpen': '<ul class="main-nav__list">',
'rootClose': '</ul>',
'childOpen': '<li class="main-nav__list-item">',
'childClose': '</li>',
'template': 'MyBundle:Menu:menu-item.html.twig'
})
}}
```
> [MenuBundle] Add templating possibilities for menuItems

- composer.json
As it is not compatible with v3.0
| Fixed tickets | #810
> Fixed wrong dependency for sensio/generator-bundle 

- src/Kunstmaan/GeneratorBundle/Command/GenerateBundleCommand.php
Made validateTargetDir a local function instead of depending on the sensiolabs/SensioGeneratorBundle < 2.5.x versions.
This will resolve the issue with `app/console kuma:generate:bundle` bug that prevents generating a new bundle.
> Made validateTargetDir a local function

- src/Kunstmaan/AdminListBundle/AdminList/FilterType/ORM/DateFilterType.php
| Fixed tickets | #807 
It is quite bad solution, because it solves only part of problem. The issue occurs in other Types too.
> [AdminListBundle] Add validation for invalid filter value

- src/Kunstmaan/FormBundle/Tests/Entity/FormSubmissionTest.php
- src/Kunstmaan/FormBundle/Tests/Entity/PageParts/SubmitButtonPagePartTest.php
This is a small thing but it will remove a item from the list in the insights page.
> [FormBundle - Insights] PHP code should follow PSR-1 basic coding standard

- src/Kunstmaan/AdminBundle/Resources/ui/scss/default-theme/components/blocks/_tables.scss
- src/Kunstmaan/AdminListBundle/Resources/views/AdminListTwigExtension/widget.html.twig
- src/Kunstmaan/NodeBundle/Resources/views/NodeAdmin/_modals.html.twig
| Fixed tickets | #533 
Show only the icons of the actions. On hover, the label will be displayed. 
This way, there will be less whitespace in the tables.
Before:
Now:
> [AdminBundle] Show only icons of table actions

- UPGRADE-3.4.md
- src/Kunstmaan/AdminBundle/Helper/DomainConfiguration.php
- src/Kunstmaan/AdminBundle/Helper/DomainConfigurationInterface.php
- src/Kunstmaan/MultiDomainBundle/DependencyInjection/Configuration.php
- src/Kunstmaan/MultiDomainBundle/DependencyInjection/KunstmaanMultiDomainExtension.php
- src/Kunstmaan/MultiDomainBundle/Helper/DomainConfiguration.php
Allows you to configure locale specific extra parameters.
```
kunstmaan_multi_domain:
hosts:
general:
host: domain.com
type: multi_lang
default_locale: en
locales:
- { uri_locale: 'en', locale: 'en', extra: {country: 'UK', code: 'abc'} }
- { uri_locale: 'fr', locale: 'fr', extra: {country: 'FR', code: 'xyz'} }
extra:
param: 'bla' 
```
> [MultiDomainBundle] Allows to configure/retrieve extra parameters for each domain locale

- src/Kunstmaan/MultiDomainBundle/DependencyInjection/KunstmaanMultiDomainExtension.php
Because multiple url locales can have the same backend locale.
> [MultiDomainBundle] Use url locale to link extra parameters 

- src/Kunstmaan/MediaBundle/Helper/File/FileHandler.php
Well this will be the 2nd time we have fixed this issue.
Image thumbnailing fails for uppercase extensions.
The pull request #780 of @tentwofour removed our fix #725.
You probably want to fix this also in 3.2 and 3.3.
> [MediaBundle] Fixed uppercase extension (again)

- src/Kunstmaan/AdminBundle/Helper/Menu/MenuItem.php
- src/Kunstmaan/AdminBundle/Resources/views/Default/rectreeview.html.twig
- src/Kunstmaan/NodeBundle/Helper/Menu/PageMenuAdaptor.php
| Fixed tickets | #528 
The StructureNode now has a folder icon in the pages tree:
> [NodeBundle] StructureNode now have a folder icon in the pages tree

- src/Kunstmaan/AdminBundle/Helper/Menu/MenuItem.php
This fixes a bug introduced in this commit: https://github.com/Kunstmaan/KunstmaanBundlesCMS/commit/7e60d159e029b7055f07088e975fc2493e705370. When the folder is not explicitly set on the MenuItem, the property will not be present. The is the case on the Settings page in the admin, which causes an error.
> [AdminBundle] Make sure folder is always a property

- src/Kunstmaan/NodeBundle/Resources/views/NodeAdmin/edit.html.twig
- src/Kunstmaan/NodeBundle/Twig/NodeTwigExtension.php
Hide page status & indicator on structureNode pages
> [NodeBundle] Hide page status indicator if it's a StructureNode page

- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/defaultsite/Resources/views/Layout/submenu.html.twig
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/defaultsite/Resources/views/PageParts/PageBannerPagePart/view.html.twig
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/Resources/ui/scss/admin-style.scss
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/Resources/ui/scss/components/structures/_header-visual.scss
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/Resources/ui/scss/general/_base.scss
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/gulp/gulpfile.js
- src/Kunstmaan/NodeBundle/Resources/views/NodeAdmin/edit.html.twig
- src/Kunstmaan/NodeBundle/Twig/NodeTwigExtension.php
> [GeneratorBundle] Add FE styling to pageparts in CMS

- src/Kunstmaan/AdminBundle/Resources/ui/js/_colorpicker.js
- src/Kunstmaan/AdminBundle/Resources/ui/js/_datepicker.js
- src/Kunstmaan/AdminBundle/Resources/ui/js/_nested-form.js
- src/Kunstmaan/AdminBundle/Resources/ui/js/_pagepart-editor.js
- src/Kunstmaan/AdminBundle/Resources/ui/js/_rich-editor.js
- src/Kunstmaan/AdminBundle/Resources/ui/js/_tooltip.js
- src/Kunstmaan/AdminBundle/Resources/views/Form/fields.html.twig
Each time a new pagepart was added to a page, several javascript modules got reinitialised, even when they had nothing to do with this pagepart.
This feature makes it possible to just reinitialise one or more specific modules. This way, it is also possible to reinitialise modules which aren't default in the bundles.
This is an example of how you can trigger a reinitialise. Give the element a 'js-reinit' class and in the data attribute 'data-reinit-js' you can set the modules that need to be reinitialised for this pagepart.
It is important that the module has a public reInit function, because this is the function that will get triggered when the …
> [AdminBundle] Dynamic reinit modules when a pagepart is added

- UPGRADE-3.5.md
- src/Kunstmaan/NodeBundle/Resources/config/services.yml
Continuation of #779.
Remove `gedmo.listener.tree` definition from `NodeBundle`.
> [NodeBundle] Remove gedmo.listener.tree definition

- src/Kunstmaan/AdminBundle/Resources/ui/js/_nested-form.js
| Fixed tickets | #857, #823
The datepicker plugin was not being initialized on nested forms that were dynamically added to a page. This fix calls the datepicker's reInit method to fix this.
> [AdminBundle] Added datepicker reinit for nested forms

- src/Kunstmaan/AdminBundle/Resources/views/Form/fields.html.twig
The ckeditor was not being initialized when a pagepart with type 'wysiwyg' was added to the page. This fix calls the ckeditor's reInit method to fix this.
Based on #849
> [AdminBundle] Add reinit-js attribute on the wysiwyg textarea

- src/Kunstmaan/MediaBundle/Controller/ChooserController.php
When opening the media chooser with an empty `type` GET parameter, the type parameter from the previous request was used. So if the previous request had `type = image`, and the next request did not specify the type, only images could be selected.
> [MediaBundle] Fix media chooser type selector when no type was passed

- src/Kunstmaan/AdminListBundle/Resources/views/AdminListTwigExtension/widget.html.twig
Not the best possible fix (double loop), but atleast it solves the issue for now.
| Fixed tickets | https://github.com/Kunstmaan/KunstmaanBundlesCMS/issues/870
> [AdminListBundle] Fix for adding bulk actions that prevent the delete button from working on the first item

- src/Kunstmaan/MediaBundle/Form/AbstractRemoteType.php
- src/Kunstmaan/MediaBundle/Form/File/FileType.php
- src/Kunstmaan/MediaBundle/Form/FolderType.php
- src/Kunstmaan/MenuBundle/Form/MenuItemAdminType.php
> [MediaBundle, MediaBundle] Fix: the "property" option is deprecated since version 2.7 and will be removed in 3.0. Use "choice_label" instead

- src/Kunstmaan/AdminBundle/Helper/FormWidgets/Tabs/TabPane.php
Symfony 2.7 does not know the new symfony 2.8 form syntax. Revert it to correct 2.7 syntax.
> [AdminBundle]: symfony 2.7 syntax

- src/Kunstmaan/AdminBundle/Form/UserType.php
- src/Kunstmaan/AdminBundle/Resources/views/Form/fields.html.twig
- src/Kunstmaan/FormBundle/Entity/PageParts/ChoicePagePart.php
- src/Kunstmaan/FormBundle/Form/ChoiceFormSubmissionType.php
- src/Kunstmaan/FormBundle/Form/ChoicePagePartAdminType.php
- src/Kunstmaan/FormBundle/Resources/doc/FormBundle.md
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/defaultsite/Form/BikeAdminType.php
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/defaultsite/Form/PageParts/ServicePagePartAdminType.php
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/Resources/views/Form/fields.html.twig
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/pagepart/Form/PageParts/ButtonPagePart/ButtonPagePartAdminType.php
- src/Kunstmaan/MenuBundle/Form/MenuItemAdminType.php
- src/Kunstmaan/NodeBundle/Form/NodeMenuTabTranslationAdminType.php
> [AllBundles] Deprecated "empty_value" option when using choice as form type. Replace it with "placeholder"

- src/Kunstmaan/MenuBundle/Entity/BaseMenuItem.php
When validating entities, we can't use the addViolationAt method but have to change it to buildViolation
> [MenuBundle] Deprecated addViolationAt

- src/Kunstmaan/LanguageChooserBundle/Controller/LanguageChooserController.php
- src/Kunstmaan/NodeBundle/Controller/WidgetsController.php
- src/Kunstmaan/TranslatorBundle/Controller/TranslatorController.php
- src/Kunstmaan/VotingBundle/Controller/VotingController.php
Calling $this->getRequest() in a controller is deprecated. We have to inject the $request variable in the controller action.
> [TranslatorBundle, VotingBundle] Deprecated request call

- src/Kunstmaan/AdminBundle/Form/UserType.php
The "array" type hint was removed from the OptionsResolverInterface methods setRequired(), setAllowedValues(), addAllowedValues(), setAllowedTypes() and addAllowedTypes()
> [AdminBundle] The "array" type hint was removed from the OptionsResolverInterface

- src/Kunstmaan/MenuBundle/Repository/MenuItemRepository.php
> [MenuBundle] Do not require online NodeTranslation for url_link MenuItems

- src/Kunstmaan/AdminBundle/Resources/ui/js/_pagepart-editor.js
- src/Kunstmaan/PagePartBundle/Resources/views/FormWidgets/PageTemplateWidget/widget.html.twig
> [PagePartBundle] Edited max min all pp to max min region

- UPGRADE-3.5.md
- src/Kunstmaan/MediaBundle/DependencyInjection/KunstmaanMediaExtension.php
- src/Kunstmaan/MediaBundle/Helper/Imagine/BackgroundFilterLoader.php
- src/Kunstmaan/MediaBundle/Helper/Imagine/CacheManager.php
- src/Kunstmaan/MediaBundle/Helper/Imagine/ImagineController.php
- src/Kunstmaan/MediaBundle/Helper/Imagine/WebPathResolver.php
- src/Kunstmaan/MediaBundle/Resources/config/imagine.xml
- src/Kunstmaan/MediaBundle/Resources/config/imagine_filters.yml
- src/Kunstmaan/MediaBundle/Resources/config/services.yml
- src/Kunstmaan/MediaBundle/composer.json
Should be merged together with https://github.com/Kunstmaan/KunstmaanBundlesStandardEdition/pull/182
| Fixed tickets | #914 #228
The possibility to change the format of the cached images will be implemented in version 2.0 of the LiipImagineBundle. In the meanwhile we can upgrade by extending some logic.
> [MediaBundle] Update LiipImagineBundle to v1.4.3 with workaround

- src/Kunstmaan/AdminBundle/Resources/ui/js/_pagepart-editor.js
- src/Kunstmaan/AdminBundle/Resources/ui/js/_rich-editor.js
- src/Kunstmaan/AdminBundle/Resources/views/Form/fields.html.twig
| Fixed tickets | #865 #216
Nested forms can now also be sorted by using the up and down arrow.
Also a fix for the rich editor. When moving a element around in the DOM by sorting it, the ckeditor gets disabled and the content is removed. This is a known bug in Ckeditor. I have fixed it by destroying all the rich editors and reinitialise them when moving them around.
> [AdminBundle] Added up/down arrows on nested forms, fix rich editor when moving elements in DOM

- src/Kunstmaan/AdminBundle/Controller/DefaultController.php
- src/Kunstmaan/LeadGenerationBundle/Controller/AbstractNewsletterController.php
- src/Kunstmaan/MediaBundle/Controller/ChooserController.php
- src/Kunstmaan/MediaBundle/Controller/FolderController.php
- src/Kunstmaan/MediaBundle/Form/FolderType.php
- src/Kunstmaan/SeoBundle/Controller/Admin/SettingsController.php
- src/Kunstmaan/TranslatorBundle/Controller/TranslatorController.php
- src/Kunstmaan/TranslatorBundle/Form/TranslationAdminType.php
- src/Kunstmaan/UserManagementBundle/Controller/GroupsController.php
- src/Kunstmaan/UserManagementBundle/Controller/RolesController.php
Passing type instances to Form::add(), FormBuilder::add() and the FormFactory::create*() methods is deprecated
> [AllBundles]: Change deprecated form functions

- src/Kunstmaan/AdminBundle/Helper/FormWidgets/Tabs/TabPane.php
- src/Kunstmaan/DashboardBundle/Controller/GoogleAnalyticsAJAXController.php
- src/Kunstmaan/DashboardBundle/Entity/AnalyticsConfig.php
- src/Kunstmaan/FormBundle/Entity/PageParts/CheckboxPagePart.php
- src/Kunstmaan/FormBundle/Entity/PageParts/ChoicePagePart.php
- src/Kunstmaan/FormBundle/Entity/PageParts/EmailPagePart.php
- src/Kunstmaan/FormBundle/Entity/PageParts/FileUploadPagePart.php
- src/Kunstmaan/FormBundle/Entity/PageParts/MultiLineTextPagePart.php
- src/Kunstmaan/FormBundle/Entity/PageParts/SingleLineTextPagePart.php
- src/Kunstmaan/GeneratorBundle/Command/KunstmaanGenerateCommand.php
- src/Kunstmaan/MediaBundle/Form/FolderType.php
- src/Kunstmaan/MediaBundle/Helper/RemoteVideo/RemoteVideoHandler.php
- src/Kunstmaan/NodeSearchBundle/Services/SearchService.php
- src/Kunstmaan/TranslatorBundle/Resources/config/services.yml
- src/Kunstmaan/TranslatorBundle/Service/Command/Importer/Importer.php
> [AllBundles] Fixes for SensiolabsInsights

- src/Kunstmaan/AdminBundle/Helper/FormWidgets/Tabs/TabPane.php
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/defaultsite/Form/BikeAdminType.php
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/defaultsite/Form/PageParts/ServicePagePartAdminType.php
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/pagepart/Form/PageParts/ButtonPagePart/ButtonPagePartAdminType.php
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/pagepart/Form/PageParts/HeaderPagePart/HeaderPagePartAdminType.php
- src/Kunstmaan/LanguageChooserBundle/Router/LanguageChooserRouter.php
- src/Kunstmaan/LeadGenerationBundle/Form/Rule/LocaleBlackListAdminType.php
- src/Kunstmaan/LeadGenerationBundle/Form/Rule/LocaleWhiteListAdminType.php
- src/Kunstmaan/MediaBundle/Form/AbstractRemoteType.php
- src/Kunstmaan/MediaBundle/Form/FolderType.php
- src/Kunstmaan/MediaBundle/Form/RemoteAudio/RemoteAudioType.php
- src/Kunstmaan/MediaBundle/Form/RemoteSlide/RemoteSlideType.php
- src/Kunstmaan/MediaBundle/Form/RemoteVideo/RemoteVideoType.php
- src/Kunstmaan/MenuBundle/Form/MenuItemAdminType.php
- src/Kunstmaan/NodeBundle/Form/NodeMenuTabTranslationAdminType.php
- src/Kunstmaan/PagePartBundle/Form/HeaderPagePartAdminType.php
- src/Kunstmaan/RedirectBundle/Form/RedirectAdminType.php
- src/Kunstmaan/SeoBundle/Form/SeoType.php
- src/Kunstmaan/SeoBundle/Form/SocialType.php
- src/Kunstmaan/TaggingBundle/Form/TagsAdminType.php
- src/Kunstmaan/TranslatorBundle/Controller/TranslatorController.php
- src/Kunstmaan/TranslatorBundle/Form/TranslationAdminType.php
- Change absolute url parameter from boolean to constant
- Change form types to fully qualified name
- Add choices_as_values to forms and switch some choices keys with array values
> [AllBundles] Dep#small issues

- src/Kunstmaan/FixturesBundle/Resources/config/services.yml
Malformed inline YAML string ('@doctrine.orm.entity_manager) at line 21 (near "- '@doctrine.orm.entity_manager").
> [FixturesBundle] Fix missing singe quote in yaml config

- src/Kunstmaan/FormBundle/Resources/views/SubmitButtonPagePart/view-admin.html.twig
When this pagepart was beeing rendered in the admin, it was actually clickable and would submit the page ...  this PR disables the button in the admin view
> [FormBundle] fix btn pagepart dont submit in admin

- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/defaultsite/Resources/views/Error/error.html.twig
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/Resources/views/Error/layout.html.twig
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/Resources/views/Layout/_webfonts.html.twig
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/Resources/views/Layout/layout.html.twig
> [GeneratorBundle] stripped layout for error pages

- src/Kunstmaan/AdminListBundle/Controller/AdminListController.php
- src/Kunstmaan/AdminListBundle/Event/AdminListEvent.php
- src/Kunstmaan/AdminListBundle/Event/AdminListEvents.php
> [AdminListBundle] Add events to AdminListController

- src/Kunstmaan/FixturesBundle/Builder/MediaBuilder.php
This feature allows you to use the internal name of a Folder as reference for a Media item location.
> [FixturesBundle] Set Media folder name by internal name in fixtures

- src/Kunstmaan/NodeBundle/Controller/SlugController.php
Only use `$request->attributes` to get `NodeTranslation`, since user provided value (via GET or POST) will break the site.
> [NodeBundle] only use `$request->attributes` to get `NodeTranslation`

- src/Kunstmaan/NodeBundle/AdminList/NodeAdminListConfigurator.php
- src/Kunstmaan/NodeBundle/Controller/NodeAdminController.php
- src/Kunstmaan/NodeBundle/Helper/Menu/PageMenuAdaptor.php
Does this count as a new feature maybe even a bc break ?
It can give some unexpected behaviour, when you update to this code, and previously had a page wich you only viewed and edited in the admin, but had not set any view permissions on, for any role,   this page will no longer be visible in your admin .... as you would now require the view permission to be able to see it in the admin.
| New feature?  | no?
| BC breaks?    | no?
| Fixed tickets | https://github.com/Kunstmaan/KunstmaanBundlesCMS/issues/705
> [NodeBundle] View permission on node in adminlist

- src/Kunstmaan/AdminBundle/Resources/views/ChangePassword/changePassword.html.twig
- src/Kunstmaan/AdminBundle/Resources/views/Resetting/checkEmail.html.twig
- src/Kunstmaan/AdminBundle/Resources/views/Resetting/passwordAlreadyRequested.html.twig
- src/Kunstmaan/AdminBundle/Resources/views/Security/login.html.twig
| Fixed tickets |  
The overriding of resources only works when you refer to resources with the @FOSUserBundle/Resources/config/routing/security.xml method. If you refer to resources without using the @BundleName shortcut, they can't be overridden in this way.
> [AdminBundle]: change fosuser template extends

- src/Kunstmaan/MenuBundle/Resources/config/services.yml
- src/Kunstmaan/MenuBundle/Service/MenuService.php
| Fixed tickets | https://github.com/Kunstmaan/KunstmaanBundlesCMS/issues/998
> [MenuBundle] Use kunstmaan_menu.entity.menu.class param instead of harcoded class

- src/Kunstmaan/FormBundle/UPGRADE-3.5.1.md
- src/Kunstmaan/MediaBundle/Resources/views/Chooser/chooserShowFolder.html.twig
- src/Kunstmaan/MediaBundle/Resources/views/Form/formWidgets.html.twig
> [MediaBundle]: imageurlretina not defined

- .github/CONTRIBUTING.md
- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.md
Add the default github templates. (pull request template and issue template)
Move all github templates (including contributing guidelines) to a .github folder.
> add github templates, move templates to .github folder

- src/Kunstmaan/SearchBundle/Provider/ElasticaProvider.php
To avoid BC breaks the username and password options are optional.
It's easy to add by overruling the default elastic search provider service.
```
kunstmaan_search.search_provider.elastica:
class: '%kunstmaan_search.search_provider.elastica.class%'
calls:
- [ addNode, ['%kunstmaan_search.hostname%', '%kunstmaan_search.port%', '%kunstmaan_search.username%', '%kunstmaan_search.password%'] ]
tags:
- { name: kunstmaan_search.search_provider, alias: Elastica }
```
Password and username can be added as parameters.
> [SearchBundle] Add basic auth support for Elasticsearch with shield plugin

- src/Kunstmaan/AdminBundle/Helper/Security/Acl/Permission/MaskBuilder.php
- src/Kunstmaan/AdminBundle/Helper/Security/Acl/Permission/PermissionMap.php
- src/Kunstmaan/AdminBundle/Helper/Security/Acl/Voter/AclVoter.php
- src/Kunstmaan/AdminBundle/Resources/config/services.yml
When upgrading to symfony 3, the custom acl permission map does not get called anymore. Therefore our permissions like Publish and Unpublish don't work anymore.
By adding a AclVoter we can provide our own permission map as an extension. As of symfony 3 there is also now the class AbstractMaskBuilder and MaskBuilderRetrievalInterface. We can remove our own methods and just extend these classes.
> [AdminBundle]: add custom AclVoter

- src/Kunstmaan/NodeSearchBundle/Controller/AbstractSearchPageController.php
- src/Kunstmaan/NodeSearchBundle/Services/SearchService.php
| BC breaks?    |  no
Deprecated the wrong syntax getter and setter.
> Fix typo in SearchBundle (RenderContect -> RenderContext)

- src/Kunstmaan/NodeBundle/Controller/SlugController.php
- src/Kunstmaan/NodeBundle/EventListener/RenderContextListener.php
As of version https://github.com/sensiolabs/SensioFrameworkExtraBundle/releases/tag/v3.0.13 of the SensioFrameworkExtraBundle, the TemplateListener has been changed.
Normally we could do the following where $view is the name of your twig template file.
$request->attributes->set('_template', $view);
In the latest version we have to provide a template object. Therefore I added:
$template = new Template(array());
$template->setTemplate($view);
$request->attributes->set('_template', $template);
> [NodeBundle]: rewrite implementation for templatelistener

- src/Kunstmaan/AdminBundle/Resources/ui/scss/default-theme/components/forms/_form-control.scss
- src/Kunstmaan/NodeBundle/Resources/views/Form/formWidgets.html.twig
| Fixed tickets | Form info text not styled correctly #257
> [AdminBundle]update styling info text

- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/Helper/Menu/MenuAdaptor.php
> [GeneratorBundle]: update menuadaptor to correct syntax

- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/Resources/views/Error/layout.html.twig
Dries Beerten deleted the `_js_header.html.twig` file in `1f099dd8e40750f290982b8ae7fd3ca575e6a59b` commit, but didn't remove this file from `Error/layout` only `Layout/layout`.
> [GeneratorBundle]: Upgrade error layout skeleton: Remove deleted js twig

- docs/05-01-going-single-language.md
> [Documentation] Single language documentation fix

- docs/05-12-using-the-config-bundle.md
- src/Kunstmaan/ConfigBundle/Controller/ConfigController.php
- src/Kunstmaan/ConfigBundle/DependencyInjection/Compiler/KunstmaanConfigConfigurationPass.php
- src/Kunstmaan/ConfigBundle/DependencyInjection/Configuration.php
- src/Kunstmaan/ConfigBundle/DependencyInjection/KunstmaanConfigExtension.php
- src/Kunstmaan/ConfigBundle/Entity/AbstractConfig.php
- src/Kunstmaan/ConfigBundle/Entity/ConfigurationInterface.php
- src/Kunstmaan/ConfigBundle/Helper/Menu/ConfigMenuAdaptor.php
- src/Kunstmaan/ConfigBundle/KunstmaanConfigBundle.php
- src/Kunstmaan/ConfigBundle/LICENSE
- src/Kunstmaan/ConfigBundle/README.md
- src/Kunstmaan/ConfigBundle/Resources/config/routing.yml
- src/Kunstmaan/ConfigBundle/Resources/config/services.yml
- src/Kunstmaan/ConfigBundle/Resources/doc/ConfigBundle.md
- src/Kunstmaan/ConfigBundle/Resources/views/Settings/configSettings.html.twig
- src/Kunstmaan/ConfigBundle/Twig/ConfigTwigExtension.php
| New feature?  | yes|
BC breaks?    | no
This bundle allows you to create a entity that extends the AbstractConfig class.
By doing this you can create a settings form with some custom configuration variables.
> [ConfigBundle]: add new configuration bundle

- src/Kunstmaan/RedirectBundle/Resources/config/services.yml
Currently the RedirectBundle add/edit is not working because the form type is not receiving its argument.
> [RedirectBundle] Redirect bugfix

- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/Resources/views/Layout/layout.html.twig
The original version ignore the user created content! Eg: the user owner create a text page part with the following content:
```
<strong>Strong</strong> <u>underline</u> <em>other text</em>
```
The full page `{% spaceless %}` causes wrong "spaceless" output:
```
Strongunderlineother text
```
Other problem from twig documentation ( http://twig.sensiolabs.org/doc/tags/spaceless.html ):
> If you want to create a tag that actually removes all extra whitespace in an HTML string, be warned that this is not as easy as it seems to be (think of textarea or pre tags for instance). Using a third-party library like Tidy is probably a better idea.
The full …
> [GeneratorBundle] Spaceless fix

- src/Kunstmaan/AdminBundle/Resources/views/Default/_ckeditor_configs.html.twig
- src/Kunstmaan/AdminBundle/Resources/views/Default/_css.html.twig
- src/Kunstmaan/AdminBundle/Resources/views/Default/_js_footer.html.twig
- src/Kunstmaan/AdminBundle/Resources/views/Default/_js_header.html.twig
- src/Kunstmaan/PagePartBundle/Resources/views/PagePartAdminTwigExtension/widget.html.twig
| Fixed tickets | #683
The overriding of resources only works when you refer to resources with the @KunstmaanAdminBundle/Resources/views/Default/_js_header_extra.html.twig method. If you refer to resources without using the @BundleName shortcut, they can't be overridden in this way.
> [AdminBundle] Change admin template extends

- src/Kunstmaan/MediaBundle/Helper/Imagine/CacheManager.php
The assets version from app/config/config.yml will also be append to image urls. The extension will then be jpg?v1 which won't work for the cache resolver.
> [MediaBundle] Fixed image cache path

- src/Kunstmaan/FormBundle/Resources/views/CheckboxPagePart/view.html.twig
- src/Kunstmaan/FormBundle/Resources/views/ChoicePagePart/view.html.twig
- src/Kunstmaan/FormBundle/Resources/views/EmailPagePart/view.html.twig
- src/Kunstmaan/FormBundle/Resources/views/FileUploadPagePart/view.html.twig
- src/Kunstmaan/FormBundle/Resources/views/MultiLineTextPagePart/view.html.twig
- src/Kunstmaan/FormBundle/Resources/views/SingleLineTextPagePart/view.html.twig
In symfony 3 the method bound is deprecated, we need to replace it with the submitted function.
> [FormBundle]: change bound to submitted

- src/Kunstmaan/MediaBundle/Resources/views/Folder/show.html.twig
> [MediaBundle] Added delete confirmation modal when deleting images from media

- src/Kunstmaan/AdminBundle/Resources/ui/js/_app-sidebar-search-focus.js
- src/Kunstmaan/AdminBundle/Resources/ui/js/app.js
- src/Kunstmaan/AdminBundle/Resources/views/Default/_js_footer.html.twig
| Deprecations? | |no
This is done by the added js module. When search icon in sidebar is clicked, focus on input in the sidebar search is set on
> [AdminBundle] Added focus on sidebar search input when sidebar search is made visible

- src/Kunstmaan/AdminListBundle/Controller/AdminListController.php
When submitting a form at an admin list, form submit should be replaced by handlerequest.
> [AdminListBundle]: form submit to form handlerequest

- src/Kunstmaan/AdminBundle/Helper/Security/OAuth/OAuthUserCreator.php
[AdminBundle] check if instanceof $this->userClass instead of User
> [AdminBundle] Instanceof check always fails with a custom user class in oauthusercreator

- src/Kunstmaan/AdminBundle/Resources/views/Modules/index.html.twig
Modules page availables from the breadcrumb, but there is nothing now. This fix enables the sidebar menu.
> Load modules in sidebar

- src/Kunstmaan/UserManagementBundle/Controller/UsersController.php
| BC breaks?    | no 
| Fixed tickets | ~
Fixes
> The form's view data is expected to be an instance of class Kunstmaan\AdminBundle\Entity\User, but is an instance of class **Company\Entity\User**. You can avoid this error by setting the "data_class" option to null or by adding a view transformer that transforms an instance of class **Company\Entity\User** to an instance of Kunstmaan\AdminBundle\Entity\User.
at `/admin/settings/users/add` and  #`/admin/settings/users/xxx/edit`
as we configured `fos.user_class` in `config.yml`
> [UserManagementBundle] workaround for custom user entity class

- docs/03-01-system-requirements.md
The Kunstmaan is not compatible now with Elasticsearch 2.x .
> Documentation fix (Elasticsearch version)

- src/Kunstmaan/AdminBundle/Controller/DefaultController.php
- src/Kunstmaan/AdminBundle/EventListener/PasswordCheckListener.php
- src/Kunstmaan/AdminBundle/FlashMessages/FlashTypes.php
- src/Kunstmaan/AdminBundle/Resources/config/services.yml
- src/Kunstmaan/AdminBundle/Resources/translations/messages.en.yml
- src/Kunstmaan/AdminBundle/Resources/views/Default/flashmessages.html.twig
- src/Kunstmaan/AdminBundle/Security/OAuthAuthenticator.php
- src/Kunstmaan/DashboardBundle/Controller/GoogleAnalyticsAJAXController.php
- src/Kunstmaan/MediaBundle/Controller/FolderController.php
- src/Kunstmaan/MediaBundle/Controller/MediaController.php
- src/Kunstmaan/MultiDomainBundle/EventListener/HostOverrideListener.php
- src/Kunstmaan/MultiDomainBundle/Resources/config/services.yml
- src/Kunstmaan/MultiDomainBundle/Tests/EventListener/HostOverrideListenerTest.php
- src/Kunstmaan/NodeBundle/Controller/NodeAdminController.php
- src/Kunstmaan/NodeBundle/EventListener/NodeTranslationListener.php
- src/Kunstmaan/NodeBundle/Resources/translations/messages.en.yml
- src/Kunstmaan/NodeBundle/Resources/views/NodeAdmin/_modals.html.twig
- src/Kunstmaan/SeoBundle/Controller/Admin/SettingsController.php
- src/Kunstmaan/TranslatorBundle/Controller/TranslatorCommandController.php
- src/Kunstmaan/TranslatorBundle/Controller/TranslatorController.php
- src/Kunstmaan/TranslatorBundle/Resources/translations/messages.en.yml
- src/Kunstmaan/TranslatorBundle/Resources/views/Modals/_modals.html.twig
- src/Kunstmaan/UserManagementBundle/Controller/RolesController.php
- src/Kunstmaan/UserManagementBundle/Controller/UsersController.php
- src/Kunstmaan/UserManagementBundle/Resources/translations/messages.en.yml
Translate flash messages and add the `FlashTypes` to AdminBundle to prevent using invalid type (Eg: `notice`, there isn't `alarm-notice` class to format message)
> [Global] Add flash and modal translations

- src/Kunstmaan/GeneratorBundle/DataFixtures/ORM/GroupFixtures.php
- src/Kunstmaan/GeneratorBundle/DataFixtures/ORM/RoleFixtures.php
- src/Kunstmaan/GeneratorBundle/DataFixtures/ORM/UserFixtures.php
With this people can reference the built-in fixtures in their own custom fixtures without surprises. I replaced all reference strings with constanst.
> [GeneratorBundle] use constants for fixture references

- src/Kunstmaan/AdminBundle/Resources/ui/js/_pagepart-editor.js
> [AdminBundle] Prevent duplicate reinits in same pagepart (reorder)

- src/Kunstmaan/UserManagementBundle/Resources/views/Users/edit.html.twig
| New feature?  | no|
| BC breaks?    | no|
| Deprecations? | no|
| Fixed tickets | #1141|
Had to figure this one out :) the problem is we have 2 instances of `FormView`, one assigned by default to the template (https://github.com/Kunstmaan/KunstmaanBundlesCMS/blob/master/src/Kunstmaan/UserManagementBundle/Controller/UsersController.php#L197) the other one is generated from `TabPane::getFormView` when needed. Both track their own "am i rendered" state.
So we have to ignore one based on `tabPane` being set yes/no, as done with rendering the form itself;
https://github.com/Kunstmaan/KunstmaanBundlesCMS/blob/master/src/Kunstmaan/UserManagementBundle/Resources/views/Users/edit.html.twig#L49
Your welcome :) not sure this is also …
> [UserManagementBundle] User form rendered twice when using tabpanes

- src/Kunstmaan/AdminBundle/EventListener/AdminLocaleListener.php
When logging in with the google sign in, we do not have a UsernamePassword token anymore. The check for which token the user has is not needed anymore.
> [AdminBundle]: remove check for user token

- src/Kunstmaan/ArticleBundle/AdminList/AbstractArticlePageAdminListConfigurator.php
- src/Kunstmaan/ArticleBundle/Resources/translations/messages.en.yml
- src/Kunstmaan/ArticleBundle/Resources/views/AbstractArticlePageAdminList/list.html.twig
Added ability to select which overview page to add an article page to when there are multiple overview pages. Falls back to single button when there is only one overview page.
A dropdown list is shown with the page titles of the overview pages. When clicked, a modal shows.
The title in the modal that is shown indicates in which overview page the item is being added.
- Added several translations, some were not translated yet. (eg: Add, Cancel, warning modal, ..)
- Added a getEntityClassName to the AbstractArticlePageAdminListConfigurator in order to dynamically determine the type. [This was fixed in the …
> [ArticleBundle] Added ability to select which overview page to add an article page to

- src/Kunstmaan/AdminBundle/Helper/Security/OAuth/OAuthUserCreator.php
- src/Kunstmaan/AdminBundle/Helper/Security/OAuth/OAuthUserCreatorInterface.php
- src/Kunstmaan/AdminBundle/Helper/Security/OAuth/OAuthUserFinder.php
- src/Kunstmaan/AdminBundle/Helper/Security/OAuth/OAuthUserFinderInterface.php
- src/Kunstmaan/AdminBundle/Resources/config/services.yml
- src/Kunstmaan/AdminBundle/Security/OAuthAuthenticator.php
| Fixed tickets | #1144 
When someone signs in for the first time using google sign in, his user should be searched based on
email or username.
> [AdminBundle] OAuthUserCreator Should query on username and email

- src/Kunstmaan/AdminBundle/Command/UpdateAclCommand.php
**Description**:
With this command you can easily set permissions for a role on every existing node.
**Scenario 1 (new role)**:
After adding a new role in Kunstmaan, the role has no permissions on existing nodes.
The user wants to add "view" and "edit" permission for that user for every node.
**Scenario 2 (existing role)**:
When a role needs to have "publish" and "unpublish" permissions for every existing node.
> [AdminBundle] Command to update all nodes with given permission(s) for a desired role.

- src/Kunstmaan/AdminBundle/EventListener/AdminLocaleListener.php
I extended the admin/preview check. The check to see if the url contains /admin/preview was not working if you have a preview route like /admin/project/preview
> [AdminBundle] fix regex to check if admin preview

- src/Kunstmaan/UserManagementBundle/Controller/UsersController.php
- src/Kunstmaan/UserManagementBundle/Event/UserEvents.php
Also added an check which checks of the user is found
> [UserManagementBundle] Added event listeners for user management

- src/Kunstmaan/NodeSearchBundle/DependencyInjection/Configuration.php
- src/Kunstmaan/NodeSearchBundle/DependencyInjection/KunstmaanNodeSearchExtension.php
- src/Kunstmaan/NodeSearchBundle/Resources/config/services.yml
- src/Kunstmaan/NodeSearchBundle/Search/NodeSearcher.php
While we search with "állam" (= state) then get back the title "vállalat" ( = company), because find "álla" in the "vállalat". This is wrong, and we don't want to allow it in some project.
> [NodeSearchBundle] Change title search + add configuration

- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/Resources/views/Form/fields.html.twig
Form label class (form-control-label) is only rendering if required is true
> [GeneratorBundle] Fixed rendering form label class

- src/Kunstmaan/NodeBundle/Form/NodeChoiceType.php
- src/Kunstmaan/NodeBundle/Resources/config/services.yml
I have added a new form type to use instead of the EntityType when working with node translations.
When you want to have a entity fields that has a relationship to a node and you want to create a form for this entities relationship, you would normally use the EntityType. By using the NodeTranslationChoiceType, the title used as choice_label, will be automatically the title in the current language. You can also provide the "locale" parameter to set a default locale.
Example:
`   ->add('question', NodeTranslationChoiceType::class,
array(
'page_class' => array(StartersVraagPage::class),
)
)`
> [NodeBundle]: add custom form type for node translations

- src/Kunstmaan/NodeBundle/Controller/NodeAdminController.php
- src/Kunstmaan/NodeBundle/DependencyInjection/Configuration.php
- src/Kunstmaan/NodeBundle/DependencyInjection/KunstmaanNodeExtension.php
It is not easy to hide the add homepage button (except with css). Added extra bundle configuration option
```
kunstmaan_node:
show_add_homepage: false
```
> [NodeBundle] Make it easier to hide add homepage button

- src/Kunstmaan/NodeBundle/Entity/NodeIterator.php
In my usecase I needed a iterator that gets me all the children of a node directly. You can use it like this:
`$nodes = new \RecursiveIteratorIterator(new NodeIterator($parentNode->getChildren()), \RecursiveIteratorIterator::SELF_FIRST);`
> [NodeBundle]: add recursive children iterator

- UPGRADE-3.6.md
- src/Kunstmaan/MediaBundle/Command/CleanDeletedMediaCommand.php
- src/Kunstmaan/MediaBundle/Entity/Media.php
- src/Kunstmaan/MediaBundle/Helper/File/FileHandler.php
- src/Kunstmaan/MediaBundle/Repository/MediaRepository.php
I have added a new column removed_from_file_system to indicate in the database if it is removed from the fs or not.
Furthermore I fixed some small issues I had when using the command
> [MediaBundle] CleanDeleteMediaCommand fix + new column in Media

- src/Kunstmaan/NodeBundle/Controller/WidgetsController.php
- src/Kunstmaan/NodeBundle/Resources/views/Widgets/selectLink.html.twig
> Fix URLChooser to work with both single and multi language setups

- src/Kunstmaan/MediaBundle/Form/File/FileType.php
- src/Kunstmaan/MediaBundle/Helper/ExtensionGuesserFactory.php
- src/Kunstmaan/MediaBundle/Helper/ExtensionGuesserFactoryInterface.php
- src/Kunstmaan/MediaBundle/Helper/File/FileHandler.php
- src/Kunstmaan/MediaBundle/Helper/File/SVGExtensionGuesser.php
- src/Kunstmaan/MediaBundle/Helper/Image/ImageHandler.php
- src/Kunstmaan/MediaBundle/Resources/config/handlers.yml
- src/Kunstmaan/MediaBundle/Resources/config/services.yml
- src/Kunstmaan/MediaBundle/Tests/Helper/File/PdfHandlerTest.php
- src/Kunstmaan/MediaBundle/Validator/Constraints/HasGuessableExtension.php
- src/Kunstmaan/MediaBundle/Validator/Constraints/HasGuessableExtensionValidator.php
| Fixed tickets | #1183 
Allow files to be uploaded without an extension in the filename. Detect it based on Symfony's MimeTypeGuesser and ExtensionGuesser.
I was going to write a simple check check to avoid the internal server error first but I figured this small "feature" is pretty cool.
> [MediaBundle] Auto guess Extension when missing from file or throw validation error if not possible to guess.

- src/Kunstmaan/MediaBundle/Entity/Media.php
When adding a new media object set the removedFromFileSystem property to false.
> [MediaBundle] fix adding new media object crash

- src/Kunstmaan/AdminBundle/Resources/ui/js/_media-chooser.js
If you have multiple images in an pagepart and you remove one of them all image previews are gone.
> [AdminBundle] Remove only current image preview

- src/Kunstmaan/MediaBundle/Resources/config/pdf_preview.yml
Because of the changed FileHandler in pull request https://github.com/Kunstmaan/KunstmaanBundlesCMS/pull/1208, the Pdf media handler also needs to pass the new parameter.
> [MediaBundle]: extension_guesser needs to be passed to pdf handler to

- src/Kunstmaan/AdminListBundle/Resources/views/Default/export.csv.twig
In pull request https://github.com/Kunstmaan/KunstmaanBundlesCMS/pull/889 the export.csv.twig was changed. This does not work so therefor this revert.
Also use getStringValue instead of getValue, the ExportList class does not contain the getValue method.
> [AdminListBundle]: revert pull request #889

- src/Kunstmaan/PagePartBundle/Twig/Extension/PagePartTwigExtension.php
When having a twig file calling the render_pageparts twig function with another name for the variable "page", the twig function will not work.
For example when executing "{{ render_pageparts(projectPage, 'main') }}", the widget.html.twig in the PagePartBundle will return an error that the variable "page" does not exist. Therefor we pass it to the twig widget file.
> [PagePartBundle]: pass the page parameter to twig

- src/Kunstmaan/AdminBundle/Resources/ui/js/_url-chooser.js
When using the new url chooser, sequence values can't be submitted with ajax. Otherwise, choosing another link type will not work.
> [AdminBundle]: sequence can't be submitted for new url chooser

- src/Kunstmaan/SearchBundle/Search/AnalysisFactory.php
Re enables nGram filters by default in elasticsearch.
> [SearchBundle] Reenable nGrams by default, we need it more often than not

- src/Kunstmaan/MultiDomainBundle/Helper/DomainConfiguration.php
When indexing nodes, $this->getHost() is empty, therefore we need to check it it exists.
> Check if host exists

- src/Kunstmaan/SearchBundle/Resources/config/services.yml
- src/Kunstmaan/SearchBundle/Resources/doc/SearchBundle.md
- src/Kunstmaan/SearchBundle/Search/AbstractAnalysisFactory.php
- src/Kunstmaan/SearchBundle/Search/AnalysisFactoryInterface.php
- src/Kunstmaan/SearchBundle/Search/LanguageAnalysisFactory.php
- src/Kunstmaan/SearchBundle/Search/NGramAnalysisFactory.php
Minor BC break: method name in analysisfactory interface changed. addnGramFilter has been changed to addnGramTokenizer because nGrams are supposed to be used as tokenizers and not as a filter. This change actually reflects how elasticsearch is implemented.
> [SearchBundle] Allow easier switching between language and ngram word analyzers.

- src/Kunstmaan/SearchBundle/Provider/ElasticaProvider.php
Check if the index exists before trying to delete it, otherwise it throws an exception.
> [SearchBundle] check if index exists before deleting

- composer.json
- src/Kunstmaan/AdminListBundle/Service/ExportService.php
- src/Kunstmaan/AdminListBundle/Tests/Service/ExportServiceTest.php
| Fixed tickets | #1234
We ran into some troubles with extremely large databases. Sometimes connections would time out and memory limits of the hardware would be exceeded. By using a much more performant excel bundle we will be able to avoid those hardware limits a lot longer. In fact spout will never flood the memory like PhpExcel does because it works with chucks of the excel and leaves untouched parts out of memory. Spout will scale better in general
| Bundles + PhpExcel | Bundles + Spout
--- | -------------------- | ----------------- 
1 | 04m 10s | 01m 15s
2 | 04m 12s | 01m 17s
3 | 04m 12s | 01m 15s
4 | 04m 15s | 01m 12s
5 | 04m 14s | 01m 12s
Average memory …
> [AdminListBundle] replace PhpExcel for a more performant variant box/spout

- src/Kunstmaan/FixturesBundle/Builder/PageBuilder.php
- src/Kunstmaan/FixturesBundle/Resources/config/services.yml
| Bug fix?      | yes/no (TBD)
This will make fixtures more _production ready_ :)
It's a BC break because projects with _wrong_ fixtures will have to adjust their code.
> [FixtureBundle] Check allowed_children and getPossibleChildTypes in fixture generator

- src/Kunstmaan/NodeBundle/Form/NodeMenuTabTranslationAdminType.php
| Fixed tickets | #1226 
This fixes the issue where when trying to update the slug of a page the error messages would not be displayed correctly. The only problem for me is that I do not understand why this fix works and the original code does not. It should give the exact same results? Maybe a bug in the Assert/Regex code?
> [NodeBundle] fix bug error label not correct slugchooser

- src/Kunstmaan/FixturesBundle/Parser/Parser.php
- src/Kunstmaan/FixturesBundle/Parser/Property/Method.php
This pull request changes two things:
Currently if you have a provider implementing a method that is called without arguments the MethodParser will try and complete these arguments based on type or name. If it is called with arguments they are passed two the providers method. This PR changes this to check if the number of arguments passed to the function matches the number of required arguments and will try to complete the missing ones as before.
Also, as the parses will try to complete missing arguments based on name, we pass all the fixtures currently being parsed with the `fixtures` key. This will allow you to add a parameter named …
> [FixturesBundle] Improve argument matching and pass set of fixtures

- src/Kunstmaan/MediaBundle/Resources/config/pdf_preview.yml
PdfHandler service definition doesn't call setSlugifier(), causing PdfHandler::prepareMedia() to fail if it's ever called.
> Define parent service of PDF handler

- src/Kunstmaan/AdminBundle/Composer/ScriptHandler.php
- src/Kunstmaan/GeneratorBundle/Command/GenerateDefaultSiteCommand.php
- src/Kunstmaan/GeneratorBundle/Generator/DefaultSiteGenerator.php
- src/Kunstmaan/GeneratorBundle/Tests/Generator/DefaultSiteGeneratorTest.php
| Fixed tickets | 1086
[AdminBundle] Added post-install script to setup configs for single language file
[GeneratorBundle] Use multilanguage parameter to detect multi/single language, when generating default-site
> [AdminBundle] Added post-install script to setup single lang site

- src/Kunstmaan/AdminListBundle/Controller/AdminListController.php
When having an admin list form with a urlchooser, the new urlchooser does not work because when submitting the form with ajax, you will get redirected to the listing. This fix prevents this.
> [AdminListBundle]: urlchooser ajax requests

- src/Kunstmaan/GeneratorBundle/DataFixtures/ORM/UserFixtures.php
The original fixture ignores the custom FOS User config. It force uses the `Kunstmaan\AdminBundle\Entity\User` regardless of the config.
> Fix user create (custom user error)

- src/Kunstmaan/NodeBundle/Controller/WidgetsController.php
| Fixed tickets | #1314 
Forgot to provide parameter multilanguage which cause twig file to always render urls without locale
> [NodeBundle] Fix CKE url chooser

- src/Kunstmaan/AdminBundle/Resources/ui/js/_url-chooser.js
- src/Kunstmaan/NodeBundle/Form/EventListener/URLChooserFormSubscriber.php
- src/Kunstmaan/NodeBundle/Form/Type/URLChooserType.php
- src/Kunstmaan/NodeBundle/Helper/URLHelper.php
- src/Kunstmaan/SeoBundle/Form/SocialType.php
| Fixed tickets | #1293
- Removed the internal_link_only option in favour of the link_types option to provide which link types can be used. 
- Adapted the SocialForm to allow external and internal url's for og:url.
- Removed absolute url when the link is on the current host.
> [URLChooser]: add link_types

- src/Kunstmaan/NodeBundle/Controller/NodeAdminController.php
When changing the link type of the URL chooser in a node edit, we can not execute the redirect when ajax request is made. When for example choosing the "external" link type, an ajax request will submit the form to change the field. The edit action will redirect again to the edit page and the field will not be replaced.
> [NodeBundle]: url chooser fix

- src/Kunstmaan/TranslatorBundle/Resources/ui/js/_inline-edit.js
Scale textareas to the content that is being edited.
Textarea was too small for the content.
> [TranslatorBundle]: Scale textarea to content

- src/Kunstmaan/AdminBundle/Twig/AdminPermissionsTwigExtension.php
- src/Kunstmaan/AdminBundle/Twig/DateByLocaleExtension.php
- src/Kunstmaan/AdminBundle/Twig/FormToolsExtension.php
- src/Kunstmaan/AdminBundle/Twig/GoogleSignInTwigExtension.php
- src/Kunstmaan/AdminBundle/Twig/LocaleSwitcherTwigExtension.php
- src/Kunstmaan/AdminBundle/Twig/MenuTwigExtension.php
- src/Kunstmaan/AdminBundle/Twig/MultiDomainAdminTwigExtension.php
- src/Kunstmaan/AdminBundle/Twig/TabsTwigExtension.php
- src/Kunstmaan/AdminListBundle/Twig/AdminListTwigExtension.php
- src/Kunstmaan/ConfigBundle/Twig/ConfigTwigExtension.php
- src/Kunstmaan/LeadGenerationBundle/Twig/PopupTwigExtension.php
- src/Kunstmaan/MenuBundle/Twig/MenuTwigExtension.php
- src/Kunstmaan/MultiDomainBundle/Twig/MultiDomainTwigExtension.php
- src/Kunstmaan/NodeBundle/Twig/NodeTwigExtension.php
- src/Kunstmaan/NodeBundle/Twig/PagesConfigurationTwigExtension.php
- src/Kunstmaan/NodeBundle/Twig/UrlReplaceTwigExtension.php
- src/Kunstmaan/NodeSearchBundle/Twig/KunstmaanNodeSearchTwigExtension.php
- src/Kunstmaan/PagePartBundle/Twig/Extension/PagePartAdminTwigExtension.php
- src/Kunstmaan/PagePartBundle/Twig/Extension/PagePartTwigExtension.php
- src/Kunstmaan/PagePartBundle/Twig/Extension/PageTemplateTwigExtension.php
- src/Kunstmaan/SeoBundle/Twig/GoogleAnalyticsTwigExtension.php
- src/Kunstmaan/SeoBundle/Twig/SeoTwigExtension.php
- src/Kunstmaan/SitemapBundle/Twig/SitemapTwigExtension.php
- src/Kunstmaan/UtilitiesBundle/Twig/UtilitiesTwigExtension.php
| Fixed tickets | #1321 
As of twig 1.26 they removed the twig extension getName() function.
I removed the getName() function in all twig extension files.
> [AllBundle]: removed getName from twig extensions

- src/Kunstmaan/SeoBundle/Resources/views/SeoTwigExtension/metadata.html.twig
- src/Kunstmaan/SeoBundle/Twig/SeoTwigExtension.php
When the selected ogImage is no longer present on disk, `get_image_dimensions` will throw an exception.
> [SeoBundle] Catch exception when OG image no longer exists

- src/Kunstmaan/AdminListBundle/Controller/AdminListController.php
- src/Kunstmaan/NodeBundle/Controller/NodeAdminController.php
When switching URL chooser in the adminlist add form, we can not do the redirect when submitting the form.
> [AdminListBundle]: don't redirect on add form

- composer.json
As of twig 1.26 they removed the twig extension getName() function. 
See https://github.com/twigphp/Twig/issues/2147
Symfony has also released a new tag but we do not install dev releases of symfony. Therefore we need to use twig 1.25 for now.
> [Composer]: revert twig to 1.25

- src/Kunstmaan/FormBundle/Resources/views/FormSubmissions/edit.html.twig
InternalName was removed in 3eb66d60d91a27594828f7c4a2f8264d98d34ad3
Removed use of this variable in twig file
> [FormBundle]: fix TopMenuItem

- src/Kunstmaan/NodeBundle/Helper/URLHelper.php
- src/Kunstmaan/NodeBundle/Resources/views/Widgets/selectLink.html.twig
| Fixed tickets | #1296
Fix for URLHelper, url needs to be passed correctly.
Fix for selectLink template, pass the host of the switchedHost to the get_backend_locales() function instead of the full object.
> [NodeBundle]: change selectLink template

- src/Kunstmaan/NodeSearchBundle/Configuration/NodePagesConfiguration.php
| Q | A |
| --- | --- |
When populating the search index, the NodePagesConfiguration calls the enterRequestScope() function. In this function it checks if there is a current request. If not, a new request is created with the language of the node translation. When a new node translation is indexed, with another language, and we already have a request, this function will not be executed fully. Therefore we always have the language of our first node translation in the twig templates. 
This fix will check if the current request locale is different from the node translation locale.
> [NodeSearchBundle]: fix request scope

- src/Kunstmaan/AdminBundle/Controller/DefaultController.php
- src/Kunstmaan/DashboardBundle/Controller/GoogleAnalyticsController.php
- src/Kunstmaan/LanguageChooserBundle/Controller/LanguageChooserController.php
- src/Kunstmaan/NodeBundle/Controller/NodeAdminController.php
- src/Kunstmaan/NodeBundle/Controller/WidgetsController.php
- src/Kunstmaan/SeoBundle/Controller/Admin/SettingsController.php
- src/Kunstmaan/SeoBundle/Controller/RobotsController.php
- src/Kunstmaan/TranslatorBundle/Controller/TranslatorCommandController.php
- src/Kunstmaan/TranslatorBundle/Controller/TranslatorController.php
- src/Kunstmaan/UserManagementBundle/Controller/UsersController.php
> [AllBundles] Use built-in getParameter

- UPGRADE-4.0.md
- src/Kunstmaan/AdminListBundle/Controller/AdminListController.php
- src/Kunstmaan/AdminListBundle/Event/AdminListEvent.php
| BC breaks?   | yes
| Deprecations?|no
Add Form and Request property in the AdminListEvent to have more flexibility in adapting the adminlistscontroller.
Also added a Response function, so you can give a custom Response in the adminlistcontoller.
> [AdminListBundle]: Add Form & Request property and Response function in AdminListEvent

- src/Kunstmaan/ArticleBundle/PagePartAdmin/AbstractArticleOverviewPagePagePartAdminConfigurator.php
- src/Kunstmaan/ArticleBundle/PagePartAdmin/AbstractArticlePagePagePartAdminConfigurator.php
| Fixed tickets | #1381 
new interfaces forces implementing method getWidgetTemplate but is not necessary for article configurators.
> [ArticleBundle] fix syntax error in configurators

- docs/07-06-community-bundles.md
Hello,
I gathered all projects extending the core and put them in a separate documentation page. I think it would be beneficial for all to advertise those project this way:
* Kunstmaan Bundles CMS will build a larger community and will encourage to create new bundles
* Bundle creators will have their work acknowledged and introduced to a larger audience
* End users (developers) will have it easier to find more functionality for their Kunstmaan Bundles CMS projects
Those are all of the projects I can find that require `kunstmaan/bundles-cms` in their composer, aren’t deprecated, have some readme, etc.
What do you think? 🎉
> Create a „Community Bundles” documentation page

- src/Kunstmaan/MediaBundle/EventListener/DoctrineMediaListener.php
When deleting a file that no longer exists on the filesystem you will get an error that the file does not exists. This check will verify that the file exists on the filesystem and will not do the rename action when it does not exists. This way the delete process can continue.
> [MediaBundle]: check if file exists

- src/Kunstmaan/ConfigBundle/Controller/ConfigController.php
- src/Kunstmaan/ConfigBundle/Helper/Menu/ConfigMenuAdaptor.php
- src/Kunstmaan/ConfigBundle/Resources/config/routing.yml
> [ConfigBundle] Fixed variable name, in routing and view, for ConfigController::indexAction.

- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/defaultsite/DataFixtures/ORM/DefaultSiteGenerator/DefaultSiteFixtures.php
Due to the deprecation fixer tool it sorted the use statements. Because of that it will generate datafixtures without the correct uses.
> [GeneratorBundle] fixed datafixtures for default site

- src/Kunstmaan/PagePartBundle/Controller/PagePartAdminController.php
- src/Kunstmaan/PagePartBundle/Twig/Extension/PagePartAdminTwigExtension.php
We are using the page variable very frequently inside our pagepart twig templates. The page variable is not available when editing a node. Therefor you need to create a admin view template for this issue. By adding the page variable always, we can use it also in the admin views.
> [PagePartBundle]: make page variable available inside pagepart admin

- src/Kunstmaan/PagePartBundle/Event/Events.php
- src/Kunstmaan/PagePartBundle/Event/PagePartEvent.php
- src/Kunstmaan/PagePartBundle/PagePartAdmin/PagePartAdmin.php
- src/Kunstmaan/TaggingBundle/EventListener/TagsListener.php
- src/Kunstmaan/TaggingBundle/Resources/config/services.yml
[PagePartBundle]: add post persist event
When using the TaggingBundle and adding tags on a pagePart, the tags are not persisted in the database when saving the node. Therefore I've added a post persist event for the PageParts that can be used in the TaggingListener for each pagePart.
> [PagePartBundle]: add post persist event

- src/Kunstmaan/MenuBundle/Controller/MenuItemAdminListController.php
Avoid being stuck in the MenuItems of a menu for a different locale when switching locale at the MenuItemAdminListView.
Finds the correct Menu based on the newly requested locale and name of the current menu.
| Fixed tickets |  #1437
> [MenuBundle] View would not automatically switch to the menuitems of your new locale

- src/Kunstmaan/GeneratorBundle/Generator/DefaultEntityGenerator.php
The generator for entities was changed before but the new entity was not extending AbstractEntity anymore. This fix will make it possible again.
> [GeneratorBundle]: make new entity extend AbstractEntity again

- src/Kunstmaan/AdminBundle/Resources/ui/js/_rich-editor.js
When using the URL chooser in a wysiwyg, when selecting a media item, the protocol should be put to other as in the node url chooser.
> [AdminBundle]: url chooser fix for media

- src/Kunstmaan/AdminBundle/Resources/ui/js/_app-entity-version-lock.js
- src/Kunstmaan/AdminBundle/Resources/ui/js/app.js
- src/Kunstmaan/AdminBundle/Resources/views/Default/_js_footer.html.twig
- src/Kunstmaan/AdminListBundle/Controller/AdminListController.php
- src/Kunstmaan/AdminListBundle/Controller/EntityLockCheckController.php
- src/Kunstmaan/AdminListBundle/DependencyInjection/Configuration.php
- src/Kunstmaan/AdminListBundle/DependencyInjection/KunstmaanAdminListExtension.php
- src/Kunstmaan/AdminListBundle/Entity/EntityVersionLock.php
- src/Kunstmaan/AdminListBundle/Entity/LockableEntity.php
- src/Kunstmaan/AdminListBundle/Entity/LockableEntityInterface.php
- src/Kunstmaan/AdminListBundle/Repository/EntityVersionLockRepository.php
- src/Kunstmaan/AdminListBundle/Repository/LockableEntityRepository.php
- src/Kunstmaan/AdminListBundle/Resources/config/routing.yml
- src/Kunstmaan/AdminListBundle/Resources/config/services.yml
- src/Kunstmaan/AdminListBundle/Resources/doc/AdminListBundle.md
- src/Kunstmaan/AdminListBundle/Resources/translations/messages.en.yml
- src/Kunstmaan/AdminListBundle/Resources/views/Default/add_or_edit.html.twig
- src/Kunstmaan/AdminListBundle/Service/EntityVersionLockService.php
- src/Kunstmaan/AdminListBundle/Tests/Model/TestLockableEntityInterfaceImplementation.php
- src/Kunstmaan/AdminListBundle/Tests/Service/EntityVersionLockServiceTest.php
| Fixed tickets
Dont forget!  -- if you enable the feature you need to add the routing from AdminListBundle to your app/config/routing.yml or all admin lists will break.
Allows you to implement the LockableEntityInterface on every Entity you have an adminlist for. By doing this, each entity will automatically be locked/unlocked when users are working on them. Only 1 user can work on a locked Entity, all others will get a notification and be redirected back to it's respective overview.
> [AdminListBundle] Allow locking of individual entities in adminlists.

- src/Kunstmaan/NodeBundle/DependencyInjection/Configuration.php
If a default value is applied the PagesConfiguration will never fallback to checking wether or node `HomePageInterface` is implemented. See https://github.com/Kunstmaan/KunstmaanBundlesCMS/blob/master/src/Kunstmaan/NodeBundle/Helper/PagesConfiguration.php#L110
> [NodeBundle] Remove default for is_homepage

- src/Kunstmaan/AdminBundle/Helper/Security/Acl/Permission/PermissionAdmin.php
When using bundles with symfony 2 version, the kernel root dir was the same as the console directory. This is not the case anymore in symfony 3  so we need to change this piece of code.
When updating the permissions of a node and recursively updating the children, it wil not work anymore.
> [AdminBundle]: fix permissionadmin for sf3

- src/Kunstmaan/AdminBundle/Entity/BaseUser.php
Use case: 
- Disable a user in the CMS
- Request a new password for this user
- Click on the link you received in your email
- Set a new password
- User is enabled again
FOSUserBundle has created a new eventlistener for this:
https://github.com/FriendsOfSymfony/FOSUserBundle/pull/2076
I've added the isAccountNonLocked function to our BaseUser and this should check the enabled status of a user in our purpose.
> [AdminBundle]: fix fos user enabled state

- src/Kunstmaan/AdminListBundle/Service/EntityVersionLockService.php
- src/Kunstmaan/AdminListBundle/Tests/Service/EntityVersionLockServiceTest.php
In the new Lockable Entity feature there is a bug that prevents you to edit upon first install. This is because there is not lock present in the database and during the check it makes a new lock. This results in an access denied because the new lock did not yet expire. The solution is to verify during the expire check if the lock is newly created or not.
> [AdminListBundle] fix lockable entity denied access upon first edit

- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/pagepart/Resources/views/PageParts/IntroTextPagePart/view.html.twig
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/pagepart/Resources/views/PageParts/TextPagePart/view.html.twig
When generation a new default site, the text and intro text pagepart should contain the replace_url twig function by default for the URL Chooser to work properly.
> [GeneratorBundle]: add replace_url by default

- src/Kunstmaan/AdminBundle/Form/MediaTokenTransformer.php
- src/Kunstmaan/AdminBundle/Form/WysiwygType.php
- src/Kunstmaan/FormBundle/Form/AbstractFormPageAdminType.php
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/defaultsite/Form/PageParts/ServicePagePartAdminType.php
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/defaultsite/Form/Pages/FormPageAdminType.php
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/pagepart/Form/PageParts/IntroTextPagePart/IntroTextPagePartAdminType.php
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/pagepart/Form/PageParts/TextPagePart/TextPagePartAdminType.php
- src/Kunstmaan/MediaBundle/Resources/views/Chooser/chooserShowFolder.html.twig
- src/Kunstmaan/PagePartBundle/Form/TextPagePartAdminType.php
When we introduced the new url chooser, we had some problems with the ckeditor and the media chooser. When you choose a media item in the ckeditor, the URL of it will be a token. This is our wished behaviour but the ckeditor does not render this token. 
With this PR I've added a Transformer that will do this correctly.
I've also changed all the old TextAreaTypes to the new WysiwygType because the transformer only works on this form type.
> [AllBundles]: fix ckeditor media tokens

- UPGRADE-4.1.md
- docs/05-14-using-the-cache-bundle.md
- src/Kunstmaan/CacheBundle/Controller/VarnishController.php
- src/Kunstmaan/CacheBundle/DependencyInjection/KunstmaanCacheExtension.php
- src/Kunstmaan/CacheBundle/EventListener/VarnishListener.php
- src/Kunstmaan/CacheBundle/Form/Varnish/BanType.php
- src/Kunstmaan/CacheBundle/Helper/Menu/VarnishMenuAdaptor.php
- src/Kunstmaan/CacheBundle/Helper/VarnishHelper.php
- src/Kunstmaan/CacheBundle/KunstmaanCacheBundle.php
- src/Kunstmaan/CacheBundle/LICENSE
- src/Kunstmaan/CacheBundle/README.md
- src/Kunstmaan/CacheBundle/Resources/config/routing.yml
- src/Kunstmaan/CacheBundle/Resources/config/services.yml
- src/Kunstmaan/CacheBundle/Resources/translations/messages.en.yml
- src/Kunstmaan/CacheBundle/Resources/translations/messages.nl.yml
- src/Kunstmaan/CacheBundle/Resources/views/Varnish/ban.html.twig
- src/Kunstmaan/NodeBundle/Helper/Menu/ActionsMenuBuilder.php
| Fixed tickets | 1331
This bundle is compatible with all Symfony 3.* releases. More information about installing can be found in this line by line walkthrough of installing Symfony and all our bundles, please refer to the [Getting Started guide](http://bundles.kunstmaan.be/getting-started) and enjoy the full blown experience.
This bundle allows you to do stuff with caching. For now it's a starting bundle with the possibility
to ban stuff from varnish.
This bundle works with the fos http cache bundle. Therefore you need to add the following configuration, of course with your own varnish path.
```YAML
fos_http_cache:
proxy_client:
varnish:
servers:
- 127.0.0.1:6081 …
```
> [KunstmaanCacheBundle]: add new caching bundle

- src/Kunstmaan/AdminBundle/Form/MediaTokenTransformer.php
In the previous PR @mlebkowski asked for an improvement.
https://github.com/Kunstmaan/KunstmaanBundlesCMS/pull/1492
> [KunstmaanAdminBundle]: use addHtmlContent for domcrawler

- src/Kunstmaan/AdminBundle/Form/MediaTokenTransformer.php
| Fixed tickets | #1502
After #1502 the null values are throwing ```InvalidArgumentException``` in ```MediaTokenTransformer```.
> [AdminBundle] Fix MediaTokenTransformer with null values

- src/Kunstmaan/AdminBundle/Resources/config/console_listener.yml
Needed for Symfony 3.3 compatibility (see https://github.com/symfony/symfony/pull/21383)
> [AdminBundle] Remove key for ConsoleExceptionListener argument

- src/Kunstmaan/AdminListBundle/Resources/views/Default/view.html.twig
Left the code that creates values in the controller so there are no breaking changes.
> [AdminListBundle] Use getStringValue for adminlist view template

- src/Kunstmaan/AdminBundle/Resources/ui/js/_nested-form.js
- src/Kunstmaan/AdminBundle/Resources/ui/js/_pagepart-editor.js
| New feature?  | |no
When creating nested pagepart forms, not all javascript modules are reinitialised. When you create a form with a text field with 'maxlength', the charactersLeft library is not reinitialised. 
There is already a function in the pagepart-editor.js file that I reused now for this. Now all form items in the nested forms will be checked and reinitialised correctly.
> [KunstmaanAdminBundle]: reinit modules javascript on nested forms

- src/Kunstmaan/AdminBundle/DependencyInjection/Configuration.php
- src/Kunstmaan/AdminBundle/DependencyInjection/KunstmaanAdminExtension.php
- src/Kunstmaan/AdminBundle/Entity/BaseUser.php
- src/Kunstmaan/AdminBundle/Resources/config/services.yml
- src/Kunstmaan/AdminBundle/Resources/translations/validators.en.yml
- src/Kunstmaan/AdminBundle/Tests/Validator/Constraints/PasswordRestrictionsValidatorTest.php
- src/Kunstmaan/AdminBundle/Validator/Constraints/PasswordRestrictions.php
- src/Kunstmaan/AdminBundle/Validator/Constraints/PasswordRestrictionsValidator.php
| Fixed tickets | #1469
To set the optional parameters for the password restrictions, in app/config.yml:
```
kunstmaan_admin:
password_restrictions:
min_digits: 2
min_uppercase: 2
min_special_characters: 1
min_length: 8
max_length: 15
```
**TODO:**
> [AdminBundle] Added optional password restrictions

- UPGRADE-5.0.md
- composer.json
- src/Kunstmaan/NodeSearchBundle/Search/NodeSearcher.php
The ruflin/elastica bundle has been upgraded to the latest 5.1 version.
This version is compatible with the latest elasticsearch version.
The only change that should be made is when you override the NodeSearcher that comes by default from the bundles:
**The setMinimumNumberShouldMatch function is now replaced by the setMinimumShouldMatch function**
When you have created some extra extensions on elastica you should read the changelog:
https://github.com/ruflin/Elastica/blob/master/CHANGELOG.md
> [KunstmaanNodeSearchBundle]: upgrade elastica to 5.1

- src/Kunstmaan/NodeBundle/Resources/views/NodeAdmin/edit.html.twig
Original breadcrumb got overwritten in `NodeAdmin/edit.html.twig` for the new abstract page adminlist. This fixes layout and original breadcrumb when not in an adminlist.
> [NodeBundle] fix overwrite of original breadcrumb

- src/Kunstmaan/FixturesBundle/Provider/Node.php
- src/Kunstmaan/FixturesBundle/Resources/config/services.yml
Can be used to refer to a node inside a fixture: `node: <getNode(@homepage)>`
> [FixturesBundle] Add provider to get Node by fixture

- src/Kunstmaan/PagePartBundle/Resources/views/PagePartAdminTwigExtension/add_pagepart.html.twig
- src/Kunstmaan/PagePartBundle/Resources/views/PagePartAdminTwigExtension/widget.html.twig
When adding a new pagepart below an existing, it's always added as the first pagepart. In the javascript the classname "js-add-pp-select--first" will be checked.
> [KunstmaanPagePartBundle]: check if add pagepart button is the first one

- src/Kunstmaan/AdminListBundle/AdminList/Configurator/AbstractPageAdminListConfigurator.php
Always get the latest overviewpage. Otherwise children will not be added to the right parent.
> [KunstmaanAdminListBundle]: always get latest overviewpage

- src/Kunstmaan/AdminListBundle/EventSubscriber/AdminListSubscriber.php
- src/Kunstmaan/AdminListBundle/Resources/config/services.yml
When using the new AbstractPageAdminList and implementing the OverviewNavigationInterface, it would be good if you get redirected to the overview page when deleting a node.
> [KunstmaanAdminListBundle]: add new event subscriber

- src/Kunstmaan/TranslatorBundle/Resources/config/services.yml
- src/Kunstmaan/TranslatorBundle/Tests/Service/Importer/ImporterTest.php
Fixed phpunit tests. Not sure if this is the right way..
Service `kunstmaan_translator.service.translator.loader` is only used in tests so changed to yml.
> [TranslatorBundle] Fix phpunit tests for translator bundle

- src/Kunstmaan/MenuBundle/Controller/MenuItemAdminListController.php
- src/Kunstmaan/MenuBundle/DependencyInjection/Configuration.php
> [MenuBundle] Fix adminlist to use FQCN instead of object for form type

- .gitignore
- .travis.yml
- groundcontrol/admin-bundle.tasks.js
- groundcontrol/gulp-plugins/twig.js
- groundcontrol/tasks/build-gc-skeleton.js
- gulpfile.babel.js
- package.json
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/groundcontrol/bin/configured-tasks.js
In some file in groundcontrol twig syntax is used, this makes it very hard to test this. I've added a new task to parse the groundcontrol files and turn it into a rendered template using dummy values. This makes it a lot easier to build and test groundcontrol. No need to run `kuma:generate:bundle` anymore :-)
Added a new task which allows you to generate a processed ground control skeleton.
Under the hood uses "twig.js" for processing the twig templates.
Run `npm run generateGcExample` to generate the example.
To run the generated example itself go to `KunstmaanBundlesCMS/src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/ …
> [UI] Added buildGroundControlSkeleton task

- src/Kunstmaan/TranslatorBundle/Resources/config/services.yml
- src/Kunstmaan/TranslatorBundle/Tests/Service/Importer/ImporterTest.php
- src/Kunstmaan/TranslatorBundle/Tests/app/config/config.yml
Fix #1562 broke the translator bundle so instead of changing the service to yml, we added the default yml definition to the test app.
> [TranslatorBundle] revert fix #1562 with new solution

- src/Kunstmaan/NodeSearchBundle/DependencyInjection/Configuration.php
- src/Kunstmaan/NodeSearchBundle/DependencyInjection/KunstmaanNodeSearchExtension.php
- src/Kunstmaan/NodeSearchBundle/Search/NodeSearcher.php
Elasticsearch does not use string anymore so we need to allow the new `text` type. Also the boost is not allowed anymore at mapping level but instead needs to be done at query time. This is recommended by elasticsearch because it's more flexible.
> [NodeSearchBundle] fixes for elasticsearch 5.0

- src/Kunstmaan/AdminBundle/Toolbar/BundleVersionDataCollector.php
- src/Kunstmaan/NodeBundle/Toolbar/NodeDataCollector.php
This is needed for the ToolbarTwigExtension to work.
> [Toolbar]: return empty array when no data can be collected

- src/Kunstmaan/AdminBundle/Entity/AbstractEntity.php
| Fixed tickets | https://github.com/Kunstmaan/KunstmaanBundlesCMS/issues/1609
> [AdminBundle] Fix docblock so child entities fluent setters wont break

- src/Kunstmaan/GeneratorBundle/Command/KunstmaanGenerateCommand.php
When creating a new page with a video, the default values are not set so an error will appear.
> [KunstmaanGeneratorBundle]: add default values while generating page

- src/Kunstmaan/AdminListBundle/Resources/views/Page/list.html.twig
The AbstractPageAdminList has a different template then the normal lists. But this template does not include the normal header actions like "Export" etc..
> [KunstmaanAdminListBundle]: fix abstract page admin list

- .sensiolabs.yml
- .travis.yml
- composer.json
- src/Kunstmaan/TranslatorBundle/Tests/app/config/config.yml
We are not able anymore to install V4 due to the php 5.5 minimum requirement and the dependency of cmf-routing that does not mix well. So we are bending the rules a bit to fix this, otherwise it would be uninstallable for the rest of ages.
> [Composer] update php minimum requirement to be able to install version 4 again

- src/Kunstmaan/AdminBundle/Resources/ui/js/_input-range-slider.js
Currently initRangePercentage sets all range fields on the page.
| Fixed tickets | #1551
> [AdminBundle] Update _input-range-slider.js

- src/Kunstmaan/AdminListBundle/Entity/LockableEntity.php
Originated from #1623
Fixed column names in doctrine index
[Doctrine\DBAL\Schema\SchemaException]
There is no column with name 'entityId' on table 'kuma_lockable_entity'.
Couldn't create LockableEntity using doctrine:schema:create when using AdminListBundle
Column names are seperated by underscore
> [AdminListBundle] Fixed doctrine Index for LockableEntity 

- src/Kunstmaan/NodeSearchBundle/Configuration/NodePagesConfiguration.php
- src/Kunstmaan/SearchBundle/Command/SetupIndexCommand.php
- src/Kunstmaan/SearchBundle/Search/Search.php
| Fixed tickets | #1246
Now we can use language names like "en", "en_US", "en_us", also fixes error mentioned in #1246 ticket.
--edited by numkil
Also with new feature to check for unavailable language analyzers and prompt the user.
> [NodeSearchBundle][SearchBundle] Multi domain/language search population fix

- docs/03-02-system-requirements.md
Minimal version of PHP in composer.json is 5.6, so we need change this in docs.
> [Docs] System requirements

- src/Kunstmaan/GeneratorBundle/Command/GenerateDefaultSiteCommand.php
- src/Kunstmaan/GeneratorBundle/Generator/ArticleGenerator.php
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/AdminList/CategoryAdminListConfigurator.php
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/AdminList/TagAdminListConfigurator.php
1. We can't create new article because path to _MenuAdaptorPartial_ is incorrect.
2. We can't using _--demosite_ param in _kuma:generate:article_ because param _--namespacehomepage_ in article command generator can't be null. Quiet verbose mode don't gave a choice so task never ending.
3. Bad FQCN in _AdminListConfigurator_
> [GeneratorBundle] Article generator fix

- src/Kunstmaan/AdminBundle/Resources/ui/jsnext/PagePartChooser.js
Searching for pageparts was broken in IE11
> [AdminBundle] Fix the extended ppchooser search for IE11

- src/Kunstmaan/NodeSearchBundle/Configuration/NodePagesConfiguration.php
By merging https://github.com/Kunstmaan/KunstmaanBundlesCMS/pull/1630 and publishing a node with empty text, you will get an invalidargument exception from the DomCrawler.
> [NodeSearchBundle]: check if we have html

- src/Kunstmaan/MediaBundle/Controller/FolderController.php
- src/Kunstmaan/MediaBundle/Controller/MediaController.php
This fixes the sensiolabs insight "PHP super globals should never be used" error
> [SensiolabsInsight] Replace the usage of superglobals with the symfony request object

- src/Kunstmaan/PagePartBundle/Resources/views/PagePartAdminTwigExtension/modal.html.twig
When creating a custom PagePartAdminConfigurator, can be not defined.
> [PagePartBundle]: check if preview is defined

- src/Kunstmaan/AdminListBundle/Exception/ExportException.php
The `ExceptionInterface` was undefined and I couldn't find it anywhere (even not in the original PR)
> [SensiolabsInsight] Removed undefined implemented class

- src/Kunstmaan/AdminListBundle/Resources/config/services.yml
- src/Kunstmaan/AdminListBundle/Twig/AdminListTwigExtension.php
| BC breaks?    | yes (if users extend this class it's a BC break)
Fixes a warning from sensiolabs insight ("The Symfony Dependency Injection Container should not be passed as an argument") and also some leftover code of the cleanup in #1255
> [SensiolabsInsight] Removed unused constructor parameter

- src/Kunstmaan/AdminBundle/Resources/views/Default/_js_footer.html.twig
- src/Kunstmaan/AdminBundle/Resources/views/Default/layout.html.twig
- src/Kunstmaan/DashboardBundle/Resources/views/GoogleAnalytics/setupcontainer.html.twig
- src/Kunstmaan/MediaBundle/Resources/views/Default/layout.html.twig
- src/Kunstmaan/MediaBundle/Resources/views/Folder/show.html.twig
- src/Kunstmaan/TranslatorBundle/Resources/views/Translator/list.html.twig
A previous commit changed the way bundle scripts are loaded, but only did this for the admin bundle.
This fixes the script loading for the:
- DashboardBundle
- MediaBudle
- TranslatorBundle
If this is not the proper way to fix this, or it can be optimized, please let me know.
| Fixed tickets | #1670
> [AllBundles][5.0] Fix JavaScript loading errors

- src/Kunstmaan/AdminListBundle/Controller/AdminListController.php
- src/Kunstmaan/TranslatorBundle/Controller/TranslatorController.php
| BC breaks?    | no-ish (different exception class as before)
Fixes the sensiolabs insight error "Symfony applications should not throw AccessDeniedHttpException". Not sure if this is a "real" BC break, if so I can rebase this against 5.0!
> [SensiolabsInsight] Throw AccessDeniedException instead of AccessDeniedHttpException

- src/Kunstmaan/MediaBundle/AdminList/MediaAdminListConfigurator.php
| Fixed tickets | https://github.com/Kunstmaan/KunstmaanBundlesCMS/issues/1632
> [MediaBundle] Paginate Image thumbnail view to 24 images (6 rows of 4) per page

- src/Kunstmaan/NodeBundle/Resources/config/services.yml
| New feature?  | o
| Fixed tickets | #1684
Because off the removal of the request stack in the constructor call in PR #1684, the injection needs to be removed to.
> [NodeBundle]: remove request stack injection

- src/Kunstmaan/SearchBundle/Search/AbstractAnalysisFactory.php
If you have this-is-a-test it will be split into this, is, a, test and when you search for this-is-a-test you will get no results. The punctuation token_chars prevent tokens from being split on those chars.
> [SearchBundle] add punctuation to kuma_ngram tokenizer

- composer.json
- src/Kunstmaan/NodeBundle/Form/Type/SlugType.php
- src/Kunstmaan/UtilitiesBundle/Helper/Slugifier.php
- src/Kunstmaan/UtilitiesBundle/Helper/SlugifierInterface.php
- src/Kunstmaan/UtilitiesBundle/Tests/Helper/SlugifierTest.php
- src/Kunstmaan/UtilitiesBundle/Twig/UtilitiesTwigExtension.php
- src/Kunstmaan/UtilitiesBundle/composer.json
| New feature?  | improvment
I think we should use `Behat/Transliterator` is more accurate. It's made some BC breaks, but the second argument in slugify function never been used.
> [UtilitiesBundle] Feature transliterator

- src/Kunstmaan/FormBundle/Form/FileUploadPagePartAdminType.php
> [FormBundle] Default file upload label required to false

- composer.json
- src/Kunstmaan/UtilitiesBundle/Command/CipherCommand.php
- src/Kunstmaan/UtilitiesBundle/Helper/Cipher/Cipher.php
- src/Kunstmaan/UtilitiesBundle/Helper/Cipher/CipherInterface.php
- src/Kunstmaan/UtilitiesBundle/Helper/Cipher/UrlSafeCipher.php
- src/Kunstmaan/UtilitiesBundle/Tests/Helper/Cipher/CipherTest.php
- src/Kunstmaan/UtilitiesBundle/Tests/Helper/Cipher/UrlSafeCipherTest.php
| New feature?  | yes 
[mcrypt_decrypt](http://php.net/manual/en/function.mcrypt-decrypt.php), [mcrypt_encrypt](http://php.net/manual/en/function.mcrypt-encrypt.php) - deprecated for PHP 7.1
> [UtilitiesBundle] Cipher deprecations

- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/Resources/views/Form/fields.html.twig
When using the fields.html.twig as form theme, you will get invalid HTML when adding a class to a form input field. This occurs because a class is already added in the twig template. Therefore we need to merge this classes with the ones received from the form type. The block widget_attributes will then render the classes.
> [GeneratorBundle]: fix classes in fields.html.twig

- src/Kunstmaan/AdminBundle/Resources/ui/js/_nested-form.js
- src/Kunstmaan/AdminBundle/Resources/views/Form/fields.html.twig
When having a collection form type inside another collection type with the "Add new" button it will not work because the replace of the prototype for the nested collection is already done in the replace of the parent prototype so you will get a javascript error.
Solution is to only change the parts of the current collection.
**If someone has a better solution for this, or a nicer way, please say so ;)**
@Devolicious is it also a BC-break by introducing the data-prototype-name here ?
> [KunstmaanAdminBundle]: fix nested forms

- UPGRADE-5.0.md
- src/Kunstmaan/NodeBundle/EventListener/NodeTranslationListener.php
- src/Kunstmaan/NodeBundle/Resources/config/services.yml
The nodetranslation listener makes use of the postFlush event where it's persisting and flushing the entitymanager again and again. It's a better way to put everything in the onFlush listener and to recompute the entity changeset on the unit of work.
I've also changed some code style while on it.
@deZinc worked on it also.
> [NodeBundle]: better node translation listener

- src/Kunstmaan/FixturesBundle/Parser/Parser.php
| Fixed tickets | NA
When using the node provider of the fixtures in an array of a property in the fixtures.yml additional should be passed through.
`propertyName: ["<getNode(@fixture_1)>"]`
Pair coded with @sandergo90
> [FixturesBundle] fixed parser for array

- src/Kunstmaan/AdminBundle/Resources/views/Default/layout.html.twig
- src/Kunstmaan/DashboardBundle/Resources/views/Dashboard/index.html.twig
A previously commit added the block extrajavascript. This block is not needed because we can embed the js_footer and add our extra javascript here. TranslatorBundle also used this method.
> [DashboardBundle] fix javascript error

- src/Kunstmaan/NodeSearchBundle/DependencyInjection/Configuration.php
As of elasticsearch 5.x, the string data type is deprecated and replaced by "keyword" and "text". 
https://www.elastic.co/guide/en/elasticsearch/reference/5.5/string.html
When having old indexes with the string datatype, it will stil work because elasticsearch is able to auto upgrade those fields. But when you have special types, the auto upgrade does not work and we need to be able to use the "keyword" datatype.
> [KunstmaanNodeSearchBundle] add keyword as data type

- src/Kunstmaan/GeneratorBundle/Command/GenerateDefaultSiteCommand.php
- src/Kunstmaan/GeneratorBundle/Command/GenerateLayoutCommand.php
| Fixed tickets | #1774 
This allows to add the browserSync url from the command line.
> [GeneratorBundle] Fix missing browser sync option for generate commands

- src/Kunstmaan/LeadGenerationBundle/Entity/Popup/AbstractPopup.php
Abstract function should be public because it's being called outside the entity.
> [Leadgenerationbundle]: abstract functions should be public

- src/Kunstmaan/UtilitiesBundle/Command/CipherCommand.php
- src/Kunstmaan/UtilitiesBundle/DependencyInjection/KunstmaanUtilitiesExtension.php
- src/Kunstmaan/UtilitiesBundle/Resources/config/commands.yml
**Changes**
- Mark the class final with the annotation.
This way it isn't a hard BC break but users in dev environment will receive a deprecation that the class is not supposed to be extended from. But still they can extend the class until the next major version. This way we allow the users (our we internally) some time to migrate extended classes or re-open the the class to be extended (just remove the annotation and deprecation notice).
Users will see this kind of deprecation:
```
User Deprecated: The "FQCN" class is considered final since version 5.0. It may change without further notice as of its next major version. You should not extend it …
```
> [UtilitiesBundle][5.1] Commands as services and mark commands as final

- composer.json
- src/Kunstmaan/TranslatorBundle/Command/ExportTranslationsCommand.php
- src/Kunstmaan/TranslatorBundle/Command/ImportTranslationsCommand.php
- src/Kunstmaan/TranslatorBundle/Command/MigrationsDiffCommand.php
- src/Kunstmaan/TranslatorBundle/Command/TranslationCacheCommand.php
- src/Kunstmaan/TranslatorBundle/Command/TranslationFlagCommand.php
- src/Kunstmaan/TranslatorBundle/DependencyInjection/KunstmaanTranslatorExtension.php
- src/Kunstmaan/TranslatorBundle/Resources/config/commands.yml
- src/Kunstmaan/TranslatorBundle/composer.json
**Changes**
- Mark the class final with the annotation.
This way it isn't a hard BC break but users in dev environment will receive a deprecation that the class is not supposed to be extended from. But still they can extend the class until the next major version. This way we allow the users (our we internally) some time to migrate extended classes or re-open the the class to be extended (just remove the annotation and deprecation notice).
Users will see this kind of deprecation:
```
User Deprecated: The "FQCN" class is considered final since version 5.0. It may change without further notice as of its next major version. You should not extend it …
```
> [TranslatorBundle][5.1] Commands as services and mark commands as final

- src/Kunstmaan/AdminListBundle/Controller/AdminListController.php
- src/Kunstmaan/MenuBundle/Controller/MenuAdminListController.php
- src/Kunstmaan/MenuBundle/Controller/MenuItemAdminListController.php
- src/Kunstmaan/RedirectBundle/Controller/RedirectAdminListController.php
- src/Kunstmaan/TranslatorBundle/Controller/TranslatorController.php
I left the upgrade guide for now, let's do that after 5.0 is released and before the PR gets merged.
This PR prepares the code to move away from direct container access in controllers. All `$this->get()` usages are replaced by `$this->container->get()` to avoid triggering deprecations in non-user code. In 6.0 we should:
- remove the `get` and `getParameter` overrides
- extend from the symfony `AbstractController`
- override the `getSubscribedServices` method to extend the list of services to make sure we have all the "default" symfony services and the ones the kuma adminstlist controller needs in the service locator. Users extending from our …
> [AdminListBundle][5.1] Deprecate direct container access in controllers

- src/Kunstmaan/AdminBundle/Helper/AdminRouteHelper.php
- src/Kunstmaan/AdminBundle/Resources/config/services.yml
- src/Kunstmaan/AdminBundle/Toolbar/BundleVersionDataCollector.php
- src/Kunstmaan/ArticleBundle/Resources/config/services.yml
- src/Kunstmaan/ArticleBundle/Twig/ArticleTwigExtension.php
- src/Kunstmaan/ConfigBundle/Controller/ConfigController.php
- src/Kunstmaan/ConfigBundle/Resources/config/services.yml
- src/Kunstmaan/GeneratorBundle/Command/GenerateArticleCommand.php
| Bug fix?      | no (cleanup)
| Fixed tickets | related to #1767
> [AllBundles]: Backport pr #1767 but keeping BC

- src/Kunstmaan/PagePartBundle/PagePartAdmin/PagePartAdmin.php
This PR solves the issue stated in the closed #1802 PR due to no reaction.
> [PagePartBundle] Fix for PHP 7.2 - value passed to count() cannot be null

- src/Kunstmaan/AdminBundle/Form/MediaTokenTransformer.php
- src/Kunstmaan/AdminBundle/Tests/Form/MediaTokenTransformerTest.php
| Fixed tickets | #1857
The `MediaTokenTransformer::reverseTransform()` method uses the `Crawler::html()` method to produce the HTML it returns, but this method automatically URL-encodes the `src` attribute of image tags.
This PR does a search and replace on the final HTML to make sure that the square brackets used for the tokens are preserved.
_NB: the Symfony docs mention that the DomCrawler Component is not designed to re-dump HTML, and so it might be worth considering looking for a different tool to use in this class. (See https://symfony.com/doc/current/components/dom_crawler.html#component-dom-crawler-dumping)._
> [AdminBundle] Fix escaping of img src attributes in WYSIWYG fields

- src/Kunstmaan/SeoBundle/Form/SeoType.php
Fields are not required so set the correct form value.
> [SeoBundle]: fields are not required

- src/Kunstmaan/NodeBundle/Entity/AbstractPage.php
- src/Kunstmaan/NodeBundle/Entity/PageInterface.php
As said in #1839 we are removing the service function in 6.0. This PR will add deprecation notice for the master branch.
> [NodeBundle]: deprecate service function

- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/Resources/views/Layout/layout.html.twig
> [GeneratorBundle] Change logic of page title

- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/Controller/AuthorAdminListController.php
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/Controller/PageAdminListController.php
- src/Kunstmaan/LeadGenerationBundle/Controller/PopupsAdminListController.php
- src/Kunstmaan/LeadGenerationBundle/Controller/RulesAdminListController.php
- src/Kunstmaan/MediaBundle/Controller/MediaController.php
- src/Kunstmaan/MenuBundle/Controller/MenuAdminListController.php
- src/Kunstmaan/MenuBundle/Controller/MenuItemAdminListController.php
- src/Kunstmaan/NodeBundle/Controller/WidgetsController.php
- src/Kunstmaan/RedirectBundle/Controller/RedirectAdminListController.php
- src/Kunstmaan/TaggingBundle/Controller/TagAdminListController.php
- src/Kunstmaan/TranslatorBundle/Controller/TranslatorController.php
Changing method visibility is a BC break imo. Should I add "symfony style" deprecations to 4.0/5.0 branches when extending the controllers and calling these methods?
Fixes the sensiolabs insight "Public methods in controller classes should only be actions" error
> [SensiolabsInsight] Changed method visibility for non-action methods in controller classes

- composer.json
- src/Kunstmaan/NodeSearchBundle/DependencyInjection/Configuration.php
- src/Kunstmaan/NodeSearchBundle/DependencyInjection/KunstmaanNodeSearchExtension.php
- src/Kunstmaan/NodeSearchBundle/Helper/ElasticSearchUtil.php
- src/Kunstmaan/NodeSearchBundle/Resources/doc/ElasticSearch.md
> [NodeSearchBundle] Elastic search version 6 support

- UPGRADE-5.1.md
- src/Kunstmaan/ArticleBundle/Controller/AbstractArticleEntityAdminListController.php
- src/Kunstmaan/MediaBundle/Controller/MediaController.php
- src/Kunstmaan/NodeBundle/Controller/WidgetsController.php
| Fixed tickets | #1690
@sandergo90 this is the backport PR for the changes in #1690. I've deprecated the removed controller actions and documented the method visibility changes.
> [AllBundles] Deprecate unused controller actions and document changes

- src/Kunstmaan/AdminListBundle/Resources/views/Default/add_or_edit.html.twig
| Fixed tickets | #1716 
This PR checks to see whether an admin list's add/edit for has tabs, and, if it does, uses the form view from the tab pane instead of the entity's default form type.
This is necessary because if a field in your form class uses Symfony's `FileType` class, `form_start()` automatically gives your `<form>` tag the `enctype="multipart/form-data"` attribute.
However, this currently only works if your Admin List's entity's main form class is the one that has the `FileType` class. If you are trying to use this field type in a tab's form type, and not in the main one, your form will not have the `enctype` attribute. This PR fixes this issue.
> [AdminListBundle] Start and end form using tab pane form view, if it exists

- docs/cookbook/enabling-google-auth-login.md
- src/Kunstmaan/AdminBundle/Helper/Security/OAuth/OAuthUserCreator.php
When logging in with Google, the user will receive the ROLES given in access_roles in your configuration. This should not add roles, but should add the kuma groups instead.
> [KunstmaanAdminBundle]: access level for google should add groups

- src/Kunstmaan/MultiDomainBundle/Controller/SiteSwitchController.php
When switching host in the backend on a multidomain site, the default locale is being called for the new host. But because the host override is set after the getDefaultLocale call, the locale of the host switched from will be returned.
> [MultiDomainBundle]: host override should be set before getting default locale

- src/Kunstmaan/UtilitiesBundle/Helper/Cipher/Cipher.php
| Fixed tickets | Introduced in #1673
In PR #1673 there is the use of the webmozart bundle. It's only required in dev trough phpunit so we can't use it for production. It's also a quick if to write with an InvalidArgumentException.
> [KunstmaanUtilitiesBundle]: assert bundle is only installed in dev

- src/Kunstmaan/NodeSearchBundle/Helper/ElasticSearchUtil.php
When running elasticsearch 2.4 on a PHP 7 environment, the current check will still return that it has to use version 6. This extra check will create a connection to elasticsearch and will get the version.
> [NodeSearchBundle]: elasticsearch util should check the running version of elasticsearch

- src/Kunstmaan/AdminListBundle/Resources/translations/messages.de.yml
- src/Kunstmaan/AdminListBundle/Resources/translations/messages.en.yml
- src/Kunstmaan/AdminListBundle/Resources/translations/messages.es.yml
- src/Kunstmaan/AdminListBundle/Resources/translations/messages.fr.yml
- src/Kunstmaan/AdminListBundle/Resources/translations/messages.hu.yml
- src/Kunstmaan/AdminListBundle/Resources/translations/messages.it.yml
- src/Kunstmaan/AdminListBundle/Resources/translations/messages.nl.yml
- src/Kunstmaan/AdminListBundle/Resources/translations/messages.pl.yml
| Fixed tickets | #1899
Translations would freak out and display 1 or '' in english locale without adding these quotes.
> [AdminListBundle] avoid translations freakout when the key is true or false without escaping

- src/Kunstmaan/AdminBundle/Resources/views/Toolbar/toolbar_item.html.twig
- src/Kunstmaan/TranslatorBundle/Resources/views/Toolbar/translations.html.twig
- src/Kunstmaan/TranslatorBundle/Toolbar/TranslatorDataCollector.php
Translation data collector should show the translation instead of the key, key is meaningless for clients.
> [TranslatorBundle]: change toolbar data collector to show message instead of key

- src/Kunstmaan/AdminBundle/Resources/views/Form/fields.html.twig
- src/Kunstmaan/AdminListBundle/Resources/translations/messages.en.yml
| Fixed tickets | #1902, #1903 
Removing the translation domain in #1730 broke the translate of the error message. But symfony already translates this message so we just can print it.
Second commit is a bugfix for the standard edition build
> [AdminBundle] Messages are already translated by symfony

- UPGRADE-5.1.md
- src/Kunstmaan/NodeBundle/Resources/config/services.yml
- src/Kunstmaan/NodeBundle/Router/SlugRouter.php
Deprecate the usage of the service container and inject the required services instead.
> [NodeBundle] Deprecate container usage in the slug router

- src/Kunstmaan/AdminBundle/Resources/translations/messages.nl.yml
- src/Kunstmaan/AdminListBundle/Resources/translations/messages.de.yml
- src/Kunstmaan/AdminListBundle/Resources/translations/messages.es.yml
- src/Kunstmaan/AdminListBundle/Resources/translations/messages.fr.yml
- src/Kunstmaan/AdminListBundle/Resources/translations/messages.hu.yml
- src/Kunstmaan/AdminListBundle/Resources/translations/messages.it.yml
- src/Kunstmaan/AdminListBundle/Resources/translations/messages.nl.yml
- src/Kunstmaan/AdminListBundle/Resources/translations/messages.pl.yml
Removed a duplicate translation key and fixed unquoted non-string key. When merging crowdin translation pr's we should check that we don't add duplicate yaml keys and unquoted non-string keys as this won't work on sf4.0+
Fixed deprecations:
> Duplicate key "toolbar" detected whilst parsing YAML. Silent handling of duplicate mapping keys in YAML is deprecated since Symfony 3.2 and will throw \Symfony\Component\Yaml\Exception\ParseException in 4.0
> Implicit casting of non-string key to string is deprecated since Symfony 3.3 and will throw \Symfony\Component\Yaml\Exception\ParseException in 4.0. Quote your evaluable mapping keys instead
> [AdminBundle][AdminListBundle]Fixed yaml translation file deprecations

- src/Kunstmaan/TranslatorBundle/DependencyInjection/KunstmaanTranslatorExtension.php
Symfony marks the translator aliases default as public because of usage in controllers. We override these aliases with our custom translator so we should also mark them as public
> [TranslatorBundle] Mark the translator service aliases as public

- src/Kunstmaan/NodeBundle/DependencyInjection/Compiler/FixRouterPass.php
- src/Kunstmaan/NodeBundle/KunstmaanNodeBundle.php
Symfony marks the router alias default as public because of the usage in controllers but symfony-cmf/routerBundle overrides this alias and doesn't mark it as public. This is resolved in symfony-cmf/routing-bundle#404. This fix is only included in 2.1.0RC1 and they only support >= php7.1, so we can't use that fix/version yet. This is a workaround to fix this deprecation and can be removed after we upgrade the symfony-cmf router bundle version to 2.1.0+
> [NodeBundle] Mark the router service alias as public

- src/Kunstmaan/ConfigBundle/Helper/Menu/ConfigMenuAdaptor.php
When using more than one configuration entity, the original code would set all of them active, which causes weird problems
> [ConfigBundle] Set the correct configuration entity as active

- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/Resources/config/routing_partial.yml
When generating a new site this creates a deprecation out-of-the-box.
> [GeneratorBundle] Fix unquoted parameter in routing generator

- src/Kunstmaan/UtilitiesBundle/Tests/DependencyInjection/KunstmaanUtilitiesExtensionTest.php
UtilitiesExtensionTest was broken after the merge of pr #1939 in 5.0 and the upmerge of 5.0 in master. Master contains a lot more tests, so this was broken.
> [UtilitiesBundle] Fix UtilitiesExtensionTest after upmerge from 5.0

- src/Kunstmaan/AdminBundle/Entity/Role.php
Directly implementing the `RoleInterface` is deprecated instead we should extend from the `Role` class. This is no bc break as the `BaseRole` implements the `RoleInterface`
> [AdminBundle] Extend Role from base symfony class

- src/Kunstmaan/NodeBundle/Controller/WidgetsController.php
Currently the whole node/pages (all nodes for all domains) tree is shown when picking an url in a multidomain setup instead of only showing the nodes/pages related to the selected domain. The incorrect tree also causes incorrect urls to be selected. The generated url slug was also incorrect as it used the host instead of the config id.
> [NodeBundle] Select correct root node for the urlchooser in a multidomain setup

- UPGRADE-5.1.md
- src/Kunstmaan/TranslatorBundle/DependencyInjection/Compiler/KunstmaanTranslatorCompilerPass.php
- src/Kunstmaan/TranslatorBundle/Resources/config/services.yml
- src/Kunstmaan/TranslatorBundle/Service/Command/Importer/Importer.php
- src/Kunstmaan/TranslatorBundle/Service/Translator/Translator.php
- src/Kunstmaan/TranslatorBundle/Tests/DependencyInjection/Compiler/KunstmaanTranslatorCompilerPassTest.php
I've made our override of the translator compatible with how symfony handles the translator. This will fix the private service deprecations for all the translation file extension loaders (only happens with a cache). This change is not considered a BC break as users who want to override the translator themself should not switch the class of the `kunstmaan_translator.service.translator.translator`, but create a new custom service and add an alias for the kunstmaan translator service to their service. 
The `usedTranslations` request parameter is also deprecated because this was a leftover of the switch to the `TranslatorDataCollector`. I can't …
> [TranslatorBundle] Fix container deprecations with translation loaders

- UPGRADE-5.1.md
- src/Kunstmaan/FormBundle/AdminList/FormSubmissionAdminListConfigurator.php
- src/Kunstmaan/FormBundle/Controller/FormSubmissionsController.php
- src/Kunstmaan/FormBundle/DependencyInjection/Configuration.php
- src/Kunstmaan/FormBundle/DependencyInjection/KunstmaanFormExtension.php
- src/Kunstmaan/FormBundle/Resources/translations/messages.en.yml
- src/Kunstmaan/FormBundle/Resources/views/FormSubmissions/edit.html.twig
Added the optional `deletable_formsubmissions` config parameter, when set to true, form submissions can be deleted from the adminlist.
> [FormBundle] added deletable formsubmissions

- composer.json
Bump the version of sensio/framework-extra-bundle to 5.0. This version supports both symfony ^3.3 and ^4.0.
> [AllBundles] Bump the framework-extra-bundle version for sf4 support

- UPGRADE-5.1.md
- composer.json
| Fixed tickets | closes #2007 
Assetic is not the recommended way since symfony 3.x and is unused the cms since 5.0. It also blocks updating to sf4
> [AllBundles] Remove unused "symfony/assetic-bundle" dependency

- composer.json
We don't use this library ourself, it's a dependency of the symfony/validator. So use the same version constraint as they "suggest". I had problems with current version constraint while testing sf4 support.
> [AllBundles] Use the same version constraints as symfony for egulias/email-validator

- src/Kunstmaan/NodeBundle/Resources/config/services.yml
- src/Kunstmaan/TranslatorBundle/Resources/config/services.yml
Mark services used in our controllers as public. The urlReplaceController is marked as public because all controllers should be public for symfony.
> [NodeBundle][TranslatorBundle] Mark extra services public

- src/Kunstmaan/AdminBundle/DependencyInjection/Compiler/DomainConfigurationPass.php
- src/Kunstmaan/AdminBundle/DependencyInjection/KunstmaanAdminExtension.php
- src/Kunstmaan/AdminBundle/KunstmaanAdminBundle.php
- src/Kunstmaan/AdminBundle/Tests/KunstmaanAdminBundleTest.php
- src/Kunstmaan/MultiDomainBundle/DependencyInjection/CompilerPass/MultidomainConfigurationPass.php
- src/Kunstmaan/MultiDomainBundle/DependencyInjection/KunstmaanMultiDomainExtension.php
- src/Kunstmaan/MultiDomainBundle/KunstmaanMultiDomainBundle.php
Some extra bugfixes on the domainConfigurationService deprecations of #2006
> [AdminBundle][MultidomainBundle] Move parameter checks and service definition changes to compiler pass

- src/Kunstmaan/TranslatorBundle/Controller/TranslatorController.php
- src/Kunstmaan/UserManagementBundle/Controller/UsersController.php
Previously we deprecated container access in adminlist controllers and settings controller. So replace some get parameter calls so we don't trigger deprecations in our code.
> [TranslatorBundle][UserManagementBundle] Replace getParameter calls so our code doesn't trigger deprecations

- composer.json
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/Resources/ui/scss/config/general/_colors.scss
- src/Kunstmaan/GeneratorBundle/composer.json
| Fixed tickets | fixes #1926 
Replace the deprecated `raw` tag by `verbatim` to support twig 2
> [GeneratorBundle] Replace deprecated twig raw tag in scss file

- src/Kunstmaan/NodeBundle/Controller/NodeAdminController.php
- src/Kunstmaan/NodeBundle/Helper/NodeAdmin/NodeAdminPublisher.php
- src/Kunstmaan/NodeBundle/Resources/config/services.yml
- src/Kunstmaan/NodeBundle/Resources/views/NodeAdmin/Modals/_publish.html.twig
- src/Kunstmaan/NodeBundle/Resources/views/NodeAdmin/Modals/_unpublish.html.twig
- src/Kunstmaan/NodeBundle/Resources/views/NodeAdmin/_modals.html.twig
- src/Kunstmaan/NodeBundle/Resources/views/NodeAdmin/edit.html.twig
| Fixed tickets | closes #1581
> [NodeBundle] save on (un)publish

- src/Kunstmaan/AdminBundle/Resources/translations/messages.en.yml
Because translation was not added to the EN but to NL instead, crowdin wants to delete these translations.
> [AdminBundle] added missing translations to main language

- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/admintests/Features/Context/PageContext.php
Fixed broken behat tests after #1803
Behat tests pass after this fix: https://travis-ci.org/acrobat/KunstmaanBundlesStandardEdition/builds/403160439
> [GeneratorBundle] Fix xpath for publish modal in behat tests

- src/Kunstmaan/NodeSearchBundle/Helper/ElasticSearchUtil.php
Backport of the ES 6.2 bugfix from bundles 5.0. See #2009
> [NodeSearchBundle] Backport elasticsearch 6.2 compatibility fix from 5.0

- src/Kunstmaan/AdminListBundle/Controller/AdminListController.php
In AdminListController type options come from the configuration. They are passed to the AdaptSimpleFormEvent but then form factory use the same array. 
Due to the array isn't passed to the event by reference it's impossible to modify form options in the AdaptSimpleFormEvent listener. 
I have passed to the form factory options from the event rather than configuration.
> [AdminListBundle] fixed form options source in admin list controller

- src/Kunstmaan/TranslatorBundle/Controller/TranslatorCommandController.php
- src/Kunstmaan/TranslatorBundle/DependencyInjection/KunstmaanTranslatorExtension.php
- src/Kunstmaan/TranslatorBundle/Repository/TranslationRepository.php
- src/Kunstmaan/TranslatorBundle/Tests/app/config/parameters.yml
- When exporting translations to a csv file, only the messages domain is exported. For now we removed the messages limit. If people want to have the possibility to specify the domains to export, a PR can be created for this.
- When exporting translations, the requiredlocales parameter is being used but this should be the managed locales. In the dependency injection, i've also added the requiredlocales as default for the managed_locales parameter.
- Formatting
> [KunstmaanTranslatorBundle] export all translations, use correct locales

- src/Kunstmaan/AdminBundle/DependencyInjection/Compiler/DomainConfigurationPass.php
- src/Kunstmaan/MultiDomainBundle/DependencyInjection/CompilerPass/MultidomainConfigurationPass.php
Small fix to avoid exceptions while running these compiler passes. Discovered this error while testing 5.1 on a multidomain website
> [AdminBundle][MultidomainBundle] Check if container has service before changing it

- src/Kunstmaan/MediaBundle/DependencyInjection/Configuration.php
- src/Kunstmaan/MediaBundle/DependencyInjection/KunstmaanMediaExtension.php
- src/Kunstmaan/MediaBundle/Resources/config/services.yml
- src/Kunstmaan/MediaBundle/Tests/DependencyInjection/ConfigurationTest.php
- src/Kunstmaan/MediaBundle/Tests/Utils/SymfonyVersionTest.php
- src/Kunstmaan/MediaBundle/Utils/SymfonyVersion.php
In sf4 the web root was moved from `web` to `public` but the web directory was hardcoded for the full media upload path in our code. This change adds a configuration option to the mediabundle to override the web root path. Default it will use the symfony kernel version to set a sensible default value, `web` for <sf4 and `public` for >sf4.
> [MediaBundle] Add web_root configuration to support both web and public as the root dir for uploads

- src/Kunstmaan/DashboardBundle/Controller/DashboardController.php
- src/Kunstmaan/FormBundle/Controller/FormSubmissionsController.php
- src/Kunstmaan/MediaBundle/Controller/ChooserController.php
- src/Kunstmaan/MediaBundle/Controller/FolderController.php
- src/Kunstmaan/MediaBundle/Controller/IconFontController.php
- src/Kunstmaan/MediaBundle/Controller/MediaController.php
- src/Kunstmaan/NodeBundle/Controller/NodeAdminController.php
| Fixed tickets | closes #2039 (can be closed as the downgrade is not required anymore with this fix)
Upgrading to sensio/framework-extra-bundle 5.0 caused a bc break for camelcase template paths which were not explicitly configured (Symfony would guess the template path for the empty `@Template()` annotations. This is fixed by explicitly settings the template path for these cases. 
I've also remove some unused `@Template` annotations as these actions returned a redirect so the annotation was unused.
> [AllBundles] Fix BC break after upgrading to sensio/framework-extra-bundle 5.0

- src/Kunstmaan/AdminBundle/Helper/Security/Acl/Permission/PermissionAdmin.php
I've fixed the `RoleInterface` deprecation in #1981, this PR fixes an incompatibilty issue in the `PermissionAdmin` where the `Role` object is checked.
> [AdminBundle] Add compatibility with the new symfony Role class

- UPGRADE-5.1.md
- composer.json
- src/Kunstmaan/TranslatorBundle/Tests/app/AppKernel.php
- src/Kunstmaan/TranslatorBundle/Tests/app/config/config.yml
The `symfony/swiftmailer-bundle` is no "real" dependency of the `bundle-cms` package but should be installed by the `standard-edition`. So I will create a PR to add it to the `standard-edition`.
> [AllBundles] Remove unused symfony/swiftmailer-bundle

- UPGRADE-5.1.md
- composer.json
The `sensio/distribution-bundle` was an unused dependency and blocking the sf4 upgrade. So remove it from the package itself, but I will create a PR to add to the standard edition for new installs.
> [AllBundles] Remove unused sensio/distribution-bundle

- src/Kunstmaan/AdminBundle/EventListener/LoginListener.php
- src/Kunstmaan/AdminBundle/Tests/EventListener/LoginListenerTest.php
Don't depend on an implementation of the logger but use the abstraction instead. Discovered while splitting the `symfony/symfony` package.
> [AdminBundle] Don't depend on monolog implementation of the logger

- UPGRADE-5.1.md
- composer.json
- src/Kunstmaan/AdminBundle/Helper/AdminPanel/DefaultAdminPanelAdaptor.php
- src/Kunstmaan/AdminBundle/Resources/config/routing.yml
- src/Kunstmaan/AdminBundle/Resources/views/Resetting/check_email.html.twig
- src/Kunstmaan/UserManagementBundle/Resources/config/routing.yml
fos/user-bundle 2.1+ supports sf4 but our bundles "work" with the new versions. So relax the version contraint to allow 2.1. If users have custom code that is not compatible they should just add the correct version constraint to their `composer.json` (`"friendsofsymfony/user-bundle": "2.0.*"`)
> [AllBundles] Allow fos/user-bundle 2.1

- src/Kunstmaan/ArticleBundle/Router/TagCategoryRouter.php
Discovered an unused use during the split of the `symfony/symfony` package. Vardumper is no dependency of the bundles package and this use is unused.
> [NodeBundle] Remove unused vardumper use

- src/Kunstmaan/MediaBundle/Tests/Helper/Transformer/PdfTransformerTest.php
When running tests on your local machine ghostscript might not be installed. So this tests fails everytime. Skip the test when ghostscript is not installed, on travis ghostscript will be available.
> [MediaBundle] Skip test if ghostscript is not installed

- src/Kunstmaan/MediaBundle/Helper/Imagine/BackgroundFilterLoader.php
The BackgroundFilterLoader class as it was throws an error because the Color class no longer exists. Besides, overriding the BackgroundFilterLoader from liip is no longer necessary as the original issue is fixed in the imagine & liip versions the current bundle version uses.
> [MediaBundle] Fixed BackgroundFilterLoader issue

- src/Kunstmaan/AdminBundle/Resources/views/Form/fields.html.twig
Nested item containers conflict with page parts, because they use the same id: #-pp-container
As far as I could tell, the id of this element is never used, but the id of page part container elements is.
I have a page part with a (one to many) collection field. When the page has multiple page parts, deleting the second one actually triggers the removal of the second item of the collection field, while also marks the page part for deletion. When saving, this results in a error: Call to a member function setContext() on null at vendor/kunstmaan/bundles-cms/src/Kunstmaan/PagePartBundle/Repository/PagePartRefRepository.php:195.
> [AdminBundle] Remove id of nested form item containers

- composer.json
- src/Kunstmaan/FormBundle/Helper/FormMailer.php
- src/Kunstmaan/FormBundle/Tests/Helper/FormMailerTest.php
To support sf4 we also need to allow `symfony/swiftmailer-bundle` 3.0. But swiftmailer 3 only supports swiftmailer 6. To make sure our code works with both swiftmailer 5 and 6 I've modified the code so we are using the forward compatibility layer.
> [AllBundles] Support symfony/swiftmailerBundle 3

- src/Kunstmaan/AdminBundle/Controller/DefaultController.php
- src/Kunstmaan/MediaBundle/Controller/FolderController.php
- src/Kunstmaan/UserManagementBundle/Controller/GroupsController.php
- src/Kunstmaan/UserManagementBundle/Controller/RolesController.php
- src/Kunstmaan/UserManagementBundle/Controller/UsersController.php
Follow up PR for #2045. Some user templates could not be loaded as the directory name is with a capital letter but the guesser will look for the lowercase version. Error caught by the behat tests of the standard editition.
> [AllBundles] Explicitly set the template path for user bundle templates

- src/Kunstmaan/PagePartBundle/Twig/Extension/PagePartTwigExtension.php
> [PagePartBundle] Add has_page_parts Twig function

- src/Kunstmaan/NodeBundle/EventListener/RenderContextListener.php
- src/Kunstmaan/NodeBundle/Resources/config/services.yml
This was a left over of the clean up in PR #544. I've deprecated the unused `$templating` argument so it can be removed in the next major.
I wanted to add a test to check the deprecation behavior. But this is not possible because we run our tests with codeception. (see explanation below)
```php
<?php
namespace Kunstmaan\NodeBundle\Tests\EventListener;
use Doctrine\ORM\EntityManagerInterface;
use Kunstmaan\NodeBundle\EventListener\RenderContextListener;
use Symfony\Component\Templating\EngineInterface;
class RenderContextListenerTest extends \PHPUnit\Framework\TestCase
{
/**
* @group legacy
* @expectedDeprecation Passing a templating engine as …
```
> [NodeBundle] Deprecate unused TemplateEngine constructor argument

- src/Kunstmaan/NodeSearchBundle/DependencyInjection/KunstmaanNodeSearchExtension.php
This is a fix upon the implementation of #2075. Param `kunstmaan_search.hostnam`does not exist at the beginning state of any project so it will crash... hard.
> [NodeSearchBundle] check if params exist while building container

- src/Kunstmaan/AdminBundle/DependencyInjection/Compiler/ConsoleCompilerPass.php
- src/Kunstmaan/AdminBundle/EventListener/ConsoleExceptionSubscriber.php
- src/Kunstmaan/AdminBundle/KunstmaanAdminBundle.php
- src/Kunstmaan/AdminBundle/Resources/config/console_listener.yml
Added a new (and final) console exception subscriber, using the new error event, to replace the console exception listener.
> [AdminBundle] Added console exception subscriber/ deprecated listener

- src/Kunstmaan/AdminBundle/Tests/EventListener/ConsoleExceptionListenerTest.php
- src/Kunstmaan/AdminBundle/Tests/EventListener/ConsoleExceptionSubscriberTest.php
- src/Kunstmaan/AdminBundle/Tests/KunstmaanAdminBundleTest.php
This fixes the tests that were broken by PR #2020
> [AdminBundle] Fix broken console exception tests

- UPGRADE-5.1.md
This PR adds the missing upgrade note for #2073
> [NodeBundle] Add missing upgrade note for PR #2073

- src/Kunstmaan/TranslatorBundle/AdminList/TranslationAdminListConfigurator.php
- src/Kunstmaan/TranslatorBundle/Entity/Translation.php
- src/Kunstmaan/TranslatorBundle/Repository/TranslationRepository.php
- src/Kunstmaan/TranslatorBundle/Resources/translations/messages.en.yml
- src/Kunstmaan/TranslatorBundle/Tests/Repository/TranslationRepositoryTest.php
- src/Kunstmaan/TranslatorBundle/Tests/files/fixtures.yml
Allows translations to be "deprecated" and "disabled". 
This feature will be invisible for classic websites as the feature does not add much in their use case.
> [TranslatorBundle] add status field on translations for later use in rest api

- .travis.yml
| Fixed tickets | fixes #1895 and closes #1771
Add php 7.2 to the build matrix to make sure our code works on the current latest php.
> [AllBundles] Add php 7.2 to test matrix

- composer.json
- src/Kunstmaan/NodeSearchBundle/EventListener/NodeIndexUpdateEventListener.php
- src/Kunstmaan/NodeSearchBundle/Tests/EventListener/NodeIndexUpdateEventListenerTest.php
| Fixed tickets | fixes #2083 
| Tests pass? | Yes 🎉 
Indexing child pages of a structured node (or any of the parents is a structured node) was broken because structured nodes are always offline. Added a check to allow structured node parents to be offline. I've also added tests to check the expected behavior.
> [NodeSearchBundle] Fix search index of childpages of a structured node

- src/Kunstmaan/AdminBundle/Command/CreateUserCommand.php
When the locale is passed to the kuma:user:create command, it is being overwritten by the default local due to an incorrect if statement.
> [AdminBundle] Fixed issue with locale in kuma:user:create command

- src/Kunstmaan/AdminBundle/Command/CreateUserCommand.php
This fixes an issue when the `kuma:user:create` command is being run with `-n`|`--no-interaction`. The problem with this is that [Symfony detects if interaction mode is possible](https://github.com/symfony/symfony/blob/b959d8594cfe7ab6dada23b2b615efa566f472ff/src/Symfony/Component/Console/Application.php#L840), when it isn't - interaction mode is disabled.
Edit: To clarify, the `$this->groups` var was set in the interact method, which isn't called when `--no-interaction` flag is given to the command. The correct way is to set this var in the `initialize` method, that's what it's for.
> [AdminBundle] Fixed issue when running kuma:user:create with --no-interaction flag

- src/Kunstmaan/MediaBundle/Command/CreatePdfPreviewCommand.php
- src/Kunstmaan/MediaBundle/DependencyInjection/KunstmaanMediaExtension.php
- src/Kunstmaan/MediaBundle/Resources/config/pdf_preview.yml
In #1974 a duplicate yaml key was introduced so the command couldn't be loaded. And in #2058 I've introduced the dynamic web/public parameter, but it was not used in this command making it not usable for sf4. Changing the parameter befor the 5.1 release allows us to change it without breaking BC!
> [MediaBundle] Fix issues with CreatePdfPreviewCommand

- src/Kunstmaan/AdminBundle/EventListener/ConsoleExceptionSubscriber.php
| Fixed tickets | #2020 
(bugfix on a new feature part of master branch)
Ticket #2020 introduces the new ConsoleExeceptionSubscriber. When entering the following for example in the terminal: "bin/console kuma:", you would normally get the available commands. Now the new subscriber throws an error because the command is NULL here. We should only log an error when the command is found.
> [KunstmaanAdminBundle] check if command is not null on console error

- src/Kunstmaan/NodeBundle/Form/NodeChoiceType.php
`NodeChoiceType` should always check the deleted flag, online status and language, not only when a `page_class` is passed as an option.
> [NodeBundle] Node choice type fix

- src/Kunstmaan/NodeSearchBundle/DependencyInjection/KunstmaanNodeSearchExtension.php
- src/Kunstmaan/SearchBundle/Resources/config/services.yml
> [NodeSearchBunde] [SearchBundle]  Add parameters for ES authentication and use them in version check

- src/Kunstmaan/TranslatorBundle/Tests/Repository/TranslationRepositoryTest.php
In some cases a race condition occurs and this test fails randomly. See https://travis-ci.org/Kunstmaan/KunstmaanBundlesCMS/jobs/428044551#L2005
This is caused by the loading of the fixtures. We provide a specific updated date but the `prePersist` on the `Translation` entity is changing it to `new \DateTime()`, so in some cases this can cause a race condition. 
In the future we should rethink the entity/db related tests by just mocking the entity and have control over what this repository returns.
> [TranslatorBundle] Fix random failing test because of race condition

- src/Kunstmaan/NodeBundle/Form/NodeChoiceType.php
This reverts commit 31d0cbb67dddb448656a01670017b1b625be615a.
This reverts pull request #2115 because it's current implementation is BC breaking. In the NodeChoiceType, it's possible to overwrite the querybuilder with a custom querybuilder, for example:
```
$builder
->add('node', NodeChoiceType::class, [
'required' => true,
'multiple' => false,
'attr' => [
'class' => 'js-advanced-select',
],
'label' => 'Some label',
'query_builder' => function (NodeRepository $repo) use ($options) {
return $repo->createQueryBuilder('n')
->innerJoin('n.nodeTranslations', 'nt')
->innerJoin('nt.publicNodeVersion', 'nv')
->andWhere(.....
;
},
]) 
```
With the the …
> [NodeBundle] Revert "Fix bug in NodeChoiceType (#2115)"

- src/Kunstmaan/DashboardBundle/Command/GoogleAnalyticsConfigFlushCommand.php
- src/Kunstmaan/DashboardBundle/Resources/config/commands.yml
| Fixed tickets | related to #2022
PR #2022 generated incorrect yaml for the commands as services. Duplicated service id and 1 command service definition was missing.
> [DashboardBundle] Fixed duplicate service id and missing command in command services config

- src/Kunstmaan/AdminListBundle/Controller/AdminListController.php
When using an adminlist for pages, sorting does not work. The $entityId is the id of the NodeTranslation, not the entity. Which means that the page is never found, because $repo = $em->getRepository($configurator->getRepositoryName()); returns the repository of the page.
This fix checks if the adminlist is for a page, if it is then it should always use the NodeTranslationRepository, if not then it uses the repository of the entity.
> [AdminListBundle] Feature/sortable adminlist

- src/Kunstmaan/NodeBundle/Controller/SlugController.php
Better error message when view (path) is empty
> [NodeBundle] Improved error shown when a page does not have a view path

- src/Kunstmaan/AdminBundle/Controller/BaseSettingsController.php
- src/Kunstmaan/AdminListBundle/Controller/AdminListController.php
The method we override here is an internal method so it has changes from 3.4 -> 4.0. This makes it currently hard to support both versions without BC breaks. So I suggest to revert this deprecation warning for now (until we can come up with a better fix). We currently have a notice about removing container access in these controller in our upgrade guide so this will do for now.
> [AdminBundle][AdminListBundle] Revert code changes for container access deprecation to make symfony 4 upgrade easier

- src/Kunstmaan/NodeBundle/Repository/NodeRepository.php
> [NodeBundle] fix issue finding disctinct classes for deleted files

- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/groundcontrol/package.json
Gulp recently deleted their 4.0 branch and switched to the 4.0 tag. This removal of the branch breaks the frontend setup since it still references this branch.
> [GeneratorBundle] fix gulp dependency

- README.md
Slack channel invite link expired so replaced it with one that doesn't expire.
> [Docs] Fix slack channel link

- .travis.yml
See: https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration
Travis is deprecating the sudo keyword and moves everything to the same infrastructure (sudo really selects between two infrastructures).
> [AllBundles] Changes for upcoming travis-ci infra migration

- .travis.yml
- composer.json
- docs/installation/system-requirements.md
- docs/introduction/index.md
- src/Kunstmaan/AdminBundle/composer.json
- src/Kunstmaan/AdminListBundle/composer.json
- src/Kunstmaan/ArticleBundle/composer.json
- src/Kunstmaan/BehatBundle/composer.json
- src/Kunstmaan/DashboardBundle/composer.json
- src/Kunstmaan/FixturesBundle/composer.json
- src/Kunstmaan/FormBundle/composer.json
- src/Kunstmaan/GeneratorBundle/composer.json
- src/Kunstmaan/LeadGenerationBundle/composer.json
- src/Kunstmaan/MediaBundle/composer.json
- src/Kunstmaan/MediaPagePartBundle/composer.json
- src/Kunstmaan/MenuBundle/composer.json
- src/Kunstmaan/NodeBundle/composer.json
- src/Kunstmaan/NodeSearchBundle/composer.json
- src/Kunstmaan/PagePartBundle/composer.json
- src/Kunstmaan/RedirectBundle/composer.json
- src/Kunstmaan/SearchBundle/composer.json
- src/Kunstmaan/SeoBundle/composer.json
- src/Kunstmaan/SitemapBundle/composer.json
- src/Kunstmaan/TaggingBundle/composer.json
- src/Kunstmaan/TranslatorBundle/composer.json
- src/Kunstmaan/UserManagementBundle/composer.json
- src/Kunstmaan/UtilitiesBundle/composer.json
- src/Kunstmaan/VotingBundle/composer.json
***SHOULD ONLY BE MERGED WHEN 5.1 IS TAGGED AND THE MAINTANCE BRANCH IS CREATED***
As discussed we are bumping the minimum php version to 7.1, as this will be the minimum support version by the end of the year (http://php.net/supported-versions.php). This is also required for the symfony 4 support (dependencies that support sf4 require php 7.1)
> [AllBundles] Bump minimum php version to 7.1

- src/Kunstmaan/MediaBundle/AdminList/MediaAdminListConfigurator.php
An incompatibility discovered in our behat tests. 
Only an issue on php 5.6 -> https://3v4l.org/LKPY8
> [MediaBundle] Fix php 5.6 incompatibilty with the ChangeableLimitTrait

- composer.json
- src/Kunstmaan/MediaBundle/DependencyInjection/Compiler/MediaHandlerCompilerPass.php
- src/Kunstmaan/MediaBundle/DependencyInjection/KunstmaanMediaExtension.php
- src/Kunstmaan/MediaBundle/Helper/Transformer/PreviewTransformerInterface.php
- src/Kunstmaan/MediaBundle/Resources/config/services.yml
- src/Kunstmaan/MediaBundle/Tests/unit/DependencyInjection/KunstmaanMediaExtensionTest.php
~~_**Only merge after #2090. Ping me after merge to rebase this PR**_~~
~~Diff best viewed against the prepare-5.2 branch [prepare-5.2-php-changes...liip-imagine-bundle-2-support](https://github.com/acrobat/KunstmaanBundlesCMS/compare/prepare-5.2-php-changes...acrobat:liip-imagine-bundle-2-support).~~
#2090 is merged, rebase done.
This PR upgrades the liip/imagine-bundle to version 2, as this is the first version that supports sf4. All custom overrides made in the kunstmaan/media-bundle are ported to the new version.
> [MediaBundle] Liip imagine bundle version 2 support

- UPGRADE-5.2.md
- src/Kunstmaan/AdminBundle/Entity/Group.php
- src/Kunstmaan/AdminBundle/Entity/GroupPropertiesTrait.php
I wouldn't consider removing the interface as a "real" BC break the code for users keeps working and the `RoleInterface` shouldn't be used the indentify the `Group` entity in the first place. If we do consider this a BC break, I can rewrite the path to something [like they do in symfony/panthere](https://github.com/symfony/panther/blob/master/src/PantherTestCase.php#L19-L29).
> [AdminBundle] Remove unused RoleInterface on the group entity

- src/Kunstmaan/ConfigBundle/Controller/ConfigController.php
- src/Kunstmaan/ConfigBundle/Resources/config/services.yml
Followup pr of #2184 and fix for build error detected in Kunstmaan/KunstmaanBundlesStandardEdition#268
> [ConfigBundle] Remove route service annotation as default route is already provided as service

- src/Kunstmaan/AdminBundle/EventListener/ToolbarListener.php
This causes issues when caching pages, the use of the session triggers a `cache-control: private`
> [AdminBundle] Only use session in toolbar listener if it was started before

- src/Kunstmaan/MediaBundle/DependencyInjection/Compiler/MediaHandlerCompilerPass.php
- src/Kunstmaan/MediaBundle/Tests/unit/DependencyInjection/Compiler/MediaHandlerCompilerPassTest.php
Fixed a bug introduced in #2098. I've also added a test to avoid breaking this compiler pass again
> [MediaBundle] Fix incorrect service name in media compilerpass

- .gitignore
Php-cs-fixer config and the style-ci setup was added in #2175, but the php-cs-fixer cache file was not ignored
> [AllBundles] Add php-cs-fixer cache to gitignore

- .travis.yml
Improved the travis config in preparation for the php 7.3 build (#2203)
This also includes a fix in the groundcontrol package.json, previous build couldn't run the groundcontrol gulp task at the end the build (invalid syntax from the twig demosite ifs)
> [AllBundles] Improve travis test suite

- src/Kunstmaan/AdminBundle/DependencyInjection/Configuration.php
- src/Kunstmaan/AdminBundle/DependencyInjection/KunstmaanAdminExtension.php
- src/Kunstmaan/AdminBundle/Tests/unit/DependencyInjection/ConfigurationTest.php
- src/Kunstmaan/AdminBundle/Tests/unit/DependencyInjection/KunstmaanAdminExtensionTest.php
- src/Kunstmaan/SeoBundle/Resources/config/services.yml
Remove an unnecessary parameters provided by the KunstmaanBundlesStandardEdition to make installations more user friendly
> [AdminBundle] Move websitetitle to bundle config to remove extra parameter

- src/Kunstmaan/UtilitiesBundle/DependencyInjection/Configuration.php
- src/Kunstmaan/UtilitiesBundle/DependencyInjection/KunstmaanUtilitiesExtension.php
- src/Kunstmaan/UtilitiesBundle/Tests/unit/DependencyInjection/ConfigurationTest.php
- src/Kunstmaan/UtilitiesBundle/Tests/unit/DependencyInjection/KunstmaanUtilitiesExtensionTest.php
Deprecate setting the cipher secret parameter directly and replace by a bundle config. This also removes the need of a extra `secret` parameter being set by the user as symfony provides a `kernel.secret` parameter by default.
> [UtilitiesBundle] Deprecate direct set of parameter and use kernel.secret by default

- src/Kunstmaan/AdminBundle/DependencyInjection/KunstmaanAdminExtension.php
Fos/user-bundle has removed the default values for the `from_email` since v2.0. When installing a new  project this throws an exception during composer install/create-project. So let's provide the default values, like we do for the resetting email, to improve DX.
> [AdminBundle] Provide fos/user-bundle default values for from_email config

- composer.json
- src/Kunstmaan/AdminBundle/Resources/views/ChangePassword/changePassword.html.twig
- src/Kunstmaan/AdminBundle/Resources/views/ChangePassword/changePassword_content.html.twig
- src/Kunstmaan/AdminBundle/Resources/views/Resetting/checkEmail.html.twig
Use the new [twig `{% deprecated %}` tag ](https://symfony.com/blog/new-in-twig-deprecated-tag) to improve the template deprecations we did in 5.1
> [AdminBundle] Improve twig template deprecations

- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/defaultsite/Twig/BikesTwigExtension.php
This will make sure the twig extension is autowireable
> [GeneratorBundle] Typehint againt interface instead of concrete class

- src/Kunstmaan/TranslatorBundle/Command/ImportTranslationsFromFileCommand.php
- src/Kunstmaan/TranslatorBundle/Controller/TranslatorController.php
- src/Kunstmaan/TranslatorBundle/Resources/config/commands.yml
- src/Kunstmaan/TranslatorBundle/Service/Command/Importer/Importer.php
This requires the wrong locales so the view in cms and export excel show different locales than what the importer wants for locales.
> [TranslatorBundle] importer requires wrong locales

- src/Kunstmaan/AdminBundle/DependencyInjection/KunstmaanAdminExtension.php
Enable auto configuration (tagging) of the menu adaptor classes. Remove the needed of extra boilerplate code in the generators.
> [AdminBundle] Enable automatic tagging of menu adaptor classes

- src/Kunstmaan/TranslatorBundle/Command/ImportTranslationsCommand.php
- src/Kunstmaan/TranslatorBundle/Resources/config/commands.yml
I've improved the import translations command for better use. Default parameters configured in your  configuration files are now the standard. You can override them if you like.
The command can be used now like `php bin/console kuma:translator:import --globals` instead of having to provide all values.
> [KunstmaanTranslatorBundle] improvements to import command

- src/Kunstmaan/GeneratorBundle/DependencyInjection/KunstmaanGeneratorExtension.php
- src/Kunstmaan/GeneratorBundle/Resources/config/services.yml
These generators are ready for use in symfony 4. See #2220, #2221, #2222, #2223
> [GeneratorBundle] Enable generators that have support for sf4

- src/Kunstmaan/GeneratorBundle/DataFixtures/ORM/UserFixtures.php
It's not required to have the admin interface working (we check a db value if the password needs to be changed) + in sf4 it will be harder to "guess" the correct config file. So removing it for sf4 seems like the best solutions
> [GeneratorBundle] Remove password replace for sf4

- src/Kunstmaan/AdminBundle/Form/MediaTokenTransformer.php
When (reverse-)transforming content in the MediaTokenTransformer, the crawler can throw an InvalidArgumentException-exception.
For example with just a javascript-tag as content.
Surrounded the html()-calls with a try-catch that returns the content if the exception is caught.
> [AdminBundle] Catch InvalidArgumentException in MediaTokenTransformer

- src/Kunstmaan/AdminBundle/Resources/config/services.yml
- src/Kunstmaan/MediaBundle/Resources/config/services.yml
- src/Kunstmaan/NodeBundle/Resources/config/services.yml
- src/Kunstmaan/UserManagementBundle/Resources/config/services.yml
Define some default priorities so the menu order in the cms admin doesn't change when you don't enabling the bundles in a specific order. This more likely to happen with sf4 and the subtree split.
> [AllBundles] Set default menu adaptor priorities enabled bundle order doesn't matter

- src/Kunstmaan/GeneratorBundle/Generator/KunstmaanGenerator.php
- src/Kunstmaan/GeneratorBundle/Generator/Symfony4EntityRepositoryGenerator.php
Improved version of #2228. This pr improves the `Repository` class output for symfony 4, this way the class is ready for autowiring. Template based on the makerbundle template
Example:
```php
<?php
namespace App\Repository;
use App\Entity\Example;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Symfony\Bridge\Doctrine\RegistryInterface;
class ExampleRepository extends ServiceEntityRepository
{
public function __construct(RegistryInterface $registry)
{
parent::__construct($registry, Example::class);
}
}
```
> [GeneratorBundle] Improve entity repository class output for symfony 4

- src/Kunstmaan/AdminBundle/Helper/VersionCheck/VersionChecker.php
In #2201 we introduced a new websitetitle parameter, so use the new parameter instead of the old deprecated parameter.
> [AdminBundle] Use correct parameter to retrieve website title

- src/Kunstmaan/AdminBundle/Resources/config/services.yml
- src/Kunstmaan/AdminBundle/Twig/AdminBundleTwigExtension.php
Register twig globals needed in the cms with an extension to reduce the amount of config a user need to provide (reduce sf4 config).
This won't break current user code as the values provided by yaml config (as done in the standard edition) will override the twig extension values.
> [AdminBundle] Provide twig globals with twig extension

- src/Kunstmaan/DashboardBundle/DependencyInjection/KunstmaanDashboardExtension.php
The dashboard bundle uses esi in [`index.html.twig`](https://github.com/Kunstmaan/KunstmaanBundlesCMS/blob/cc9a81d769b266a200e47d895f3d28f56dfd24d1/src/Kunstmaan/DashboardBundle/Resources/views/Dashboard/index.html.twig#L12) , by default this is not enabled in symfony 4 (the framework bundle recipe). So make sure it's enabled when the dashboard bundle is used.
> [DashboardBundle] Enable esi by default for the dashboard bundle

- src/Kunstmaan/MediaBundle/Resources/views/Chooser/chooserShowFolder.html.twig
PR #2158 added the width/height info to the media bundle chooser view but some media metadata might not contain this info, in my case a video didn't have that info. Check first if we have this data before printing it.
> [MediaBundle] Check if media metadata has width/height info

- src/Kunstmaan/GeneratorBundle/Command/GenerateFormPageCommand.php
- src/Kunstmaan/GeneratorBundle/Generator/FormPageGenerator.php
- src/Kunstmaan/GeneratorBundle/Resources/config/services.yml
> [GeneratorBundle] refactored formpage generator

- src/Kunstmaan/AdminListBundle/AdminList/Configurator/AbstractDoctrineORMAdminListConfigurator.php
- src/Kunstmaan/AdminListBundle/Tests/unit/AdminList/Configurator/AbstractDoctrineORMAdminListConfiguratorTest.php
This change makes it possible to sort an admin list by a 1:many association, which is quite useful.
> [AdminListBundle] Allow sorting by association

- src/Kunstmaan/AdminBundle/Resources/ui/scss/default-theme/components/forms/_form-group.scss
In our cms, rawHtml type didn't respect the form-group--no-max-width because the textarea under has class form-control which overwrite with max-width: 40rem;
> [AdminBundle] Update _form-group.scss

- src/Kunstmaan/GeneratorBundle/Generator/KunstmaanGenerator.php
Just appending a "s" at the end of a table name isn't correct, use the `tableize` and `pluralize` methods from doctrine to generate a correct tablename.
A case that was broken in the current setup -> entity `Category` produced tablename `categorys`
> [GeneratorBundle] Fix incorrect plural of certain table names

- src/Kunstmaan/MultiDomainBundle/Tests/unit/DependencyInjection/ConfigurationTest.php
- src/Kunstmaan/MultiDomainBundle/Tests/unit/DependencyInjection/KunstmaanMultiDomainExtensionTest.php
- src/Kunstmaan/MultiDomainBundle/Tests/unit/EventListener/HostOverrideListenerTest.php
- src/Kunstmaan/MultiDomainBundle/Tests/unit/Helper/AdminPanel/SitesAdminPanelAdaptorTest.php
- src/Kunstmaan/MultiDomainBundle/Tests/unit/Helper/DomainConfigurationTest.php
- src/Kunstmaan/MultiDomainBundle/Tests/unit/Helper/HostOverrideCleanupHandlerTest.php
- src/Kunstmaan/MultiDomainBundle/Tests/unit/Router/DomainBasedLocaleRouterTest.php
- src/Kunstmaan/MultiDomainBundle/composer.json
> [MultiDomainBundle] upgraded dev dependencies

- src/Kunstmaan/VotingBundle/Tests/unit/DependencyInjection/KunstmaanVotingExtensionTest.php
- src/Kunstmaan/VotingBundle/Tests/unit/Entity/AbstractVoteTest.php
- src/Kunstmaan/VotingBundle/Tests/unit/Event/Facebook/FacebookLikeEventTest.php
- src/Kunstmaan/VotingBundle/Tests/unit/Event/Facebook/FacebookSendEventTest.php
- src/Kunstmaan/VotingBundle/Tests/unit/Event/LinkedIn/LinkedInShareEventTest.php
- src/Kunstmaan/VotingBundle/Tests/unit/Event/UpDown/DownVoteEventTest.php
- src/Kunstmaan/VotingBundle/Tests/unit/Event/UpDown/UpVoteEventTest.php
- src/Kunstmaan/VotingBundle/Tests/unit/EventListener/Security/MaxNumberByIpEventListenerTest.php
- src/Kunstmaan/VotingBundle/Tests/unit/Services/RepositoryResolverTest.php
- src/Kunstmaan/VotingBundle/composer.json
> [VotingBundle] upgraded dev dependencies

- src/Kunstmaan/AdminBundle/DependencyInjection/Compiler/DeprecateClassParametersPass.php
- src/Kunstmaan/AdminBundle/KunstmaanAdminBundle.php
- src/Kunstmaan/AdminBundle/Tests/unit/DependencyInjection/Compiler/DeprecateClassParametersPassTest.php
- src/Kunstmaan/AdminBundle/Tests/unit/KunstmaanAdminBundleTest.php
> [AdminBundle] Deprecate service class parameters

- src/Kunstmaan/AdminListBundle/DependencyInjection/Compiler/DeprecateClassParametersPass.php
- src/Kunstmaan/AdminListBundle/KunstmaanAdminListBundle.php
- src/Kunstmaan/AdminListBundle/Tests/unit/DependencyInjection/Compiler/DeprecateClassParametersPassTest.php
> [AdminListBundle] Deprecate service class parameters

- src/Kunstmaan/ConfigBundle/DependencyInjection/Compiler/DeprecateClassParametersPass.php
- src/Kunstmaan/ConfigBundle/KunstmaanConfigBundle.php
- src/Kunstmaan/ConfigBundle/Tests/unit/DependencyInjection/Compiler/DeprecateClassParametersPassTest.php
> [ConfigBundle] Deprecate service class parameters

- src/Kunstmaan/FormBundle/DependencyInjection/Compiler/DeprecateClassParametersPass.php
- src/Kunstmaan/FormBundle/KunstmaanFormBundle.php
- src/Kunstmaan/FormBundle/Tests/unit/DependencyInjection/Compiler/DeprecateClassParametersPassTest.php
> [FormBundle] Deprecate service class parameters

- src/Kunstmaan/CacheBundle/DependencyInjection/Compiler/DeprecateClassParametersPass.php
- src/Kunstmaan/CacheBundle/KunstmaanCacheBundle.php
- src/Kunstmaan/CacheBundle/Tests/_support/Helper/Unit.php
- src/Kunstmaan/CacheBundle/Tests/_support/UnitTester.php
- src/Kunstmaan/CacheBundle/Tests/unit.suite.yml
- src/Kunstmaan/CacheBundle/Tests/unit/DependencyInjection/Compiler/DeprecateClassParametersPassTest.php
- src/Kunstmaan/CacheBundle/codeception.yml
> [CacheBundle] Deprecate service class parameters

- src/Kunstmaan/DashboardBundle/DependencyInjection/Compiler/DeprecateClassParametersPass.php
- src/Kunstmaan/DashboardBundle/KunstmaanDashboardBundle.php
- src/Kunstmaan/DashboardBundle/Tests/unit/DependencyInjection/Compiler/DeprecateClassParametersPassTest.php
> [DashboardBundle] Deprecate service class parameters

- src/Kunstmaan/LeadGenerationBundle/DependencyInjection/Compiler/DeprecateClassParametersPass.php
- src/Kunstmaan/LeadGenerationBundle/KunstmaanLeadGenerationBundle.php
- src/Kunstmaan/LeadGenerationBundle/Tests/unit/DependencyInjection/Compiler/DeprecateClassParametersPassTest.php
> [LeadGenerationBundle] Deprecate service class parameters

- src/Kunstmaan/MenuBundle/DependencyInjection/Compiler/DeprecateClassParametersPass.php
- src/Kunstmaan/MenuBundle/KunstmaanMenuBundle.php
- src/Kunstmaan/MenuBundle/Tests/unit/DependencyInjection/Compiler/DeprecateClassParametersPassTest.php
> [MenuBundle] Deprecate service class parameters

- src/Kunstmaan/MediaBundle/DependencyInjection/Compiler/DeprecateClassParametersPass.php
- src/Kunstmaan/MediaBundle/KunstmaanMediaBundle.php
- src/Kunstmaan/MediaBundle/Tests/unit/DependencyInjection/Compiler/DeprecateClassParametersPassTest.php
> [MediaBundle] Deprecate service class parameters

- src/Kunstmaan/MultiDomainBundle/DependencyInjection/CompilerPass/DeprecateClassParametersPass.php
- src/Kunstmaan/MultiDomainBundle/KunstmaanMultiDomainBundle.php
- src/Kunstmaan/MultiDomainBundle/Tests/unit/DependencyInjection/Compiler/DeprecateClassParametersPassTest.php
> [MultiDomainBundle] Deprecate service class parameters

- src/Kunstmaan/NodeBundle/DependencyInjection/Compiler/DeprecateClassParametersPass.php
- src/Kunstmaan/NodeBundle/KunstmaanNodeBundle.php
- src/Kunstmaan/NodeBundle/Tests/unit/DependencyInjection/Compiler/DeprecateClassParametersPassTest.php
> [NodeBundle] Deprecate service class parameters

- src/Kunstmaan/NodeSearchBundle/DependencyInjection/Compiler/DeprecateClassParametersPass.php
- src/Kunstmaan/NodeSearchBundle/KunstmaanNodeSearchBundle.php
- src/Kunstmaan/NodeSearchBundle/Tests/unit/DependencyInjection/Compiler/DeprecateClassParametersPassTest.php
> [NodeSearchBundle] Deprecate service class parameters

- src/Kunstmaan/RedirectBundle/DependencyInjection/Compiler/DeprecateClassParametersPass.php
- src/Kunstmaan/RedirectBundle/KunstmaanRedirectBundle.php
- src/Kunstmaan/RedirectBundle/Tests/unit/DependencyInjection/Compiler/DeprecateClassParametersPassTest.php
> [RedirectBundle] Deprecate service class parameters

- src/Kunstmaan/TranslatorBundle/DependencyInjection/Compiler/DeprecateClassParametersPass.php
- src/Kunstmaan/TranslatorBundle/KunstmaanTranslatorBundle.php
- src/Kunstmaan/TranslatorBundle/Tests/unit/DependencyInjection/Compiler/DeprecateClassParametersPassTest.php
> [TranslatorBundle] Deprecate service class parameters

- src/Kunstmaan/SearchBundle/DependencyInjection/Compiler/DeprecateClassParametersPass.php
- src/Kunstmaan/SearchBundle/KunstmaanSearchBundle.php
- src/Kunstmaan/SearchBundle/Tests/unit/DependencyInjection/Compiler/DeprecateClassParametersPassTest.php
> [SearchBundle] Deprecate service class parameters

- src/Kunstmaan/PagePartBundle/DependencyInjection/Compiler/DeprecateClassParametersPass.php
- src/Kunstmaan/PagePartBundle/KunstmaanPagePartBundle.php
- src/Kunstmaan/PagePartBundle/Tests/unit/DependencyInjection/Compiler/DeprecateClassParametersPassTest.php
> [PagePartBundle] Deprecate service class parameters

- src/Kunstmaan/UserManagementBundle/DependencyInjection/Compiler/DeprecateClassParametersPass.php
- src/Kunstmaan/UserManagementBundle/KunstmaanUserManagementBundle.php
- src/Kunstmaan/UserManagementBundle/Tests/unit/DependencyInjection/Compiler/DeprecateClassParametersPassTest.php
> [UserManagementBundle] Deprecate service class parameters

- src/Kunstmaan/UtilitiesBundle/DependencyInjection/Compiler/DeprecateClassParametersPass.php
- src/Kunstmaan/UtilitiesBundle/KunstmaanUtilitiesBundle.php
- src/Kunstmaan/UtilitiesBundle/Tests/unit/DependencyInjection/Compiler/DeprecateClassParametersPassTest.php
> [UtilitiesBundle] Deprecate service class parameters

- UPGRADE-5.2.md
- src/Kunstmaan/MediaBundle/DependencyInjection/Configuration.php
- src/Kunstmaan/MediaBundle/DependencyInjection/KunstmaanMediaExtension.php
- src/Kunstmaan/MediaBundle/Resources/config/handlers.yml
- src/Kunstmaan/MediaBundle/Tests/unit/DependencyInjection/ConfigurationTest.php
- src/Kunstmaan/MediaBundle/Tests/unit/DependencyInjection/KunstmaanMediaExtensionTest.php
> [MediaBundle] Move aviary_api_key parameter to media bundle config instead of parameter

- UPGRADE-5.2.md
- src/Kunstmaan/AdminBundle/DependencyInjection/Configuration.php
- src/Kunstmaan/AdminBundle/DependencyInjection/KunstmaanAdminExtension.php
- src/Kunstmaan/AdminBundle/Helper/DomainConfiguration.php
- src/Kunstmaan/AdminBundle/Resources/config/services.yml
- src/Kunstmaan/AdminBundle/Tests/unit/DependencyInjection/ConfigurationTest.php
- src/Kunstmaan/AdminBundle/Tests/unit/DependencyInjection/KunstmaanAdminExtensionTest.php
- src/Kunstmaan/AdminBundle/Tests/unit/Helper/DomainConfigurationTest.php
- src/Kunstmaan/AdminListBundle/Tests/unit/Helper/DomainConfigurationTest.php
- src/Kunstmaan/MultiDomainBundle/Resources/config/services.yml
- src/Kunstmaan/MultiDomainBundle/Tests/unit/Helper/DomainConfigurationTest.php
- src/Kunstmaan/TranslatorBundle/DependencyInjection/KunstmaanTranslatorExtension.php
- src/Kunstmaan/TranslatorBundle/Tests/unit/DependencyInjection/KunstmaanTranslatorExtensionTest.php
Deprecated setting the locale parameters as parameters directly.
> [AdminBundle] Move admin locale parameters to admin_bundle config instead of parameters

- src/Kunstmaan/TranslatorBundle/Resources/config/services.yml
- src/Kunstmaan/TranslatorBundle/Service/Command/Importer/Importer.php
- src/Kunstmaan/TranslatorBundle/Service/TranslationGroupManager.php
| Fixed tickets |  #2211 
Old setup worked in this way.
for each translation
fetch translation from database
create/update translation
flush
endfor
new setup will fetch entire translations database in memory and do the logic internally. Memory usage is limited because the translation object is super small. avg 15mb per 5500 records.
> [TranslatorBundle] Speed up bulk import of large translation files

- UPGRADE-5.2.md
- src/Kunstmaan/DashboardBundle/Controller/GoogleAnalyticsController.php
- src/Kunstmaan/DashboardBundle/DependencyInjection/Configuration.php
- src/Kunstmaan/DashboardBundle/DependencyInjection/KunstmaanDashboardExtension.php
- src/Kunstmaan/DashboardBundle/Resources/config/services.yml
- src/Kunstmaan/DashboardBundle/Tests/unit/DependencyInjection/ConfigurationTest.php
- src/Kunstmaan/DashboardBundle/Tests/unit/DependencyInjection/KunstmaanDashboardExtensionTest.php
Deprecated setting the google api parameters as parameters directly.
> [DashboardBundle] Move google api parameters to dashboard bundle config instead of parameters

- src/Kunstmaan/SearchBundle/Resources/config/services.yml
This is needed to make the kuma:search:setup command work in sf4
> [SearchBundle] Make search analysis service public for kuma:search:setup command

- src/Kunstmaan/AdminBundle/Resources/config/services.yml
Use the correct parameters added in #2273 otherwise this service definition throws an exception when using the new admin bundle config
> [AdminBundle] Use new admin bundle parameters instead of the old deprecated

- src/Kunstmaan/AdminListBundle/AdminList/Configurator/AbstractAdminListConfigurator.php
- src/Kunstmaan/AdminListBundle/AdminList/Configurator/AdminListConfiguratorInterface.php
- src/Kunstmaan/AdminListBundle/Tests/unit/AdminList/AdminListTest.php
> [AdminListBundle] added getViewUrl to adminlist config. interface

- UPGRADE-5.2.md
- src/Kunstmaan/NodeSearchBundle/EventListener/NodeIndexUpdateEventListener.php
- src/Kunstmaan/NodeSearchBundle/Resources/config/services.yml
- src/Kunstmaan/NodeSearchBundle/Resources/config/update_listener.yml
- src/Kunstmaan/NodeSearchBundle/Tests/unit/EventListener/NodeIndexUpdateEventListenerTest.php
Inject the correct dependency instead of the full service container.
> [NodeSearchBundle] Deprecate container access in NodeIndexUpdateEventListener

- src/Kunstmaan/ArticleBundle/Entity/AbstractAuthor.php
- src/Kunstmaan/ArticleBundle/Entity/AbstractCategory.php
- src/Kunstmaan/ArticleBundle/Entity/AbstractTag.php
- src/Kunstmaan/ArticleBundle/Tests/unit/Entity/AbstractAuthorTest.php
> [ArticleBundle] Fixed missing sprintf with classname in deprecation message

- src/Kunstmaan/CacheBundle/composer.json
The incorrect namespace was added in #2259
> [CacheBundle] Fixed incorrect composer autoload namespace

- src/Kunstmaan/AdminBundle/DependencyInjection/KunstmaanAdminExtension.php
- src/Kunstmaan/MediaBundle/Resources/config/services.yml
These are dependencies only for our bundles so don't bother the user with setting up config for these dependencies. 
- FosUserBundle needs the templating service
- The media library needs the gedmo tree listener service to be registered
I would consider this a bugfix for 5.2 as installing the cms-skeleton will throw errors after install on cache:clear
> [AdminBundle][MediaBundle] Configure bundle dependencies by default

- src/Kunstmaan/GeneratorBundle/Generator/DefaultSiteGenerator.php
- src/Kunstmaan/GeneratorBundle/Tests/unit/Generator/DefaultSiteGeneratorTest.php
Use the new multi_language parameter that is always set (even on empty installs)
> [GeneratorBundle] Use new multi language parameter as the check is broken on empty install

- src/Kunstmaan/AdminListBundle/AdminList/Configurator/AbstractAdminListConfigurator.php
> [AdminListBundle] Fix getStringValue to allow displaying \DateTimeImmutable objects

- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/page/Entity/Pages/ExtraFunctions.php
This PR fixes some problems when generating a Page(part).
The error that was reported was:
```
In ExtraFunctions.php line 26:
Impossible to invoke a method ("getName") on a string variable ("TestWebsiteBundle").  
```
And
```
In ExtraFunctions.php line 8:
An exception has been thrown during the rendering of a template ("Catchable Fatal Error: Object of class Test\WebsiteBundle\TestWebsiteBundle could not be converted to string").  
In Environment.php(378) : eval()'d code line 33:
Catchable Fatal Error: Object of class Test\WebsiteBundle\TestWebsiteBundle could not be converted to string  
```
Another possible solution would be to modify the …
> [GeneratorBundle] Fixed Page(part) generating

- src/Kunstmaan/TranslatorBundle/Service/Command/Importer/ImportCommandHandler.php
The --globals flag was not working anymore. This prevented translation files from being imported from the app/Resources/translations directory.
> [TranslatorBundle] Fixed --globals flag for kuma:translator:import command

- src/Kunstmaan/TranslatorBundle/Service/Command/Importer/ImportCommandHandler.php
- src/Kunstmaan/TranslatorBundle/Service/TranslationFileExplorer.php
- src/Kunstmaan/TranslatorBundle/Tests/unit/app/translations/messages.en.yml
- src/Kunstmaan/TranslatorBundle/Tests/unit/app/translations/messages.nl.yml
- src/Kunstmaan/TranslatorBundle/Tests/unit/app/translations/newdomain.de.yml
Some basic changes to make the translations import (cms admin and cli command) work on sf4. Some more cleanup (deprecations) should be done for the next minor.
> [TranslatorBundle] Fix translations import on sf4 applications

- composer.json
- src/Kunstmaan/AdminBundle/composer.json
The `kunstmaan_admin.logger` and `kunstmaan_admin.logger.handler` have a dependency on the monolog-bridge/monolog packages. This was missed during the dependency split in 5.2
> [AdminBundle] Added missing monolog dependency

- src/Kunstmaan/FormBundle/Entity/FormSubmissionFieldTypes/FileFormSubmissionField.php
- src/Kunstmaan/FormBundle/composer.json
The gedmo urlizer class uses the behat transliterator class without any extra added features, so replace our current dependency to remove the extra overhead dependency on the gedmo/doctrine-extensions. See https://github.com/Atlantic18/DoctrineExtensions/pull/1079
> [FormBundle] Replace Gemdo urlizer class with behat transliterator

- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/DataFixtures/ORM/ArticleGenerator/ArticleFixtures.php
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/searchpage/DataFixtures/ORM/SearchPageGenerator/SearchFixtures.php
Without this fix the fixtures will fail on a sf4 skeleton installation
> [GeneratorBundle] Fix old optional parameter usages

- src/Kunstmaan/FormBundle/Event/SubmissionEvent.php
- src/Kunstmaan/FormBundle/EventListener/SendEmailListener.php
- src/Kunstmaan/FormBundle/Helper/FormHandler.php
- src/Kunstmaan/FormBundle/Resources/config/services.yml
| Fixed tickets | #2390
Moved sending the email to a listener. The listener can be removed when no email needs to be send after form submission. For example when the form submission is used to create a MailChimp user.
> [FormBundle] Moved FormMailer dependency to separate listener

- src/Kunstmaan/AdminBundle/EventListener/ConsoleExceptionListener.php
- src/Kunstmaan/AdminBundle/EventListener/ConsoleExceptionSubscriber.php
- src/Kunstmaan/AdminBundle/Tests/unit/EventListener/ConsoleExceptionSubscriberTest.php
Because our standard sentry config has error logging on `critical`, console errors never showed up.
> [AdminBundle] Log console errors as critical instead of error

- src/Kunstmaan/NodeSearchBundle/EventListener/NodeIndexUpdateEventListener.php
- src/Kunstmaan/NodeSearchBundle/Resources/config/update_listener.yml
- src/Kunstmaan/NodeSearchBundle/Tests/unit/EventListener/NodeIndexUpdateEventListenerTest.php
| Fixed tickets | #2380 
bugfix without bc break for above ticket.
> [NodeSearchBundle] fix #2380 childs of structurenodes never get indexed and tests

- src/Kunstmaan/TranslatorBundle/Service/Command/Exporter/CSVFileExporter.php
I assume when the code was written "utf8_decode" was wrongfully assumed to guarantee that all text is returned in utf8 encoding. It does nothing like that at all and it is much better to enfore encoding in database or spreadsheet software.
> [TranslatorBundle] Export fails to print non standard characters correctly.

- src/Kunstmaan/NodeBundle/Controller/NodeAdminController.php
Fixed the start value of the weight reorder of pages so that is in line with manual adding pages (the weight starts at 1 when adding)
> [NodeBundle] Start page reorder weight at 1 instead of 0

- src/Kunstmaan/DashboardBundle/Resources/config/services.yml
Running the `bin/console kuma:dashboard:collect` command on sf4 will throw an error that this service is private. I currently run this command without a google account configured, so maybe more services fixes are required. I will create new pr's if necessary.
> [DashboardBundle] Mark google analytics helper service as public

- link
You can use this script to link you local copy of KunstmaanBundlesCMS to a local project using the cms with all bundles seperated like for instance the `cms-skeleton`. This way you can easily make development changes with an existing project. All you have to do in your command line is the following:
```
cd /path/to/local/copy/of/KunstmaanBundlesCMS
composer install
php link /path/to/your/project
```
> [AllBundles] Added link script for development

- src/Kunstmaan/NodeBundle/Form/EventListener/URLChooserFormSubscriber.php
- src/Kunstmaan/NodeBundle/Form/EventListener/URLChooserLinkTypeSubscriber.php
- src/Kunstmaan/NodeBundle/Resources/views/Form/formWidgets.html.twig
The external url and email value of the url chooser type was not validated.
Url validation (http/https is required): 
Email validation
> [NodeBundle] Fix for missing validation of url/email link chooser

- src/Kunstmaan/NodeBundle/DependencyInjection/KunstmaanNodeExtension.php
Without this import the `kuma:nodes:cron` is not available on sf4 apps
> [NodeBundle] Import commands.yml to register command in sf4

- docs/bundles/node-bundle/locking.md
The command doesn't exsist anymore, the lock cleanup is integrated into the lock check in the controller.
> [NodeBundle] Remove old/incorrect doc about lock command

- src/Kunstmaan/AdminBundle/Helper/VersionCheck/VersionChecker.php
- src/Kunstmaan/GeneratorBundle/Command/GenerateDefaultSiteCommand.php
- src/Kunstmaan/GeneratorBundle/Command/GenerateLayoutCommand.php
- src/Kunstmaan/GeneratorBundle/DataFixtures/ORM/UserFixtures.php
- src/Kunstmaan/MediaBundle/Helper/IconFont/AbstractIconFontLoader.php
- src/Kunstmaan/TranslatorBundle/Service/Command/AbstractCommandHandler.php
- src/Kunstmaan/TranslatorBundle/Service/Command/Importer/ImportCommandHandler.php
> [AllBundles] Replace deprecated getRootDir calls

- src/Kunstmaan/FormBundle/Helper/FormMailer.php
- src/Kunstmaan/FormBundle/Tests/unit/Helper/FormMailerTest.php
> [FormBundle] In newer versions of symfony the @templating service is replaced by the delegatingengine by default

- src/Kunstmaan/AdminBundle/DependencyInjection/KunstmaanAdminExtension.php
> [AdminBundle] Fix FOSUserBundle config prepend

- src/Kunstmaan/NodeBundle/Resources/config/services.yml
The latest addition of entity tabs doesn't work, because the services that add the tabs to the forms aren't registered.
> [NodeBundle] Register services that enable the node bundle entity tabs

- src/Kunstmaan/AdminListBundle/AdminList/Configurator/AbstractAdminListConfigurator.php
The $sort param uses the wrong type for the method addfield.
> [AdminListbundle] Bugfix/wrong param in docblock

- src/Kunstmaan/FormBundle/Entity/PageParts/CheckboxPagePart.php
- src/Kunstmaan/FormBundle/Entity/PageParts/ChoicePagePart.php
- src/Kunstmaan/FormBundle/Entity/PageParts/EmailPagePart.php
- src/Kunstmaan/FormBundle/Entity/PageParts/FileUploadPagePart.php
- src/Kunstmaan/FormBundle/Entity/PageParts/MultiLineTextPagePart.php
- src/Kunstmaan/FormBundle/Entity/PageParts/SingleLineTextPagePart.php
- src/Kunstmaan/FormBundle/Form/BooleanFormSubmissionType.php
- src/Kunstmaan/FormBundle/Form/ChoiceFormSubmissionType.php
- src/Kunstmaan/FormBundle/Form/EmailFormSubmissionType.php
- src/Kunstmaan/FormBundle/Form/FileFormSubmissionType.php
- src/Kunstmaan/FormBundle/Form/StringFormSubmissionType.php
- src/Kunstmaan/FormBundle/Form/TextFormSubmissionType.php
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/pagepart/Entity/PageParts/CheckboxPagePart/CheckboxPagePart.php
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/pagepart/Entity/PageParts/ChoicePagePart/ChoicePagePart.php
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/pagepart/Entity/PageParts/EmailPagePart/EmailPagePart.php
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/pagepart/Entity/PageParts/FileUploadPagePart/FileUploadPagePart.php
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/pagepart/Entity/PageParts/MultiLineTextPagePart/MultiLineTextPagePart.php
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/pagepart/Entity/PageParts/SingleLineTextPagePart/SingleLineTextPagePart.php
| Fixed tickets | #2435 
The form pageparts use the default `constraints` option to pass the constraints from the `adaptForm` method to the actual form. Problem is that this will set the constraints on the parent Form object also which means that if you have for instance a `SingleLineTextPagePart` that is not required and used a pattern to be filled in, the form will be stuck because of the constraints that are set on the `StringFormSubmissionType` while the validation on the `value` property passes.
> [FormBundle][GeneratorBundle] Fix constraints on form pageparts 

- docs/contributing/groundcontrol.md
The `docs/contributing/groundcontrol.md` was missing on the `5.0` branch. This will make the 5.0 docs branch build pass again.
> [AllBundles] Re-add file to make the 5.0 doc build pass again

- mkdocs.yml
This was fixed in #2418 (only on master/5.3), so backport this fix to make the 5.1 and 5.2 branches builds pass again
> [AllBundles] Backport page rename fix in docs config file

- .sensiolabs.yml
Sensiolabs insights was not able to run composer install as we bumped the php version to 7.1
> [AllBundles] Fix sensiolabs insight config to make the run start again

- src/Kunstmaan/FormBundle/composer.json
The form-bundle has missing dependency on `symfony/css-selector`. Bug surfaced when executing the the tests only for the form-bundle. 
```
1) Kunstmaan\FormBundle\Tests\Form\AbstractFormPageAdminTypeTest::testFormType
LogicException: To filter with a CSS selector, install the CssSelector component ("composer require symfony/css-selector"). Or use filterXpath instead.
```
> [FormBundle] Missing symfony/css-selector dependency

- src/Kunstmaan/DashboardBundle/Resources/translations/messages.de.yml
- src/Kunstmaan/DashboardBundle/Resources/translations/messages.en.yml
- src/Kunstmaan/DashboardBundle/Resources/translations/messages.es.yml
- src/Kunstmaan/DashboardBundle/Resources/translations/messages.fr.yml
- src/Kunstmaan/DashboardBundle/Resources/translations/messages.hu.yml
- src/Kunstmaan/DashboardBundle/Resources/translations/messages.it.yml
- src/Kunstmaan/DashboardBundle/Resources/translations/messages.nl.yml
- src/Kunstmaan/DashboardBundle/Resources/translations/messages.pl.yml
The documentation link for the setup of a google analytics dashboard was still pointed to the old documentation
> [DashboardBundle] Update incorrect documentation url

- src/Kunstmaan/NodeBundle/Resources/translations/messages.en.yml
- src/Kunstmaan/NodeBundle/Resources/views/NodeAdmin/edit.html.twig
These keys are used in the nodeAdmin template but were not translated
https://github.com/Kunstmaan/KunstmaanBundlesCMS/blob/a7fff6a4045d20deb0b6dc832176c7ddb2254b38/src/Kunstmaan/NodeBundle/Resources/views/NodeAdmin/edit.html.twig#L28
Now they are available to be translated in crowdin
> [NodeBundle] Added missing translation keys

- UPGRADE-5.4.md
- src/Kunstmaan/AdminBundle/Composer/ScriptHandler.php
This class was only used in the standard-edition but [was removed a long time ago](https://github.com/Kunstmaan/KunstmaanBundlesStandardEdition/commit/31c1486f48757ae2fc18dd06707dfa1147299b90#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780L46).
> [AdminBundle] Deprecate unused composer script class

- src/Kunstmaan/AdminBundle/Resources/views/Toolbar/bundles_version.html.twig
Backported the version fix from #2477. Currently no version info could be shown when using the cms with sf4 and the separate packages
> [AdminBundle] Get correct version when using the separate packages

- composer.json
- src/Kunstmaan/NodeBundle/composer.json
The urlchooser route uses a condition to check the request.
https://github.com/Kunstmaan/KunstmaanBundlesCMS/blob/481373eea1afffadbe908204c099aa39f23c3352/src/Kunstmaan/NodeBundle/Controller/UrlReplaceController.php#L28-L33
This option needs the symfony/expression-language component, so explicitly require it.
> [NodeBundle] Explicitly require expression language

- src/Kunstmaan/NodeBundle/Tests/unit/Helper/Validation/UrlValidatorTest.php
- src/Kunstmaan/NodeBundle/Validation/URLValidator.php
Applied the `'[0-9]' can be replaced with '\d' (safe in non-unicode mode)` suggestion of php inspections ea. I've added a test to check the behavior.
> [NodeBundle] Replace numeric regex check

- src/Kunstmaan/ArticleBundle/AdminList/AbstractArticleCategoryAdminListConfigurator.php
- src/Kunstmaan/ArticleBundle/AdminList/AbstractArticlePageAdminListConfigurator.php
- src/Kunstmaan/ArticleBundle/AdminList/AbstractArticleTagAdminListConfigurator.php
- src/Kunstmaan/ArticleBundle/Entity/AbstractAuthor.php
- src/Kunstmaan/ArticleBundle/Entity/AbstractCategory.php
- src/Kunstmaan/ArticleBundle/Entity/AbstractTag.php
- src/Kunstmaan/ArticleBundle/Router/TagCategoryRouter.php
- src/Kunstmaan/ArticleBundle/Tests/unit/AdminList/AbstractArticleAuthorAdminListConfiguratorTest.php
- src/Kunstmaan/ArticleBundle/Tests/unit/AdminList/AbstractArticlePageAdminListConfiguratorTest.php
- src/Kunstmaan/ArticleBundle/Tests/unit/Entity/AbstractArticleOverviewPageTest.php
- src/Kunstmaan/ArticleBundle/Tests/unit/Entity/AbstractArticlePageTest.php
- src/Kunstmaan/ArticleBundle/Tests/unit/PagePartAdmin/AbstractArticleOverviewPagePagePartAdminConfiguratorTest.php
- src/Kunstmaan/ArticleBundle/Tests/unit/PagePartAdmin/AbstractArticlePagePagePartAdminConfiguratorTest.php
- src/Kunstmaan/ArticleBundle/Twig/ArticleTwigExtension.php
> [ArticleBundle] Code improvement found by static code analysis

- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/groundcontrol/bin/config/webpack.config.admin-extra.js
The default output path is /dist, so it will generate `./dist/public/frontend/js/admin-bundle-extra.js`. By setting the path explicitly the output is correctly generated. Follow up of #2179
> [GeneratorBundle] Fix webpack output path for admin-bundle-extra js

- src/Kunstmaan/AdminBundle/Entity/Role.php
Our method conflicts with the parent method in symfony 4.3. So add the string typehint to be compatible with symfony 4.3 and keep the `__toString()` working for older versions. 
```
Declaration of Kunstmaan\AdminBundle\Entity\Role::__toString() must be compatible with Symfony\Component\Security\Core\Role\Role::__toString(): string
```
> [AdminBundle] Add string return typehint to be compatible with symfony 4.3

- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/groundcontrol/bin/config/webpack.config.admin-extra.js
| Bug fix?      |  yes
#2462 was missing an import for the path var
> [GeneratorBundle] Added missing import in admin js task

- package-lock.json
- package.json
Fix for jquery security warning (CVE-201911385)
> [AllBundles] Upgrade jquery to fix security warning

- src/Kunstmaan/TranslatorBundle/DependencyInjection/Compiler/KunstmaanTranslatorCompilerPass.php
With all the previous deprecation fix in 5.x we forgot to add an alias for the symfony translation datacollector. With this fix the symfony translation toolbar item will work again.
> [TranslatorBundle] Restored missing service alias for translator datacollector

- src/Kunstmaan/NodeBundle/Resources/translations/messages.nl.yml
Translation exists in messages.en.yml, missing in messages.nl.yml
> [NodeBundle] missing form error translations

- src/Kunstmaan/AdminBundle/Form/MediaTokenTransformer.php
| Fixed tickets | Fixed #2507
Make sure the transform and reverseTransform methods replace href attributes of anchor tags as well as src attributes of image tags.
> [AdminBundle] added support for anchor tags in MediaTokenTransformer

- src/Kunstmaan/AdminListBundle/Controller/AdminListController.php
When an admin list has custom item actions (by defining `getItemActions()` in admin list configurator), you can not add an entity anymore. This is because both add and edit actions use the same template (`Kunstmaan/AdminListBundle/Resources/views/Default/add_or_edit.html.twig`).
However, only the edit action passes the `entity` variable. So when using the add action, it causes an error
> [AdminListBundle] Fixed undefined entity when creating entity having itemActions

- src/Kunstmaan/NodeBundle/Form/Type/SlugType.php
| BC breaks?    |  no
Updated SlugType prefix build to avoid double slashes when using StructurePage.
Using the same method as in https://github.com/Kunstmaan/KunstmaanBundlesCMS/blob/5.0/src/Kunstmaan/NodeBundle/Entity/NodeTranslation.php#L255
This bug appears on the 'Menu' tab of a page, the prefix to render a preview url (from js) should not contain double slashes. A double slash is possible when the parent page is a structure page (without slug).
> [NodeBundle] Updated SlugType prefix build

- src/Kunstmaan/AdminListBundle/Resources/config/services.yml
> [AdminListBundle] Mark export service public to fix sf4 incompatibility in form submission export

- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/Controller/PageAdminListController.php
The second parameter `$type` was missing
> [GeneratorBundle] Add missing parameter in article adminlist controller

- src/Kunstmaan/NodeSearchBundle/Services/SearchService.php
Trigger the deprecation after the `container->get()` call, this way we don't trigger deprecations for undefined service id's. As the container will throw a `ServiceNotFoundException`, we will only trigger the deprecation when an existing service is used.
> [NodeSearchBundle] Trigger deprecation after container get

- src/Kunstmaan/MediaBundle/Resources/config/imagine_filters.yml
When uploading any image with exif rotation/orientation data, imagine ignores these informations, so images are being processed with wrong rotation.
Here's a sample image with orientation exif data: https://github.com/ianare/exif-samples/blob/master/jpg/orientation/portrait_2.jpg
If you upload this image via MediaBundle you'll get a mirrored image with wrong orientation.
Adding `auto_rotate: ~` to liip_imagine configuration fixes this issue.
> [MediaBundle] Fixed imagine ignoring EXIF orientation data

- src/Kunstmaan/NodeBundle/Form/EventListener/URLChooserFormSubscriber.php
- src/Kunstmaan/NodeBundle/Form/EventListener/URLChooserLinkTypeSubscriber.php
- src/Kunstmaan/NodeBundle/Tests/unit/Validator/Constraint/ValidExternalUrlValidatorTest.php
- src/Kunstmaan/NodeBundle/Validator/Constraint/ValidExternalUrl.php
- src/Kunstmaan/NodeBundle/Validator/Constraint/ValidExternalUrlValidator.php
#2413 added url validation to the external url from the url chooser, but this broke the ability to link to anchors on the page (#anchor-name, # and #!)
> [NodeBundle] Fix url chooser to allow # and #! urls

- src/Kunstmaan/TranslatorBundle/AdminList/TranslationAdminListConfigurator.php
| Fixed tickets |  /
Got some complaints on a project that only 10 translations  at a time were visible in the translationadminlist. Since we already have a changeablelimitinterface in the bundles I decided to implement it for the translations.
> [TranslatorBundle] implement changeablelimitinterface on translationadminlist

- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/AdminList/AuthorAdminListConfigurator.php
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/AdminList/CategoryAdminListConfigurator.php
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/AdminList/PageAdminListConfigurator.php
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/AdminList/TagAdminListConfigurator.php
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/Controller/ArticleController.php
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/Controller/AuthorAdminListController.php
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/Controller/CategoryAdminListController.php
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/Controller/PageAdminListController.php
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/Controller/TagAdminListController.php
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/Entity/Author.php
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/Entity/Category.php
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/Entity/Pages/OverviewPage.php
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/Entity/Pages/Page.php
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/Entity/Tag.php
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/Form/AuthorAdminType.php
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/Form/Pages/OverviewPageAdminType.php
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/Form/Pages/PageAdminType.php
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/Form/Pages/PageAdminTypePartial.php.twig
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/article/Helper/Menu/MenuAdaptor.php
This PR improves the output of the generated article files. List of changes:
- Mixup of indentations (tabs and spaces) -> all spaces
- Removed unused uses
- Use the symfony best practice to extend from `AbstractController` instead of `Controller`
- Made all the generated base routes unique. `/admin/page` -> `/admin/blog-page`, this to avoid issues when generating multiple article style entities
- Short array usages
> [GeneratorBundle] Improved the generated article classes

- UPGRADE-5.4.md
- src/Kunstmaan/AdminListBundle/Resources/config/services.yml
- src/Kunstmaan/AdminListBundle/Service/ExportService.php
- src/Kunstmaan/AdminListBundle/Tests/unit/Service/ExportServiceTest.php
Deprecate the `@templating` injection and replace it by `@twig`. Also deprecate setter injection and move it to the constructor.
> [AdminListBundle] Deprecate setter injection and usage of symfony templating

- src/Kunstmaan/NodeBundle/Controller/SlugController.php
- src/Kunstmaan/NodeBundle/EventListener/RenderContextListener.php
Fixed incompatibility with `sensio/framework-extra-bundle ^5.5`. Follow up of #2572
> [NodeBundle] Fix incompatibility with framework-extra-bundle 5.5.*

- src/Kunstmaan/NodeBundle/Resources/translations/messages.de.yml
- src/Kunstmaan/NodeBundle/Resources/translations/messages.en.yml
- src/Kunstmaan/NodeBundle/Resources/translations/messages.es.yml
- src/Kunstmaan/NodeBundle/Resources/translations/messages.fr.yml
- src/Kunstmaan/NodeBundle/Resources/translations/messages.hu.yml
- src/Kunstmaan/NodeBundle/Resources/translations/messages.it.yml
- src/Kunstmaan/NodeBundle/Resources/translations/messages.nl.yml
- src/Kunstmaan/NodeBundle/Resources/translations/messages.pl.yml
- src/Kunstmaan/NodeBundle/Resources/views/Form/formWidgets.html.twig
"URL-chooser" and "Choose" are now translatable in urlchooser_widget of NodeBundle.
> [NodeBundle] added translations for  URL-chooser  and  Choose

- src/Kunstmaan/AdminListBundle/Resources/doc/AdminListBundle.md
- src/Kunstmaan/AdminListBundle/Resources/doc/PageAdminListBundle.md
- src/Kunstmaan/DashboardBundle/Widget/DashboardWidget.php
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/defaultsite/Controller/BikeAdminListController.php
- src/Kunstmaan/LeadGenerationBundle/Controller/AbstractNewsletterController.php
Remove the usages of deprecated annotations `Sensio\Bundle\FrameworkExtraBundle\Configuration\{Route/Method};`
> [AllBundles] Remove deprecated FrameworkExtraBundle annotations

- src/Kunstmaan/NodeBundle/Helper/Menu/PageMenuAdaptor.php
Fixed issue where all page icons would fall back to 'fa fa-home' in sidebar of node module.
> [NodeBundle] Fixed default page icon

- UPGRADE-5.4.md
- src/Kunstmaan/AdminBundle/DependencyInjection/KunstmaanAdminExtension.php
- src/Kunstmaan/AdminListBundle/Resources/config/services.yml
> [AdminListBundle] Don't call deprecated setters in ExportService

- composer.json
- src/Kunstmaan/SitemapBundle/Controller/SitemapController.php
- src/Kunstmaan/SitemapBundle/Event/PreSitemapRenderEvent.php
- src/Kunstmaan/SitemapBundle/Model/SitemapUrl.php
- src/Kunstmaan/SitemapBundle/Resources/views/Sitemap/view.xml.twig
- src/Kunstmaan/SitemapBundle/Resources/views/SitemapIndex/view.xml.twig
- src/Kunstmaan/SitemapBundle/Tests/unit/Model/SitemapUrlTest.php
- src/Kunstmaan/SitemapBundle/composer.json
Currently you have to override the controller/view for the sitemap-locale route to add additional items. This PR adds an event so you can write a listener in your application to add additional non-cms urls to the sitemap.
I've also updated the main `sitemap.xml.twig` to use the symfony route to generate the specific locale urls. So don't squash the commits here to keep the history
> [SitemapBundle] Allow to include other items in the sitemap

- src/Kunstmaan/AdminBundle/Twig/AdminPermissionsTwigExtension.php
- src/Kunstmaan/AdminBundle/Twig/LocaleSwitcherTwigExtension.php
- src/Kunstmaan/AdminBundle/Twig/MultiDomainAdminTwigExtension.php
- src/Kunstmaan/AdminBundle/Twig/TabsTwigExtension.php
- src/Kunstmaan/AdminBundle/Twig/ToolbarTwigExtension.php
- src/Kunstmaan/NodeSearchBundle/Twig/KunstmaanNodeSearchTwigExtension.php
- src/Kunstmaan/PagePartBundle/Twig/Extension/PagePartAdminTwigExtension.php
- src/Kunstmaan/PagePartBundle/Twig/Extension/PagePartTwigExtension.php
- src/Kunstmaan/PagePartBundle/Twig/Extension/PageTemplateTwigExtension.php
- src/Kunstmaan/SeoBundle/Twig/GoogleAnalyticsTwigExtension.php
- src/Kunstmaan/SeoBundle/Twig/SeoTwigExtension.php
Replace the internal `loadTemplate` method call by the new public api method `load`. See twigphp/twig#2236
> [AllBundles] Replace internal loadTemplate twig method

- UPGRADE-5.4.md
- src/Kunstmaan/AdminBundle/EventListener/PasswordCheckListener.php
- src/Kunstmaan/AdminBundle/FlashMessages/FlashTypes.php
- src/Kunstmaan/AdminBundle/Security/OAuthAuthenticator.php
- src/Kunstmaan/FormBundle/Controller/FormSubmissionsController.php
- src/Kunstmaan/MediaBundle/Controller/FolderController.php
- src/Kunstmaan/MediaBundle/Controller/MediaController.php
The error flashtype was a leftover of the boostrap v2 integration where an error alert was `alert-error` since v3 it is `alert-danger`. This PR deprecates the error flash type and replaces the usages in our code so that the styling of these alerts shows up correctly.
Example of the first login after an installation:
Before:
After:
> [AllBundles] Deprecate old flash "error" type

- UPGRADE-5.4.md
- src/Kunstmaan/AdminBundle/Helper/Menu/MenuBuilder.php
- src/Kunstmaan/AdminBundle/Helper/UserProcessor.php
- src/Kunstmaan/AdminBundle/Resources/config/services.yml
- src/Kunstmaan/AdminBundle/Tests/unit/Helper/Menu/MenuBuilderTest.php
- src/Kunstmaan/AdminBundle/Tests/unit/Helper/UserProcessorTest.php
Inject the correct dependency instead of the full service container.
> [AdminBundle] Deprecate container access in adminbundle classes

- src/Kunstmaan/AdminListBundle/Tests/unit/AdminList/AdminListTest.php
- src/Kunstmaan/AdminListBundle/Tests/unit/AdminList/Configurator/AbstractAdminListConfiguratorTest.php
- src/Kunstmaan/AdminListBundle/Tests/unit/AdminList/ExportListTest.php
- src/Kunstmaan/AdminListBundle/Tests/unit/AdminList/FieldTest.php
- src/Kunstmaan/AdminListBundle/Tests/unit/AdminList/FilterBuilderTest.php
- src/Kunstmaan/AdminListBundle/Tests/unit/AdminList/Helper/DoctrineDBALAdapterTest.php
I've executed our testsuite with infection and fixed some of the issues found. These improvement harden our testsuite to catch more bugs that can possibly be introduced. The actual improvement (higher is better):
Before:
```
635 mutations were generated:
232 mutants were killed
235 mutants were not covered by tests
120 covered mutants were not detected
48 errors were encountered
0 time outs were encountered
Metrics:
Mutation Score Indicator (MSI): 44%
Mutation Code Coverage: 62%
Covered Code MSI: 70%
```
After:
```
635 mutations were generated:
258 mutants were killed
233 mutants were not covered by tests
96 covered mutants were not detected
48 …
```
> [AdminListBundle] Improve the quality of the phpunit testcases

- src/Kunstmaan/TranslatorBundle/AdminList/TranslationAdminListConfigurator.php
- src/Kunstmaan/TranslatorBundle/Controller/TranslatorCommandController.php
- src/Kunstmaan/TranslatorBundle/Controller/TranslatorController.php
- src/Kunstmaan/TranslatorBundle/Resources/translations/messages.de.yml
- src/Kunstmaan/TranslatorBundle/Resources/translations/messages.en.yml
- src/Kunstmaan/TranslatorBundle/Resources/translations/messages.es.yml
- src/Kunstmaan/TranslatorBundle/Resources/translations/messages.fr.yml
- src/Kunstmaan/TranslatorBundle/Resources/translations/messages.hu.yml
- src/Kunstmaan/TranslatorBundle/Resources/translations/messages.it.yml
- src/Kunstmaan/TranslatorBundle/Resources/translations/messages.nl.yml
- src/Kunstmaan/TranslatorBundle/Resources/translations/messages.pl.yml
- src/Kunstmaan/TranslatorBundle/Resources/views/Translator/inline_edit.html.twig
- src/Kunstmaan/TranslatorBundle/Resources/views/Translator/list.html.twig
[TranslatorBundle] use the common export logic instead of a custom export but only from the settings view and not from commandline.
> [TranslatorBundle] use the common export logic instead of a custom export

- .travis.yml
Switch the code coverage run to the latest php. This also include a speed improvement because travis now comes with xdebug 2.9 which the improves code coverage by 50% for us. ([Even more for others](https://xdebug.org/announcements/2019-12-09))
> [AllBundles] Switch code coverage to latest php + codecoverage speed up

- src/Kunstmaan/PagePartBundle/Resources/views/PagePartAdminTwigExtension/modal.html.twig
| Fixed tickets | https://github.com/Kunstmaan/KunstmaanBundlesCMS/issues/2519
This commit allows to translate PageParts names in "choose PagePart" modal and search by translated names.
> [PagepartBundle] Fixed not being able to search for translated names of PageParts

- src/Kunstmaan/AdminBundle/DependencyInjection/KunstmaanAdminExtension.php
| ------------- | ----
The templating component should still be enable, otherwise we get errors in `NodeSearchConfiguration`. Temporary re-enable the component, so we can deprecate the remaining usages.
https://github.com/Kunstmaan/KunstmaanBundlesCMS/blob/f760926cb4f626646bd19745c97ecebb7ebeed6f/src/Kunstmaan/NodeSearchBundle/Configuration/NodePagesConfiguration.php#L577-L635
> [AdminBundle] Re-enable templating component for search nodepages config

- src/Kunstmaan/RedirectBundle/Entity/Redirect.php
Target urls could potentially be long and 255 chars could be too few.
> [RedirectBundle] Fix target column length for long urls

- src/Kunstmaan/RedirectBundle/Router/RedirectRouter.php
- src/Kunstmaan/RedirectBundle/Tests/unit/Router/RedirectRouterTest.php
If the origin of a redirect contains UTF-8 chars this will throw an Logic exception eg. Cannot use UTF-8 route patterns without setting the "utf8" option for route "fiscalité".
> [RedirectBundle] Fix UTF-8 issue with redirect origin

- src/Kunstmaan/AdminBundle/DependencyInjection/Compiler/InjectUntrackedTokenStorageCompilerPass.php
- src/Kunstmaan/AdminBundle/EventListener/AdminLocaleListener.php
- src/Kunstmaan/AdminBundle/EventListener/PasswordCheckListener.php
- src/Kunstmaan/AdminBundle/KunstmaanAdminBundle.php
- src/Kunstmaan/AdminBundle/Tests/unit/EventListener/AdminLocaleListenerTest.php
- src/Kunstmaan/AdminBundle/Tests/unit/EventListener/PasswordCheckListenerTest.php
- src/Kunstmaan/AdminBundle/Tests/unit/KunstmaanAdminBundleTest.php
Symfony changed the default behavior of the tokenstorage service in symfony 4.4, to track and increase the session usage index. This will trigger the response to be private. 
By changing a few checks we can avoid triggering this meganism when is it not necessary.
> [AdminBundle] Avoid accessing user token when it is not needed

- src/Kunstmaan/NodeBundle/Helper/NodeMenuItem.php
| Fixed tickets | fixes #1888 
The `NodeMenuItem::getLang` method was incorrectly removed in #1255, the `NodeMenu::getLang` method was deprecated and removed but this method should have been reworked to use the new `getLocale` method.
> [NodeBundle] Restore NodeMenuItem::getLang method to fix BC break

- src/Kunstmaan/MediaBundle/Resources/views/Chooser/chooserShowFolder.html.twig
- src/Kunstmaan/MediaBundle/Resources/views/Folder/show.html.twig
On the mobile view of the media bundle there were some incorrect icons
Before:
After:
> [MediaBundle] Replace incorrect mobile icons

- src/Kunstmaan/MediaBundle/Helper/Imagine/WebPathResolver.php
Since v2.2 some overrides we do for the liip/imagine-bundle didn't work anymore. This causes issues with uploads with a different extension than the filter outputs.
> [MediaBundle] Fix incompatibility with liip/imagine-bundle 2.2+

- src/Kunstmaan/RedirectBundle/Router/RedirectRouter.php
The `RedirectableUrlMatcher` is deprecated, but we specify the `_controller` ourself on redirects so no need for a redirectable matcher.
> [RedirectBundle] Replace deprecated RedirectableUrlMatcher

- src/Kunstmaan/AdminBundle/Resources/config/services.yml
> [AdminBundle] Inject correct dependency in UserProcessor

- docs/bundles/config-reference.md
- src/Kunstmaan/AdminBundle/DependencyInjection/Compiler/EnablePermissionsPass.php
- src/Kunstmaan/AdminBundle/Helper/Security/Acl/AclHelper.php
- src/Kunstmaan/AdminBundle/Helper/Security/Acl/AclNativeHelper.php
- src/Kunstmaan/AdminBundle/Helper/Security/Acl/Voter/AclVoter.php
- src/Kunstmaan/AdminBundle/KunstmaanAdminBundle.php
- src/Kunstmaan/AdminBundle/Tests/unit/KunstmaanAdminBundleTest.php
- src/Kunstmaan/NodeBundle/DependencyInjection/Configuration.php
- src/Kunstmaan/NodeBundle/DependencyInjection/KunstmaanNodeExtension.php
- src/Kunstmaan/NodeBundle/EventListener/NodeListener.php
- src/Kunstmaan/NodeBundle/EventListener/SlugSecurityListener.php
- src/Kunstmaan/NodeBundle/Resources/config/services.yml
- src/Kunstmaan/NodeBundle/Tests/unit/DependencyInjection/ConfigurationTest.php
This will allow a project to disable the permission module. This will disable the permission checking on frontend pages (VIEW) and in the admin (VIEW, EDIT, (UN)PUBLISH, ...) and will hide the permissions tab in the page admin.
> [AllBundles] Add configuration option to disable permission module/checking

- src/Kunstmaan/AdminBundle/Helper/Security/Acl/Voter/AclVoter.php
> [AdminBundle] Aclvoter should only grant access for supported attributes with disabled permissions 

- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/defaultsite/Controller/DefaultController.php
> [GeneratorBundle] getParameter should be called on the controller class

- src/Kunstmaan/NodeBundle/EventListener/NodeTranslationListener.php
- src/Kunstmaan/NodeBundle/Resources/config/services.yml
Because of https://github.com/symfony/symfony/pull/36063 the session is now always started. Besides that is the service deprecated in https://github.com/symfony/symfony/pull/36273
> [NodeBundle] Use flashbag from session

- src/Kunstmaan/MediaBundle/Helper/Image/ImageHandler.php
- src/Kunstmaan/MediaBundle/Tests/unit/Fixtures/sample.svg
- src/Kunstmaan/MediaBundle/Tests/unit/Helper/Image/ImageHandlerTest.php
| Fixed tickets | fixes #2667
@igst Can you check if this fixes the error you have?
> [MediaBundle] Fix php 7.4 incompatibility

- src/Kunstmaan/GeneratorBundle/Command/InstallCommand.php
Because during the install command the `security.yaml` is replaced by the new security config, this is not available during this run (current container is still loaded in the process), this will make the `doctrine:fixtures:load` command fail with the error `No encoder has been configured for ...`
> [GeneratorBundle] Fix doctrine fixtures error during install command

- src/Kunstmaan/AdminBundle/Helper/DomainConfiguration.php
- src/Kunstmaan/AdminBundle/Helper/DomainConfigurationInterface.php
- src/Kunstmaan/MultiDomainBundle/Helper/DomainConfiguration.php
- src/Kunstmaan/NodeBundle/Helper/URLHelper.php
Don't typecast host id parameter as this can be a string or an int depending on the user config. Bug introduced in #2629 and was caused by incorrect phpdocs. Both the typecast and phpdoc's have been fixed
> [AllBundles] Fix incorrect typecast in UrlHelper

- src/Kunstmaan/NodeBundle/Helper/URLHelper.php
- src/Kunstmaan/NodeBundle/Tests/unit/Helper/UrlHelperTest.php
Previously the urlHelper class would load all node translations and all media items before replacing urls. This is unnecessary and would load large amounts of data for large websites. With this setup we do the lookup more efficient by only executing a query to the db for the requested nodetranslations/media objects.
> [NodeBundle] Improve url helper by replacing full data load by specific lookup

- UPGRADE-5.6.md
- composer.json
- src/Kunstmaan/NodeSearchBundle/Configuration/NodePagesConfiguration.php
- src/Kunstmaan/NodeSearchBundle/DependencyInjection/KunstmaanNodeSearchExtension.php
- src/Kunstmaan/NodeSearchBundle/Resources/config/services.yml
- src/Kunstmaan/NodeSearchBundle/Search/AbstractElasticaSearcher.php
- src/Kunstmaan/NodeSearchBundle/Search/NodeSearcher.php
- src/Kunstmaan/NodeSearchBundle/Search/SearcherInterface.php
- src/Kunstmaan/SearchBundle/Provider/ElasticaProvider.php
| Fixed tickets | fixes #2688 
This PR adds support for `ruflin/elastica` 7.0 (and with that also elasticsearch 7). With this change previous versions of elasticsearch and `ruflin/elastica` <7.0, are deprecated and support for these versions will be removed in 6.0.
> [SearchBundle][NodeSearch] Add elastica/elasticsearch 7 support

- .build/stubs/RoleInterface.php
- phpstan.neon
- stubs/RoleInterface.php
Related to https://github.com/phpstan/phpstan/issues/3542 and https://github.com/Kunstmaan/KunstmaanBundlesCMS/pull/2696.
BTW you already have some real errors since the PHPStan check was disabled in the CI so you should also look into them :)
```
------ -------------------------------------------------------------------------
Line   Kunstmaan/DashboardBundle/Repository/AnalyticsSegmentRepository.php
------ -------------------------------------------------------------------------
53     Class Kunstmaan\DashboardBundle\Repository\AnalyticsOverview not found.
💡 Learn more at https://phpstan.org/user-guide/discovering-symbols
------ -------------------------------------------------------------------------
------ --------------------------------------------------------------------
Line …
```
> [AdminBundle] Fix nonexistent RoleInterface for the BC layer

- src/Kunstmaan/TranslatorBundle/Form/TranslationsFileUploadType.php
| Fixed tickets | [2710](https://github.com/Kunstmaan/KunstmaanBundlesCMS/issues/2710)
> [TranslatorBundle] Added missing validation on translation file

- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/config/security.yaml
This option is a no-op config as it's always true in symfony 4 and is deprecated in symfony 4.1, this will avoid generating deprecations in new projects
> [GeneratorBundle] Don't add deprecated logout_on_user_change config option

- composer.json
- src/Kunstmaan/MediaBundle/Resources/config/services.yml
- src/Kunstmaan/MediaBundle/composer.json
> [MediaBundle] Fix liip/imagine controller deprecation

- src/Kunstmaan/NodeBundle/EventListener/NodeTranslationListener.php
The call to getFlashBag in the constructor triggers a session start which is not needed.
> [NodeBundle] Dont start session if not needed

- src/Kunstmaan/AdminBundle/Resources/ui/scss/default-theme/config/vendors/font-awesome/_font-awesome-imports.scss
> [AdminBundle] Add brands to font awesome imports

- src/Kunstmaan/MediaBundle/Resources/views/AdminList/ItemAction/select.html.twig
> [MediaBundle] getImageUrl has only 2 params

- composer.json
- src/Kunstmaan/AdminBundle/DependencyInjection/KunstmaanAdminExtension.php
- src/Kunstmaan/AdminBundle/composer.json
The config we set in the admin extension is equal to the default config. Prepare code to support symfony 5
Needs rebase after #2748 to make the builds pass
> [AdminBundle] Bump knplabs/knp-menu-bundle and remove default config

- src/Kunstmaan/TranslatorBundle/Service/Command/Importer/Importer.php
When importing translations from a spreadsheet the full temporary filepath (eg. `/private/var/folders/7x/tddvmt1x6lx5frst752qqzp80000gy/T/phpE8splr`) is used and this might exceed the column length of `Translation::$file`. So don't pass it for spreadsheet imports as there is no filename available that would make sense.
> [TranslatorBundle] Don't use temporary filename for spreadsheet translation imports

- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/defaultsite/DataFixtures/ORM/DefaultSiteGenerator/DefaultSiteFixtures.php
- src/Kunstmaan/NodeBundle/Entity/Node.php
This PR fixes the issues that internal links should be in `[NTXXX]` style otherwise saving pages in a demo install will trigger validation errors on pagepart urls. Also some indentation fixes to cleanup the outputted file
Best viewed without whitespace changes: https://github.com/Kunstmaan/KunstmaanBundlesCMS/pull/2767/files?w=1
> [GeneratorBundle] Fix demo site datafixtures url validation errors

- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/pagepart/Resources/views/PageParts/DownloadPagePart/view.html.twig
- src/Kunstmaan/MediaBundle/Resources/views/Media/File/show.html.twig
- src/Kunstmaan/MediaBundle/Resources/views/Media/Image/show.html.twig
- src/Kunstmaan/MediaPagePartBundle/Resources/views/DownloadPagePart/view.html.twig
- src/Kunstmaan/MediaPagePartBundle/Resources/views/ImagePagePart/view.html.twig
- src/Kunstmaan/SeoBundle/Resources/views/SeoTwigExtension/metadata.html.twig
Use absolute_url twig function instead of making the url based on app.request data. This allows to set a custom base_url.
> [AllBundles] Use absolute_url twig function instead of using app.request data

- UPGRADE-5.7.md
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/groundcontrol/gulpfile.babel.js
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/layout/groundcontrol/package.json
> [GeneratorBundle] Remove buildCmsAssets from generated FE tasks - assets are compiled in git repo

- UPGRADE-5.7.md
- composer.json
- src/Kunstmaan/AdminBundle/DependencyInjection/Compiler/VersionCheckerCacheBcPass.php
- src/Kunstmaan/AdminBundle/Helper/VersionCheck/VersionChecker.php
- src/Kunstmaan/AdminBundle/KunstmaanAdminBundle.php
- src/Kunstmaan/AdminBundle/Resources/config/services.yml
- src/Kunstmaan/AdminBundle/Tests/unit/Helper/VersionCheck/VersionCheckTest.php
- src/Kunstmaan/AdminBundle/Tests/unit/KunstmaanAdminBundleTest.php
- src/Kunstmaan/AdminBundle/Toolbar/BundleVersionDataCollector.php
- src/Kunstmaan/AdminBundle/composer.json
The doctrine/cache-bundle is deprecated for symfony 5 and the usage of symfony/cache is advised
> [AdminBundle] Prepare code to remove deprecated doctrine/cache and replace with symfony/cache

- src/Kunstmaan/NodeBundle/Repository/NodeTranslationRepository.php
- src/Kunstmaan/NodeBundle/Twig/NodeTwigExtension.php
Follow up for #2716. Don't use the deprecated repository method in our own code and remove the int typehint for now (and deprecate passing other values than integers) to avoid an indirect BC break as passing an object was possible in the past (although the phpdoc didn't indicate this) and actually produced the expected results
> [NodeBundle] Improve nodetranslation repository deprecation

- src/Kunstmaan/AdminListBundle/Tests/unit/AdminList/Helper/DoctrineDBALAdapterTest.php
> [AdminListBundle] Fix: Remove wrong PHPDoc

- src/Kunstmaan/MediaBundle/Resources/views/Folder/show.html.twig
When no pagination is available you see this
After
With pagination
> [MediaBundle] Fix media list without pagination

- composer.json
- src/Kunstmaan/NodeBundle/Entity/NodeTranslation.php
- src/Kunstmaan/NodeBundle/composer.json
Currently there is a database limit of 255 chars on urls, this might cause troubles on sites with deep nested content and/or long slugs
> [NodeBundle] Change nodetranslation slug/url fields to text type to allow long values

- src/Kunstmaan/AdminBundle/Resources/ui/scss/default-theme/components/_components.scss
- src/Kunstmaan/AdminBundle/Resources/ui/scss/default-theme/components/forms/_slug-chooser.scss
- src/Kunstmaan/AdminBundle/Resources/views/Form/fields.html.twig
- src/Kunstmaan/NodeBundle/Resources/views/Form/formWidgets.html.twig
| Fixed tickets | #2749
Allow the slug input-group to use more space, if available. If not, we truncate de prefix so the input always has enough space.
Screenshots:
> [AdminBundle] allow slug input-group to use more space if available

- src/Kunstmaan/FormBundle/Entity/FormSubmissionFieldTypes/StringFormSubmissionField.php
The max length in the database is 255. Without validation you get an database error.
> [FormBundle] Add length validation to string form field

- src/Kunstmaan/MultiDomainBundle/DependencyInjection/Configuration.php
- src/Kunstmaan/MultiDomainBundle/Tests/DependencyInjection/ConfigurationTest.php
- src/Kunstmaan/MultiDomainBundle/Tests/DependencyInjection/KunstmaanMultiDomainExtensionTest.php
| New feature? |no
| Fixed tickets | N/a
This fixes the configuration for the hosts in the multi domain bundle.
When modifying the configuration from another bundle (using PrependExtensionInterface) the configuration get re-indexed by the Symfony configuration component. This cause the configuration to be added twice.
Once using the origin key (the modified configuration) and once using numeric ids re-indexed by Symfony.
I figured this was attempted previously as the code is commented out. Enabling this as-is will remove the 'host' configuration field. (as it is should only be used as the key, not a value).
By using a different name for the attribute, the original configuration is …
> [MultiDomainBundle] Fix keying of host configurations

- UPGRADE-5.9.md
- src/Kunstmaan/AdminListBundle/Service/EntityVersionLockService.php
- src/Kunstmaan/AdminListBundle/Tests/Service/EntityVersionLockServiceTest.php
> [AdminlistBundle] Deprecate setter methods in EntityVersionLockService

- UPGRADE-5.9.md
- src/Kunstmaan/NodeSearchBundle/Entity/AbstractSearchPage.php
- src/Kunstmaan/NodeSearchBundle/Tests/Entity/AbstractSearchPageTest.php
the class was already named abstract and will be made abstract in 6.0
> [NodeSearchBundle] Deprecate direct instantiation of the abstractSearchPage

- UPGRADE-5.9.md
- src/Kunstmaan/DashboardBundle/Command/DashboardCommand.php
- src/Kunstmaan/DashboardBundle/Controller/GoogleAnalyticsAJAXController.php
- src/Kunstmaan/DashboardBundle/DependencyInjection/KunstmaanDashboardExtension.php
- src/Kunstmaan/DashboardBundle/Resources/config/services.yml
- src/Kunstmaan/DashboardBundle/Tests/DependencyInjection/KunstmaanDashboardExtensionTest.php
- src/Kunstmaan/DashboardBundle/Tests/Widget/DashboardWidgetTest.php
- src/Kunstmaan/DashboardBundle/Widget/DashboardWidget.php
> [Dashboardbundle] Rework dashboard command calls

- UPGRADE-5.9.md
- src/Kunstmaan/AdminBundle/Event/AdaptSimpleFormEvent.php
- src/Kunstmaan/AdminBundle/Event/DeepCloneAndSaveEvent.php
- src/Kunstmaan/AdminBundle/Event/Events.php
- src/Kunstmaan/AdminListBundle/Event/AdminListEvent.php
- src/Kunstmaan/AdminListBundle/Event/AdminListEvents.php
- src/Kunstmaan/FormBundle/Event/SubmissionEvent.php
- src/Kunstmaan/NodeBundle/Event/AdaptFormEvent.php
- src/Kunstmaan/NodeBundle/Event/ConfigureActionMenuEvent.php
- src/Kunstmaan/NodeBundle/Event/CopyPageTranslationNodeEvent.php
- src/Kunstmaan/NodeBundle/Event/Events.php
- src/Kunstmaan/NodeBundle/Event/RecopyPageTranslationNodeEvent.php
- src/Kunstmaan/NodeBundle/Event/RevertNodeAction.php
- src/Kunstmaan/NodeBundle/Event/SlugEvent.php
- src/Kunstmaan/NodeSearchBundle/Event/IndexNodeEvent.php
- src/Kunstmaan/PagePartBundle/Event/Events.php
- src/Kunstmaan/PagePartBundle/Event/PagePartEvent.php
- src/Kunstmaan/UserManagementBundle/Event/UserEvents.php
- src/Kunstmaan/VotingBundle/Event/Events.php
- src/Kunstmaan/VotingBundle/Event/Facebook/FacebookLikeEvent.php
- src/Kunstmaan/VotingBundle/Event/Facebook/FacebookSendEvent.php
- src/Kunstmaan/VotingBundle/Event/LinkedIn/LinkedInShareEvent.php
- src/Kunstmaan/VotingBundle/Event/UpDown/DownVoteEvent.php
- src/Kunstmaan/VotingBundle/Event/UpDown/UpVoteEvent.php
Mark all kunstmaan event classes as final, because overriding them doesn't change the dispatched event and it will make it easier to do changes in the future
> [AllBundles] Mark event classes final

- UPGRADE-5.9.md
- src/Kunstmaan/GeneratorBundle/Command/GenerateBundleCommand.php
- src/Kunstmaan/GeneratorBundle/Command/GenerateEntityCommand.php
- src/Kunstmaan/GeneratorBundle/Generator/BundleGenerator.php
- src/Kunstmaan/GeneratorBundle/Generator/DefaultEntityGenerator.php
> [GeneratorBundle] Deprecate generate bundle and entity commands

- UPGRADE-5.9.md
- src/Kunstmaan/MediaBundle/Helper/File/FileHandler.php
- src/Kunstmaan/MediaBundle/Helper/File/FileHelper.php
- src/Kunstmaan/MediaBundle/Tests/Helper/File/FileHelperTest.php
> [MediaBundle] Use parameter instead of hardcoded media path

- src/Kunstmaan/FormBundle/Entity/PageParts/AbstractFormPagePart.php
- src/Kunstmaan/FormBundle/Entity/PageParts/CheckboxPagePart.php
- src/Kunstmaan/FormBundle/Entity/PageParts/ChoicePagePart.php
- src/Kunstmaan/FormBundle/Entity/PageParts/EmailPagePart.php
- src/Kunstmaan/FormBundle/Entity/PageParts/FileUploadPagePart.php
- src/Kunstmaan/FormBundle/Entity/PageParts/MultiLineTextPagePart.php
- src/Kunstmaan/FormBundle/Entity/PageParts/SingleLineTextPagePart.php
- src/Kunstmaan/FormBundle/Entity/PageParts/SubmitButtonPagePart.php
- src/Kunstmaan/FormBundle/Form/CheckboxPagePartAdminType.php
- src/Kunstmaan/FormBundle/Form/ChoicePagePartAdminType.php
- src/Kunstmaan/FormBundle/Form/FileUploadPagePartAdminType.php
- src/Kunstmaan/FormBundle/Form/MultiLineTextPagePartAdminType.php
- src/Kunstmaan/FormBundle/Form/SingleLineTextPagePartAdminType.php
- src/Kunstmaan/FormBundle/Tests/Form/CheckboxPagePartAdminTypeTest.php
- src/Kunstmaan/FormBundle/Tests/Form/FileUploadPagePartAdminTypeTest.php
- src/Kunstmaan/FormBundle/Tests/Form/MultiLineTextPagePartAdminTypeTest.php
- src/Kunstmaan/FormBundle/Tests/Form/SingleLineTextPagePartAdminTypeTest.php
The max length in the database is 255. Without validation you get an database error.
> [FormBundle] Add length validation to form fields

- UPGRADE-5.9.md
- composer.json
- src/Kunstmaan/AdminBundle/DependencyInjection/Compiler/PagerfantaBridgePass.php
- src/Kunstmaan/AdminBundle/DependencyInjection/PagerfantaConfiguration.php
- src/Kunstmaan/AdminBundle/DependencyInjection/PagerfantaExtension.php
- src/Kunstmaan/AdminBundle/KunstmaanAdminBundle.php
- src/Kunstmaan/AdminBundle/Tests/DependencyInjection/Compiler/PagerfantaBridgePassTest.php
- src/Kunstmaan/AdminBundle/Tests/DependencyInjection/PagerfantaExtensionTest.php
- src/Kunstmaan/AdminBundle/composer.json
- src/Kunstmaan/AdminListBundle/AdminList/Configurator/AbstractDoctrineORMAdminListConfigurator.php
- src/Kunstmaan/AdminListBundle/Tests/AdminList/Helper/DoctrineDBALAdapterTest.php
- src/Kunstmaan/AdminListBundle/composer.json
- src/Kunstmaan/ArticleBundle/composer.json
- src/Kunstmaan/MediaBundle/composer.json
- src/Kunstmaan/NodeSearchBundle/composer.json
| Fixed tickets | fixes #2755
The `white-october/pagerfanta-bundle` package is not a required dependency for the cms, this will also make supporting symfony 5 easier. This PR also adds a BC layer to convert "old" WhiteOctober bundle config to the new bundle
TODO:
> [AdminListBundle] Change pagerfanta dependencies to require the minimum needed packages

- UPGRADE-5.9.md
- src/Kunstmaan/DashboardBundle/Command/GoogleAnalyticsDataCollectCommand.php
- src/Kunstmaan/DashboardBundle/Resources/config/commands.yml
> [DashboardBundle] Deprecate remaining container usages in command

- src/Kunstmaan/AdminBundle/DependencyInjection/KunstmaanAdminExtension.php
- src/Kunstmaan/AdminBundle/Tests/DependencyInjection/KunstmaanAdminExtensionTest.php
> [AdminBundle] Fix remaining usages of deprecated admin_exception_excludes config

- src/Kunstmaan/TranslatorBundle/Command/ImportTranslationsCommand.php
- src/Kunstmaan/TranslatorBundle/Resources/views/Translator/list.html.twig
This option is too dangerous for admin users to accidentally click on it and overwrite all translations. It's still possible to do a forced import from the cli.
In the second commit I removed the incorrect deprecation on the command
> [TranslatorBundle] Remove forced import from admin interface

- src/Kunstmaan/AdminBundle/Entity/BaseUser.php
- src/Kunstmaan/AdminBundle/Resources/config/authentication.yml
- src/Kunstmaan/AdminBundle/Resources/views/Default/_css.html.twig
- src/Kunstmaan/AdminBundle/Resources/views/Default/layout.html.twig
- src/Kunstmaan/AdminBundle/Resources/views/authentication/layout.html.twig
- src/Kunstmaan/AdminBundle/Resources/views/authentication/login.html.twig
- src/Kunstmaan/AdminBundle/Security/UserChecker.php
- src/Kunstmaan/GeneratorBundle/Resources/SensioGeneratorBundle/skeleton/config/security.yaml
> [AdminBundle] New authentication bugfixes and improvements

- src/Kunstmaan/AdminBundle/composer.json
- src/Kunstmaan/ArticleBundle/composer.json
- src/Kunstmaan/LeadGenerationBundle/composer.json
- src/Kunstmaan/MenuBundle/composer.json
- src/Kunstmaan/RedirectBundle/composer.json
- src/Kunstmaan/TaggingBundle/composer.json
- src/Kunstmaan/TranslatorBundle/composer.json
These bundles still use a deprecated controller class so it makes them incompatible with v6
> [AllBundles] Update adminlist-bundle version constraint to allow only ^5.9
